force-app/main/default/objects/Certifications__c/Certifications__c.object-meta.xml
<CustomObject>
    <label>Skills &amp; Certification</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Credentials ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Skills &amp; Certifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Certifications__c/fields/Certification_Name__c.field-meta.xml
<CustomField>
    <fullName>Certification_Name__c</fullName>
    <label>Certification Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Salesforce Certified Associate</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified Administrator</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified Advanced Administrator</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified Business Analyst</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified Platform App Builder</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified Data Architect</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified Development Lifecycle and Deployment Architect</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified Identity and Access Management Architect</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified Integration Architect</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified Sharing and Visibility Architect</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified System Architect</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified Application Architect</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified Heroku Architect</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified B2B Solution Architect</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified B2C Commerce Architect</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified B2C Solution Architect</fullName>
            </value>
            <value>
                <fullName>Certified Technical Architect (CTA)</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified Education Cloud Consultant</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified Experience Cloud Consultant</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified Field Service Consultant</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified Nonprofit Cloud Consultant</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified OmniStudio Consultant</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified Sales Cloud Consultant</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified Service Cloud Consultant</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified Tableau CRM and Einstein Discovery Consultant</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified CPQ Specialist</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified User Experience Designer</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified Strategy Designer</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified B2C Commerce Developer</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified Industries CPQ Developer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Certifications__c/fields/Completion_Date__c.field-meta.xml
<CustomField>
    <fullName>Completion_Date__c</fullName>
    <label>Completion Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Certifications__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Certifications</relationshipLabel>
    <relationshipName>Certifications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Certifications__c/fields/Onboarding_Request__c.field-meta.xml
<CustomField>
    <fullName>Onboarding_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Onboarding Request</label>
    <referenceTo>EMS_EM_Onboarding_Request__c</referenceTo>
    <relationshipName>Certifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Certifications__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Certification</fullName>
            </value>
            <value>
                <fullName>Skill</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_EM_Degree__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_Degree__c</fullName>
    <label>Diploma / Degree</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_EM_Field_of_Study__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_Field_of_Study__c</fullName>
    <label>Field of Study</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_EM_GDate__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_GDate__c</fullName>
    <label>Graduation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_EM_IName__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_IName__c</fullName>
    <label>Institution Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ems_EM_Additional_Detail__c/ems_EM_Additional_Detail__c.object-meta.xml
<CustomObject>
    <label>Professional Proficiency</label>
    <nameField>
        <displayFormat>PP-{00000}</displayFormat>
        <label>Professional Proficiency Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Professional Proficiency</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ems_EM_Additional_Detail__c/fields/ContactId__c.field-meta.xml
<CustomField>
    <fullName>ContactId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Additional_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ems_EM_Additional_Detail__c/fields/EMS_EM_Degree__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_Degree__c</fullName>
    <label>Degree</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/ems_EM_Additional_Detail__c/fields/EMS_EM_Education__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_Education__c</fullName>
    <label>Level of Education</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Post Graduate</fullName>
            </value>
            <value>
                <fullName>Graduate</fullName>
            </value>
            <value>
                <fullName>Std X/SSC</fullName>
            </value>
            <value>
                <fullName>Std XII/HSC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ems_EM_Additional_Detail__c/fields/EMS_EM_Field_of_Study__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_Field_of_Study__c</fullName>
    <label>Field of Study</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ems_EM_Additional_Detail__c/fields/Onboarding_Request__c.field-meta.xml
<CustomField>
    <fullName>Onboarding_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Onboarding Request</label>
    <referenceTo>EMS_EM_Onboarding_Request__c</referenceTo>
    <relationshipName>Additional_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/certificationController.cls
public class certificationController {
    
    @AuraEnabled( cacheable = true )
    public static List<Certifications__c> fetchCertifications(String recordId) {
        return [SELECT Id, 
                Onboarding_Request__c, 
                Contact__c, 
                Certification_Name__c, 
                Completion_Date__c, Type__c 
                FROM Certifications__c WHERE Onboarding_Request__c =:recordId AND Type__c = 'Certification' LIMIT 20];
    }
    
    @AuraEnabled
    public static string dmlOnCertifications(Object data, String removeCertificationIds) {
        List<Certifications__c> updateCertifications = (List<Certifications__c>) JSON.deserialize(JSON.serialize(data), List<Certifications__c>.class);
        List<Certifications__c> deleteCertifications = new List<Certifications__c>();
        
        if(String.isNotBlank(removeCertificationIds)){
            List<Id> CertificationIds = removeCertificationIds.split(',');
            deleteCertifications = [SELECT Id FROM Certifications__c WHERE Id IN :CertificationIds];
        }
        
        try {
            if(updateCertifications != null && !updateCertifications.isEmpty()){
                upsert updateCertifications;
            }
            
            if(deleteCertifications != null && !deleteCertifications.isEmpty()){    
                delete deleteCertifications;
            }
            return 'Success: Contact(s) upsert/delete successfully';
        }
        catch (Exception e) {
            String errorMsg = 'The following exception has occurred: ' + e.getMessage();
            throw new AuraHandledException(ErrorMsg);
        }
        // return '';
    }
    
    @AuraEnabled( cacheable = true )
    public static List<ems_EM_Additional_Detail__c> fetchEducation(String recordId) {
        Id EduRecordTypeId = Schema.SObjectType.ems_EM_Additional_Detail__c.getRecordTypeInfosByName().get('Education Details').getRecordTypeId();
        return [SELECT Id, 
                Onboarding_Request__c, 
                ContactId__c, 
                RecordTypeId, 
                EMS_EM_Education__c,
                EMS_EM_Degree__c,
                EMS_EM_Field_of_Study__c,
                EMS_EM_IName__c,
                EMS_EM_GDate__c
                FROM ems_EM_Additional_Detail__c WHERE Onboarding_Request__c =:recordId AND RecordTypeId =: EduRecordTypeId LIMIT 20];
    }
    
    @AuraEnabled
    public static string dmlOnEducation(Object data, String removeCertificationIds) {
        List<ems_EM_Additional_Detail__c> updateCertifications = (List<ems_EM_Additional_Detail__c>) JSON.deserialize(JSON.serialize(data), List<ems_EM_Additional_Detail__c>.class);
        List<ems_EM_Additional_Detail__c> deleteCertifications = new List<ems_EM_Additional_Detail__c>();
        
        if(String.isNotBlank(removeCertificationIds)){
            List<Id> CertificationIds = removeCertificationIds.split(',');
            deleteCertifications = [SELECT Id FROM ems_EM_Additional_Detail__c WHERE Id IN :CertificationIds];
        }
        
        try {
            if(updateCertifications != null && !updateCertifications.isEmpty()){
                upsert updateCertifications;
            }
            
            if(deleteCertifications != null && !deleteCertifications.isEmpty()){    
                delete deleteCertifications;
            }
            return 'Success: Education(s) upsert/delete successfully';
        }
        catch (Exception e) {
            String errorMsg = 'The following exception has occurred: ' + e.getMessage();
            throw new AuraHandledException(ErrorMsg);
        }
        // return '';
    }
    @AuraEnabled
    public static void uploadFiles(List<String> fileContents, List<String> fileNames) {
        List<ContentVersion> fileVersions = new List<ContentVersion>();
        
        for (Integer i = 0; i < fileContents.size(); i++) {
            String fileContent = fileContents.get(i);
            String fileName = fileNames.get(i);
            
            ContentVersion fileVersion = new ContentVersion(
                Title = fileName,
                PathOnClient = fileName,
                VersionData = EncodingUtil.base64Decode(fileContent)
            );
            
            fileVersions.add(fileVersion);
        }
        
        insert fileVersions;
    }
    
}