force-app/main/default/objects/Certifications__c/Certifications__c.object-meta.xml
<CustomObject>
    <label>Skills &amp; Certification</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Credentials ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Skills &amp; Certifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Certifications__c/fields/Certification_Name__c.field-meta.xml
<CustomField>
    <fullName>Certification_Name__c</fullName>
    <label>Certification Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Salesforce Certified Associate</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified Administrator</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified Advanced Administrator</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified Business Analyst</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified Platform App Builder</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified Data Architect</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified Development Lifecycle and Deployment Architect</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified Identity and Access Management Architect</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified Integration Architect</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified Sharing and Visibility Architect</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified System Architect</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified Application Architect</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified Heroku Architect</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified B2B Solution Architect</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified B2C Commerce Architect</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified B2C Solution Architect</fullName>
            </value>
            <value>
                <fullName>Certified Technical Architect (CTA)</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified Education Cloud Consultant</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified Experience Cloud Consultant</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified Field Service Consultant</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified Nonprofit Cloud Consultant</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified OmniStudio Consultant</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified Sales Cloud Consultant</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified Service Cloud Consultant</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified Tableau CRM and Einstein Discovery Consultant</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified CPQ Specialist</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified User Experience Designer</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified Strategy Designer</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified B2C Commerce Developer</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified Industries CPQ Developer</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Certifications__c/fields/Completion_Date__c.field-meta.xml
<CustomField>
    <fullName>Completion_Date__c</fullName>
    <label>Completion Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Certifications__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Certifications</relationshipLabel>
    <relationshipName>Certifications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Certifications__c/fields/Other__c.field-meta.xml
<CustomField>
    <fullName>Other__c</fullName>
    <label>Other</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Certifications__c/fields/Skill__c.field-meta.xml
<CustomField>
    <fullName>Skill__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Skill</label>
    <referenceTo>Skill__c</referenceTo>
    <relationshipName>Certifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Certifications__c/fields/Skill_Rating__c.field-meta.xml
<CustomField>
    <fullName>Skill_Rating__c</fullName>
    <label>Skill Rating</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Certifications__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Certification</fullName>
            </value>
            <value>
                <fullName>Skill</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_RM_Employee_Id__c.field-meta.xml
<CustomField>
    <fullName>EMS_RM_Employee_Id__c</fullName>
    <label>Employee ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Resource_Role__c.field-meta.xml
<CustomField>
    <fullName>Resource_Role__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Role</label>
    <referenceTo>Resource_Role__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Resource_Role__c/Resource_Role__c.object-meta.xml
<CustomObject>
    <label>Resource Role</label>
    <nameField>
        <label>Resource Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resource Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Skill__c/Skill__c.object-meta.xml
<CustomObject>
    <label>Skill</label>
    <nameField>
        <label>Skill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Skills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Skill__c/fields/Resource_Role__c.field-meta.xml
<CustomField>
    <fullName>Resource_Role__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Role</label>
    <referenceTo>Resource_Role__c</referenceTo>
    <relationshipLabel>Resource Skills</relationshipLabel>
    <relationshipName>Skills</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/mySkillsAndCertifcationsTest.cls
@isTest
public class mySkillsAndCertifcationsTest {
    public testmethod static void skillCreationTest(){
         Resource_Role__c role = TestDataFactory.createResourceRole(true);
         TestDataFactory.createLeaveType(true);
         Account acc = TestDataFactory.createAccount(true);
		 Contact con=  TestDataFactory.createResourceContact(acc.id, false);
         con.EMS_RM_Employee_Id__c = 'CP10234';
         con.Resource_Role__c = role.Id;
         insert con;
        User u = Testdatafactory.createCommunityUserWithAccAndContact(acc.id,con.Id,true);
        Skill__c sl = new Skill__c();
        sl.Name = 'Test Skill';
        insert sl;
        system.runAs(u){
         Certifications__c cert = new Certifications__c();
         cert.Certification_Name__c = 'Other';
         cert.Other__c = 'Test Other';
         cert.Completion_Date__c = system.today();
         cert.Contact__c = con.Id;
         cert.Type__c = 'Certification';
         insert cert;
            
         Certifications__c cert2 = new Certifications__c();
         cert2.Contact__c = con.Id;
         cert2.Type__c = 'Skill';
         cert2.Skill_Rating__c = '5';
         cert2.Skill__c = sl.Id;
         insert cert2;
         Test.startTest();
          mySkillsAndCertifcations.getMyCertificationsAndSkills();
         Test.stopTest();
        } 
    }
}