force-app/main/default/objects/Certifications__c/Certifications__c.object-meta.xml
<CustomObject>
    <label>Skills &amp; Certification</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Credentials ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Skills &amp; Certifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Certifications__c/fields/Certification_Name__c.field-meta.xml
<CustomField>
    <fullName>Certification_Name__c</fullName>
    <label>Certification Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Salesforce Certified Associate</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified Administrator</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified Advanced Administrator</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified Business Analyst</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified Platform App Builder</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified Data Architect</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified Development Lifecycle and Deployment Architect</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified Identity and Access Management Architect</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified Integration Architect</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified Sharing and Visibility Architect</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified System Architect</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified Application Architect</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified Heroku Architect</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified B2B Solution Architect</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified B2C Commerce Architect</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified B2C Solution Architect</fullName>
            </value>
            <value>
                <fullName>Certified Technical Architect (CTA)</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified Education Cloud Consultant</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified Experience Cloud Consultant</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified Field Service Consultant</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified Nonprofit Cloud Consultant</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified OmniStudio Consultant</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified Sales Cloud Consultant</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified Service Cloud Consultant</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified Tableau CRM and Einstein Discovery Consultant</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified CPQ Specialist</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified User Experience Designer</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified Strategy Designer</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified B2C Commerce Developer</fullName>
            </value>
            <value>
                <fullName>Salesforce Certified Industries CPQ Developer</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Certifications__c/fields/Completion_Date__c.field-meta.xml
<CustomField>
    <fullName>Completion_Date__c</fullName>
    <label>Completion Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Certifications__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Certifications</relationshipLabel>
    <relationshipName>Certifications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Certifications__c/fields/Last_Used_Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Used_Project_Name__c</fullName>
    <label>Last Used Project Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Certifications__c/fields/Other__c.field-meta.xml
<CustomField>
    <fullName>Other__c</fullName>
    <label>Other</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Certifications__c/fields/Skill__c.field-meta.xml
<CustomField>
    <fullName>Skill__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Skill</label>
    <referenceTo>Skill__c</referenceTo>
    <relationshipName>Certifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Certifications__c/fields/Skill_Rating__c.field-meta.xml
<CustomField>
    <fullName>Skill_Rating__c</fullName>
    <label>Skill Rating</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Certifications__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Certification</fullName>
            </value>
            <value>
                <fullName>Skill</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Skill__c/Skill__c.object-meta.xml
<CustomObject>
    <label>Skill</label>
    <nameField>
        <label>Skill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Skills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/mySkillsAndCertifcations.cls
/**
* @author Subba Kalavala
* @date 01/03/2023
* @description  mySkillsAndCertifcations Class to show the data on Home page for certification details
*
*               Test code coverage provided by the following test class:
*               - mySkillsAndCertifcationsTest
*
* CHANGE HISTORY
* ====================================================================================================
* DATE          NAME                    DESCRIPTION
* N/A           N/A                     N/A
* ====================================================================================================
**/
public class mySkillsAndCertifcations {
    
@AuraEnabled(cacheable=true)
public static datawrapper getMyCertificationsAndSkills(){
        List<Certifications__c> certSkillList = new List<Certifications__c>();
        List<skillCert> skillList = new List<skillCert>();
        User uRec = [SELECT Id,ContactId FROM User WHERE Id=:Userinfo.getUserId()];
        certSkillList = [SELECT id,Name,contact__c,Certification_Name__c,Other__c,Completion_Date__c,Last_Used_Project_Name__c,Skill__r.Name,Skill__c,Skill_Rating__c,Type__c FROM Certifications__c WHERE contact__c=:uRec.ContactId];
        for(Certifications__c exp : certSkillList){
          
           skillCert ex = new skillCert();
            if(exp.Type__c == 'Skill'){
                ex.name = exp.Skill__r.Name; 
                ex.isSkill = true;
                ex.rating = exp.Skill_Rating__c;
            }else{
                ex.name = exp.Certification_Name__c != 'Other' ? exp.Certification_Name__c : exp.Other__c; 
                ex.certifcationdate = exp.Completion_Date__c;
                 ex.isSkill = false;
            }
            ex.typeval = exp.Type__c;
            ex.recordid = exp.Id;

            skillList.add(ex);
        }
        datawrapper dw = new datawrapper();
        dw.resourceId = uRec.ContactId;
        dw.skillList=skillList;
        return dw;
    }
    
    public class datawrapper {
        @AuraEnabled
        public string resourceId;
        @AuraEnabled
        public List<skillCert> skillList;
    }
    
    public class skillCert{
        @AuraEnabled
        public string name;
         @AuraEnabled
        public Date certifcationdate;
         @AuraEnabled
        public boolean isSkill;
         @AuraEnabled
        public string typeval;
        @AuraEnabled
        public string rating;
         @AuraEnabled
        public string recordid;
        
    }

}