force-app/main/default/objects/Case/fields/Request_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Request_Sub_Type__c</fullName>
    <label>Request Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Educational Details</fullName>
            </value>
            <value>
                <fullName>Bank Details</fullName>
            </value>
            <value>
                <fullName>Family/Dependent Information</fullName>
            </value>
            <value>
                <fullName>Offboarding</fullName>
            </value>
            <value>
                <fullName>Leave Request</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Problem</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_TM_User__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Resource_Manager__c.field-meta.xml
<CustomField>
    <fullName>Resource_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Manager</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Resource</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contacts (Resource Manager)</relationshipLabel>
    <relationshipName>Contacts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/caseAssignmentToManager.cls
/**
* @author Subba Kalavala
* @date 2/22/2023
* @description  caseAssignmentToManager Class to update the ownership of the case.
*
*               Test code coverage provided by the following test class:
*               - 
*
* CHANGE HISTORY
* ====================================================================================================
* DATE          NAME                    DESCRIPTION
* N/A           N/A                     N/A
* ====================================================================================================
**/
public without sharing class caseAssignmentToManager implements TriggerAction.BeforeInsert {
    /**
* @author Subba Kalavala
* @date 2/22/2023
* @description After Insert 
*
* CHANGE HISTORY
* ====================================================================================================
* DATE          NAME                    DESCRIPTION
* N/A           N/A                     N/A
* ====================================================================================================
**/
    public void beforeInsert(List<Case> newList) {      
        System.debug(LoggingLevel.DEBUG, 'caseAssignmentToManager.beforeInsert() : BEGIN');
        updateOwnership(newList);
        System.debug(LoggingLevel.DEBUG, 'caseAssignmentToManager.beforeInsert() : END');       
    }
       /**
*   {Purpose} - Method to assign the Owner 
*
*   CHANGE HISTORY
*   ====================================================================================================
*   Date        Name                    Description
*   N/A         N/A                     N/A
*   ====================================================================================================
**/
    public void updateOwnership(List<Case> newlist) {
       Map<String,Contact> contactWithManager = new Map<String,contact>();
    
       set<Id> contactIds = new set<Id>();
       List<Case> filteredCase = new List<Case>();
        for(Case casenew : newlist){
            if(casenew.Type == 'Apply Resignation' || casenew.Type == 'Request for Special Leaves'){
              filteredCase.add(casenew);
              contactIds.add(casenew.ContactId);
            }
        }
        if(!filteredCase.isEmpty()){
            for(Contact con : [SELECT Id,Resource_Manager__c,Resource_Manager__r.EMS_TM_User__c,ReportsToId,ReportsTo.EMS_TM_User__c 
                               FROM Contact 
                               WHERE Id IN:contactIds
                                AND RecordTypeid =: contactConstant.RESOURCE_RECORDTYPEID]){
               contactWithManager.put(con.id,con); 
            }
            
            for(Case cnew : filteredCase){
                if(contactWithManager.containsKey(cnew.ContactId)){
                    Id ResourceManager = contactWithManager.get(cnew.ContactId).Resource_Manager__r.EMS_TM_User__c;
                    Id ReportingManager = contactWithManager.get(cnew.ContactId).ReportsTo.EMS_TM_User__c;
                    if(cnew.Request_Sub_Type__c == 'Offboarding' && (ReportingManager != null || ResourceManager != null)){
                        cnew.OwnerId = ResourceManager != null ? ResourceManager : ReportingManager;
                    }else if(ReportingManager != null && (cnew.Request_Sub_Type__c == 'Paternity' || cnew.Request_Sub_Type__c == 'Marriage' || cnew.Request_Sub_Type__c == '	Bereavement Leave' || cnew.Request_Sub_Type__c == 'Comp off')){
                        cnew.OwnerId = ReportingManager;
                    }
                }
            }
        }
    }
}