force-app/main/default/objects/Fiscal_Year__c/Fiscal_Year__c.object-meta.xml
<CustomObject>
    <label>Fiscal Year</label>
    <nameField>
        <label>Fiscal Year Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fiscal Years</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reward_And_Recognition__c/Reward_And_Recognition__c.object-meta.xml
<CustomObject>
    <label>Reward And Recognition</label>
    <nameField>
        <displayFormat>REC{0000000}</displayFormat>
        <label>Nominee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rewards And Recognitions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reward_And_Recognition__c/fields/Award_Type__c.field-meta.xml
<CustomField>
    <fullName>Award_Type__c</fullName>
    <label>Award Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Best Entrepreneur</fullName>
            </value>
            <value>
                <fullName>Most Professional</fullName>
            </value>
            <value>
                <fullName>Rising Star</fullName>
            </value>
            <value>
                <fullName>Rock Star</fullName>
            </value>
            <value>
                <fullName>Service Awards</fullName>
            </value>
            <value>
                <fullName>Recognize</fullName>
            </value>
            <value>
                <fullName>Shout Out</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reward_And_Recognition__c/fields/Fiscal_Year__c.field-meta.xml
<CustomField>
    <fullName>Fiscal_Year__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fiscal Year</label>
    <referenceTo>Fiscal_Year__c</referenceTo>
    <relationshipLabel>Rewards And Recognitions</relationshipLabel>
    <relationshipName>Rewards_And_Recognitions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reward_And_Recognition__c/fields/Nomination_Submitted__c.field-meta.xml
<CustomField>
    <fullName>Nomination_Submitted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Nomination Submitted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Reward_And_Recognition__c/fields/Primary_Nomination__c.field-meta.xml
<CustomField>
    <fullName>Primary_Nomination__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Nomination</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Reward_And_Recognition__c/fields/Reason_for_award__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_award__c</fullName>
    <label>Reason for award</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Reward_And_Recognition__c/fields/Recognization_By__c.field-meta.xml
<CustomField>
    <fullName>Recognization_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Stores the information about the user of user who created this</inlineHelpText>
    <label>Recognization By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Rewards_And_Recognitions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reward_And_Recognition__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <label>Resource</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Rewards And Recognitions</relationshipLabel>
    <relationshipName>Rewards_And_Recognitions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reward_And_Recognition__c/fields/Secondary_Nomination__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Nomination__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Secondary Nomination</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Reward_And_Recognition__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nominated</fullName>
                <default>true</default>
                <label>Nominated</label>
            </value>
            <value>
                <fullName>Review In Progress</fullName>
            </value>
            <value>
                <fullName>Not Qualified</fullName>
            </value>
            <value>
                <fullName>Winner</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reward_And_Recognition__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ShoutOut</fullName>
            </value>
            <value>
                <fullName>Recognize</fullName>
            </value>
            <value>
                <fullName>Annual Award</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reward_And_Recognition__c/recordTypes/Nominations.recordType-meta.xml
<RecordType>
    <fullName>Nominations</fullName>
    <active>true</active>
    <label>Nominations</label>
</RecordType>

force-app/main/default/classes/AnnualAwardNominationsController.cls
public without sharing class AnnualAwardNominationsController {

    public static final String RECORD_TYPE_NAME = 'Nominations'; 
    public static final String STATUS_NOMINATED = 'Nominated';

    @AuraEnabled(cacheable=true)
    public static List<Reward_And_Recognition__c> getAnnualAwardNominationRecords() {
        Id UserId = UserInfo.getUserId();
        List<Reward_And_Recognition__c> annualAwardList;
        Id nominationsRecTypeId = Schema.SObjectType.Reward_And_Recognition__c.getRecordTypeInfosByName().get(RECORD_TYPE_NAME).getRecordTypeId();
        try {
            annualAwardList = [
                            SELECT Id, Award_Type__c,Fiscal_Year__c,Primary_Nomination__c,Secondary_Nomination__c,Nomination_Submitted__c,
                            Reason_for_award__c,Recognization_By__c,Resource__c,Resource__r.Name,Status__c,Type__c,RecordTypeId,CreatedById
                            FROM Reward_And_Recognition__c
                            WHERE CreatedById =: UserId AND RecordTypeId =: nominationsRecTypeId AND Recognization_By__c =:UserId AND Status__c =: STATUS_NOMINATED
        ];
        } catch (Exception e) {
            throw new AuraHandledException('Unable to retrieve AnnualAwardNomination records: ' + e.getMessage());
        }
        System.debug('IN annualAwardList ' + annualAwardList.toString());
        return annualAwardList;    
    }

    @AuraEnabled
    public static List<Reward_And_Recognition__c> createAnnualAwardNominationRecords(List<Reward_And_Recognition__c> recordsToCreate,Id currentfy) {
        List<Reward_And_Recognition__c> awardListToInsert = new List<Reward_And_Recognition__c>();
        Id nominationsRecTypeId = Schema.SObjectType.Reward_And_Recognition__c.getRecordTypeInfosByName().get(RECORD_TYPE_NAME).getRecordTypeId();
        System.debug('### INSIDE createAnnualAwardNominationRecords');
        System.debug('### recordsToCreate value ' + recordsToCreate);

        for(Reward_And_Recognition__c rrr : recordsToCreate) {
            rrr.RecordTypeId = nominationsRecTypeId;
            rrr.Fiscal_Year__c = currentfy;
            awardListToInsert.add(rrr);
        }
        
        List<Database.UpsertResult> results;
        try {
            System.debug('### awardListToInsert value ' + awardListToInsert.toString());
            results = Database.upsert(awardListToInsert, false);
        } catch (DmlException e) {
            throw new AuraHandledException('Unable to perform the DML operation on Reward_And_Recognition__c records: ' + e.getMessage());
        }

        for (Database.UpsertResult result : results) {
            if (result.isSuccess()) {
                System.debug('Successfully inserted Reward_And_Recognition__c record: ' + result.getId());
            } else {
                for (Database.Error error : result.getErrors()) {
                    System.debug('Error Status: ' + error.getStatusCode() + ', Error Fields: ' + error.getFields());
                }
            }
        }
        System.debug('B4 RETURN : ' + awardListToInsert.toString());
        return awardListToInsert;
    }

    @AuraEnabled
    public static List<Reward_And_Recognition__c> submitAnnualAwardNominationRecords(List<Reward_And_Recognition__c> recordsToSubmit,Id currentfy) {
        List<Reward_And_Recognition__c> awardListToSubmit = new List<Reward_And_Recognition__c>();
        Id nominationsRecTypeId = Schema.SObjectType.Reward_And_Recognition__c.getRecordTypeInfosByName().get(RECORD_TYPE_NAME).getRecordTypeId();
        System.debug('### INSIDE submitAnnualAwardNominationRecords');
        System.debug('### recordsToSubmit value ' + recordsToSubmit);
        System.debug('### nominationsRecTypeId value ' + nominationsRecTypeId);

        for(Reward_And_Recognition__c rrr : recordsToSubmit) {
            rrr.RecordTypeId = nominationsRecTypeId;
            rrr.Fiscal_Year__c = currentfy;
            rrr.Nomination_Submitted__c = true;
            awardListToSubmit.add(rrr);
        }
        
        List<Database.UpsertResult> results;
        try {
            results = Database.upsert(awardListToSubmit, false);
        } catch (DmlException e) {
            throw new AuraHandledException('Unable to perform the DML operation on Reward_And_Recognition__c records: ' + e.getMessage());
        }

        for (Database.UpsertResult result : results) {
            if (result.isSuccess()) {
                System.debug('Successfully inserted Reward_And_Recognition__c record: ' + result.getId());
            } else {
                for (Database.Error error : result.getErrors()) {
                    System.debug('Error Status: ' + error.getStatusCode() + ', Error Fields: ' + error.getFields());
                }
            }
        }
        return awardListToSubmit;
    }
}