force-app/main/default/objects/Fiscal_Year__c/Fiscal_Year__c.object-meta.xml
<CustomObject>
    <label>Fiscal Year</label>
    <nameField>
        <label>Fiscal Year Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fiscal Years</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reward_And_Recognition__c/Reward_And_Recognition__c.object-meta.xml
<CustomObject>
    <label>Reward And Recognition</label>
    <nameField>
        <displayFormat>REC{0000000}</displayFormat>
        <label>Nominee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rewards And Recognitions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reward_And_Recognition__c/fields/Award_Type__c.field-meta.xml
<CustomField>
    <fullName>Award_Type__c</fullName>
    <label>Award Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Best Entrepreneur</fullName>
            </value>
            <value>
                <fullName>Most Professional</fullName>
            </value>
            <value>
                <fullName>Rising Star</fullName>
            </value>
            <value>
                <fullName>Rock Star</fullName>
            </value>
            <value>
                <fullName>Service Awards</fullName>
            </value>
            <value>
                <fullName>Recognize</fullName>
            </value>
            <value>
                <fullName>Shout Out</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reward_And_Recognition__c/fields/Fiscal_Year__c.field-meta.xml
<CustomField>
    <fullName>Fiscal_Year__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fiscal Year</label>
    <referenceTo>Fiscal_Year__c</referenceTo>
    <relationshipLabel>Rewards And Recognitions</relationshipLabel>
    <relationshipName>Rewards_And_Recognitions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reward_And_Recognition__c/fields/of_Primary_Nominations__c.field-meta.xml
<CustomField>
    <fullName>of_Primary_Nominations__c</fullName>
    <label># of Primary Nominations</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Reward_And_Recognition__c/fields/of_Secondary_Nominations__c.field-meta.xml
<CustomField>
    <fullName>of_Secondary_Nominations__c</fullName>
    <label># of Secondary Nominations</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Reward_And_Recognition__c/fields/Primary_Nomination__c.field-meta.xml
<CustomField>
    <fullName>Primary_Nomination__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Nomination</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Reward_And_Recognition__c/fields/Reason_for_award__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_award__c</fullName>
    <label>Reason for award</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Reward_And_Recognition__c/fields/Recognization_By__c.field-meta.xml
<CustomField>
    <fullName>Recognization_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Stores the information about the user of user who created this</inlineHelpText>
    <label>Recognization By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Rewards_And_Recognitions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reward_And_Recognition__c/fields/Recognization_By_Text__c.field-meta.xml
<CustomField>
    <fullName>Recognization_By_Text__c</fullName>
    <label>Recognization By (Text)</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Reward_And_Recognition__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <label>Resource</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Rewards And Recognitions</relationshipLabel>
    <relationshipName>Rewards_And_Recognitions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reward_And_Recognition__c/fields/Secondary_Nomination__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Nomination__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Secondary Nomination</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Reward_And_Recognition__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nominated</fullName>
                <default>true</default>
                <label>Nominated</label>
            </value>
            <value>
                <fullName>Review In Progress</fullName>
            </value>
            <value>
                <fullName>Not Qualified</fullName>
            </value>
            <value>
                <fullName>Winner</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reward_And_Recognition__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ShoutOut</fullName>
            </value>
            <value>
                <fullName>Recognize</fullName>
            </value>
            <value>
                <fullName>Annual Award</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reward_And_Recognition__c/recordTypes/Nominations.recordType-meta.xml
<RecordType>
    <fullName>Nominations</fullName>
    <active>true</active>
    <label>Nominations</label>
</RecordType>

force-app/main/default/objects/Reward_And_Recognition__c/recordTypes/Scoring.recordType-meta.xml
<RecordType>
    <fullName>Scoring</fullName>
    <active>true</active>
    <description>Used  for Annual Awards Scoring</description>
    <label>Scoring</label>
</RecordType>

force-app/main/default/classes/BatchToCreateScoringForAwards.cls
global class BatchToCreateScoringForAwards implements Database.Batchable<sObject> {
    global Database.QueryLocator start(Database.BatchableContext BC) {
         Id nomRecordTypeId = Schema.SObjectType.Reward_And_Recognition__c.getRecordTypeInfosByName().get('Nominations').getRecordTypeId();
         return Database.getQueryLocator([SELECT Id,Status__c,Award_Type__c,Resource__c,Primary_Nomination__c,
                                          Secondary_Nomination__c,Recognization_By__c,Recognization_By__r.Name,Reason_for_award__c 
                                          FROM Reward_And_Recognition__c WHERE Status__c = 'Nominated'
                                          and RecordTypeId=:nomRecordTypeId and Type__c = 'Annual Award']);
    }
    global void execute(Database.BatchableContext BC, List<Reward_And_Recognition__c> rrList) {
       Fiscal_Year__c currentFY = [SELECT Id,Name,Start_Date__c,End_Date__c FROM Fiscal_Year__c where Start_Date__c = THIS_FISCAL_YEAR Order BY Start_Date__c ASC];
        List<Reward_And_Recognition__c> scoringInsert = new List<Reward_And_Recognition__c>(); 
         List<Reward_And_Recognition__c> scoringUpdate = new List<Reward_And_Recognition__c>(); 
        Map<String, List<Reward_And_Recognition__c>>  awardWithNomnMap = new Map<String, List<Reward_And_Recognition__c>>();
        Map<String, Map<String,List<Reward_And_Recognition__c>>>  awardresourceWithNomnMap = new Map<String, Map<String,List<Reward_And_Recognition__c>>>();
        Map<String, Reward_And_Recognition__c>  scoringWithNomnMap = new Map<String, Reward_And_Recognition__c>();
        set<Id> contactIds = new set<Id>();
        for(Reward_And_Recognition__c rr : rrList){
            contactIds.add(rr.Resource__c);
            if(awardWithNomnMap.containsKey(rr.Award_Type__c)){
                awardWithNomnMap.get(rr.Award_Type__c).add(rr);
            }else{
                awardWithNomnMap.put(rr.Award_Type__c, new List<Reward_And_Recognition__c>{rr});  
            } 
        }
        system.debug(awardWithNomnMap.size()+'===awardWithNomnMap===='+awardWithNomnMap);
         system.debug(contactIds.size()+'===contactIds===='+contactIds);
        
         for(String award : awardWithNomnMap.keySet()){
                Map<String,List<Reward_And_Recognition__c>> tempMap = new Map<String,List<Reward_And_Recognition__c>>();
                for(Reward_And_Recognition__c res : awardWithNomnMap.get(award)){
                    if(tempMap.containsKey(res.Resource__c)){
                     tempMap.get(res.Resource__c).add(res);   
                    }else{
                      tempMap.put(res.Resource__c, new List<Reward_And_Recognition__c>{res});  
                    } 
                }
                awardresourceWithNomnMap.put(award,tempMap);
           } 
         system.debug(awardresourceWithNomnMap.size()+'===awardresourceWithNomnMap===='+awardresourceWithNomnMap);
        
        Id scoringRecordTypeId = Schema.SObjectType.Reward_And_Recognition__c.getRecordTypeInfosByName().get('Scoring').getRecordTypeId();
        for(Reward_And_Recognition__c score : [SELECT Id,Award_Type__c,Resource__c FROM Reward_And_Recognition__c WHERE Resource__c IN:contactIds and  RecordTypeId=:scoringRecordTypeId and Status__c = 'Review In Progress' ] ){
           String uniqueKey = score.Resource__c+';'+score.Award_Type__c;
           scoringWithNomnMap.put(uniqueKey,score);
        }
        system.debug(scoringWithNomnMap.size()+'===scoringWithNomnMap===='+scoringWithNomnMap);
        
        for(String award : awardresourceWithNomnMap.keySet()){
             Map<String,List<Reward_And_Recognition__c>> resMap = awardresourceWithNomnMap.get(award);
            for(String resource : resMap.keySet()){
                Decimal noOfPrimary = 0;
                Decimal noOfSecondary = 0;
                String amendComments = '';
                String amendRec = '';
                for(Reward_And_Recognition__c noms : resMap.get(resource)){
                    if(noms.Primary_Nomination__c){
                        noOfPrimary++;
                    }else if(noms.Secondary_Nomination__c){
                        noOfSecondary++;
                    }
                    if(amendComments != null){
                      String resourcestring = '<b>'+noms.Recognization_By__r.Name+' :</b> <br/>';
                      amendComments = amendComments+'<br/>'+resourcestring + noms.Reason_for_award__c;  
                    }else{
                      String resourcestring = '<b>'+noms.Recognization_By__r.Name+' :</b> <br/>';
                      amendComments = resourcestring + noms.Reason_for_award__c;
                       
                    }
                    if(amendRec != null){
                      String resourcestring = '<b>'+noms.Recognization_By__r.Name+'</b> <br/>';
                      amendRec = amendRec+resourcestring;  
                    }else{
                      String resourcestring = '<b>'+noms.Recognization_By__r.Name+'</b> <br/>';
                      amendRec = resourcestring ;
                       
                    }
                }
                 String uniqueKey = resource+';'+award; 
                  if(scoringWithNomnMap.containsKey(uniqueKey)){
                      Reward_And_Recognition__c scrr = new Reward_And_Recognition__c();
                      scrr.Id = scoringWithNomnMap.get(uniqueKey).Id;
                      scrr.of_Primary_Nominations__c = noOfPrimary;
                      scrr.of_Secondary_Nominations__c = noOfSecondary;
                      scrr.Reason_for_award__c = amendComments;
                      scrr.Recognization_By_Text__c = amendRec;
                      scoringUpdate.add(scrr); 
                  }else{
                     Reward_And_Recognition__c scrr = new Reward_And_Recognition__c();
                      scrr.RecordTypeId = scoringRecordTypeId;
                      scrr.Status__c = 'Review In Progress';
                      scrr.Resource__c = resource;
                      scrr.Award_Type__c = award;
                      scrr.of_Primary_Nominations__c = noOfPrimary;
                      scrr.of_Secondary_Nominations__c = noOfSecondary;
                      scrr.Reason_for_award__c = amendComments;
                      scrr.Fiscal_Year__c = CurrentFY.Id;
                      scrr.Recognization_By_Text__c = amendRec;
                      scoringInsert.add(scrr);
                      system.debug('==scrr===='+scrr); 
                  }
 
            }
            
        } 
                                
        system.debug('==scoringInsert===='+scoringInsert); 
        system.debug('==scoringUpdate===='+scoringUpdate); 
        
        try{
            update scoringUpdate;
            insert scoringInsert;
          
        }catch(exception ex){
           LogException.logHandledException(ex, 'BatchToCreateKRAforQuaterly', 'execute');  
        }
    }
    
    global void finish(Database.BatchableContext BC) {
        
    }
}