force-app/main/default/objects/EMS_TM_Project__c/EMS_TM_Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_TM_Project__c/fields/Offshore_Project_Manager__c.field-meta.xml
<CustomField>
    <fullName>Offshore_Project_Manager__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Offshore Project Manager</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND (2 OR 3)</booleanFilter>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Resource</value>
        </filterItems>
        <filterItems>
            <field>Contact.Resource_Role__r.Name</field>
            <operation>equals</operation>
            <value>Sr Project Manager</value>
        </filterItems>
        <filterItems>
            <field>Contact.Resource_Role__r.Name</field>
            <operation>equals</operation>
            <value>Project Manager</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Projects (Offshore Project Manager)</relationshipLabel>
    <relationshipName>Projects1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Project__c/fields/Project_Manager__c.field-meta.xml
<CustomField>
    <fullName>Project_Manager__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Onshore Project Manager</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND (2 OR 3)</booleanFilter>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Resource</value>
        </filterItems>
        <filterItems>
            <field>Contact.Resource_Role__r.Name</field>
            <operation>equals</operation>
            <value>Sr Project Manager</value>
        </filterItems>
        <filterItems>
            <field>Contact.Resource_Role__r.Name</field>
            <operation>equals</operation>
            <value>Project Manager</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Project__c/fields/Type_Of_Project__c.field-meta.xml
<CustomField>
    <fullName>Type_Of_Project__c</fullName>
    <label>Type of Project</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Client Projects</fullName>
            </value>
            <value>
                <fullName>Internal Projects</fullName>
            </value>
            <value>
                <fullName>Global Projects</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project_Manager__c.field-meta.xml
<CustomField>
    <fullName>Project_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_to_Project_Mapping__mdt/Opportunity_to_Project_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>Opportunity to Project Mapping</label>
    <pluralLabel>Opportunity to Project Mapping</pluralLabel>
</CustomObject>

force-app/main/default/objects/Opportunity_to_Project_Mapping__mdt/fields/Opportunity_Field_API__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Field_API__c</fullName>
    <label>Opportunity Field API</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_to_Project_Mapping__mdt/fields/Project_Field_API__c.field-meta.xml
<CustomField>
    <fullName>Project_Field_API__c</fullName>
    <label>Project Field API</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/createProjectAfterOppWon.cls
/**
* @author Subba
* @date 09/01/2023
* @description  createProjectAfterOppWon Class to create new project when Opportunity is Closed Won 
*              
*               Test code coverage provided by the following test class:
*               - createProjectAfterOppWonTest
*
* CHANGE HISTORY
* ====================================================================================================
* DATE          NAME                    DESCRIPTION
* N/A           N/A                     N/A
* ====================================================================================================
**/
public without sharing class createProjectAfterOppWon implements TriggerAction.AfterUpdate {
/**
* @author Subba
* @date 09/01/2023
* @description After Update 
*
* CHANGE HISTORY
* ====================================================================================================
* DATE          NAME                    DESCRIPTION
* N/A           N/A                     N/A
* ====================================================================================================
**/
    public void afterUpdate(List<Opportunity> newList, List<Opportunity> oldList) {      
        System.debug(LoggingLevel.DEBUG, 'createProjectAfterOppWon.afterUpdate() : BEGIN');
        createNewProject(newList,new Map<Id, Opportunity>(oldList));
        System.debug(LoggingLevel.DEBUG, 'createProjectAfterOppWon.afterUpdate() : END');       
    }
    /**
*   {Purpose} - Method for calculate available leave balance of the employee
*
*   CHANGE HISTORY
*   ====================================================================================================
*   Date        Name                    Description
*   N/A         N/A                     N/A
*   ====================================================================================================
**/
    private void createNewProject(List<Opportunity> newList, Map<Id,Opportunity> oldMap){
        Map<Id,Opportunity> filteredOppMap = new Map<Id,Opportunity>();
        List<EMS_TM_Project__c> projectInsert = new List<EMS_TM_Project__c>();
        for(Opportunity opp : newList){
            if(opp.StageName == 'Closed Won' && opp.StageName != oldMap.get(opp.Id).StageName ){
               filteredOppMap.put(opp.Id,opp); 
            }
        } 
        List<Opportunity_to_Project_Mapping__mdt> oppPrjMap = new List<Opportunity_to_Project_Mapping__mdt>(); 
        oppPrjMap = [SELECT Id,Opportunity_Field_API__c,Project_Field_API__c FROM Opportunity_to_Project_Mapping__mdt];
        SYstem.debug('oppPrjMap'+oppPrjMap);
           
        if(!filteredOppMap.isEmpty() && !oppPrjMap.isEmpty()){
          
         //  Id clientProjectRecordTypeId = Schema.SObjectType.EMS_TM_Project__c.getRecordTypeInfosByName().get('Client Projects').getRecordTypeId();
            for(Opportunity opp : filteredOppMap.values()){
                 EMS_TM_Project__c  proj = new EMS_TM_Project__c();
            //     proj.RecordTypeId = clientProjectRecordTypeId;
                   proj.Type_Of_Project__c ='Client Projects';
                //smaske: Required Fields ON/OFF Shore Manager field was missing so test class was failing .
                proj.Offshore_Project_Manager__c = opp.Project_Manager__c;
                proj.Project_Manager__c = opp.Project_Manager__c; 
                
                for(Opportunity_to_Project_Mapping__mdt ppm : oppPrjMap){
                    System.debug('ppm'+ppm);
                 proj.put(ppm.Project_Field_API__c,opp.get(ppm.Opportunity_Field_API__c)); 
                } 
                projectInsert.add(proj);
            }
        }
        System.debug('projectInsert'+projectInsert);
        try{
         insert projectInsert;  
            System.debug('projectInsert'+projectInsert);
        }catch(exception ex){
            SYstem.debug('eeee'+ex.getMessage());
         LogException.logHandledException(ex, 'createProjectAfterOppWon', 'CreateProject');   
        }  
    }
}