force-app/main/default/objects/EMS_Timesheet__c/EMS_Timesheet__c.object-meta.xml
<CustomObject>
    <label>Timesheet</label>
    <nameField>
        <displayFormat>TS-{0000}</displayFormat>
        <label>Time Sheet ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_Timesheet__c/fields/enddate__c.field-meta.xml
<CustomField>
    <fullName>enddate__c</fullName>
    <formula>CASE( 
MOD( EMS_TM_Week__c - DATE(1900, 1, 6),7), 
0, EMS_TM_Week__c + 7, 
1, EMS_TM_Week__c + 6, 
2, EMS_TM_Week__c + 5, 
3, EMS_TM_Week__c + 4, 
4, EMS_TM_Week__c + 3, 
5, EMS_TM_Week__c + 2, 
6, EMS_TM_Week__c + 1,
7, EMS_TM_Week__c + 0, 
NULL 
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>endWeek</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Timesheets</relationshipLabel>
    <relationshipName>Timesheets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/Week_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Week_Start_Date__c</fullName>
    <label>Week Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/WFH_Fri__c.field-meta.xml
<CustomField>
    <fullName>WFH_Fri__c</fullName>
    <defaultValue>false</defaultValue>
    <label>WFH Fri</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/WFH_Mon__c.field-meta.xml
<CustomField>
    <fullName>WFH_Mon__c</fullName>
    <defaultValue>false</defaultValue>
    <label>WFH Mon</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/WFH_Sat__c.field-meta.xml
<CustomField>
    <fullName>WFH_Sat__c</fullName>
    <defaultValue>false</defaultValue>
    <label>WFO Saturday</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/WFH_Sun__c.field-meta.xml
<CustomField>
    <fullName>WFH_Sun__c</fullName>
    <defaultValue>false</defaultValue>
    <label>WFO Sunday</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/WFH_Thu__c.field-meta.xml
<CustomField>
    <fullName>WFH_Thu__c</fullName>
    <defaultValue>false</defaultValue>
    <label>WFO Thursday</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/WFH_Tue__c.field-meta.xml
<CustomField>
    <fullName>WFH_Tue__c</fullName>
    <defaultValue>false</defaultValue>
    <label>WFH Tue</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/WFH_Wed__c.field-meta.xml
<CustomField>
    <fullName>WFH_Wed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>WFH Wed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/countWfoDaysForResource.cls
public class countWfoDaysForResource {
    
    public static Integer GetWfoDaysForCurrentMonth() {
        Date today = Date.today();
        Integer currentYear = today.year();
        Integer currentMonth = today.month();
        Date monthStartDate = Date.newInstance(currentYear, currentMonth, 1);
        Integer lastDayOfMonth = Date.daysInMonth(currentYear, currentMonth);
        Date monthEndDate = Date.newInstance(currentYear, currentMonth, lastDayOfMonth);
        
        System.debug('Current Month Start Date: ' + monthStartDate);
        System.debug('Current Month End Date: ' + monthEndDate);
        
        Integer wfoDaysCount = 0;
        User usrConId = [SELECT Id, ContactId FROM User WHERE Id =: LeaveRequestConstant.LOGGEDIN_USERID];
        // Query Timesheet records that have a date range overlapping with the current month
        List<EMS_Timesheet__c> timesheetRecords = [
            SELECT Id,WFH_Mon__c,WFH_Tue__c,WFH_Wed__c,WFH_Thu__c,WFH_Fri__c,WFH_Sat__c,WFH_Sun__c,Week_Start_Date__c,enddate__c  from EMS_Timesheet__c 
            WHERE Week_Start_Date__c <= :monthEndDate AND enddate__c  >= :monthStartDate and Resource__c  =:usrConId.ContactId];//usrConId.ContactId
        system.debug('timesheetRecords---'+timesheetRecords);
        for (EMS_Timesheet__c record : timesheetRecords) {
            // Determine the valid range for counting days
            Date validStartDate = record.Week_Start_Date__c < monthStartDate ? monthStartDate : record.Week_Start_Date__c;
            Date validEndDate = record.enddate__c  > monthEndDate ? monthEndDate : record.enddate__c ;
            system.debug('validStartDate---'+validStartDate);
            system.debug('validEndDate---'+validEndDate);
                DateTime dt = DateTime.newInstance(validStartDate.year(), validStartDate.month(), validStartDate.day(), 0, 0, 0);
            DateTime dt2 = DateTime.newInstance(validEndDate.year(), validEndDate.month(), validEndDate.day(), 0, 0, 0);
            Integer startOffset = Integer.valueOf(dt.format('u')) - 1;
            Integer endOffset =  Integer.valueOf(dt2.format('u')) - 1;
            system.debug('startOffset---'+startOffset);
            system.debug('endOffset---'+endOffset);
            //Integer startOffset = (Integer) validStartDate.format('u'); // 'u' gives 1 (Monday) to 7 (Sunday)
            // Integer startOffset = validStartDate.dayOfWeek() - 1; // Convert Monday=1 to index 0
            // Integer endOffset = validEndDate.dayOfWeek() - 1;
            
            List<Boolean> weeklyData = new List<Boolean>{
                record.WFH_Mon__c, record.WFH_Tue__c, record.WFH_Wed__c, record.WFH_Thu__c,
                    record.WFH_Fri__c, record.WFH_Sat__c, record.WFH_Sun__c
                    };
                        system.debug('weeklyData----'+weeklyData);
            
            // Count only the relevant WFO days in the current month
            for (Integer i = startOffset; i <= endOffset; i++) {
                if (weeklyData[i]) {
                    wfoDaysCount++;
                    system.debug('wfoDaysCount----'+wfoDaysCount);
                }
            }
        }
        
        return wfoDaysCount;
    }
    
    // Function to test WFO calculations
    @AuraEnabled(Cacheable = true)
    public static integer RunWfoCalculations() {
        Integer wfoDays = GetWfoDaysForCurrentMonth();
        System.debug('Total Work From Office days in Current Month: ' + wfoDays);
        return wfoDays;
    }
}