force-app/main/default/objects/EMS_Timesheet__c/EMS_Timesheet__c.object-meta.xml
<CustomObject>
    <label>Timesheet</label>
    <nameField>
        <displayFormat>TS-{0000}</displayFormat>
        <label>Time Sheet ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_Timesheet__c/fields/EMS_TM_Project__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>EMS_TM_Project__c</referenceTo>
    <relationshipLabel>Timesheets</relationshipLabel>
    <relationshipName>Timesheets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/EMS_TM_Status__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Not Approved</fullName>
            </value>
            <value>
                <fullName>Reported</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Saved</fullName>
            </value>
            <value>
                <fullName>Locked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Timesheets</relationshipLabel>
    <relationshipName>Timesheets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/Week_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Week_End_Date__c</fullName>
    <label>Week End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/Week_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Week_Start_Date__c</fullName>
    <label>Week Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Assignment__c/EMS_TM_Assignment__c.object-meta.xml
<CustomObject>
    <label>Assignment</label>
    <nameField>
        <displayFormat>A.ID-{0000}</displayFormat>
        <label>Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_TM_Assignment__c/fields/EMS_TM_EmployeeName__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_EmployeeName__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Employee Name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Resource</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Assignments</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Assignment__c/fields/EMS_TM_ProjectName_Asgn__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_ProjectName_Asgn__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Name</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>EMS_TM_Project__c.Type_Of_Project__c</field>
            <operation>notEqual</operation>
            <value>Global Projects</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>EMS_TM_Project__c</referenceTo>
    <relationshipLabel>Project Assignees</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Project__c/EMS_TM_Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_TM_Project__c/fields/EMS_TM_Status__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ongoing</fullName>
                <default>true</default>
                <label>Ongoing</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EMS_TM_Project__c/fields/Offshore_Project_Manager__c.field-meta.xml
<CustomField>
    <fullName>Offshore_Project_Manager__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Offshore Project Manager</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND (2 OR 3)</booleanFilter>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Resource</value>
        </filterItems>
        <filterItems>
            <field>Contact.Resource_Role__r.Name</field>
            <operation>equals</operation>
            <value>Sr Project Manager</value>
        </filterItems>
        <filterItems>
            <field>Contact.Resource_Role__r.Name</field>
            <operation>equals</operation>
            <value>Project Manager</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Projects (Offshore Project Manager)</relationshipLabel>
    <relationshipName>Projects1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Project__c/fields/Project_Manager__c.field-meta.xml
<CustomField>
    <fullName>Project_Manager__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Onshore Project Manager</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND (2 OR 3)</booleanFilter>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Resource</value>
        </filterItems>
        <filterItems>
            <field>Contact.Resource_Role__r.Name</field>
            <operation>equals</operation>
            <value>Sr Project Manager</value>
        </filterItems>
        <filterItems>
            <field>Contact.Resource_Role__r.Name</field>
            <operation>equals</operation>
            <value>Project Manager</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/NotifyTesting.cls
public class NotifyTesting {
    public static void getingcont(){
         Date todayval = system.today(); 
        Date considerDate = todayval.toStartofWeek().addDays(-2);
        Date weekStart = considerDate.toStartofWeek().addDays(1);
        Date weekEnd = considerDate.toStartofWeek().addDays(7);
        System.debug('===weekStart==='+weekStart);
        System.debug('===weekEnd==='+weekEnd);
       List<Contact> Contctwotc = [select id,name from contact where id not in(select resource__c from EMS_Timesheet__C where Week_Start_Date__c>=:weekStart AND Week_End_Date__c<=:weekEnd)];
                                 system.debug('Contctwotc==========='+Contctwotc);
// Map to store project manager Ids and their corresponding projects
Map<Id, List<EMS_TM_Project__c>> managerToProjectsMap = new Map<Id, List<EMS_TM_Project__c>>();

// Map to store project Ids and their corresponding contacts
Map<Id, List<Id>> projectToContactsMap = new Map<Id, List<Id>>();

// Map to store contact Ids and their corresponding timesheets
Map<Id, List<EMS_Timesheet__c>> contactToTimesheetsMap = new Map<Id, List<EMS_Timesheet__c>>();

// Query for projects assigned to project managers
for (EMS_TM_Project__c project : [SELECT Id, Project_Manager__c, Offshore_Project_Manager__c
                                   FROM EMS_TM_Project__c where EMS_TM_Status__c='Active'
                                   ]) {
    if (!managerToProjectsMap.containsKey(project.Project_Manager__c)) {
        managerToProjectsMap.put(project.Project_Manager__c, new List<EMS_TM_Project__c>());
    }
    managerToProjectsMap.get(project.Project_Manager__c).add(project);

if (!managerToProjectsMap.containsKey(project.Offshore_Project_Manager__c)) {
        managerToProjectsMap.put(project.Offshore_Project_Manager__c, new List<EMS_TM_Project__c>());
    }
    managerToProjectsMap.get(project.Offshore_Project_Manager__c).add(project);
}
    
// Query for contacts assigned to projects
for (EMS_TM_Assignment__c assignment : [SELECT Id, EMS_TM_EmployeeName__c, EMS_TM_ProjectName_Asgn__c FROM EMS_TM_Assignment__c WHERE EMS_TM_ProjectName_Asgn__c IN :managerToProjectsMap.keySet()]) {
    if (!projectToContactsMap.containsKey(assignment.EMS_TM_ProjectName_Asgn__c)) {
        projectToContactsMap.put(assignment.EMS_TM_ProjectName_Asgn__c, new List<Id>());
    }
    projectToContactsMap.get(assignment.EMS_TM_ProjectName_Asgn__c).add(assignment.EMS_TM_EmployeeName__c);
}
/*
for (EMS_Timesheet__c timesheet : [SELECT Id, Resource__c FROM EMS_Timesheet__c WHERE Resource__c IN :projectToContactsMap.values()]) {
    if (!contactToTimesheetsMap.containsKey(timesheet.Resource__c)) {
        contactToTimesheetsMap.put(timesheet.Resource__c, new List<EMS_Timesheet__c>());
    }
    contactToTimesheetsMap.get(timesheet.Resource__c).add(timesheet);
}
*/
//List<Messaging.SingleEmailMessage> emailMessages = new List<Messaging.SingleEmailMessage>();

// Prepare email messages for each project manager
List<Messaging.SingleEmailMessage> emailMessages = new List<Messaging.SingleEmailMessage>();

for (Contact manager : Contctwotc) {
    List<String> employeesWithoutTimesheets = new List<String>();
    for (EMS_TM_Project__c project : managerToProjectsMap.get(manager.Id)) {
        for (Id contactId : projectToContactsMap.get(project.Id)) {
            if (!contactToTimesheetsMap.containsKey(contactId) || contactToTimesheetsMap.get(contactId).isEmpty()) {
                employeesWithoutTimesheets.add(contactId);
            }
        }
    }

    // Prepare email message
    if (!employeesWithoutTimesheets.isEmpty()) {
        Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
        email.setSubject('Employees without timesheets');
        email.setHtmlBody('Dear ' + manager.Name + ',<br><br>' +
                         'The following employees have not submitted their timesheets:<br>' +
                         String.join(employeesWithoutTimesheets, ', ') +
                         '<br><br>Regards,<br>Your Company');
        email.setToAddresses(new List<String>{manager.Email});
        emailMessages.add(email);
    }
}

// Send the email messages
if (!emailMessages.isEmpty()) {
    Messaging.sendEmail(emailMessages);
}
        /*
         Date todayval = system.today(); 
        Date considerDate = todayval.toStartofWeek().addDays(-2);
        Date weekStart = considerDate.toStartofWeek().addDays(1);
        Date weekEnd = considerDate.toStartofWeek().addDays(7);
        System.debug('===weekStart==='+weekStart);
        System.debug('===weekEnd==='+weekEnd);
        list<string> Project=new list<string>();
        set<string> pmid=new set<string>();
        map<id,list<string>> mangerwithcontact=new map<id,list<string>>();
         Map<Id, List<Contact>> projectContactMap = new Map<Id, List<Contact>>();
        list<contact> con=[select id,Name from contact where id not in(select Resource__c FROM EMS_Timesheet__c where Week_Start_Date__c>=:weekStart AND Week_End_Date__c<=:weekEnd)];
        for(EMS_TM_Assignment__c ass:[select id,EMS_TM_ProjectName_Asgn__c,EMS_TM_EmployeeName__c,EMS_TM_ProjectName_Asgn__r.Offshore_Project_Manager__c from EMS_TM_Assignment__c where EMS_TM_EmployeeName__c In:Con]){
            Project.Add(ass.EMS_TM_ProjectName_Asgn__c);
            Id projectId = ass.EMS_TM_ProjectName_Asgn__c;
            ID contact = ass.EMS_TM_EmployeeName__c;
             if (!projectContactMap.containsKey(projectId)) {
                projectContactMap.put(projectId, new List<Contact>());
            }
            
            // Add the contact to the list associated with the project
            projectContactMap.get(projectId).add(contact);
            
            //mangerwithcontact.put(ass.EMS_TM_ProjectName_Asgn__r.Offshore_Project_Manager__c,ass.EMS_TM_EmployeeName__c);
        }
        */
    }

    
}