force-app/main/default/objects/EMS_Timesheet__c/EMS_Timesheet__c.object-meta.xml
<CustomObject>
    <label>Timesheet</label>
    <nameField>
        <displayFormat>TS-{0000}</displayFormat>
        <label>Time Sheet ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_Timesheet__c/fields/EMS_TM_Fri__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Fri__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Fri</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/EMS_TM_Mon__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Mon__c</fullName>
    <label>Mon</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/EMS_TM_Sat__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Sat__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Sat</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/EMS_TM_Status__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Not Approved</fullName>
            </value>
            <value>
                <fullName>Reported</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Saved</fullName>
            </value>
            <value>
                <fullName>Locked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/EMS_TM_Thu__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Thu__c</fullName>
    <label>Thu</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/EMS_TM_Tue__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Tue__c</fullName>
    <label>Tue</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/EMS_TM_Wed__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Wed__c</fullName>
    <label>Wed</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/EMS_TM_Week__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Week__c</fullName>
    <label>Week</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Timesheets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/Week_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Week_End_Date__c</fullName>
    <label>Week End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/User/fields/TA_Admin__c.field-meta.xml
<CustomField>
    <fullName>TA_Admin__c</fullName>
    <defaultValue>false</defaultValue>
    <label>TA Admin</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Timesheet_Admin__c.field-meta.xml
<CustomField>
    <fullName>Timesheet_Admin__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Timesheet Admin</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TestClass_EMS_TM_Lock_Previous_Week.cls
@istest
public class TestClass_EMS_TM_Lock_Previous_Week {
        @testSetup
    public static void getAdminUser(){
              user adminuser = TestDataFactory.createAdminUser(false);
             adminuser.TA_Admin__c = true;
             adminuser.Timesheet_Admin__c =true;
             Insert adminuser;
        
    }
      public static testMethod void testschedule() {
            User adminUser = [Select Id From User Where firstname ='Alan' AND IsActive = true Limit 1];
		Test.StartTest();
        EMS_Timesheet__c emsts = new EMS_Timesheet__c();
        emsts.EMS_TM_Status__c='New';
        emsts.User__c=adminuser.id; 
        emsts.EMS_TM_Mon__c=8;
        emsts.EMS_TM_Tue__c=8;
        emsts.EMS_TM_Wed__c=8;
        emsts.EMS_TM_Thu__c=8;
        emsts.EMS_TM_Fri__c=8;
        emsts.EMS_TM_Sat__c=8;
        emsts.EMS_TM_Week__c=System.today()-5;
         emsts.Week_End_Date__c = System.today()-5;
        insert emsts;
          EMS_TM_Lock_Previous_Week batchExecute = new EMS_TM_Lock_Previous_Week(); 
        Database.executeBatch(batchExecute);
		Test.stopTest();
          EMS_Timesheet__c timesheetRec =[SELECT Id,EMS_TM_Status__c FROM EMS_Timesheet__c LIMIT 1];
          System.assertEquals('Locked', timesheetRec.EMS_TM_Status__c);
          
	}
    public static testMethod void testscheduleclass() {
		Test.StartTest();
		EMS_TM_Lock_Previous_Week_sch testsche = new EMS_TM_Lock_Previous_Week_sch();
		String sch = '0 0 23 * * ?';
		system.schedule('Test BatchToCalculateTheAvaiLeaves Check', sch, testsche );
		Test.stopTest();
	}

}