force-app/main/default/objects/EMS_Timesheet__c/EMS_Timesheet__c.object-meta.xml
<CustomObject>
    <label>Timesheet</label>
    <nameField>
        <displayFormat>TS-{0000}</displayFormat>
        <label>Time Sheet ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_Timesheet__c/fields/EMS_TM_Fri__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Fri__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Fri</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/EMS_TM_Mon__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Mon__c</fullName>
    <label>Mon</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/EMS_TM_Sat__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Sat__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Sat</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/EMS_TM_Status__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Not Approved</fullName>
            </value>
            <value>
                <fullName>Reported</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Saved</fullName>
            </value>
            <value>
                <fullName>Locked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/EMS_TM_Sun__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Sun__c</fullName>
    <label>Sun</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/EMS_TM_Thu__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Thu__c</fullName>
    <label>Thu</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/EMS_TM_Tue__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Tue__c</fullName>
    <label>Tue</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/EMS_TM_Wed__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Wed__c</fullName>
    <label>Wed</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/EMS_TM_Week__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Week__c</fullName>
    <label>Week</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Timesheets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/EMS_TM_Auto_Create_Timsheet.cls
global class EMS_TM_Auto_Create_Timsheet implements Schedulable {
    global void execute(SchedulableContext cnt) {

        List<Id> newTimesheetUsers = new List<Id>();
        List<Id> timesheetUsers = new List<Id>();
        List<Id> profileIds = new List<Id>();
        List<EMS_Timesheet__c> newTimeSheets = new List<EMS_Timesheet__c>();

        Date today = Date.today();
        Date weekStart = today.toStartofWeek().addDays(1);
        Date weekEnd = today.toStartofWeek().addDays(7);
        String completeWeek = weekStart + ' - ' + weekEnd;

        List<Profile> profileList = [SELECT Id, Name FROM Profile WHERE Name IN :EMS_TM_GlobalConstants.USERPROFILES];
        for (Profile profile : profileList) {
            profileIds.add(profile.Id);
        }

        List<EMS_Timesheet__c> timeSheets = [SELECT Id, User__c, EMS_TM_Week__c
                                                FROM EMS_Timesheet__c
                                                WHERE EMS_TM_Week__c = :weekStart];
        for (EMS_Timesheet__c timesheet : timeSheets) {
            timesheetUsers.add(timesheet.user__c);
        }

        List<User> usersList = [SELECT Id, ProfileId, FirstName, LastName, Name FROM User WHERE ProfileId IN :profileIds AND UserRole.name !='Leadership' And isActive = true];
        for (User user : usersList) {
            if (!(timesheetUsers.contains(user.Id))) {
                newTimesheetUsers.add(user.Id);
            }
        }

        for (Id userId : newTimesheetUsers) {
            EMS_Timesheet__c timesheet = new EMS_Timesheet__c();
            timesheet.EMS_TM_Sun__c                         = 0;
            timesheet.EMS_TM_Mon__c                         = 0;
            timesheet.EMS_TM_Tue__c                         = 0;
            timesheet.EMS_TM_Wed__c                         = 0;
            timesheet.EMS_TM_Thu__c                         = 0;
            timesheet.EMS_TM_Fri__c                         = 0;
            timesheet.EMS_TM_Sat__c                         = 0;
            timesheet.EMS_TM_Week__c                        = weekStart;
         //   timesheet.Complete_Week__c                      = completeWeek;
            timesheet.EMS_TM_Status__c                      = EMS_TM_GlobalConstants.STATUS_SAVED;
            timesheet.User__c                               = userId;
            timesheet.OwnerId                               = userId;
            newTimeSheets.add(timesheet);
        }

        Database.insert(newTimeSheets, false);
    }
}