force-app/main/default/objects/EMS_Timesheet__c/EMS_Timesheet__c.object-meta.xml
<CustomObject>
    <label>Timesheet</label>
    <nameField>
        <displayFormat>TS-{0000}</displayFormat>
        <label>Time Sheet ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_Timesheet__c/fields/EMS_TM_Status__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Not Approved</fullName>
            </value>
            <value>
                <fullName>Reported</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Saved</fullName>
            </value>
            <value>
                <fullName>Locked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EMS_TM_Timesheet_Record__c/EMS_TM_Timesheet_Record__c.object-meta.xml
<CustomObject>
    <label>Timesheet Line Items</label>
    <nameField>
        <displayFormat>TLI{00000000}</displayFormat>
        <label>Timesheet Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheet Records</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_TM_Timesheet_Record__c/fields/EMS_Timesheet__c.field-meta.xml
<CustomField>
    <fullName>EMS_Timesheet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>EMS_Timesheet</label>
    <referenceTo>EMS_Timesheet__c</referenceTo>
    <relationshipName>Employee_Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Timesheet_Record__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saved</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Reassign</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/editTimeshhetwhenRejected.cls
/**
    * @author Ramakrishna 
    * @date 09/02/2023
    * @description  editTimeshhetwhenRejected  to check weather any one the timesheetRecord is related timesheet 
    *               when we will give edit access for Timesheet.
    *
    *               Test code coverage provided by the following test class:
    *               - 
    *
    * CHANGE HISTORY
    * ====================================================================================================
    * DATE          NAME                    DESCRIPTION
    * N/A           N/A                     N/A
    * ====================================================================================================
    **/
public class editTimeshhetwhenRejected implements TriggerAction.AfterUpdate{
    
          /**
    * @author Ramakrishna
    * @date 09/02/2023
    * @description After Update 
    *
    * CHANGE HISTORY
    * ====================================================================================================
    * DATE          NAME                    DESCRIPTION
    * N/A           N/A                     N/A
    * ====================================================================================================
    **/
    public void afterUpdate(List<EMS_TM_Timesheet_Record__c> newList,List<EMS_TM_Timesheet_Record__c> oldList) {      
        System.debug(LoggingLevel.DEBUG, 'timesheetRecordSubmitted.afterUpdate() : BEGIN');
        Map<id,EMS_TM_Timesheet_Record__c> timesheetOldMap = new Map<id,EMS_TM_Timesheet_Record__c>(oldList);
        wheathertimesheetRejctedupdatetimesheet(newList,timesheetOldMap);
        System.debug(LoggingLevel.DEBUG, 'timesheetRecordSubmitted.afterUpdate() : END');       
    }
     /**
    * @author Ramakrishna
    * @date 09/02/2023
    * @description In this method update Timesheet when timesheetRecord is rejected.
    *
    * CHANGE HISTORY
    * ====================================================================================================
    * DATE          NAME                    DESCRIPTION
    * N/A           N/A                     N/A
    * ====================================================================================================
    **/
    public static void wheathertimesheetRejctedupdatetimesheet(List<EMS_TM_Timesheet_Record__c> newTimeSheetList,Map<Id,EMS_TM_Timesheet_Record__c> oldMap){        
        Set<Id> timeSheeIds = new Set<Id>();
        for(EMS_TM_Timesheet_Record__c timesheetRec:newTimeSheetList){            
            if(timesheetRec.EMS_Timesheet__c != null && oldMap.get(timesheetRec.Id).Status__c != timesheetRec.Status__c){
                timeSheeIds.add(timesheetRec.EMS_Timesheet__c);
            }            
        }
        Set<Id> timesheetUpdatedIds = new Set<Id>();
        for(EMS_TM_Timesheet_Record__c timesheetRec:[SELECT Id, 
                                                     		EMS_Timesheet__c, 
                                                     		Status__c 
                                                     		FROM EMS_TM_Timesheet_Record__c
                                                    		WHERE EMS_Timesheet__c IN:timeSheeIds 
                                                            AND Status__c ='Rejected']){
                                timesheetUpdatedIds.add(timesheetRec.EMS_Timesheet__c);                            
            
        }
        List<EMS_Timesheet__c> updatedTimesheetList = new List<EMS_Timesheet__c>();        
        for(EMS_Timesheet__c timeRec :[SELECT Id, 
                                       			EMS_TM_Status__c 
                                       			FROM EMS_Timesheet__c
                                      			WHERE Id IN:timeSheeIds]){
                                                if (timesheetUpdatedIds.contains(timeRec.Id)){                                           
                                                 timeRec.EMS_TM_Status__c ='Saved';                                                
                                             }
                                                    updatedTimesheetList.add(timeRec);            
        }
        try{
            if(!updatedTimesheetList.isEmpty()){
                update updatedTimesheetList;
            }
        }catch(Exception e){
            LogException.logHandledException(e, 'editTimeshhetwhenRejected', 'wheathertimesheetRejctedupdatetimesheet');
        }        
    }
}