force-app/main/default/objects/EMS_Timesheet__c/EMS_Timesheet__c.object-meta.xml
<CustomObject>
    <label>Timesheet</label>
    <nameField>
        <displayFormat>TS-{0000}</displayFormat>
        <label>Time Sheet ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_Timesheet__c/fields/Assignment__c.field-meta.xml
<CustomField>
    <fullName>Assignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assignment</label>
    <referenceTo>EMS_TM_Assignment__c</referenceTo>
    <relationshipLabel>Timesheets</relationshipLabel>
    <relationshipName>Timesheets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/EMS_TM_Fri__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Fri__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Fri</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/EMS_TM_Mon__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Mon__c</fullName>
    <label>Mon</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/EMS_TM_Project__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>EMS_TM_Project__c</referenceTo>
    <relationshipLabel>Timesheets</relationshipLabel>
    <relationshipName>Timesheets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/EMS_TM_Remarks__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Remarks__c</fullName>
    <label>Remarks</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/EMS_TM_Sat__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Sat__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Sat</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/EMS_TM_Sun__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Sun__c</fullName>
    <label>Sun</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/EMS_TM_Thu__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Thu__c</fullName>
    <label>Thu</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/EMS_TM_Total__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Total__c</fullName>
    <description>Display the total working hours of employee</description>
    <formula>EMS_TM_Sun__c  +  EMS_TM_Mon__c  +  EMS_TM_Tue__c  +  EMS_TM_Wed__c + EMS_TM_Thu__c+ EMS_TM_Fri__c+ EMS_TM_Sat__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Hours</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/EMS_TM_Tue__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Tue__c</fullName>
    <label>Tue</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/EMS_TM_Wed__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Wed__c</fullName>
    <label>Wed</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Assignment__c/EMS_TM_Assignment__c.object-meta.xml
<CustomObject>
    <label>Assignment</label>
    <nameField>
        <displayFormat>A.ID-{0000}</displayFormat>
        <label>Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_TM_Assignment__c/fields/EMS_TM_AssignedAs__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_AssignedAs__c</fullName>
    <label>Assigned As</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accountant</fullName>
            </value>
            <value>
                <fullName>Administrator</fullName>
            </value>
            <value>
                <fullName>Application Designer</fullName>
            </value>
            <value>
                <fullName>Business Analyst</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Consultant Architect</fullName>
            </value>
            <value>
                <fullName>Data Analyst</fullName>
            </value>
            <value>
                <fullName>Data Engineer</fullName>
            </value>
            <value>
                <fullName>Delivery Manager</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>DevOps Engineer</fullName>
            </value>
            <value>
                <fullName>Lead Business Analyst</fullName>
            </value>
            <value>
                <fullName>Lead Data Engineer</fullName>
            </value>
            <value>
                <fullName>Lead Developer</fullName>
            </value>
            <value>
                <fullName>Lead Quality Analyst</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Product Owner</fullName>
            </value>
            <value>
                <fullName>Project Manager</fullName>
            </value>
            <value>
                <fullName>Quality Analyst</fullName>
            </value>
            <value>
                <fullName>Scrum Master</fullName>
            </value>
            <value>
                <fullName>Security Engineer</fullName>
            </value>
            <value>
                <fullName>Solution Architect</fullName>
            </value>
            <value>
                <fullName>Technical Architect</fullName>
            </value>
            <value>
                <fullName>Accounting Manager</fullName>
                <isActive>false</isActive>
                <label>Accounting Manager</label>
            </value>
            <value>
                <fullName>Accounts Executive</fullName>
                <isActive>false</isActive>
                <label>Accounts Executive</label>
            </value>
            <value>
                <fullName>Analysis</fullName>
                <isActive>false</isActive>
                <label>Analysis</label>
            </value>
            <value>
                <fullName>Associate BSA</fullName>
                <isActive>false</isActive>
                <label>Associate BSA</label>
            </value>
            <value>
                <fullName>Associate Developer</fullName>
                <isActive>false</isActive>
                <label>Associate Developer</label>
            </value>
            <value>
                <fullName>Associate Engineer</fullName>
                <isActive>false</isActive>
                <label>Associate Engineer</label>
            </value>
            <value>
                <fullName>Associate Quality Analyst</fullName>
                <isActive>false</isActive>
                <label>Associate Quality Analyst</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EMS_TM_Project__c/EMS_TM_Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_TM_Timesheet_Record__c/EMS_TM_Timesheet_Record__c.object-meta.xml
<CustomObject>
    <label>Timesheet Line Items</label>
    <nameField>
        <displayFormat>TLI{00000000}</displayFormat>
        <label>Timesheet Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheet Records</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_TM_Timesheet_Record__c/fields/Assignment__c.field-meta.xml
<CustomField>
    <fullName>Assignment__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Assignment</label>
    <referenceTo>EMS_TM_Assignment__c</referenceTo>
    <relationshipName>Timesheets1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Timesheet_Record__c/fields/EMS_Timesheet__c.field-meta.xml
<CustomField>
    <fullName>EMS_Timesheet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>EMS_Timesheet</label>
    <referenceTo>EMS_Timesheet__c</referenceTo>
    <relationshipName>Employee_Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Timesheet_Record__c/fields/EMS_TM_Fri__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Fri__c</fullName>
    <label>Fri</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Timesheet_Record__c/fields/EMS_TM_Mon__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Mon__c</fullName>
    <label>Mon</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Timesheet_Record__c/fields/EMS_TM_Project__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>EMS_TM_Project__c</referenceTo>
    <relationshipLabel>Timesheet Records</relationshipLabel>
    <relationshipName>Timecard_Splits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Timesheet_Record__c/fields/EMS_TM_Remarks__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Remarks__c</fullName>
    <label>Remarks</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Timesheet_Record__c/fields/EMS_TM_Sat__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Sat__c</fullName>
    <label>Sat</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Timesheet_Record__c/fields/EMS_TM_Sun__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Sun__c</fullName>
    <label>Sun</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Timesheet_Record__c/fields/EMS_TM_Thu__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Thu__c</fullName>
    <label>Thu</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Timesheet_Record__c/fields/EMS_TM_Tue__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Tue__c</fullName>
    <label>Tue</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Timesheet_Record__c/fields/EMS_TM_Wed__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Wed__c</fullName>
    <label>Wed</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Timesheet_Record__c/fields/Project_Task__c.field-meta.xml
<CustomField>
    <fullName>Project_Task__c</fullName>
    <label>Project Task</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Timesheet_Record__c/fields/Timesheet_Weekdate__c.field-meta.xml
<CustomField>
    <fullName>Timesheet_Weekdate__c</fullName>
    <formula>EMS_Timesheet__r.Week_Start_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Timesheet Weekdate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project_Task__c/Project_Task__c.object-meta.xml
<CustomObject>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/timesheetRecordRecordPageController.cls
public with sharing class timesheetRecordRecordPageController {

    @AuraEnabled(cacheable=true)
    public  static List<WrapperClass>fetchTimesheetRecordsData(String timesheetRecordId)
    {
       
        List<WrapperClass> wrapperOppList=new List<WrapperClass>();
        for(EMS_TM_Timesheet_Record__c timesheetsRecordsRec:[select id, Name, EMS_Timesheet__r.Name, EMS_TM_Project__r.Name, EMS_TM_Project__r.Id, Assignment__r.EMS_TM_AssignedAs__c, 
                                                            EMS_Timesheet__c, Timesheet_Weekdate__c, EMS_TM_Mon__c, EMS_TM_Tue__c, EMS_TM_Wed__c, 
                                                            EMS_TM_Thu__c, EMS_TM_Fri__c, EMS_TM_Sat__c, EMS_TM_Sun__c, EMS_Timesheet__r.EMS_TM_Total__c,EMS_TM_Remarks__c,Project_Task__c 
                                                            from EMS_TM_Timesheet_Record__c 
                                                            where Id =: timesheetRecordId]) //'a0552000006L05cAAC'
        {
  
            WrapperClass wrapItemFld = new WrapperClass();
            wrapItemFld.Id = timesheetsRecordsRec.id;
            wrapItemFld.TimesheetRecordName = timesheetsRecordsRec.Name;
            wrapItemFld.ProjectName = timesheetsRecordsRec.EMS_TM_Project__r.Name;
            wrapItemFld.ProjectId = timesheetsRecordsRec.EMS_TM_Project__r.Id;
            //wrapItemFld.Assignment = timesheetsRecordsRec.Assignment__r.EMS_TM_AssignedAs__c;
            wrapItemFld.Assignment = timesheetsRecordsRec.Project_Task__c;
            wrapItemFld.Timesheet = timesheetsRecordsRec.EMS_Timesheet__c;
            wrapItemFld.Remarks=timesheetsRecordsRec.EMS_TM_Remarks__c;
            wrapItemFld.Week = timesheetsRecordsRec.Timesheet_Weekdate__c;
            wrapItemFld.Monday = timesheetsRecordsRec.EMS_TM_Mon__c != null ? timesheetsRecordsRec.EMS_TM_Mon__c : 0;
            wrapItemFld.Tuesday = timesheetsRecordsRec.EMS_TM_Tue__c != null ? timesheetsRecordsRec.EMS_TM_Tue__c : 0;
            wrapItemFld.Wednesday = timesheetsRecordsRec.EMS_TM_Wed__c != null ? timesheetsRecordsRec.EMS_TM_Wed__c : 0;
            wrapItemFld.Thursday = timesheetsRecordsRec.EMS_TM_Thu__c != null ? timesheetsRecordsRec.EMS_TM_Thu__c : 0;
            wrapItemFld.Friday = timesheetsRecordsRec.EMS_TM_Fri__c != null ? timesheetsRecordsRec.EMS_TM_Fri__c : 0;
            wrapItemFld.Saturday = timesheetsRecordsRec.EMS_TM_Sat__c != null ? timesheetsRecordsRec.EMS_TM_Sat__c : 0;
            wrapItemFld.Sunday = timesheetsRecordsRec.EMS_TM_Sun__c != null ? timesheetsRecordsRec.EMS_TM_Sun__c : 0;
            wrapItemFld.TotalHours = timesheetsRecordsRec.EMS_Timesheet__r.EMS_TM_Total__c ;
            wrapperOppList.add(wrapItemFld);
        }
        return wrapperOppList;
    }
    
    public class WrapperClass
    {
        @AuraEnabled
        public String Id;
        @AuraEnabled
        public String TimesheetRecordName;
        @AuraEnabled
        public String ProjectId;
        @AuraEnabled
        public String ProjectName;
        @AuraEnabled
        public String Assignment;
        @AuraEnabled
        public Id Timesheet;
        @AuraEnabled
        public String Remarks;
        @AuraEnabled
        public Date Week;
        @AuraEnabled
        public Decimal Monday;
        @AuraEnabled
        public Decimal Tuesday;
        @AuraEnabled
        public Decimal Wednesday;
        @AuraEnabled
        public Decimal Thursday;
        @AuraEnabled
        public Decimal Friday;
        @AuraEnabled
        public Decimal Saturday;
        @AuraEnabled
        public Decimal Sunday;
        @AuraEnabled
        public Decimal TotalHours;
    }
}