force-app/main/default/objects/EMS_Timesheet__c/EMS_Timesheet__c.object-meta.xml
<CustomObject>
    <label>Timesheet</label>
    <nameField>
        <displayFormat>TS-{0000}</displayFormat>
        <label>Time Sheet ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_Timesheet__c/fields/Assignment__c.field-meta.xml
<CustomField>
    <fullName>Assignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assignment</label>
    <referenceTo>EMS_TM_Assignment__c</referenceTo>
    <relationshipLabel>Timesheets</relationshipLabel>
    <relationshipName>Timesheets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/EMS_TM_Fri__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Fri__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Fri</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/EMS_TM_Mon__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Mon__c</fullName>
    <label>Mon</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/EMS_TM_Sat__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Sat__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Sat</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/EMS_TM_Sun__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Sun__c</fullName>
    <label>Sun</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/EMS_TM_Thu__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Thu__c</fullName>
    <label>Thu</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/EMS_TM_Tue__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Tue__c</fullName>
    <label>Tue</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/EMS_TM_Wed__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Wed__c</fullName>
    <label>Wed</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/Week_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Week_End_Date__c</fullName>
    <label>Week End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/Week_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Week_Start_Date__c</fullName>
    <label>Week Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Assignment__c/EMS_TM_Assignment__c.object-meta.xml
<CustomObject>
    <label>Assignment</label>
    <nameField>
        <displayFormat>A.ID-{0000}</displayFormat>
        <label>Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_TM_Assignment__c/fields/EMS_TM_EndDate_Asgn__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_EndDate_Asgn__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Assignment__c/fields/EMS_TM_ProjectName_Asgn__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_ProjectName_Asgn__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Name</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>EMS_TM_Project__c.Type_Of_Project__c</field>
            <operation>notEqual</operation>
            <value>Global Projects</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>EMS_TM_Project__c</referenceTo>
    <relationshipLabel>Project Assignees</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Assignment__c/fields/EMS_TM_StartDate_Asgn__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_StartDate_Asgn__c</fullName>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Project__c/EMS_TM_Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_TM_Project__c/fields/EMS_TM_EndDate__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_EndDate__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Timesheet_Record__c/EMS_TM_Timesheet_Record__c.object-meta.xml
<CustomObject>
    <label>Timesheet Line Items</label>
    <nameField>
        <displayFormat>TLI{00000000}</displayFormat>
        <label>Timesheet Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheet Records</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_TM_Timesheet_Record__c/fields/Assignment__c.field-meta.xml
<CustomField>
    <fullName>Assignment__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Assignment</label>
    <referenceTo>EMS_TM_Assignment__c</referenceTo>
    <relationshipName>Timesheets1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Timesheet_Record__c/fields/EMS_Timesheet__c.field-meta.xml
<CustomField>
    <fullName>EMS_Timesheet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>EMS_Timesheet</label>
    <referenceTo>EMS_Timesheet__c</referenceTo>
    <relationshipName>Employee_Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Timesheet_Record__c/fields/EMS_TM_Fri__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Fri__c</fullName>
    <label>Fri</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Timesheet_Record__c/fields/EMS_TM_Mon__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Mon__c</fullName>
    <label>Mon</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Timesheet_Record__c/fields/EMS_TM_Sat__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Sat__c</fullName>
    <label>Sat</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Timesheet_Record__c/fields/EMS_TM_Sun__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Sun__c</fullName>
    <label>Sun</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Timesheet_Record__c/fields/EMS_TM_Thu__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Thu__c</fullName>
    <label>Thu</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Timesheet_Record__c/fields/EMS_TM_Tue__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Tue__c</fullName>
    <label>Tue</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Timesheet_Record__c/fields/EMS_TM_Wed__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Wed__c</fullName>
    <label>Wed</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Timesheet_Record__c/fields/Week_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Week_End_Date__c</fullName>
    <label>Week End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Timesheet_Record__c/fields/Week_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Week_Start_Date__c</fullName>
    <label>Week Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/restrictAssignmentTimePreandPost.cls
public class restrictAssignmentTimePreandPost implements triggerAction.BeforeInsert,TriggerAction.BeforeUpdate {
    public void beforeInsert(List<EMS_TM_Timesheet_Record__c> newList) {      
        System.debug(LoggingLevel.DEBUG, 'restrictAssignmentTimePreandPost.beforeInsert() : BEGIN');
        restrictAssCreationForClosedProjects(newList,null);
        System.debug(LoggingLevel.DEBUG, 'restrictAssignmentTimePreandPost.beforeInsert() : END');       
    }
    
    public void beforeUpdate(List<EMS_TM_Timesheet_Record__c> newList,List<EMS_TM_Timesheet_Record__c> oldList) {      
        System.debug(LoggingLevel.DEBUG, 'restrictAssignmentTimePreandPost.beforeUpdate() : BEGIN');
        restrictAssCreationForClosedProjects(newList,new Map<Id,EMS_TM_Timesheet_Record__c>(oldList));
        System.debug(LoggingLevel.DEBUG, 'restrictAssignmentTimePreandPost.beforeUpdate() : END');       
    }
    
    
    /**
*
*   CHANGE HISTORY
*   ====================================================================================================
*   Date        Name                    Description
*   N/A         N/A                     N/A
*   ====================================================================================================
**/
    private void restrictAssCreationForClosedProjects(List<EMS_TM_Timesheet_Record__c> timesheetdata, Map<Id,EMS_TM_Timesheet_Record__c> oldMap) {
        set<Id> assignmentIds = new set<Id>();
        List<EMS_TM_Timesheet_Record__c> filteredlist = new List<EMS_TM_Timesheet_Record__c>();
        Map<Id,EMS_TM_Assignment__c> assMap = new Map<Id,EMS_TM_Assignment__c>();
        Set<Id> TimeSheetId = New Set<Id>();
        Map<Id,EMS_Timesheet__c> Timesheetmap = new Map<Id,EMS_Timesheet__c>();
        
        
        for(EMS_TM_Timesheet_Record__c newRec : timesheetdata){
            if(newRec.Assignment__c != null){
                assignmentIds.add(newRec.Assignment__c); 
                TimeSheetId.add(newRec.EMS_Timesheet__c);
                filteredlist.add(newRec);
            }
        }
        SYstem.debug('**assignmentIds'+assignmentIds);
        SYstem.debug('**filteredlist'+filteredlist);
        
        if(!filteredlist.isEmpty()){
            Timesheetmap = new Map<ID, EMS_Timesheet__c>([SELECT Id, Name, Week_End_Date__c, Week_Start_Date__c FROM EMS_Timesheet__c WHERE Id IN: TimeSheetId]);
            for(EMS_TM_Assignment__c ass : [SELECT Id,EMS_TM_StartDate_Asgn__c,EMS_TM_EndDate_Asgn__c,EMS_TM_ProjectName_Asgn__r.name,EMS_TM_ProjectName_Asgn__r.EMS_TM_EndDate__c from EMS_TM_Assignment__c WHERE Id IN:assignmentIds ]){
                assMap.put(ass.id,ass);  
            }
            SYstem.debug('**assMap------->'+assMap);
            for(EMS_TM_Timesheet_Record__c newRec : filteredlist){
                EMS_TM_Assignment__c ass = assMap.get(newRec.Assignment__c);
                string projectName = ass.EMS_TM_ProjectName_Asgn__r.name;
                Date assStartDate = ass.EMS_TM_StartDate_Asgn__c;
                //Date assEndDate = ass.EMS_TM_EndDate_Asgn__c;
                Date assEndDate = (ass.EMS_TM_EndDate_Asgn__c != null) ? ass.EMS_TM_EndDate_Asgn__c : ass.EMS_TM_ProjectName_Asgn__r.EMS_TM_EndDate__c;
                Date weekStart = Timesheetmap.get(newRec.EMS_Timesheet__c).Week_Start_Date__c;
                Date weekEnd = Timesheetmap.get(newRec.EMS_Timesheet__c).Week_End_Date__c;
                boolean throwError = false;
                
                if((newRec.EMS_TM_Mon__c != null && newRec.EMS_TM_Mon__c != 0) && (weekStart < assStartDate || weekStart > assEndDate)){
                    
                    throwError = true;
                }
                else if((newRec.EMS_TM_Tue__c != null && newRec.EMS_TM_Tue__c != 0) && (weekStart.addDays(1) < assStartDate || weekStart.addDays(1) > assEndDate)){
                    throwError = true;
                }
                else if((newRec.EMS_TM_Wed__c != null && newRec.EMS_TM_Wed__c != 0) && (weekStart.addDays(2) < assStartDate || weekStart.addDays(2) > assEndDate)){
                    throwError = true;
                }
                else if((newRec.EMS_TM_THU__c != null && newRec.EMS_TM_THU__c != 0) && (weekStart.addDays(3) < assStartDate || weekStart.addDays(3) > assEndDate)){
                    throwError = true;
                }
                else if((newRec.EMS_TM_FRI__c != null && newRec.EMS_TM_FRI__c != 0) && (weekStart.addDays(4) < assStartDate || weekStart.addDays(4) > assEndDate)){
                    throwError = true;
                }
                else if((newRec.EMS_TM_SAT__c != null && newRec.EMS_TM_SAT__c != 0) && (weekStart.addDays(5) < assStartDate || weekStart.addDays(5) > assEndDate)){
                    throwError = true;
                }
                else if((newRec.EMS_TM_Sun__c != null && newRec.EMS_TM_Sun__c != 0) && (weekStart.addDays(6) < assStartDate || weekStart.addDays(6) > assEndDate)){
                    throwError = true;
                }
                
                if (throwError) {
                    String errorMessage = projectName + ': Please enter time within the start (' + String.valueOf(assStartDate.day()) + '/' + String.valueOf(assStartDate.month()) + '/' + String.valueOf(assStartDate.year())
                        + ') and end (' + String.valueOf(assEndDate.day()) + '/' + String.valueOf(assEndDate.month()) + '/' + String.valueOf(assEndDate.year())
                        + ') dates of your assignment, for other days fill zero hours.';
                    /*String errorMessage='You are not allowed to fill hours to this project as you are not designated for it on the chosen date.'; */
                    newRec.addError(errorMessage);
                    
                }
                
                
            }   
            
        }
    }
}