force-app/main/default/objects/Family_Information__c/Family_Information__c.object-meta.xml
<CustomObject>
    <label>Family Information</label>
    <nameField>
        <label>Family Details Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Family Informations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Family_Information__c/fields/Relationships__c.field-meta.xml
<CustomField>
    <fullName>Relationships__c</fullName>
    <label>Relationships</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Father</fullName>
            </value>
            <value>
                <fullName>Mother</fullName>
            </value>
            <value>
                <fullName>Spouse</fullName>
            </value>
            <value>
                <fullName>Son</fullName>
            </value>
            <value>
                <fullName>Daughter</fullName>
            </value>
            <value>
                <fullName>Brother</fullName>
            </value>
            <value>
                <fullName>Sister</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Cousin</fullName>
                <isActive>false</isActive>
                <label>Cousin</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Family_Information__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <label>Resource</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Family Informations</relationshipLabel>
    <relationshipName>Family_Informations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/restrictSameSpouseFatherMother.cls
/**
* @author Mukesh Rawat
* @date 3/2/2023
* @description  restrictSameSpouseFatherMother Class to restrict the duplicate Spouse And Father And Mother
*
*               Test code coverage provided by the following test class:
*               - 
*
* CHANGE HISTORY
* ====================================================================================================
* DATE          NAME                    DESCRIPTION
* N/A           N/A                     N/A
* ====================================================================================================
**/
public without sharing class restrictSameSpouseFatherMother implements TriggerAction.BeforeInsert{
    /**
* @author Mukesh Rawat
* @date 3/2/2023
* @description Before Insert 
*
* CHANGE HISTORY
* ====================================================================================================
* DATE          NAME                    DESCRIPTION
* N/A           N/A                     N/A
* ====================================================================================================
**/
    public void beforeInsert(List<Family_Information__c> newList) {      
        System.debug(LoggingLevel.DEBUG, 'restrictSameSpouseFatherMother.beforeInsert() : BEGIN');
        restrictTheDuplicateRalationship(newList);
        System.debug(LoggingLevel.DEBUG, 'restrictSameSpouseFatherMother.beforeInsert() : END');       
    }
    
    
    /**
*   {Purpose} - Method to restrict the same date leaves 
*
*   CHANGE HISTORY
*   ====================================================================================================
*   Date        Name                    Description
*   N/A         N/A                     N/A
*   ====================================================================================================
**/
    public void restrictTheDuplicateRalationship(List<Family_Information__c> newlist) {
        // Get the set of contact Ids for the records being inserted
        Set<Id> contactIds = new Set<Id>();
        for (Family_Information__c fi : newlist) {
            contactIds.add(fi.Resource__c);
        }
        System.debug('======resourcId========'+contactIds);
        
        // Query for existing Family Information records for the same contact with the same Relationships value
        Map<Id, Set<String>> existingRelationships = new Map<Id, Set<String>>();
        for (Family_Information__c fi : [SELECT Resource__c, Relationships__c FROM Family_Information__c WHERE Resource__c IN :contactIds AND Relationships__c IN ('Spouse', 'Father', 'Mother')]) {
            if (!existingRelationships.containsKey(fi.Resource__c)) {
                existingRelationships.put(fi.Resource__c, new Set<String>());
            }
            existingRelationships.get(fi.Resource__c).add(fi.Relationships__c);
        }
        System.debug('======existingRelationships========'+existingRelationships);
        
        // Check the Relationships values for the records being inserted and prevent duplicates     
        for (Family_Information__c fi : newlist) {
            if (fi.Relationships__c != null && (fi.Relationships__c == 'Spouse' || fi.Relationships__c == 'Father' || fi.Relationships__c == 'Mother')) {
                if (existingRelationships.containsKey(fi.Resource__c) && existingRelationships.get(fi.Resource__c).contains(fi.Relationships__c)) {
                    fi.addError('Family member already exists with the same relationship.');
                } 
            }
        }
    }
}