force-app/main/default/objects/Family_Information__c/Family_Information__c.object-meta.xml
<CustomObject>
    <label>Family Information</label>
    <nameField>
        <label>Family Details Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Family Informations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Family_Information__c/fields/Contact_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Contact_Email_Address__c</fullName>
    <label>Contact Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Family_Information__c/fields/Contact_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Contact_Phone_Number__c</fullName>
    <label>Contact Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Family_Information__c/fields/Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Birth__c</fullName>
    <label>Dependent&apos;s Date of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Family_Information__c/fields/Family_Member_Name__c.field-meta.xml
<CustomField>
    <fullName>Family_Member_Name__c</fullName>
    <label>Family Member Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Family_Information__c/fields/Is_It_Emergency_Contact__c.field-meta.xml
<CustomField>
    <fullName>Is_It_Emergency_Contact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is It Emergency Contact ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Family_Information__c/fields/Relationships__c.field-meta.xml
<CustomField>
    <fullName>Relationships__c</fullName>
    <label>Relationships</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Father</fullName>
            </value>
            <value>
                <fullName>Mother</fullName>
            </value>
            <value>
                <fullName>Spouse</fullName>
            </value>
            <value>
                <fullName>Son</fullName>
            </value>
            <value>
                <fullName>Daughter</fullName>
            </value>
            <value>
                <fullName>Brother</fullName>
            </value>
            <value>
                <fullName>Sister</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Cousin</fullName>
                <isActive>false</isActive>
                <label>Cousin</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Family_Information__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <label>Resource</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Family Informations</relationshipLabel>
    <relationshipName>Family_Informations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/getFamilyInfoInOnboarding.cls
public class getFamilyInfoInOnboarding {
    
    @AuraEnabled(cacheable=true)
    public static getFamilyInformaition getFamilyInfo(String contactId){
        List<Family_Information__c> listfamilyrecords = new List<Family_Information__c>();
        try{
            listfamilyrecords = [SELECT Id,
                                 IsDeleted, 
                                 Name, 
                                 CreatedDate, 
                                 CreatedById,
                                 Contact_Email_Address__c,
                                 Contact_Phone_Number__c,
                                 Date_of_Birth__c,
                                 Resource__c,
                                 Relationships__c,
                                 Is_It_Emergency_Contact__c,
                                 Family_Member_Name__c
                                 FROM Family_Information__c Where Resource__c =:contactId LIMIT 5];
        }Catch(Exception ex){
            System.debug('### Exception Occured With'+ex.getStackTraceString());
            System.debug('### Exception Occured With'+ex.getMessage());
            listfamilyrecords = null;
        }  
        getFamilyInformaition wrapper = new getFamilyInformaition();
        
        wrapper.listfamilyrecords = listfamilyrecords;
        return wrapper;
    }
    
    public class getFamilyInformaition{
        @AuraEnabled
        public List<Family_Information__c> listfamilyrecords;
    }
    
}