force-app/main/default/objects/EMS_EM_Request__c/EMS_EM_Request__c.object-meta.xml
<CustomObject>
    <label>Request</label>
    <nameField>
        <displayFormat>R_{00000}</displayFormat>
        <label>Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_EM_Request__c/fields/EMS_EM_CA_City__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_CA_City__c</fullName>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EMS_EM_Request__c/fields/EMS_EM_CA_State__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_CA_State__c</fullName>
    <label>State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EMS_EM_Request__c/fields/EMS_EM_CA_Zip__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_CA_Zip__c</fullName>
    <label>Zip</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EMS_EM_Request__c/fields/EMS_EM_CAddress_Line_1__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_CAddress_Line_1__c</fullName>
    <label>Address Line 1</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/EMS_EM_Request__c/fields/EMS_EM_CAddress_Line_2__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_CAddress_Line_2__c</fullName>
    <label>Address Line 2</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/EMS_EM_Request__c/fields/EMS_EM_Request_Type__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_Request_Type__c</fullName>
    <label>Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Address Details</fullName>
            </value>
            <value>
                <fullName>Bank Details</fullName>
            </value>
            <value>
                <fullName>Education Details</fullName>
            </value>
            <value>
                <fullName>Emergency Details</fullName>
            </value>
            <value>
                <fullName>Personal Details</fullName>
            </value>
            <value>
                <fullName>Vehicle Details</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EMS_EM_RequestViewFetch_Test.cls
@istest
public class EMS_EM_RequestViewFetch_Test {
   
    public static testmethod void testMethod1(){
        EMS_EM_Request__c req = new EMS_EM_Request__c();
        req.EMS_EM_Request_Type__c = 'Address Details';
        req.EMS_EM_CAddress_Line_1__c = 'Line1';
        req.EMS_EM_CAddress_Line_2__c = 'Line 2';
        req.EMS_EM_CA_City__c = 'Hyderabad';
        req.EMS_EM_CA_State__c = 'Telangana';
        req.EMS_EM_CA_Zip__c = '500082';
        insert req;
        EMS_EM_RequestViewFetch.getUserContactInfo(req.Id);
    }
}