force-app/main/default/objects/EMS_EM_Request__c/EMS_EM_Request__c.object-meta.xml
<CustomObject>
    <label>Request</label>
    <nameField>
        <displayFormat>R_{00000}</displayFormat>
        <label>Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_EM_Request__c/fields/Approver__c.field-meta.xml
<CustomField>
    <fullName>Approver__c</fullName>
    <formula>Contact__r.EMS_EM_HR_Assigned__r.FirstName &amp; &apos; &apos; &amp;  Contact__r.EMS_EM_HR_Assigned__r.LastName</formula>
    <label>Approver</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EMS_EM_Request__c/fields/EMS_EM_Add_Education__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_Add_Education__c</fullName>
    <label>What do you want to add?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Degree</fullName>
            </value>
            <value>
                <fullName>Certificate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EMS_EM_Request__c/fields/EMS_EM_Raised_On__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_Raised_On__c</fullName>
    <formula>CreatedDate</formula>
    <label>Raised On</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EMS_EM_Request__c/fields/EMS_EM_Request_Status__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_Request_Status__c</fullName>
    <label>Request Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Auto-Approved</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EMS_EM_Request__c/fields/EMS_EM_Request_Type__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_Request_Type__c</fullName>
    <label>Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Address Details</fullName>
            </value>
            <value>
                <fullName>Bank Details</fullName>
            </value>
            <value>
                <fullName>Education Details</fullName>
            </value>
            <value>
                <fullName>Emergency Details</fullName>
            </value>
            <value>
                <fullName>Personal Details</fullName>
            </value>
            <value>
                <fullName>Vehicle Details</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EMS_EM_Request__c/fields/What_do_you_want_to_change__c.field-meta.xml
<CustomField>
    <fullName>What_do_you_want_to_change__c</fullName>
    <label>What do you want to change?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contact Info</fullName>
            </value>
            <value>
                <fullName>Marital Status</fullName>
            </value>
            <value>
                <fullName>Update Resume</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Ems_Em_Request_DataFetch.cls
public inherited sharing class Ems_Em_Request_DataFetch {
    @AuraEnabled(Cacheable = true)
    public static List<EMS_EM_Request__c> getRequestHistory(){
        return [SELECT Id, EMS_EM_Request_Type__c, EMS_EM_Raised_On__c, EMS_EM_Request_Status__c, Approver__c, What_do_you_want_to_change__c, EMS_EM_Add_Education__c  FROM EMS_EM_Request__c
                WHERE OwnerId=:UserInfo.getUserID() 
               order by CreatedDate desc];
    }
    
    @AuraEnabled(Cacheable = true)
    public static List<EMS_EM_Request__c> getRequestByStatus( String statusType){
         System.debug('Status Type called');
           
        return [SELECT Id, EMS_EM_Request_Type__c, EMS_EM_Raised_On__c, EMS_EM_Request_Status__c, Approver__c  FROM EMS_EM_Request__c
                WHERE OwnerId=:UserInfo.getUserID() AND EMS_EM_Request_Status__c =:statusType
               order by CreatedDate desc];
    }
    
    @AuraEnabled(cacheable=true)
        public static Map<ID, String> getRelatedFilesByRecordId(String recordId) {
            // Get record file IDs        
            List<ContentDocumentLink> files = [SELECT ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId = :recordId];
            List<ID> fileIDs = new List<ID>();
            for (ContentDocumentLink docLink : files) {
                fileIDs.add(docLink.ContentDocumentId);
            }
     
            List<ContentVersion> docs = [SELECT ContentDocumentId, FileExtension, Title 
                FROM ContentVersion WHERE ContentDocumentId IN : fileIDs];
            Map<ID, String> mapIdTitle = new Map<ID, String>();
            for (ContentVersion docLink : docs) {
                mapIdTitle.put(docLink.ContentDocumentId, docLink.Title);
            }
            return mapIdTitle;
        }

}