force-app/main/default/objects/EMS_EM_Request__c/EMS_EM_Request__c.object-meta.xml
<CustomObject>
    <label>Request</label>
    <nameField>
        <displayFormat>R_{00000}</displayFormat>
        <label>Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_EM_Request__c/fields/EMS_EM_Contact_Number__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_Contact_Number__c</fullName>
    <label>Contact Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/EMS_EM_Request__c/fields/EMS_EM_Request_Status__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_Request_Status__c</fullName>
    <label>Request Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Auto-Approved</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EMS_EM_Request__c/fields/EMS_EM_Request_Type__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_Request_Type__c</fullName>
    <label>Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Address Details</fullName>
            </value>
            <value>
                <fullName>Bank Details</fullName>
            </value>
            <value>
                <fullName>Education Details</fullName>
            </value>
            <value>
                <fullName>Emergency Details</fullName>
            </value>
            <value>
                <fullName>Personal Details</fullName>
            </value>
            <value>
                <fullName>Vehicle Details</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EMS_EM_Request__c/fields/Personal_Email_Id__c.field-meta.xml
<CustomField>
    <fullName>Personal_Email_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Personal Email Id</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/EMS_EM_Request__c/fields/What_do_you_want_to_change__c.field-meta.xml
<CustomField>
    <fullName>What_do_you_want_to_change__c</fullName>
    <label>What do you want to change?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contact Info</fullName>
            </value>
            <value>
                <fullName>Marital Status</fullName>
            </value>
            <value>
                <fullName>Update Resume</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Ems_Em_Request_DataFetch_Test.cls
@isTest
public class Ems_Em_Request_DataFetch_Test {
    
    @isTest
    private static void getRequestHistoryTest(){
        
        EMS_EM_Request__c req1 = new EMS_EM_Request__c();
        req1.EMS_EM_Request_Type__c = 'Personal Details';
        req1.What_do_you_want_to_change__c = 'Contact Info';
        req1.EMS_EM_Contact_Number__c = '7897897897';
        req1.Personal_Email_Id__c = 'abcds@gmail.com';
        insert req1;
        
        Test.startTest();
        Ems_Em_Request_DataFetch.getRequestHistory();
        Test.stopTest();
        EMS_EM_Request__c req = [select EMS_EM_Request_Type__c from EMS_EM_Request__c LIMIT 1];
        
    }
    
    @isTest
    private static void getRequestByStatusTest(){
        
        EMS_EM_Request__c req1 = new EMS_EM_Request__c();
        req1.EMS_EM_Request_Type__c = 'Personal Details';
        req1.What_do_you_want_to_change__c = 'Contact Info';
        req1.EMS_EM_Contact_Number__c = '7897897897';
        req1.Personal_Email_Id__c = 'abcds@gmail.com';
        req1.EMS_EM_Request_Status__c = 'Pending';
        insert req1;
        
        Test.startTest();
        Ems_Em_Request_DataFetch.getRequestByStatus('Pending');
        Test.stopTest();
      
        
    }
    
    @isTest
    private static void getRelatedFilesByRecordIdTest(){
        
        Contact con = new Contact();
        con.Firstname = 'test';
        con.LastName = 'dsd';
        insert con;
        
        ContentVersion cv = new Contentversion();
        cv.title='ABC';
        cv.PathOnClient ='ABC.jpg';
        cv.versiondata=EncodingUtil.base64Decode('Unit Test Attachment Body');
        insert cv;
        ContentVersion testContent = [SELECT id, ContentDocumentId FROM ContentVersion where Id = :cv.Id];	
        
        ContentDocumentLink contentlink = new ContentDocumentLink();
        contentlink.LinkedEntityId = con.id;
        contentlink.ShareType= 'V';
        contentlink.ContentDocumentId = testcontent.ContentDocumentId;
        contentlink.Visibility = 'AllUsers';
        insert contentlink;
        
        Test.startTest();
        //Please write your class name before function.
        Ems_Em_Request_DataFetch.getRelatedFilesByRecordId(con.Id);
        Test.stopTest();
    }
    
}