force-app/main/default/objects/Exception_Log__c/Exception_Log__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>EL- {0000000}</displayFormat>
        <label>Exception Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exception_Log__c/fields/Bypass_Retry_Exception__c.field-meta.xml
<CustomField>
    <fullName>Bypass_Retry_Exception__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass Retry Exception</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Exception_Log__c/fields/ClassName__c.field-meta.xml
<CustomField>
    <fullName>ClassName__c</fullName>
    <label>Class Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exception_Log__c/fields/ContextUser__c.field-meta.xml
<CustomField>
    <fullName>ContextUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Context User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Exception_Log__c/fields/ConvertedToDefect__c.field-meta.xml
<CustomField>
    <fullName>ConvertedToDefect__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Converted To Defect</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Exception_Log__c/fields/Data_Log__c.field-meta.xml
<CustomField>
    <fullName>Data_Log__c</fullName>
    <label>Data Log</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Exception_Log__c/fields/Exception_Resolved__c.field-meta.xml
<CustomField>
    <fullName>Exception_Resolved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Exception Resolved</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Exception_Log__c/fields/Exception_Retry_Complete__c.field-meta.xml
<CustomField>
    <fullName>Exception_Retry_Complete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Exception Retry Complete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Exception_Log__c/fields/ExceptionDescription__c.field-meta.xml
<CustomField>
    <fullName>ExceptionDescription__c</fullName>
    <label>Exception Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exception_Log__c/fields/ExceptionDetails__c.field-meta.xml
<CustomField>
    <fullName>ExceptionDetails__c</fullName>
    <label>Exception Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Exception_Log__c/fields/ExceptionLogTimestamp__c.field-meta.xml
<CustomField>
    <fullName>ExceptionLogTimestamp__c</fullName>
    <label>ExceptionLog Timestamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Exception_Log__c/fields/ExceptionType__c.field-meta.xml
<CustomField>
    <fullName>ExceptionType__c</fullName>
    <label>Exception Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exception_Log__c/fields/High_Priority_triggered__c.field-meta.xml
<CustomField>
    <fullName>High_Priority_triggered__c</fullName>
    <defaultValue>false</defaultValue>
    <label>High Priority triggered</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Exception_Log__c/fields/IsHandled__c.field-meta.xml
<CustomField>
    <fullName>IsHandled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Handled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Exception_Log__c/fields/MethodName__c.field-meta.xml
<CustomField>
    <fullName>MethodName__c</fullName>
    <label>Method Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exception_Log__c/fields/NumberOfTimesOccured__c.field-meta.xml
<CustomField>
    <fullName>NumberOfTimesOccured__c</fullName>
    <label>Number of Times Occured</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Exception_Log__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Exception_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Raised</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Exception_LogTriggerTest.cls
@isTest public class Exception_LogTriggerTest {
    @testsetup static void setup() {
        Account acc = new Account();
        acc.Name = 'Test';
        insert acc;
    }
    @isTest public static void testFirst() {
        List<Account> accList = new List<Account>();
        Account acc = getAccountRecord('Test');
        acc.Name = 'Test';
        accList.add(acc);
        
        String strAcc = JSON.serialize(accList);
        
        Exception_Log__c exception_log = new Exception_Log__c(
            ClassName__c = 'CDLCallBackCreation',
            ContextUser__c = Userinfo.getUserId(), ConvertedToDefect__c = false,
            ExceptionDescription__c =
            'Insert failed. First exception on row 0; first error: CANNOT_EXECUTE_FLOW_TRIGGER, We can\'t save thi',
            ExceptionDetails__c =
            'System.DmlException:Insert failed. First exception on row 0; first error: CANNOT_EXECUTE_FLOW_TRIGGER, We can\'t save this record because the “Event 1” process failed. Give your Salesforce admin these details. <b>An unhandled fault has occurred in this flow</b><br>An unhandled fault has occurred while processing the flow.  Please contact your system administrator for more information. Error ID: 1265650124-79949 (-374067804)ase contact your system administrator for more information. Error ID: 1265650124-79949 (-374067804): []Class.CDLCallBackCreation.createCallBackRecord: line 100, column 1',
            ExceptionType__c = 'System.DmlException',
            ExceptionLogTimestamp__c =
            DateTime.newInstance(2021, 8, 18, 17, 1054, 63244),
            IsHandled__c = false, MethodName__c = 'createCallBackRecord',
            NumberOfTimesOccured__c = 1.0, Status__c = 'Raised',
            Data_Log__c = strAcc, Objects__c = 'Account',
            Exception_Retry_Complete__c = false, Exception_Resolved__c = false,
            Priority__c = 'High', Retry_Count__c = 0.0,
            High_Priority_triggered__c = true, Bypass_Retry_Exception__c = false);
        insert exception_log;

        Exception_Log__c exception_logUpdated = [SELECT id,
                                                 name,
                                                 Exception_Resolved__c
                                                 FROM Exception_Log__c
                                                 WHERE id =:exception_log.Id ];
    }

    public static Account getAccountRecord(String name) {
            return [SELECT id,
                    Name
                    FROM Account
                    WHERE Name =:name ];
        }
}