force-app/main/default/objects/ems_EM_Additional_Detail__c/ems_EM_Additional_Detail__c.object-meta.xml
<CustomObject>
    <label>Professional Proficiency</label>
    <nameField>
        <displayFormat>PP-{00000}</displayFormat>
        <label>Professional Proficiency Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Professional Proficiency</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ems_EM_Additional_Detail__c/fields/EMS_EM_Education1__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_Education1__c</fullName>
    <label>Level of Education</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Post Graduate</fullName>
            </value>
            <value>
                <fullName>Graduate</fullName>
            </value>
            <value>
                <fullName>Std X/SSC</fullName>
            </value>
            <value>
                <fullName>Std XII/HSC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ems_EM_Additional_Detail__c/fields/EMS_EM_Education2__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_Education2__c</fullName>
    <label>Level of Education</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Post Graduate</fullName>
            </value>
            <value>
                <fullName>Graduate</fullName>
            </value>
            <value>
                <fullName>Std X/SSC</fullName>
            </value>
            <value>
                <fullName>Std XII/HSC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ems_EM_Additional_Detail__c/fields/EMS_EM_Education3__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_Education3__c</fullName>
    <label>Level of Education</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Post Graduate</fullName>
            </value>
            <value>
                <fullName>Graduate</fullName>
            </value>
            <value>
                <fullName>Std XII/HSC</fullName>
            </value>
            <value>
                <fullName>Std X/SSC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ems_EM_Additional_Detail__c/fields/EMS_EM_Education4__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_Education4__c</fullName>
    <label>Level of Education</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Post Graduate</fullName>
            </value>
            <value>
                <fullName>Graduate</fullName>
            </value>
            <value>
                <fullName>Std XII/HSC</fullName>
            </value>
            <value>
                <fullName>Std X/SSC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ems_EM_Additional_Detail__c/fields/EMS_EM_Education5__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_Education5__c</fullName>
    <label>Level of Education</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Post Graduate</fullName>
            </value>
            <value>
                <fullName>Graduate</fullName>
            </value>
            <value>
                <fullName>Std XII/HSC</fullName>
            </value>
            <value>
                <fullName>Std X/SSC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ems_EM_Additional_Detail__c/fields/EMS_EM_Education__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_Education__c</fullName>
    <label>Level of Education</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Post Graduate</fullName>
            </value>
            <value>
                <fullName>Graduate</fullName>
            </value>
            <value>
                <fullName>Std X/SSC</fullName>
            </value>
            <value>
                <fullName>Std XII/HSC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ems_EM_Additional_Detail__c/fields/EMS_EM_IName1__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_IName1__c</fullName>
    <label>Institution Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ems_EM_Additional_Detail__c/fields/EMS_EM_IName3__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_IName3__c</fullName>
    <label>Institution Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ems_EM_Additional_Detail__c/fields/EMS_EM_IName5__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_IName5__c</fullName>
    <label>Institution Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ems_EM_Additional_Detail__c/fields/Onboarding_Request__c.field-meta.xml
<CustomField>
    <fullName>Onboarding_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Onboarding Request</label>
    <referenceTo>EMS_EM_Onboarding_Request__c</referenceTo>
    <relationshipName>Additional_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_EM_Onboarding_Request__c/EMS_EM_Onboarding_Request__c.object-meta.xml
<CustomObject>
    <label>Onboarding Request</label>
    <nameField>
        <displayFormat>O-{00000}</displayFormat>
        <label>Onboarding Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Onboarding Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_EM_Onboarding_Request__c/fields/EMS_EM_Education1__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_Education1__c</fullName>
    <label>Level of Education</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Post Graduate</fullName>
            </value>
            <value>
                <fullName>Graduate</fullName>
            </value>
            <value>
                <fullName>Std XII/HSC</fullName>
            </value>
            <value>
                <fullName>Std X/SSC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EMS_EM_Onboarding_Request__c/fields/EMS_EM_Education2__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_Education2__c</fullName>
    <label>Level of Education</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Post Graduate</fullName>
            </value>
            <value>
                <fullName>Graduate</fullName>
            </value>
            <value>
                <fullName>Std XII/HSC</fullName>
            </value>
            <value>
                <fullName>Std X/SSC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EMS_EM_Onboarding_Request__c/fields/EMS_EM_Education3__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_Education3__c</fullName>
    <label>Level of Education</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Post Graduate</fullName>
            </value>
            <value>
                <fullName>Graduate</fullName>
            </value>
            <value>
                <fullName>Std XII/HSC</fullName>
            </value>
            <value>
                <fullName>Std X/SSC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EMS_EM_Onboarding_Request__c/fields/EMS_EM_Education4__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_Education4__c</fullName>
    <label>Level of Education</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Post Graduate</fullName>
            </value>
            <value>
                <fullName>Graduate</fullName>
            </value>
            <value>
                <fullName>Std XII/HSC</fullName>
            </value>
            <value>
                <fullName>Std X/SSC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EMS_EM_Onboarding_Request__c/fields/EMS_EM_Education__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_Education__c</fullName>
    <label>Level of Education</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Post Graduate</fullName>
            </value>
            <value>
                <fullName>Graduate</fullName>
            </value>
            <value>
                <fullName>Std X/SSC</fullName>
            </value>
            <value>
                <fullName>Std XII/HSC</fullName>
            </value>
            <value>
                <fullName>Under Graduate(+2)</fullName>
                <isActive>false</isActive>
                <label>Under Graduate(+2)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EMS_EM_Onboarding_Request__c/fields/EMS_EM_First_Name__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_First_Name__c</fullName>
    <label>First Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EMS_EM_Onboarding_Request__c/fields/EMS_EM_IName2__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_IName2__c</fullName>
    <label>Institution Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EMS_EM_Onboarding_Request__c/fields/EMS_EM_IName4__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_IName4__c</fullName>
    <label>Institution Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EMS_EM_Onboarding_Request__c/fields/EMS_EM_IName__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_IName__c</fullName>
    <label>Institution Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EMS_EM_Onboarding_Request__c/fields/Is_Inegration_Needed__c.field-meta.xml
<CustomField>
    <fullName>Is_Inegration_Needed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Inegration Needed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/EMS_EM_Additional_Details_HandlerTest.cls
@isTest
public class EMS_EM_Additional_Details_HandlerTest {
      private class RestMock implements HttpCalloutMock {

        public HTTPResponse respond(HTTPRequest req) {
            String fullJson = '{"name" : "","mimeType" : "application/vnd.google-apps.folder"}';

            HTTPResponse res = new HTTPResponse();
            res.setHeader('Content-Type', 'text/json');
            res.setBody(fullJson);
            res.setStatusCode(200);
            return res;
        }
    }
    
    static testMethod void myTest(){
        Test.setMock(HttpCalloutMock.class, new RestMock());
        List<ems_EM_Additional_Detail__c> addList=new List<ems_EM_Additional_Detail__c>();
        EMS_EM_Onboarding_Request__c onboard =new EMS_EM_Onboarding_Request__c();
        //onboard.EMS_EM_First_Name__c='test';
        onboard.Is_Inegration_Needed__c=true;
        
        insert onboard;
        
        ems_EM_Additional_Detail__c addionalDetail=new ems_EM_Additional_Detail__c();
        //addionalDetail.Name='AD-00331';
        addionalDetail.Onboarding_Request__c=onboard.Id;
        addionalDetail.EMS_EM_Education__c='Graduate';
        addionalDetail.EMS_EM_Education1__c='Graduate';
        addionalDetail.EMS_EM_Education2__c='Graduate';
        addionalDetail.EMS_EM_Education3__c='Graduate';
        addionalDetail.EMS_EM_Education4__c='Graduate';
        addionalDetail.EMS_EM_Education5__c='Graduate';
        addionalDetail.EMS_EM_IName__c='Manipal university';
         addionalDetail.EMS_EM_IName2__c='Manipal university';
         addionalDetail.EMS_EM_IName3__c='Manipal university';
         addionalDetail.EMS_EM_IName4__c='Manipal university';
         addionalDetail.EMS_EM_IName1__c='Manipal university';
         addionalDetail.EMS_EM_IName5__c='Manipal university';
        addList.add(addionalDetail);
       
        insert addList;
        
       

    }
   
}