force-app/main/default/objects/ems_EM_Additional_Detail__c/ems_EM_Additional_Detail__c.object-meta.xml
<CustomObject>
    <label>Professional Proficiency</label>
    <nameField>
        <displayFormat>PP-{00000}</displayFormat>
        <label>Professional Proficiency Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Professional Proficiency</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ems_EM_Additional_Detail__c/fields/Onboarding_Request__c.field-meta.xml
<CustomField>
    <fullName>Onboarding_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Onboarding Request</label>
    <referenceTo>EMS_EM_Onboarding_Request__c</referenceTo>
    <relationshipName>Additional_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ems_EM_Additional_Detail__c/fields/Work_Details_Filled__c.field-meta.xml
<CustomField>
    <fullName>Work_Details_Filled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Work Details Filled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EMS_EM_Onboarding_Request__c/EMS_EM_Onboarding_Request__c.object-meta.xml
<CustomObject>
    <label>Onboarding Request</label>
    <nameField>
        <displayFormat>O-{00000}</displayFormat>
        <label>Onboarding Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Onboarding Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_EM_Onboarding_Request__c/fields/Address_Details_Value_Filled__c.field-meta.xml
<CustomField>
    <fullName>Address_Details_Value_Filled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Address Details Value Filled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EMS_EM_Onboarding_Request__c/fields/Education_Details_Filled__c.field-meta.xml
<CustomField>
    <fullName>Education_Details_Filled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Education Details Filled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EMS_EM_Onboarding_Request__c/fields/Identify_Details_Value_Filled__c.field-meta.xml
<CustomField>
    <fullName>Identify_Details_Value_Filled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Identify Details Value Filled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EMS_EM_Onboarding_Request__c/fields/Other_Certifications_Value_Filled__c.field-meta.xml
<CustomField>
    <fullName>Other_Certifications_Value_Filled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Other Certifications Value Filled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EMS_EM_Onboarding_Request__c/fields/Personal_Details_Value_Filled__c.field-meta.xml
<CustomField>
    <fullName>Personal_Details_Value_Filled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Personal Details Value Filled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ProgressBarApplicantController.cls
public class ProgressBarApplicantController {
    
    @AuraEnabled(cacheable = true)
    public static List<EMS_EM_Onboarding_Request__c> fetchOnboardingRecords(String onboardingId){
        return[SELECT Id, 
                    Personal_Details_Value_Filled__c, 
                    Identify_Details_Value_Filled__c, 
                    Address_Details_Value_Filled__c,
                    Other_Certifications_Value_Filled__c,
                    Work_Details_Filled__c,
                    Education_Details_Filled__c
                    FROM EMS_EM_Onboarding_Request__c 
                    WHERE Id =: onboardingId ];
    }

    /*@AuraEnabled(cacheable = true)
    public static List<ems_EM_Additional_Detail__c> fetchAdditionalDetailRecords(String additionalDetailId){
        return[SELECT Id, 
                    Work_Details_Filled__c, 
                    Education_Details_Filled__c,
                    Onboarding_Request__r.Id
                    FROM ems_EM_Additional_Detail__c 
                    WHERE Onboarding_Request__r.Id =: additionalDetailId ]; 
    }*/
    
}