force-app/main/default/objects/EMS_TM_Assignment__c/EMS_TM_Assignment__c.object-meta.xml
<CustomObject>
    <label>Assignment</label>
    <nameField>
        <displayFormat>A.ID-{0000}</displayFormat>
        <label>Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_TM_Assignment__c/fields/EMS_TM_ProjectName_Asgn__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_ProjectName_Asgn__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Name</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>EMS_TM_Project__c.Type_Of_Project__c</field>
            <operation>notEqual</operation>
            <value>Global Projects</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>EMS_TM_Project__c</referenceTo>
    <relationshipLabel>Project Assignees</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Assignment__c/fields/EMS_TM_Status_Asgn__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Status_Asgn__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <isActive>false</isActive>
                <label>Cancelled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EMS_TM_Project__c/EMS_TM_Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_TM_Project__c/fields/EMS_TM_Status__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ongoing</fullName>
                <default>true</default>
                <label>Ongoing</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EMS_TM_ProjectHandler.cls
public class EMS_TM_ProjectHandler {
    
    public static void assignmentStatusUpdate(List<EMS_TM_Project__c> projectList){
        Set<id> projectIds = new set<id>();
        for (EMS_TM_Project__c proj : projectList){
            if(proj.EMS_TM_Status__c == 'Completed'){
                projectIds.add(proj.Id);
            }   
        }
        System.debug('projectIds'+projectIds);
        List<EMS_TM_Assignment__C> assignList = new List<EMS_TM_Assignment__C>();
        for (EMS_TM_Assignment__C assignData: [SELECT Id, EMS_TM_ProjectName_Asgn__c, EMS_TM_Status_Asgn__c 
                                               FROM EMS_TM_Assignment__c where EMS_TM_ProjectName_Asgn__c =:projectIds ]){
                 assignData.EMS_TM_Status_Asgn__c ='Closed' ;
                 assignList.add(assignData);
                                                   
         }
        System.debug('assignList'+assignList);
        if (assignList.size() > 0){
            update assignList;
        }
    }

    public static void assignmentCreate(List<EMS_TM_Assignment__C> assigndata){
        set<id> projectIds = new Set<id>();
        for(EMS_TM_Assignment__C assign :assigndata ){
            if(assign.EMS_TM_ProjectName_Asgn__c != null){
               projectIds.add(assign.EMS_TM_ProjectName_Asgn__c); 
            }
           List<EMS_TM_Project__c> projList = new List<EMS_TM_Project__c>();           
            for(EMS_TM_Project__c p : [Select id, EMS_TM_Status__c from EMS_TM_Project__c where id =:projectIds]){
                
                if(p.EMS_TM_Status__c == 'Completed')
                {
                    projList.add(p);
                }
            }
            
            for(EMS_TM_Assignment__C assignL :assigndata ){
                if(projList.size()!=0)
                {
                    assignL.addError('Assignment create only for ongoing Projects only');
                }
            }
        }
    }
    
}