force-app/main/default/objects/EMS_TM_Assignment__c/EMS_TM_Assignment__c.object-meta.xml
<CustomObject>
    <label>Assignment</label>
    <nameField>
        <displayFormat>A.ID-{0000}</displayFormat>
        <label>Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_TM_Assignment__c/fields/EMS_TM_AssignedAs__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_AssignedAs__c</fullName>
    <label>Assigned As</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accountant</fullName>
            </value>
            <value>
                <fullName>Administrator</fullName>
            </value>
            <value>
                <fullName>Application Designer</fullName>
            </value>
            <value>
                <fullName>Business Analyst</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Consultant Architect</fullName>
            </value>
            <value>
                <fullName>Data Analyst</fullName>
            </value>
            <value>
                <fullName>Data Engineer</fullName>
            </value>
            <value>
                <fullName>Delivery Manager</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>DevOps Engineer</fullName>
            </value>
            <value>
                <fullName>Lead Business Analyst</fullName>
            </value>
            <value>
                <fullName>Lead Data Engineer</fullName>
            </value>
            <value>
                <fullName>Lead Developer</fullName>
            </value>
            <value>
                <fullName>Lead Quality Analyst</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Product Owner</fullName>
            </value>
            <value>
                <fullName>Project Manager</fullName>
            </value>
            <value>
                <fullName>Quality Analyst</fullName>
            </value>
            <value>
                <fullName>Scrum Master</fullName>
            </value>
            <value>
                <fullName>Security Engineer</fullName>
            </value>
            <value>
                <fullName>Solution Architect</fullName>
            </value>
            <value>
                <fullName>Technical Architect</fullName>
            </value>
            <value>
                <fullName>Accounting Manager</fullName>
                <isActive>false</isActive>
                <label>Accounting Manager</label>
            </value>
            <value>
                <fullName>Accounts Executive</fullName>
                <isActive>false</isActive>
                <label>Accounts Executive</label>
            </value>
            <value>
                <fullName>Analysis</fullName>
                <isActive>false</isActive>
                <label>Analysis</label>
            </value>
            <value>
                <fullName>Associate BSA</fullName>
                <isActive>false</isActive>
                <label>Associate BSA</label>
            </value>
            <value>
                <fullName>Associate Developer</fullName>
                <isActive>false</isActive>
                <label>Associate Developer</label>
            </value>
            <value>
                <fullName>Associate Engineer</fullName>
                <isActive>false</isActive>
                <label>Associate Engineer</label>
            </value>
            <value>
                <fullName>Associate Quality Analyst</fullName>
                <isActive>false</isActive>
                <label>Associate Quality Analyst</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EMS_TM_Assignment__c/fields/EMS_TM_EmployeeName__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_EmployeeName__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Employee Name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Resource</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Assignments</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Assignment__c/fields/EMS_TM_EndDate_Asgn__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_EndDate_Asgn__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Assignment__c/fields/EMS_TM_ProjectName_Asgn__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_ProjectName_Asgn__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Name</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>EMS_TM_Project__c.Type_Of_Project__c</field>
            <operation>notEqual</operation>
            <value>Global Projects</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>EMS_TM_Project__c</referenceTo>
    <relationshipLabel>Project Assignees</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Assignment__c/fields/EMS_TM_StartDate_Asgn__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_StartDate_Asgn__c</fullName>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/GetContactWhoReportToManger.cls
public without sharing class GetContactWhoReportToManger {

    @AuraEnabled(cacheable=true)
    public static List<Contact> getContacts(){

        List<Contact> contactist =  [SELECT Id,Name 
                                     			FROM Contact 
                                     			WHERE recordTypeId =:ContactConstant.RESOURCE_RECORDTYPEID];
        return contactist;
    }
     @AuraEnabled 
    public static List<EMS_TM_Assignment__c> insertMultipleAssignments(Date startDate,Date endDate, List<Id> contactIds,Id projectId,String assignedAs){
        System.debug('startDate'+startDate);
        System.debug('endDate'+endDate);
        System.debug('contactIds'+contactIds);
        System.debug('projectIdmultipleassignments'+projectId);
        List<EMS_TM_Assignment__c> assignmentList = new List<EMS_TM_Assignment__c>();

        for(Id contactId:contactIds){
            System.debug('contactId'+contactId);
         EMS_TM_Assignment__c assignmentRec = new EMS_TM_Assignment__c();
         assignmentRec.EMS_TM_EndDate_Asgn__c = endDate;
         assignmentRec.EMS_TM_StartDate_Asgn__c = startDate;
         assignmentRec.EMS_TM_ProjectName_Asgn__c = projectId;
         assignmentRec.EMS_TM_EmployeeName__c = contactId;
         assignmentRec.EMS_TM_AssignedAs__c = assignedAs;
         assignmentList.add(assignmentRec);   
        }
        try{
           insert assignmentList;
            return assignmentList;
        }catch(Exception e){
            System.debug(e.getmessage());
              throw new AuraHandledException(e.getMessage());
        }
    }
}