force-app/main/default/objects/EMS_TM_Timesheet_Record__c/EMS_TM_Timesheet_Record__c.object-meta.xml
<CustomObject>
    <label>Timesheet Line Items</label>
    <nameField>
        <displayFormat>TLI{00000000}</displayFormat>
        <label>Timesheet Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheet Records</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_TM_Timesheet_Record__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saved</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Reassign</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UpdateStatusTimeSheet.cls
/**
* @author Vamsi
* @date 05/27/2023
* @description  This class for update Timesheet records at time.
*
* CHANGE HISTORY
* ====================================================================================================
* DATE          NAME                    DESCRIPTION
* N/A           N/A                     N/A
* ====================================================================================================
**/
public class UpdateStatusTimeSheet {
    
    public static void Approvealltimesheets(Id recordId){
        list<EMS_TM_Timesheet_Record__c> TimesheetList=new list<EMS_TM_Timesheet_Record__c>();
        List<EMS_TM_Timesheet_Record__c> Timesheetrecords=[select id,status__C from EMS_TM_Timesheet_Record__c where Id=:recordId];
        for(EMS_TM_Timesheet_Record__c Timeshhet:Timesheetrecords){
            Timeshhet.status__c='Approved';
            TimesheetList.add(Timeshhet);
            
        }
        update TimesheetList;
    }
     public static void Rejectalltimesheets(Id recordId){
        list<EMS_TM_Timesheet_Record__c> RejectTimesheetList =new list<EMS_TM_Timesheet_Record__c>();
        List<EMS_TM_Timesheet_Record__c> Rejectrecords=[select id,status__C from EMS_TM_Timesheet_Record__c where Id=:recordId];
        for(EMS_TM_Timesheet_Record__c RejectTime:Rejectrecords){
            RejectTime.status__c='Rejected';
            RejectTimesheetList.add(RejectTime);
            
        }
        update RejectTimesheetList;
    }
    
}