force-app/main/default/objects/EMS_LM_Leave_Credit__c/EMS_LM_Leave_Credit__c.object-meta.xml
<CustomObject>
    <description>To credit the Leaves to Employees as per Policies</description>
    <label>Leave Credit</label>
    <nameField>
        <displayFormat>LC-{00000}</displayFormat>
        <label>Leave Credit Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leave Credits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_LM_Leave_Credit__c/fields/EMS_LM_Employee__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Employee__c</fullName>
    <label>Employee</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Leave_Credits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_Credit__c/fields/EMS_LM_Leave_Credited_Date__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Leave_Credited_Date__c</fullName>
    <description>Total No of Leaves Credited to employee</description>
    <label>Leave Credited Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_Credit__c/fields/EMS_LM_Leaves_Credited__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Leaves_Credited__c</fullName>
    <label>Leaves Credited</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_Credit__c/fields/EMS_LM_Select_Leave_Type__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Select_Leave_Type__c</fullName>
    <label>Select Leave Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Annual Leave</fullName>
            </value>
            <value>
                <fullName>Paternity Leave</fullName>
            </value>
            <value>
                <fullName>Bereavement Leave</fullName>
            </value>
            <value>
                <fullName>Loss of Pay</fullName>
            </value>
            <value>
                <fullName>Work from Home</fullName>
            </value>
            <value>
                <fullName>Maternity Leave</fullName>
            </value>
            <value>
                <fullName>Compensatory Off</fullName>
            </value>
            <value>
                <fullName>Paid time off</fullName>
            </value>
            <value>
                <fullName>UnPaid time off</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EMS_LM_AutoLeaveCreditClass.cls
public class EMS_LM_AutoLeaveCreditClass implements
Database.Batchable<sObject>, Database.Stateful {
    public Integer recordsProcessed = 0;
    public date myDate = date.today();
    public Integer day = myDate.day();
    public Integer month = myDate.month();
    
    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(
            'SELECT ID, Name FROM Contact'
        );
    }
    public void execute(Database.BatchableContext bc, List<Contact> scope){
        
        List<EMS_LM_Leave_Credit__c> leaveCreditList = new List<EMS_LM_Leave_Credit__c>();
        
        if(Test.isRunningTest()) {
            myDate = Date.newInstance(2023, 01, 01);
            day = 1;
            month = 1;
        }
        
        // process each batch of records
        for (Contact cont : scope) { 
            if((month == 1 || month == 4 || month == 7 || month == 10) && day == 1) {
                EMS_LM_Leave_Credit__c leaveCredit = new EMS_LM_Leave_Credit__c();
                leaveCredit.EMS_LM_Employee__c = cont.Id;
                leaveCredit.EMS_LM_Leave_Credited_Date__c = System.today();
                leaveCredit.EMS_LM_Leaves_Credited__c = 5;
                leaveCredit.EMS_LM_Select_Leave_Type__c = 'Annual Leave';
                leaveCreditList.add(leaveCredit);
            }
        }
        
        try {
            if(leaveCreditList.Size() > 0) {
                insert leaveCreditList;
            }
        } catch(Exception e) {
            System.debug(e);
        }
        
    }
    public void finish(Database.BatchableContext bc){
        
    }
}