force-app/main/default/objects/Contact/fields/Account_Holder_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Holder_Name__c</fullName>
    <label>Account Holder Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <label>Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Name__c</fullName>
    <label>Bank Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Axis Bank Ltd.</fullName>
            </value>
            <value>
                <fullName>Bandhan Bank Ltd.</fullName>
            </value>
            <value>
                <fullName>Bank of Baroda</fullName>
            </value>
            <value>
                <fullName>Bank of India</fullName>
            </value>
            <value>
                <fullName>Bank of Maharashtra</fullName>
            </value>
            <value>
                <fullName>Canara Bank</fullName>
            </value>
            <value>
                <fullName>Central Bank of India</fullName>
            </value>
            <value>
                <fullName>City Union Bank Ltd.</fullName>
            </value>
            <value>
                <fullName>CSB Bank Ltd.</fullName>
            </value>
            <value>
                <fullName>DCB Bank Ltd.</fullName>
            </value>
            <value>
                <fullName>Dhanlaxmi Bank Ltd.</fullName>
            </value>
            <value>
                <fullName>Federal Bank Ltd.</fullName>
            </value>
            <value>
                <fullName>HDFC Bank Ltd</fullName>
            </value>
            <value>
                <fullName>ICICI Bank Ltd.</fullName>
            </value>
            <value>
                <fullName>IDBI Bank Ltd.</fullName>
            </value>
            <value>
                <fullName>IDFC First Bank Ltd.</fullName>
            </value>
            <value>
                <fullName>Indian Bank</fullName>
            </value>
            <value>
                <fullName>Indian Overseas Bank</fullName>
            </value>
            <value>
                <fullName>Induslnd Bank Ltd</fullName>
            </value>
            <value>
                <fullName>Jammu &amp; Kashmir Bank Ltd.</fullName>
            </value>
            <value>
                <fullName>Karnataka Bank Ltd.</fullName>
            </value>
            <value>
                <fullName>Karur Vysya Bank Ltd.</fullName>
            </value>
            <value>
                <fullName>Kotak Mahindra Bank Ltd</fullName>
            </value>
            <value>
                <fullName>Nainital Bank Ltd.</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Punjab &amp; Sind Bank</fullName>
            </value>
            <value>
                <fullName>Punjab National Bank</fullName>
            </value>
            <value>
                <fullName>RBL Bank Ltd.</fullName>
            </value>
            <value>
                <fullName>South Indian Bank Ltd.</fullName>
            </value>
            <value>
                <fullName>State Bank of India</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_EM_JD__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_JD__c</fullName>
    <label>Date of Joining</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_EM_Mstatus__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_Mstatus__c</fullName>
    <label>Marital Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Single</fullName>
            </value>
            <value>
                <fullName>Married</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>EMS_Phone_Number__c</fullName>
    <label>Contact Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Contact/fields/IFSC_Code__c.field-meta.xml
<CustomField>
    <fullName>IFSC_Code__c</fullName>
    <label>IFSC Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Resource.recordType-meta.xml
<RecordType>
    <fullName>Resource</fullName>
    <active>true</active>
    <label>Resource</label>
</RecordType>

force-app/main/default/objects/EMS_EM_Request__c/EMS_EM_Request__c.object-meta.xml
<CustomObject>
    <label>Request</label>
    <nameField>
        <displayFormat>R_{00000}</displayFormat>
        <label>Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_EM_Request__c/fields/Account_Holder_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Holder_Name__c</fullName>
    <label>Account Holder Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EMS_EM_Request__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <label>Account Number</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EMS_EM_Request__c/fields/Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Name__c</fullName>
    <label>Bank Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Axis Bank Ltd.</fullName>
            </value>
            <value>
                <fullName>Bandhan Bank Ltd.</fullName>
            </value>
            <value>
                <fullName>Bank of Baroda</fullName>
            </value>
            <value>
                <fullName>Bank of India</fullName>
            </value>
            <value>
                <fullName>Bank of Maharashtra</fullName>
            </value>
            <value>
                <fullName>Canara Bank</fullName>
            </value>
            <value>
                <fullName>Central Bank of India</fullName>
            </value>
            <value>
                <fullName>City Union Bank Ltd.</fullName>
            </value>
            <value>
                <fullName>CSB Bank Ltd.</fullName>
            </value>
            <value>
                <fullName>DCB Bank Ltd.</fullName>
            </value>
            <value>
                <fullName>Dhanlaxmi Bank Ltd.</fullName>
            </value>
            <value>
                <fullName>Federal Bank Ltd.</fullName>
            </value>
            <value>
                <fullName>HDFC Bank Ltd</fullName>
            </value>
            <value>
                <fullName>ICICI Bank Ltd.</fullName>
            </value>
            <value>
                <fullName>IDBI Bank Ltd.</fullName>
            </value>
            <value>
                <fullName>IDFC First Bank Ltd.</fullName>
            </value>
            <value>
                <fullName>Indian Bank</fullName>
            </value>
            <value>
                <fullName>Indian Overseas Bank</fullName>
            </value>
            <value>
                <fullName>Induslnd Bank Ltd</fullName>
            </value>
            <value>
                <fullName>Jammu &amp; Kashmir Bank Ltd.</fullName>
            </value>
            <value>
                <fullName>Karnataka Bank Ltd.</fullName>
            </value>
            <value>
                <fullName>Karur Vysya Bank Ltd.</fullName>
            </value>
            <value>
                <fullName>Kotak Mahindra Bank Ltd</fullName>
            </value>
            <value>
                <fullName>Nainital Bank Ltd.</fullName>
            </value>
            <value>
                <fullName>Punjab &amp; Sind Bank</fullName>
            </value>
            <value>
                <fullName>Punjab National Bank</fullName>
            </value>
            <value>
                <fullName>RBL Bank Ltd.</fullName>
            </value>
            <value>
                <fullName>South Indian Bank Ltd.</fullName>
            </value>
            <value>
                <fullName>State Bank of India</fullName>
            </value>
            <value>
                <fullName>Tamilnad Mercantile Bank Ltd.</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EMS_EM_Request__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Requests</relationshipLabel>
    <relationshipName>Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_EM_Request__c/fields/EMS_EM_Request_Type__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_Request_Type__c</fullName>
    <label>Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Address Details</fullName>
            </value>
            <value>
                <fullName>Bank Details</fullName>
            </value>
            <value>
                <fullName>Education Details</fullName>
            </value>
            <value>
                <fullName>Emergency Details</fullName>
            </value>
            <value>
                <fullName>Personal Details</fullName>
            </value>
            <value>
                <fullName>Vehicle Details</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EMS_EM_Request__c/fields/IFSC_Code__c.field-meta.xml
<CustomField>
    <fullName>IFSC_Code__c</fullName>
    <label>IFSC Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ApprovalProcessControllerTest.cls
@isTest
public class ApprovalProcessControllerTest {
    @isTest
    public static void recallApprovalTest(){
        
        Account acc = new Account();
        acc.Name ='rama';
        acc.Phone='96529015';
        //  acc.IsCustomerPortal = true;
        insert acc;
        System.debug('acc'+acc);
        Contact con = new contact();
        con.Email ='ramakrishna@gmail.com';
        con.AccountId = acc.id;
        con.FirstName ='rama111';
        con.LastName ='krishna11';
        con.EMS_Phone_Number__c ='965210752';
        con.EMS_EM_Mstatus__c  = 'Single';
        con.EMS_EM_JD__c = System.today();
        con.RecordTypeId = [SELECT Id FROM RecordType where name = 'Resource'].Id;
        insert con;
        
        EMS_EM_Request__c req1 = new EMS_EM_Request__c();
        req1.Contact__c = con.id;
        req1.EMS_EM_Request_Type__c = 'Bank Details';
        req1.Account_Number__c = '123456789456';
        req1.IFSC_Code__c = 'ABCD1234567';
        req1.Account_Holder_Name__c = 'Mukesh';
        req1.Bank_Name__c='Axis Bank Ltd.';
        insert req1;
        
        EMS_EM_Request__c req2 = new EMS_EM_Request__c();
        req1.Contact__c = con.id;
        req1.EMS_EM_Request_Type__c = 'Bank Details2';
        req1.Account_Number__c = '1234567894546';
        req1.IFSC_Code__c = 'ABCD12345667';
        req1.Account_Holder_Name__c = 'Mukesh2';
        req1.Bank_Name__c='Axis Bank Ltd.';
        insert req2;
        
        Approval.ProcessSubmitRequest app = new Approval.ProcessSubmitRequest();
        app.setObjectId(req2.id);
        Approval.ProcessResult result = Approval.process(app);
        ApprovalProcessController.recallApproval(req2.id);
        
    }
}