force-app/main/default/objects/Contact/fields/CP_Sales_Contact__c.field-meta.xml
<CustomField>
    <fullName>CP_Sales_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CP Sales _ Contact</label>
    <referenceTo>CP_Sales_Contact__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>EMS_Phone_Number__c</fullName>
    <label>Contact Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/CP_Sales_Contact__c/CP_Sales_Contact__c.object-meta.xml
<CustomObject>
    <label>Contact</label>
    <nameField>
        <label>Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CP_Sales_Contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>CP_Sales_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CustomContactHandlerTest.cls
@isTest
public class CustomContactHandlerTest {
   @isTest
    public static void CustomContactHandlerTestMethod()
    {
                
        Contact Con = new Contact();
        con.RecordTypeId=Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Sales Contact').getRecordTypeId();
        Con.FirstName = 'Test';
        Con.LastName = 'SF Contact';
        Con.Email = 'testSF@Salesforce.com';
        Con.EMS_Phone_Number__c = '123456789';
        insert Con;  
        
        CP_Sales_Contact__c cp = new CP_Sales_Contact__c();
        cp.Name ='Contact ';
        cp.Contact__c = Con.id;
        cp.Phone_Number__c = '123456789';
        insert cp;
        update cp;
             
        Campaign ca1 = new Campaign();
        ca1.Name = '5Rings';
        ca1.IsActive = TRUE;
        ca1.Type = 'Email';
        insert ca1;
        
        CampaignMember m1 = new CampaignMember();
        m1.ContactId = Con.Id; 
        m1.CampaignId = ca1.Id;
        m1.Status ='Sent';
        
        Test.StartTest();
        insert m1;
        update m1;
        Test.stopTest();
    }
}