force-app/main/default/objects/Contact/fields/Designation__c.field-meta.xml
<CustomField>
    <fullName>Designation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Designation</label>
    <referenceTo>Designation__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_Driving_License_No__c.field-meta.xml
<CustomField>
    <fullName>EMS_Driving_License_No__c</fullName>
    <label>Driving License No.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_EM_AadhaarNo__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_AadhaarNo__c</fullName>
    <label>Aadhaar Number</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_EM_BG__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_BG__c</fullName>
    <label>Blood Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A RhD positive (A+)</fullName>
            </value>
            <value>
                <fullName>A RhD negative (A-)</fullName>
            </value>
            <value>
                <fullName>B RhD positive (B+)</fullName>
            </value>
            <value>
                <fullName>B RhD negative (B-)</fullName>
            </value>
            <value>
                <fullName>O RhD positive (O+)</fullName>
            </value>
            <value>
                <fullName>O RhD negative (O-)</fullName>
            </value>
            <value>
                <fullName>AB RhD positive (AB+)</fullName>
            </value>
            <value>
                <fullName>AB RhD negative (AB-)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_EM_CA_State__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_CA_State__c</fullName>
    <label>State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_EM_CAddress_Line_1__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_CAddress_Line_1__c</fullName>
    <label>Address Line 1</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_EM_CAddress_Line_2__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_CAddress_Line_2__c</fullName>
    <label>Address Line 2</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_EM_DOB__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_DOB__c</fullName>
    <label>Date of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_EM_Gender__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_EM_HR_Assigned__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_HR_Assigned__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>HR Assigned</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND (2 OR 3 OR 4)</booleanFilter>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Resource</value>
        </filterItems>
        <filterItems>
            <field>Contact.Resource_Role__r.Name</field>
            <operation>equals</operation>
            <value>HR Executive</value>
        </filterItems>
        <filterItems>
            <field>Contact.Resource_Role__r.Name</field>
            <operation>equals</operation>
            <value>HR Director</value>
        </filterItems>
        <filterItems>
            <field>Contact.Resource_Role__r.Name</field>
            <operation>equals</operation>
            <value>HR Manager</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_EM_JD__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_JD__c</fullName>
    <label>Date of Joining</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_EM_Nationality__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_Nationality__c</fullName>
    <label>Nationality</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_EM_OLocation__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_OLocation__c</fullName>
    <label>Office Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hyderabad</fullName>
            </value>
            <value>
                <fullName>Vijayawada</fullName>
            </value>
            <value>
                <fullName>Sunnyvale</fullName>
            </value>
            <value>
                <fullName>San Ramon</fullName>
            </value>
            <value>
                <fullName>US</fullName>
            </value>
            <value>
                <fullName>3000 Executive Parkway, San Ramon</fullName>
                <isActive>false</isActive>
                <label>3000 Executive Parkway, San Ramon</label>
            </value>
            <value>
                <fullName>36 Jubilee Hills, Hyderabad</fullName>
                <isActive>false</isActive>
                <label>36 Jubilee Hills, Hyderabad</label>
            </value>
            <value>
                <fullName>830 Stewart Dr, Sunnyvale</fullName>
                <isActive>false</isActive>
                <label>830 Stewart Dr, Sunnyvale</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_EM_PAddress_Line_1__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_PAddress_Line_1__c</fullName>
    <label>Address Line 1</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_EM_PAddress_Line_2__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_PAddress_Line_2__c</fullName>
    <label>Address Line 2</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_EM_PanNo__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_PanNo__c</fullName>
    <label>PAN</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_EM_PassportNo__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_PassportNo__c</fullName>
    <label>Passport Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_EM_PFno__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_PFno__c</fullName>
    <label>UAN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_EM_PP__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_PP__c</fullName>
    <label>Probation Period (In Days)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_Employee_Type__c.field-meta.xml
<CustomField>
    <fullName>EMS_Employee_Type__c</fullName>
    <label>Employee Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Part-time</fullName>
            </value>
            <value>
                <fullName>Full-time</fullName>
            </value>
            <value>
                <fullName>Contractor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>EMS_Phone_Number__c</fullName>
    <label>Contact Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_RM_Current_Job_Role__c.field-meta.xml
<CustomField>
    <fullName>EMS_RM_Current_Job_Role__c</fullName>
    <label>Designation</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accounts Manager</fullName>
            </value>
            <value>
                <fullName>Associate Business Analyst</fullName>
            </value>
            <value>
                <fullName>Associate Developer</fullName>
            </value>
            <value>
                <fullName>Associate Engineer</fullName>
            </value>
            <value>
                <fullName>Associate Project Manager</fullName>
            </value>
            <value>
                <fullName>Associate Salesforce Business Analyst</fullName>
            </value>
            <value>
                <fullName>Associate Salesforce Developer</fullName>
            </value>
            <value>
                <fullName>Associate Salesforce Quality Analyst</fullName>
            </value>
            <value>
                <fullName>Associate SFMC Developer</fullName>
            </value>
            <value>
                <fullName>Associate Talent Acquisition Partner</fullName>
            </value>
            <value>
                <fullName>Account Executive</fullName>
            </value>
            <value>
                <fullName>Accounts Executive</fullName>
            </value>
            <value>
                <fullName>Associate Architect</fullName>
            </value>
            <value>
                <fullName>Business Systems Analyst</fullName>
            </value>
            <value>
                <fullName>Consultant Architecture</fullName>
            </value>
            <value>
                <fullName>Data Analyst</fullName>
            </value>
            <value>
                <fullName>Data Scientist</fullName>
            </value>
            <value>
                <fullName>Delivery Manager</fullName>
            </value>
            <value>
                <fullName>Director of Sales</fullName>
            </value>
            <value>
                <fullName>HR Executive</fullName>
            </value>
            <value>
                <fullName>HR Manager</fullName>
            </value>
            <value>
                <fullName>Jr. UX Designer</fullName>
            </value>
            <value>
                <fullName>Lead Data Migration Engineer</fullName>
            </value>
            <value>
                <fullName>Lead Salesforce Business System Analyst</fullName>
            </value>
            <value>
                <fullName>Lead Salesforce Developer</fullName>
            </value>
            <value>
                <fullName>Lead Salesforce Quality Analyst</fullName>
            </value>
            <value>
                <fullName>Project Manager</fullName>
            </value>
            <value>
                <fullName>Salesforce Administrator</fullName>
            </value>
            <value>
                <fullName>Salesforce Application Designer</fullName>
            </value>
            <value>
                <fullName>Salesforce Business Analyst</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_RM_Employee_Id__c.field-meta.xml
<CustomField>
    <fullName>EMS_RM_Employee_Id__c</fullName>
    <label>Employee ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_RM_Notice_Period__c.field-meta.xml
<CustomField>
    <fullName>EMS_RM_Notice_Period__c</fullName>
    <label>Notice period</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>USA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Official_Mail__c.field-meta.xml
<CustomField>
    <fullName>Official_Mail__c</fullName>
    <label>Official Email ID(old)</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Personal_Email__c.field-meta.xml
<CustomField>
    <fullName>Personal_Email__c</fullName>
    <label>Personal Email Id</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Resource_Manager__c.field-meta.xml
<CustomField>
    <fullName>Resource_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Manager</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Resource</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contacts (Resource Manager)</relationshipLabel>
    <relationshipName>Contacts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Work_Experience__c.field-meta.xml
<CustomField>
    <fullName>Work_Experience__c</fullName>
    <label>Work Experience</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GetDataForLoginUser.cls
/**
* @author Mukesh Rawat 
* @date 8/02/2023
* @description  Getting Grid Configuration Data and Login User Data Using Methods
*
*               Test code coverage provided by the following test class:
*               - 
*
* CHANGE HISTORY
* ====================================================================================================
* DATE          NAME                    DESCRIPTION
* N/A           N/A                     N/A
* ====================================================================================================
**/

public without Sharing class GetDataForLoginUser {
    public class relatedFile {
        public String PathOnClient;
        public String Title;
        public Blob VersionData;
    }
    
    @AuraEnabled
    public static contact getUserContactInfo(Id userId){
        user u =[Select id,
                 name,
                 Contactid 
                 FROM user where id =: userId  AND Contactid != null];
        System.debug('userid'+U);
        
        contact contactDetails =[SELECT Lastname,
                                 Name,
                                 Firstname,
                                 EMS_EM_Gender__c,
                                 EMS_Phone_Number__c,
                                 Personal_Email__c,
                                 EMS_EM_DOB__c,
                                 EMS_EM_BG__c,
                                 EMS_EM_Nationality__c,
                                 EMS_EM_AadhaarNo__c,
                                 EMS_EM_PanNo__c,
                                 EMS_EM_PassportNo__c,
                                 EMS_EM_PFno__c,
                                 EMS_Driving_License_No__c,
                                 EMS_RM_Employee_Id__c,
                                 Resource_Manager__c,
                                 Designation__c,
                                 EMS_RM_Current_Job_Role__c,
                                 //Department
                                 EMS_Employee_Type__c,
                                 EMS_EM_OLocation__c,
                                 AccountId,
                                 Location__c,
                                 Official_Mail__c,
                                 Work_Experience__c,
                                 EMS_EM_HR_Assigned__c,
                                 EMS_EM_JD__c,
                                 EMS_EM_PP__c,
                                 EMS_RM_Notice_Period__c,
                                 EMS_EM_CAddress_Line_1__c,
                                 EMS_EM_PAddress_Line_1__c,
                                 EMS_EM_CAddress_Line_2__c,
                                 EMS_EM_PAddress_Line_2__c,
                                 EMS_EM_CA_State__c,
                                 EMS_EM_PA_State__c,
                                 EMS_EM_CA_City__c,
                                 EMS_EM_PA_City__c,
                                 EMS_EM_CA_Zip__c,
                                 EMS_EM_PA_Zip__c,
                                 Do_you_have_a_vehicle__c,
                                 Vehicle_Number__c,
                                 Vehicle_Type__c,
                                 Post_Onboarding_Confirm__c
                                 From Contact where id =: u.contactid];
        
        return contactDetails;
        
    }
    
    @AuraEnabled(cacheable=true)
    public static List<PayRoll__c> getPayrollInfo(string conId){
        return [SELECT Id, 
                Name,
                Beneficiary_Name__c,
                Bank_Name__c,
                Branch__c,
                Beneficiary_Account_Number__c,
                IFSC_Routing_Number__c,
                Contact__c
                From PayRoll__c where Contact__c =: conId];
        
    }
    
    @AuraEnabled(cacheable=true)
    public static List<Grid_Configuration__c> WelcomeAboardData() {
        return [SELECT Id, 
                Name, 
                CreatedDate, 
                Description__c, 
                Grid_Configuration_Type__c 
                FROM Grid_Configuration__c where Grid_Configuration_Type__c = 'Welcome aboard' Limit 1];
    }
    
    @AuraEnabled(cacheable=true)
    public static List<Grid_Configuration__c> CompanyGridData() {
        return [SELECT Id, 
                Name, 
                CreatedDate, 
                Description__c, 
                Grid_Configuration_Type__c 
                FROM Grid_Configuration__c where Grid_Configuration_Type__c = 'Company Information - EMP- Onboarding' Limit 1];
    }
    
    @AuraEnabled(cacheable=true)
    public static List<Grid_Configuration__c> pfFormsid() {
        return [SELECT Id, 
                Name, 
                CreatedDate, 
                Description__c, 
                Grid_Configuration_Type__c 
                FROM Grid_Configuration__c where Grid_Configuration_Type__c = 'PF Forms' Limit 1];
    }
    
    @AuraEnabled(cacheable=true)
    public static List<Grid_Configuration__c> Documentsdata() {
        return [SELECT Id, 
                Name, 
                CreatedDate, 
                Description__c, 
                Grid_Configuration_Type__c 
                FROM Grid_Configuration__c where Grid_Configuration_Type__c = 'Documents' Limit 1];
    }
    
    @AuraEnabled(cacheable=true)
    public static List<Grid_Configuration__c> CompanyPoliciesdata() {
        return [SELECT Id, 
                Name, 
                CreatedDate, 
                Description__c, 
                Grid_Configuration_Type__c 
                FROM Grid_Configuration__c where Grid_Configuration_Type__c = 'Company Policies' Limit 1];
    }
    
    @AuraEnabled(cacheable=true)
    public static Map<ID, String> getRelatedFilesByRecordId(String recordId) {
        // Get record file IDs        
        List<ContentDocumentLink> files = [SELECT ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId = :recordId];
        List<ID> fileIDs = new List<ID>();
        for (ContentDocumentLink docLink : files) {
            fileIDs.add(docLink.ContentDocumentId);
        }
        
        List<ContentVersion> docs = [SELECT ContentDocumentId, FileExtension, Title 
                                     FROM ContentVersion WHERE ContentDocumentId IN : fileIDs];
        Map<ID, String> mapIdTitle = new Map<ID, String>();
        for (ContentVersion docLink : docs) {
            mapIdTitle.put(docLink.ContentDocumentId, docLink.Title);
        }
        return mapIdTitle;
    }
    
    @AuraEnabled(cacheable=true)
    public static String getLoginURL(){
        String baseURL = System.URL.getSalesforceBaseUrl().toExternalForm();
        User userRecord = [Select Id, AccountId, ContactId FROM User Where Id = :UserInfo.getUserId()];
        if(userRecord.ContactId != null){
            baseUrl = getExperienceURL();
        }
        return baseUrl;
    }
    
    public static String getExperienceURL(){
        String baseUrl = Network.getLoginUrl(Network.getNetworkId());
        baseURL =  baseURL.replace('/s/login', '');
        baseURL =  baseURL.replace('/s/Login', '');
        baseURL =  baseURL.replace('/login', '');
        baseURL =  baseURL.replace('/Login', '');
        return baseURL;
    }
    
    @AuraEnabled
    public static Contact updateContact( Contact newRecord,String ConRecordid,  PayRoll__c newPayroll, List<Object> files) {
        
        newRecord.Id=ConRecordid;
        update newRecord;
        
        newPayroll.Contact__c =newRecord.Id;
        
        if (newPayroll.Contact__c != null) {
            List<PayRoll__c> existingPayrolls = [SELECT Id FROM PayRoll__c WHERE Contact__c = :newRecord.Id LIMIT 1];
            
            if (existingPayrolls.size() > 0) {
                newPayroll.Id = existingPayrolls[0].Id;
                update newPayroll;
            } else {
                insert newPayroll;
            }
        } else {
            insert newPayroll;
        }
        
        List<ContentVersion> relatedDocuments = new List<ContentVersion>();
        for (Object file : files) {
            system.debug('the file'+file);
            String fileJson = JSON.serialize(file);
            relatedFile relatedDocument = (relatedFile) JSON.deserialize(fileJson, relatedFile.class);
            ContentVersion contentVersionFile = new ContentVersion();
            contentVersionFile.PathOnClient = relatedDocument.PathOnClient;
            contentVersionFile.Title = relatedDocument.Title;
            contentVersionFile.FirstPublishLocationId= newRecord.Id;
            contentVersionFile.VersionData = relatedDocument.VersionData;
            relatedDocuments.add(contentVersionFile);
            system.debug('contentVersionFile-->'+contentVersionFile);
        }
        Database.saveResult[] srFiles = Database.insert(relatedDocuments);
        return newRecord;
        
    }
    
    @AuraEnabled
    public static PayRoll__c updatepayroll( String ConRecordid,  PayRoll__c newPayroll, String PayrollId) {
        
        newPayroll.Id = PayrollId;
        newPayroll.Contact__c = ConRecordid;
        update newPayroll;
        return newPayroll;    
    }
    
    
}