force-app/main/default/objects/Contact/fields/EMS_RM_Employee_Id__c.field-meta.xml
<CustomField>
    <fullName>EMS_RM_Employee_Id__c</fullName>
    <label>Employee ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_TM_Billable__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Billable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Billable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Assignment__c/EMS_TM_Assignment__c.object-meta.xml
<CustomObject>
    <label>Assignment</label>
    <nameField>
        <displayFormat>A.ID-{0000}</displayFormat>
        <label>Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_TM_Assignment__c/fields/EMS_TM_AssignedAs__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_AssignedAs__c</fullName>
    <label>Assigned As</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accountant</fullName>
            </value>
            <value>
                <fullName>Administrator</fullName>
            </value>
            <value>
                <fullName>Application Designer</fullName>
            </value>
            <value>
                <fullName>Business Analyst</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Consultant Architect</fullName>
            </value>
            <value>
                <fullName>Data Analyst</fullName>
            </value>
            <value>
                <fullName>Data Engineer</fullName>
            </value>
            <value>
                <fullName>Delivery Manager</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>DevOps Engineer</fullName>
            </value>
            <value>
                <fullName>Lead Business Analyst</fullName>
            </value>
            <value>
                <fullName>Lead Data Engineer</fullName>
            </value>
            <value>
                <fullName>Lead Developer</fullName>
            </value>
            <value>
                <fullName>Lead Quality Analyst</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Product Owner</fullName>
            </value>
            <value>
                <fullName>Project Manager</fullName>
            </value>
            <value>
                <fullName>Quality Analyst</fullName>
            </value>
            <value>
                <fullName>Scrum Master</fullName>
            </value>
            <value>
                <fullName>Security Engineer</fullName>
            </value>
            <value>
                <fullName>Solution Architect</fullName>
            </value>
            <value>
                <fullName>Technical Architect</fullName>
            </value>
            <value>
                <fullName>Accounting Manager</fullName>
                <isActive>false</isActive>
                <label>Accounting Manager</label>
            </value>
            <value>
                <fullName>Accounts Executive</fullName>
                <isActive>false</isActive>
                <label>Accounts Executive</label>
            </value>
            <value>
                <fullName>Analysis</fullName>
                <isActive>false</isActive>
                <label>Analysis</label>
            </value>
            <value>
                <fullName>Associate BSA</fullName>
                <isActive>false</isActive>
                <label>Associate BSA</label>
            </value>
            <value>
                <fullName>Associate Developer</fullName>
                <isActive>false</isActive>
                <label>Associate Developer</label>
            </value>
            <value>
                <fullName>Associate Engineer</fullName>
                <isActive>false</isActive>
                <label>Associate Engineer</label>
            </value>
            <value>
                <fullName>Associate Quality Analyst</fullName>
                <isActive>false</isActive>
                <label>Associate Quality Analyst</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EMS_TM_Assignment__c/fields/EMS_TM_Billable__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Billable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Billable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Assignment__c/fields/EMS_TM_EmployeeName__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_EmployeeName__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Employee Name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Resource</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Assignments</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Assignment__c/fields/EMS_TM_EndDate_Asgn__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_EndDate_Asgn__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Assignment__c/fields/EMS_TM_ProjectName_Asgn__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_ProjectName_Asgn__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Name</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>EMS_TM_Project__c.Type_Of_Project__c</field>
            <operation>notEqual</operation>
            <value>Global Projects</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>EMS_TM_Project__c</referenceTo>
    <relationshipLabel>Project Assignees</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Assignment__c/fields/EMS_TM_StartDate_Asgn__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_StartDate_Asgn__c</fullName>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Assignment__c/fields/EMS_TM_Status_Asgn__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Status_Asgn__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <isActive>false</isActive>
                <label>Cancelled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EMS_TM_Assignment__c/fields/Project_Allocation__c.field-meta.xml
<CustomField>
    <fullName>Project_Allocation__c</fullName>
    <inlineHelpText>Percentage of effort allocated for this project</inlineHelpText>
    <label>Project Allocation %</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Project__c/EMS_TM_Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_TM_Project__c/fields/EMS_TM_Status__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ongoing</fullName>
                <default>true</default>
                <label>Ongoing</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EMS_TM_Project__c/fields/Type_Of_Project__c.field-meta.xml
<CustomField>
    <fullName>Type_Of_Project__c</fullName>
    <label>Type of Project</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Client Projects</fullName>
            </value>
            <value>
                <fullName>Internal Projects</fullName>
            </value>
            <value>
                <fullName>Global Projects</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProjectAllocationTabController.cls
public with sharing class ProjectAllocationTabController {
    @AuraEnabled(cacheable=true)
    public static List<AssignmentWrapper> getActiveAssignments(String searchTerm, String searchProject) {
        String searchQuery = '%' + searchTerm + '%';
        String searchProjectQuery = '%' + searchProject + '%';
        List<EMS_TM_Assignment__c> assignments = [SELECT Id,Name,EMS_TM_ProjectName_Asgn__r.Name, EMS_TM_AssignedAs__c, EMS_TM_EmployeeName__r.Name, EMS_TM_EmployeeName__r.EMS_RM_Employee_Id__c, EMS_TM_EmployeeName__r.id, EMS_TM_EmployeeName__r.Email, Project_Allocation__c, EMS_TM_StartDate_Asgn__c, EMS_TM_EndDate_Asgn__c, 
                                                  EMS_TM_Status_Asgn__c, EMS_TM_Billable__c
                                                  FROM EMS_TM_Assignment__c
                                                  WHERE EMS_TM_Status_Asgn__c = 'Active' AND EMS_TM_EmployeeName__r.Name LIKE :searchQuery AND EMS_TM_ProjectName_Asgn__r.Name LIKE: searchProjectQuery ORDER BY LastModifiedDate desc];
        
        
        List<AssignmentWrapper> assignmentWrappers = new List<AssignmentWrapper>();
        
        for (EMS_TM_Assignment__c assignment : assignments) {
            AssignmentWrapper wrapper = new AssignmentWrapper();
            wrapper.assignmentId = assignment.Id;
            wrapper.Name = assignment.Name;
            wrapper.projectName = assignment.EMS_TM_ProjectName_Asgn__r.Name;
            wrapper.projectid = assignment.EMS_TM_ProjectName_Asgn__r.Id;
            wrapper.assignedAs = assignment.EMS_TM_AssignedAs__c;
            wrapper.employeeName = assignment.EMS_TM_EmployeeName__r.Name;
            wrapper.employeeId = assignment.EMS_TM_EmployeeName__r.EMS_RM_Employee_Id__c;
            wrapper.contactId = assignment.EMS_TM_EmployeeName__r.Id;
            wrapper.employeeEmail = assignment.EMS_TM_EmployeeName__r.Email;
            wrapper.projectAllocation = assignment.Project_Allocation__c != null ? assignment.Project_Allocation__c : 0;
            wrapper.Billable = assignment.EMS_TM_Billable__c;
            wrapper.startDate = assignment.EMS_TM_StartDate_Asgn__c;
            wrapper.endDate = assignment.EMS_TM_EndDate_Asgn__c;
            wrapper.status = assignment.EMS_TM_Status_Asgn__c;
            assignmentWrappers.add(wrapper);
        }
        
        return assignmentWrappers;
    }
    
    @AuraEnabled(cacheable=true)
    public static AssignmentWrapper getAssignmentWrapperWithProjectOptions() {
        AssignmentWrapper optionsWrapper = new AssignmentWrapper();
        optionsWrapper.projectOptions = getActiveProjectsList();
        return optionsWrapper;
    }
    
    
    @AuraEnabled(cacheable=true)
    public static List<String> getActiveProjectsList() {
        List<String> projectOptions = new List<String>();
        List<EMS_TM_Project__c> projects = fetchActiveProjectsList();
        
        for (EMS_TM_Project__c project : projects) {
            projectOptions.add(project.Name);
        }
        
        return projectOptions;
    }
    
    public static List<EMS_TM_Project__c> fetchActiveProjectsList(){
        return [SELECT Id, Name, EMS_TM_Status__c FROM EMS_TM_Project__c WHERE EMS_TM_Status__c = 'Ongoing' AND Type_Of_Project__c != 'Global Projects'];
    }
    
    @AuraEnabled
    public static string dmlOnAssignments(Object data) {
        List<EMS_TM_Assignment__c> updateAssignments = (List<EMS_TM_Assignment__c>) JSON.deserialize(JSON.serialize(data), List<EMS_TM_Assignment__c>.class);
        
        
        try {
            if(updateAssignments != null && !updateAssignments.isEmpty()){
                upsert updateAssignments;
            }
            return 'Success: Assignment(s) upsert successfully';
        }
        catch (Exception e) {
            String errorMsg = 'The following exception has occurred: ' + e.getMessage();
            throw new AuraHandledException(ErrorMsg);
        }
    }
    
    
    public class AssignmentWrapper {
        @AuraEnabled public Id assignmentId;
        @AuraEnabled public Id projectid;
        @AuraEnabled public String projectName;
        @AuraEnabled public String assignedAs;
        @AuraEnabled public String employeeName;
        @AuraEnabled public String employeeId;
        @AuraEnabled public String contactId;
        @AuraEnabled public String employeeEmail;
        @AuraEnabled public Decimal projectAllocation;
        @AuraEnabled public Boolean Billable;
        @AuraEnabled public Date startDate;
        @AuraEnabled public Date endDate;
        @AuraEnabled public String status;
        @AuraEnabled public String Name;
        @AuraEnabled public List<String> projectOptions;
    }
}