force-app/main/default/objects/Contact/fields/EMS_RM_ApplicantStatus_Update__c.field-meta.xml
<CustomField>
    <fullName>EMS_RM_ApplicantStatus_Update__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Offer rolled out</fullName>
            </value>
            <value>
                <fullName>Offer accepted</fullName>
            </value>
            <value>
                <fullName>Offer rejected</fullName>
            </value>
            <value>
                <fullName>Hired</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Did not join</fullName>
            </value>
            <value>
                <fullName>Active - Probation</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Notice Period</fullName>
            </value>
            <value>
                <fullName>ABSENT</fullName>
                <isActive>false</isActive>
                <label>ABSENT</label>
            </value>
            <value>
                <fullName>Docs received</fullName>
                <isActive>false</isActive>
                <label>Docs received</label>
            </value>
            <value>
                <fullName>Docs verified</fullName>
                <isActive>false</isActive>
                <label>Docs verified</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_TM_User__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Resource_Role__c.field-meta.xml
<CustomField>
    <fullName>Resource_Role__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Role</label>
    <referenceTo>Resource_Role__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Timesheet_NoNeed__c.field-meta.xml
<CustomField>
    <fullName>Timesheet_NoNeed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Timesheet NoNeed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Resource.recordType-meta.xml
<RecordType>
    <fullName>Resource</fullName>
    <active>true</active>
    <label>Resource</label>
</RecordType>

force-app/main/default/objects/Goal__c/Goal__c.object-meta.xml
<CustomObject>
    <label>Goal</label>
    <nameField>
        <displayFormat>GOAL{000000}</displayFormat>
        <label>Goal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Goals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Goal__c/fields/Goal_Name__c.field-meta.xml
<CustomField>
    <fullName>Goal_Name__c</fullName>
    <label>Goal Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Goal__c/fields/is_Navigation_Required__c.field-meta.xml
<CustomField>
    <fullName>is_Navigation_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>is Navigation Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Goal__c/fields/Navigation_address__c.field-meta.xml
<CustomField>
    <fullName>Navigation_address__c</fullName>
    <label>Navigation address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Goal__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Goals</relationshipLabel>
    <relationshipName>Goals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Goal__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Missed</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>KRA Inreview</fullName>
            </value>
            <value>
                <fullName>KRA Completed</fullName>
            </value>
            <value>
                <fullName>Pulse Submitted</fullName>
            </value>
            <value>
                <fullName>Pulse Requested</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>HR KRA Completed</fullName>
            </value>
            <value>
                <fullName>Completed - OnTime</fullName>
                <isActive>false</isActive>
                <label>Completed - OnTime</label>
            </value>
            <value>
                <fullName>Completed - PostTime</fullName>
                <isActive>false</isActive>
                <label>Completed - PostTime</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Goal__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Survey</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>KRA</fullName>
            </value>
            <value>
                <fullName>Org Level Goal</fullName>
            </value>
            <value>
                <fullName>Resource Role Level Goal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Goal__c/recordTypes/Goal.recordType-meta.xml
<RecordType>
    <fullName>Goal</fullName>
    <active>true</active>
    <label>Goal</label>
</RecordType>

force-app/main/default/objects/Grid_Configuration__c/Grid_Configuration__c.object-meta.xml
<CustomObject>
    <label>Grid Configuration</label>
    <nameField>
        <label>Grid Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grid Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Grid_Configuration__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Grid_Configuration__c/fields/Goal_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Goal_End_Date__c</fullName>
    <label>Goal End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Grid_Configuration__c/fields/Goal_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Goal_Start_Date__c</fullName>
    <label>Goal Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Grid_Configuration__c/fields/Grid_Configuration_Type__c.field-meta.xml
<CustomField>
    <fullName>Grid_Configuration_Type__c</fullName>
    <label>Grid Configuration Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Welcome aboard</fullName>
            </value>
            <value>
                <fullName>PF Forms</fullName>
            </value>
            <value>
                <fullName>Documents</fullName>
            </value>
            <value>
                <fullName>Company Policies</fullName>
            </value>
            <value>
                <fullName>Company Information - EMP- Onboarding</fullName>
            </value>
            <value>
                <fullName>Company Information - Pre-Onboarding</fullName>
            </value>
            <value>
                <fullName>Org Level Goal</fullName>
            </value>
            <value>
                <fullName>Resource Role Level Goal</fullName>
            </value>
            <value>
                <fullName>Org Level Alert</fullName>
            </value>
            <value>
                <fullName>Resource Role Alert</fullName>
            </value>
            <value>
                <fullName>KRA</fullName>
            </value>
            <value>
                <fullName>Annual Award</fullName>
            </value>
            <value>
                <fullName>Annual Award Result</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Grid_Configuration__c/fields/is_Navigation_Required__c.field-meta.xml
<CustomField>
    <fullName>is_Navigation_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Navigation Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Grid_Configuration__c/fields/Navigation_address__c.field-meta.xml
<CustomField>
    <fullName>Navigation_address__c</fullName>
    <label>Navigation Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grid_Configuration__c/fields/Resource_Role__c.field-meta.xml
<CustomField>
    <fullName>Resource_Role__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Role</label>
    <referenceTo>Resource_Role__c</referenceTo>
    <relationshipLabel>Grid Configurations</relationshipLabel>
    <relationshipName>Grid_Configurations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Resource_Role__c/Resource_Role__c.object-meta.xml
<CustomObject>
    <label>Resource Role</label>
    <nameField>
        <label>Resource Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resource Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/BatchToCreateGoalsForRes.cls
/**
* @author Subba Kalavala
* @date 2/22/2023
* @description  BatchToCreateGoalsForRes Batch to create goals  
*              
*               Schedule class 
*               - BatchToCreateGoalsForRes
*               Test code coverage provided by the following test class:
*               - BatchToCreateGoalsForRes_Test
*
* CHANGE HISTORY
* ====================================================================================================
* DATE          NAME                    DESCRIPTION
* N/A           N/A                     N/A
* ====================================================================================================
**/
global class BatchToCreateGoalsForRes implements Database.Batchable<sObject> {
 /**
* @author Subba
* @date 22/01/2023
* @description start query to get the data of the object that required to process.
*
* CHANGE HISTORY
* ====================================================================================================
* DATE          NAME                    DESCRIPTION
* N/A           N/A                     N/A
* ====================================================================================================
**/
    global Database.QueryLocator start(Database.BatchableContext BC) {
        
        //date dt = Test.isRunningTest() ? system.today().adddays(1) : system.today() ;
        date dt =  system.today().adddays(1);
        system.debug('33');
        system.debug(dt);
       
        return Database.getQueryLocator([SELECT Id,Description__c,Name,Goal_End_Date__c,Goal_Start_Date__c,Grid_Configuration_Type__c,
                                         Navigation_address__c,is_Navigation_Required__c,Resource_Role__c 
                                         FROM Grid_Configuration__c 
                                         WHERE Goal_Start_Date__c=:dt AND (Grid_Configuration_Type__c = 'Org Level Goal' OR Grid_Configuration_Type__c = 'Resource Role Level Goal')]);
    }


/**
* @author Subba
* @date 22/01/2023
* @description  Execute method to process the business logic.
*
* CHANGE HISTORY
* ====================================================================================================
* DATE          NAME                    DESCRIPTION
* N/A           N/A                     N/A
* ====================================================================================================
**/
    global void execute(Database.BatchableContext BC, List<Grid_Configuration__c> configList) {
        system.debug('53');
        system.debug(configList);
        List<Goal__c> goalList = new List<Goal__c>();
        Grid_Configuration__c configRec = configList[0];
        
        List<Contact> conList = new List<Contact>();
        if(configRec.Grid_Configuration_Type__c == 'Org Level Goal'){
            conList = [SELECT Id,EMS_TM_User__c FROM Contact WHERE RecordTypeId=:ContactConstant.RESOURCE_RECORDTYPEID AND EMS_RM_ApplicantStatus_Update__c = 'Active' AND Timesheet_NoNeed__c = false AND EMS_TM_User__c != null AND EMS_TM_User__r.isactive = true];
           system.debug('61');
            system.debug(conList);
        }else if(configRec.Grid_Configuration_Type__c == 'Resource Role Level Goal'){
            conList = [SELECT Id,EMS_TM_User__c FROM Contact
                       WHERE RecordTypeId=:ContactConstant.RESOURCE_RECORDTYPEID 
                       AND EMS_RM_ApplicantStatus_Update__c = 'Active'
                       AND Timesheet_NoNeed__c = false
                       AND Resource_Role__c =:configRec.Resource_Role__c AND EMS_TM_User__c != null AND EMS_TM_User__r.isactive = true];  
        }
        
         for(Contact con : conList){
            Goal__c goal = new Goal__c();
            goal.Resource__c = con.id;
            goal.End_Date__c = configRec.Goal_End_Date__c;
            goal.Goal_Name__c = configRec.Name;
            goal.Description__c = configRec.Description__c;
            goal.is_Navigation_Required__c = configRec.is_Navigation_Required__c;
            goal.Navigation_address__c = configRec.Navigation_address__c;
            goal.Start_Date__c = configRec.Goal_Start_Date__c;
            goal.Status__c = 'Active';
            goal.OwnerId = con.EMS_TM_User__c;
            //smaske : [UAT_052] :  Updating Type for "Org Level Goal" 
           	goal.Type__c = 'Org Level Goal';
           goalList.add(goal);
        }
        
        try{
           insert goalList; 
            system.debug(goalList.size());
        }catch(exception ex){
           LogException.logHandledException(ex, 'BatchToCreateGoalsForRes', 'execute');  
        }
       
    }
    
         /**
* @author Subba
* @date 22/01/2023
* @description process the failures.
*
* CHANGE HISTORY
* ====================================================================================================
* DATE          NAME                    DESCRIPTION
* N/A           N/A                     N/A
* ====================================================================================================
**/
    global void finish(Database.BatchableContext BC) {
        
    }
}