force-app/main/default/objects/Contact/fields/EMS_EM_JD__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_JD__c</fullName>
    <label>Date of Joining</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_LM_No_Of_Maternity_Leaves_Credit__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_No_Of_Maternity_Leaves_Credit__c</fullName>
    <label>No Of Maternity Leaves Credit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_RM_ApplicantStatus_Update__c.field-meta.xml
<CustomField>
    <fullName>EMS_RM_ApplicantStatus_Update__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Offer rolled out</fullName>
            </value>
            <value>
                <fullName>Offer accepted</fullName>
            </value>
            <value>
                <fullName>Offer rejected</fullName>
            </value>
            <value>
                <fullName>Hired</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Did not join</fullName>
            </value>
            <value>
                <fullName>Active - Probation</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Notice Period</fullName>
            </value>
            <value>
                <fullName>ABSENT</fullName>
                <isActive>false</isActive>
                <label>ABSENT</label>
            </value>
            <value>
                <fullName>Docs received</fullName>
                <isActive>false</isActive>
                <label>Docs received</label>
            </value>
            <value>
                <fullName>Docs verified</fullName>
                <isActive>false</isActive>
                <label>Docs verified</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_RM_Employee_Id__c.field-meta.xml
<CustomField>
    <fullName>EMS_RM_Employee_Id__c</fullName>
    <label>Employee ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Resource_Role__c.field-meta.xml
<CustomField>
    <fullName>Resource_Role__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Role</label>
    <referenceTo>Resource_Role__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Work_Location__c.field-meta.xml
<CustomField>
    <fullName>Work_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Location</label>
    <referenceTo>Office_Location__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Work_Location_Country__c.field-meta.xml
<CustomField>
    <fullName>Work_Location_Country__c</fullName>
    <formula>TEXT(Work_Location__r.Country__c)</formula>
    <label>Work Location Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave__c/EMS_LM_Leave__c.object-meta.xml
<CustomObject>
    <description>Used to store types of Leaves available in Organization</description>
    <label>Leave Type</label>
    <nameField>
        <label>Leave Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leave Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fiscal_Year__c/Fiscal_Year__c.object-meta.xml
<CustomObject>
    <label>Fiscal Year</label>
    <nameField>
        <label>Fiscal Year Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fiscal Years</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fulfillment__c/Fulfillment__c.object-meta.xml
<CustomObject>
    <label>Fulfillment</label>
    <nameField>
        <displayFormat>FP{00000}</displayFormat>
        <label>Fulfillment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fulfillments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fulfillment__c/fields/Fiscal_Year__c.field-meta.xml
<CustomField>
    <fullName>Fiscal_Year__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fiscal Year</label>
    <referenceTo>Fiscal_Year__c</referenceTo>
    <relationshipLabel>Fulfillments</relationshipLabel>
    <relationshipName>Fulfillments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fulfillment__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Resource</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Fulfillments</relationshipLabel>
    <relationshipName>Fulfillments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fulfillment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Goal__c/Goal__c.object-meta.xml
<CustomObject>
    <label>Goal</label>
    <nameField>
        <displayFormat>GOAL{000000}</displayFormat>
        <label>Goal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Goals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Goal__c/fields/Fulfillment__c.field-meta.xml
<CustomField>
    <fullName>Fulfillment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fulfillment</label>
    <referenceTo>Fulfillment__c</referenceTo>
    <relationshipLabel>Goals</relationshipLabel>
    <relationshipName>Goals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Goal__c/fields/Goal_Name__c.field-meta.xml
<CustomField>
    <fullName>Goal_Name__c</fullName>
    <label>Goal Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Goal__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Goals</relationshipLabel>
    <relationshipName>Goals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Goal__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Missed</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>KRA Inreview</fullName>
            </value>
            <value>
                <fullName>KRA Completed</fullName>
            </value>
            <value>
                <fullName>Pulse Submitted</fullName>
            </value>
            <value>
                <fullName>Pulse Requested</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>HR KRA Completed</fullName>
            </value>
            <value>
                <fullName>Completed - OnTime</fullName>
                <isActive>false</isActive>
                <label>Completed - OnTime</label>
            </value>
            <value>
                <fullName>Completed - PostTime</fullName>
                <isActive>false</isActive>
                <label>Completed - PostTime</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Goal__c/recordTypes/Goal.recordType-meta.xml
<RecordType>
    <fullName>Goal</fullName>
    <active>true</active>
    <label>Goal</label>
</RecordType>

force-app/main/default/objects/Goal__c/recordTypes/KRA.recordType-meta.xml
<RecordType>
    <fullName>KRA</fullName>
    <active>true</active>
    <label>KRA</label>
</RecordType>

force-app/main/default/objects/Office_Location__c/Office_Location__c.object-meta.xml
<CustomObject>
    <label>Office Location</label>
    <nameField>
        <label>Office Locations Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Office Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Office_Location__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>United States of America</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Resource_Resource_Relationship__c/Resource_Resource_Relationship__c.object-meta.xml
<CustomObject>
    <label>Resource Relationship</label>
    <nameField>
        <displayFormat>RRR-{000000}</displayFormat>
        <label>Resource Resource Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource_Resource_Relationship__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <label>Resource</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Resource Relationships (Reports To)</relationshipLabel>
    <relationshipName>Resource_Resource_Relationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Resource_Resource_Relationship__c/fields/Resource_Role__c.field-meta.xml
<CustomField>
    <fullName>Resource_Role__c</fullName>
    <formula>Resource__r.Resource_Role__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Resource Role</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Resource_Role__c/Resource_Role__c.object-meta.xml
<CustomObject>
    <label>Resource Role</label>
    <nameField>
        <label>Resource Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resource Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/BatchToMapMissedGoals_Test.cls
/**
* @author Subba Kalavala
* @date 2/22/2023
* @description  Test class for BatchToMapMissedGoals

* CHANGE HISTORY
* ====================================================================================================
* DATE          	NAME                    DESCRIPTION
* 04-March-2024    Shubham Maske			Updated test class for BatchClass Coverage
* ====================================================================================================
**/
@isTest
public class BatchToMapMissedGoals_Test {
    public static testMethod void testscheduleclass() {
        Test.StartTest();
        BatchToMapMissedGoals_sch testsche = new BatchToMapMissedGoals_sch();
        String sch = '0 0 23 * * ?';
        system.schedule('Test BatchToMapMissedGoals_sch Check', sch, testsche );
        
        BatchToMapMissedGoals_sch2 testsche2 = new BatchToMapMissedGoals_sch2();
        system.schedule('Test BatchToMapMissedGoals_sch2 Check2', sch, testsche2 );
        Test.stopTest();
    }
    
    //smaske : Commenting below test method as it was failing and was not updated
    /*
public static testMethod void testBatchclass() {
Resource_Role__c role = TestDataFactory.createResourceRole(true);
EMS_LM_Leave__c annualtype = TestDataFactory.createLeaveType('Annual Leave',true);
EMS_LM_Leave__c loptype = TestDataFactory.createLeaveType('Loss of Pay',true);
EMS_LM_Leave__c paidtimeof = TestDataFactory.createLeaveType('Paid time off',true);
EMS_LM_Leave__c unpaidTimeOff = TestDataFactory.createLeaveType('UnPaid time off',true);
EMS_LM_Leave__c floatingholiday = TestDataFactory.createLeaveType('Floating Holiday',true);

Account acc = TestDataFactory.createAccount(true);
Contact con=  TestDataFactory.createResourceContact(acc.id, false);
con.EMS_RM_Employee_Id__c = 'CP10234';
con.Resource_Role__c = role.Id;
con.EMS_LM_No_Of_Maternity_Leaves_Credit__c = 0;
insert con;

Goal__c gl = new Goal__c();
gl.Goal_Name__c = 'TEST GOAL';
gl.Resource__c = con.Id;
gl.Start_Date__c = system.today().adddays(-6);
gl.End_Date__c  = system.today().adddays(-4);
gl.Description__c = 'TEST TESTETST';
gl.Status__c = 'Active';
insert gl;


Test.startTest();
BatchToMapMissedGoals batchExecute = new BatchToMapMissedGoals(); 
Database.executeBatch(batchExecute,10);
Test.stopTest();
} 

*/
    
    //smaske : Test Data Setup
    @testSetup
    static void setupTestData() {
        
        user adminuser = TestDataFactory.createAdminUser(true); 
        Resource_Role__c role;
        EMS_LM_Leave__c annualtype;
        EMS_LM_Leave__c loptype;
        EMS_LM_Leave__c bretype;
        EMS_LM_Leave__c compofftype;
        EMS_LM_Leave__c paternitytype;
        EMS_LM_Leave__c  Bereavementtype;
        EMS_LM_Leave__c paidTimeOff;
        Office_Location__c hydIndia;
        Office_Location__c usLocation;
        
        Resource_Role__c techLead;
        Resource_Resource_Relationship__c rrr;
        List<Resource_Role__c> resourceRoleList = new List<Resource_Role__c>();
        List<Contact> contactList = new List<Contact>();
        List<User> userList = new List<User>();
        
        Account acc;Contact con;
        system.runAs(adminuser){
            role = TestDataFactory.createResourceRole(true);
            
            annualtype = TestDataFactory.createLeaveType('Annual Leave',true);
            loptype = TestDataFactory.createLeaveType('Loss of Pay',true);
            compofftype = TestDataFactory.createLeaveType('Compensatory Off',true);
            paternitytype = TestDataFactory.createLeaveType('Paternity Leave',true);
            Bereavementtype = TestDataFactory.createLeaveType('Bereavement Leave',true);
            paidTimeOff = TestDataFactory.createLeaveType('Paid time off',true);
            
            
            hydIndia = TestDataFactory.createOfficeLocationboth('Hyderabad - India','India',true);
            usLocation = TestDataFactory.createOfficeLocationboth('California - USA','United States of America',true);
        
           /* usLocation.Name = 'California - USA';
        usLocation.Address__c = '3000 Executive Parkway Suite 215, San Ramon, CA 94583 USA';
        usLocation.Country__c = 'United States of America';
            insert usLocation;*/
        
            List<Office_Location__c> OfficeLocationList = new List<Office_Location__c>();
            OfficeLocationList.add(hydIndia);
            OfficeLocationList.add(usLocation);
            acc = TestDataFactory.createAccount(true);
            
            resourceRoleList.add(techLead = TestDataFactory.createResourceRole('Software Engineer',false));
            insert resourceRoleList;
            
            
            for(Integer i=0; i<2; i++){
                con =TestDataFactory.createResourceContact(acc.id, false);
                con.EMS_RM_Employee_Id__c = 'CP1023'+i;
                con.Resource_Role__c = resourceRoleList[0].Id;
                con.EMS_LM_No_Of_Maternity_Leaves_Credit__c = 0;
                con.EMS_RM_ApplicantStatus_Update__c = 'Active';
                con.RecordTypeId = ContactConstant.RESOURCE_RECORDTYPEID;
                con.EMS_EM_JD__c = system.today() - 180;
                con.Work_Location__c = OfficeLocationList[i].Id;
                contactList.add(con);
            }
            
            insert contactList;
           
            for(Contact cont : contactList){
                User u = Testdatafactory.createCommunityUserWithAccAndContact(acc.id,cont.Id,false);
                u.Username = u.Username + cont.Id;
                u.ContactId = cont.Id;
                userList.add(u);
                system.debug('cont.Work_Location_Country__c'+cont.Work_Location_Country__c);
            }
            Insert userList;
            
            rrr = TestDataFactory.createRRR(contactList[0].Id, true, contactList[1].Id);
            
            Fiscal_Year__c FiscalYear = TestDataFactory.createFiscalYear(true);
        }
    }
    
    //smaske : New method
    testmethod static void  testBatchclassForGoals(){
        
      /*  Contact MentorCon = [Select Id,Name,EMS_RM_Employee_Id__c,Work_Location__c From Contact WHERE EMS_RM_Employee_Id__c = 'CP10230'];
        system.debug('MentorCon-->'+MentorCon);
        Contact MenteeCon = [Select Id,Name,EMS_RM_Employee_Id__c,Work_Location__c From Contact WHERE EMS_RM_Employee_Id__c = 'CP10231'];
        system.debug('MenteeCon-->'+MenteeCon);
        Fulfillment__c Ful = TestDataFactory.createFulfillment(MenteeCon.Id, true);
        Fulfillment__c Ful2 = TestDataFactory.createFulfillment(MentorCon.Id, true);
        system.debug('Ful-->'+Ful);
        system.debug('Ful2-->'+Ful2);
        
        try {
            Goal__c KRA = TestDataFactory.createKRARecords(MenteeCon.Id, MentorCon.Id,Ful,true);
            Goal__c KRA1 = TestDataFactory.createKRARecords(MentorCon.Id, MenteeCon.Id,Ful2,true);
            List<Goal__c> ListOfGoalsToCreate = New List<Goal__c>();
            for(Integer i = 0; i < 10; i ++){
                String name = 'Certification Goal ' + '' + i;
                Date startdate = Date.today();
                Date enddate = Date.today().addDays(10);
                String descri = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit';
                Goal__c goal = TestDataFactory.createGoalRecords(MenteeCon.Id, Name, startdate, enddate, Null,false);
                ListOfGoalsToCreate.add(goal);
                Goal__c goal1 = TestDataFactory.createGoalRecords(MentorCon.Id, Name, startdate, enddate, Null,false);
                ListOfGoalsToCreate.add(goal1);
            }   
            for(Integer i = 0; i < 5; i ++){
                String name = 'Certification Goal ' + '' + i;
                Date startdate = Date.today().addDays(-10);
                Date enddate = Date.today().addDays(-1);
                String descri = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit';
                Goal__c goal = TestDataFactory.createGoalRecords(MenteeCon.Id, Name, startdate, enddate, KRA,false);
                goal.Status__c = 'Active';
                ListOfGoalsToCreate.add(goal);
                Goal__c goal1 = TestDataFactory.createGoalRecords(MentorCon.Id, Name, startdate, enddate, KRA1,false);
                goal1.Status__c = 'Active';
                ListOfGoalsToCreate.add(goal1);
            }
            for(Integer i = 0; i < 5; i ++){
                String name = 'Certification Goal ' + '' + i;
                Date startdate = Date.today().addDays(-20);
                Date enddate = Date.today().addDays(-2);
                String descri = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit';
                Goal__c goal = TestDataFactory.createGoalRecords(MenteeCon.Id, Name, startdate, enddate, KRA,false);
                goal.Status__c = 'In Progress';
                ListOfGoalsToCreate.add(goal);
                Goal__c goal1 = TestDataFactory.createGoalRecords(MentorCon.Id, Name, startdate, enddate, KRA1,false);
                goal1.Status__c = 'In Progress';
                ListOfGoalsToCreate.add(goal1);
            }
            for(Integer i = 0; i < 5; i ++){
                String name = 'Certification Goal ' + '' + i;
                Date startdate = Date.today().addDays(-30);
                Date enddate = Date.today().addDays(-10);
                String descri = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit';
                Goal__c goal = TestDataFactory.createGoalRecords(MenteeCon.Id, Name, startdate, enddate, KRA,false);
                goal.Status__c = 'Missed';
                ListOfGoalsToCreate.add(goal);
                Goal__c goal1 = TestDataFactory.createGoalRecords(MentorCon.Id, Name, startdate, enddate, KRA1,false);
                goal1.Status__c = 'Missed';
                ListOfGoalsToCreate.add(goal1);
            }
            
            Test.startTest();
            insert ListOfGoalsToCreate;
            
            String GOAL_RECORD_TYPE = 'Goal';
        	Id goalRecTypeId = Schema.SObjectType.Goal__c.getRecordTypeInfosByName().get(GOAL_RECORD_TYPE).getRecordTypeId();
            list<Goal__c> indiaGoal=[SELECT Id,Status__c,Start_Date__c,End_Date__c,RecordTypeId FROM Goal__c WHERE (Status__c='Active' OR Status__c='Missed' OR Status__c='Draft' OR Status__c='In Progress') And RecordTypeId =:goalRecTypeId AND Resource__r.Work_Location_Country__c ='India'];
            list<Goal__c> notindiaGoal=[SELECT Id,Status__c,Start_Date__c,End_Date__c,RecordTypeId FROM Goal__c WHERE (Status__c='Active' OR Status__c='Missed' OR Status__c='Draft' OR Status__c='In Progress') And RecordTypeId =:goalRecTypeId AND Resource__r.Work_Location_Country__c !='India'];
            system.debug('indiaGoal-->'+indiaGoal);
        	system.debug('notindiaGoal-->'+notindiaGoal);

            BatchToMapMissedGoals batchExecute = new BatchToMapMissedGoals(); 
            Database.executeBatch(batchExecute);
            BatchToMapMissedGoals2 batchExecute2 = new BatchToMapMissedGoals2(); 
            Database.executeBatch(batchExecute2);
            Test.stopTest();
        } catch (Exception ex) {
            String errorMsg = ex.getMessage();
            System.debug('An exception occurred: ' + errorMsg);
        }*/
        
        
    }
}