force-app/main/default/objects/Contact/fields/EMS_EM_JD__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_JD__c</fullName>
    <label>Date of Joining</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Resource.recordType-meta.xml
<RecordType>
    <fullName>Resource</fullName>
    <active>true</active>
    <label>Resource</label>
</RecordType>

force-app/main/default/objects/EMS_LM_Leave__c/EMS_LM_Leave__c.object-meta.xml
<CustomObject>
    <description>Used to store types of Leaves available in Organization</description>
    <label>Leave Type</label>
    <nameField>
        <label>Leave Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leave Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_LM_Leave__c/fields/EMS_LM_Leave_Type__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Leave_Type__c</fullName>
    <label>Leave Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Annual Leave</fullName>
            </value>
            <value>
                <fullName>Paternity Leave</fullName>
            </value>
            <value>
                <fullName>Bereavement Leave</fullName>
            </value>
            <value>
                <fullName>Loss of Pay</fullName>
            </value>
            <value>
                <fullName>Work from Home</fullName>
            </value>
            <value>
                <fullName>Maternity Leave</fullName>
            </value>
            <value>
                <fullName>Compensatory Off</fullName>
            </value>
            <value>
                <fullName>Marriage Leave</fullName>
            </value>
            <value>
                <fullName>Paid time off</fullName>
            </value>
            <value>
                <fullName>UnPaid time off</fullName>
            </value>
            <value>
                <fullName>Floating Holiday</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_Credit__c/EMS_LM_Leave_Credit__c.object-meta.xml
<CustomObject>
    <description>To credit the Leaves to Employees as per Policies</description>
    <label>Leave Credit</label>
    <nameField>
        <displayFormat>LC-{00000}</displayFormat>
        <label>Leave Credit Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leave Credits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_LM_Leave_Credit__c/fields/EMS_LM_Employee__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Employee__c</fullName>
    <label>Employee</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Leave_Credits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_Credit__c/fields/EMS_LM_Leave_Credited_Date__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Leave_Credited_Date__c</fullName>
    <description>Total No of Leaves Credited to employee</description>
    <label>Leave Credited Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_Credit__c/fields/EMS_LM_Leave_Type__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Leave_Type__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Leave Type</label>
    <referenceTo>EMS_LM_Leave__c</referenceTo>
    <relationshipName>Leave_Credits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_Credit__c/fields/EMS_LM_Leaves_Credited__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Leaves_Credited__c</fullName>
    <label>Leaves Credited</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_Credit__c/fields/EMS_LM_Select_Leave_Type__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Select_Leave_Type__c</fullName>
    <label>Select Leave Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Annual Leave</fullName>
            </value>
            <value>
                <fullName>Paternity Leave</fullName>
            </value>
            <value>
                <fullName>Bereavement Leave</fullName>
            </value>
            <value>
                <fullName>Loss of Pay</fullName>
            </value>
            <value>
                <fullName>Work from Home</fullName>
            </value>
            <value>
                <fullName>Maternity Leave</fullName>
            </value>
            <value>
                <fullName>Compensatory Off</fullName>
            </value>
            <value>
                <fullName>Paid time off</fullName>
            </value>
            <value>
                <fullName>UnPaid time off</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Leave_Accrued_Mapping__mdt/Leave_Accrued_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>Leave Accrued Mapping</label>
    <pluralLabel>Leave Accured Mapping</pluralLabel>
</CustomObject>

force-app/main/default/objects/Leave_Accrued_Mapping__mdt/fields/Is_Lessthan_15_Days__c.field-meta.xml
<CustomField>
    <fullName>Is_Lessthan_15_Days__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Lessthan 15 Days</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Leave_Accrued_Mapping__mdt/fields/Joining_Month__c.field-meta.xml
<CustomField>
    <fullName>Joining_Month__c</fullName>
    <label>Joining Month</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Leave_Accrued_Mapping__mdt/fields/Leaves_Credits__c.field-meta.xml
<CustomField>
    <fullName>Leaves_Credits__c</fullName>
    <label>Leaves Credits</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CalculateTheAnnualLeaves.cls
/**
* @author Subba Kalavala
* @date 10/01/2023
* @description  CalculateTheAnnualLeaves Class to calculate the annual 
*               leaves for an contact with record type resource
*
*               Test code coverage provided by the following test class:
*               - CalculateTheAnnualLeavesTest
*
* CHANGE HISTORY
* ====================================================================================================
* DATE          NAME                    DESCRIPTION
* N/A           N/A                     N/A
* ====================================================================================================
**/
public without sharing class CalculateTheAnnualLeaves implements TriggerAction.AfterInsert,TriggerAction.AfterUpdate{
     /**
     * @author Subba Kalavala
     * @date 10/01/2023
     * @description After Insert 
     *
     * CHANGE HISTORY
     * ====================================================================================================
     * DATE          NAME                    DESCRIPTION
     * N/A           N/A                     N/A
     * ====================================================================================================
     **/
     public void afterInsert(List<Contact> newList) {      
         System.debug(LoggingLevel.DEBUG, 'CalculateTheAnnualLeaves.afterInsert() : BEGIN');
         updateResourceLeaves(newList,null);
         System.debug(LoggingLevel.DEBUG, 'CalculateTheAnnualLeaves.afterInsert() : END');       
     }
    
     /**
     * @author Subba Kalavala
     * @date 10/01/2023
     * @description After Insert 
     *
     * CHANGE HISTORY
     * ====================================================================================================
     * DATE          NAME                    DESCRIPTION
     * N/A           N/A                     N/A
     * ====================================================================================================
     **/
     public void afterUpdate(List<Contact> newList,List<Contact> oldList) {      
         System.debug(LoggingLevel.DEBUG, 'CalculateTheAnnualLeaves.afterInsert() : BEGIN');
         updateResourceLeaves(newList, new Map<Id,Contact>(oldList));
         System.debug(LoggingLevel.DEBUG, 'CalculateTheAnnualLeaves.afterInsert() : END');       
     }
     /**
     *   {Purpose} - Method for calcualte the leaves for resource 
     *
     *   CHANGE HISTORY
     *   ====================================================================================================
     *   Date        Name                    Description
     *   N/A         N/A                     N/A
     *   ====================================================================================================
     **/
     private void updateResourceLeaves(List<Contact> contactList,Map<Id,Contact> oldMap) {
      Map<String,Decimal> leaveMap = new Map<String,Decimal>();
      Id AnnualLeaveTypeId = [Select Id FROM EMS_LM_Leave__c  Where Name = 'Annual Leave'].Id;
      List<EMS_LM_Leave_Credit__c> leaveCreditList = new List<EMS_LM_Leave_Credit__c>();
        List<Contact> filteredList = new List<Contact>();
        for(Contact conRec : contactList) {
            contact oldCon = oldMap != null ? oldMap.get(conRec.Id) : null;
             if(conRec.RecordTypeId == ContactConstant.RESOURCE_RECORDTYPEID && conRec.EMS_EM_JD__c != null && (oldCon == null || conRec.RecordTypeId != oldCon.RecordTypeId ) ){
                 filteredList.add(conRec);
             }
         }
         
         if(!filteredList.isEmpty()){
             for(Leave_Accrued_Mapping__mdt lmpRec : [SELECT Is_Lessthan_15_Days__c,Joining_Month__c,Leaves_Credits__c FROM Leave_Accrued_Mapping__mdt ]){
                 leaveMap.put(String.valueOf(integer.valueof(lmpRec.Joining_Month__c)+String.valueOf(lmpRec.Is_Lessthan_15_Days__c)),lmpRec.Leaves_Credits__c);
             }
         }
       
         for(Contact contactRec: filteredList) {
             Date joiningDate = contactRec.EMS_EM_JD__c;
             Integer joiningDay = joiningDate.day();
             Integer joiningMonth = joiningDate.month();
             Boolean isItlessthan15 = joiningDay <= 15;
             String uniqueKey = String.valueOf(joiningMonth)+String.valueOf(isItlessthan15);
                
             if(leaveMap.containsKey(uniqueKey)){
               EMS_LM_Leave_Credit__c leaveCredit = new EMS_LM_Leave_Credit__c();
                 leaveCredit.EMS_LM_Employee__c = contactRec.Id;
                 leaveCredit.EMS_LM_Leave_Credited_Date__c = System.today();
                 leaveCredit.EMS_LM_Select_Leave_Type__c = 'Annual Leave'; 
                 leaveCredit.EMS_LM_Leave_Type__c = AnnualLeaveTypeId;
                 leaveCredit.EMS_LM_Leaves_Credited__c = leaveMap.get(uniqueKey);
                 leaveCreditList.add(leaveCredit);
             }
         }  
            
         try {
             if(leaveCreditList.Size() > 0) {
                 insert leaveCreditList;
             }
         } catch(Exception excp) {
             LogException.logHandledException(excp, 'CalculateTheAnnualLeaves', 'updateResourceLeaves');
         }    
         
     }
 }