force-app/main/default/objects/Contact/fields/EMS_TM_User__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Work_Location__c.field-meta.xml
<CustomField>
    <fullName>Work_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Location</label>
    <referenceTo>Office_Location__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <label>Client</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Resource.recordType-meta.xml
<RecordType>
    <fullName>Resource</fullName>
    <active>true</active>
    <label>Resource</label>
</RecordType>

force-app/main/default/objects/EMS_Timesheet__c/EMS_Timesheet__c.object-meta.xml
<CustomObject>
    <label>Timesheet</label>
    <nameField>
        <displayFormat>TS-{0000}</displayFormat>
        <label>Time Sheet ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_Timesheet__c/fields/Assignment__c.field-meta.xml
<CustomField>
    <fullName>Assignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assignment</label>
    <referenceTo>EMS_TM_Assignment__c</referenceTo>
    <relationshipLabel>Timesheets</relationshipLabel>
    <relationshipName>Timesheets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/EMS_TM_Project__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>EMS_TM_Project__c</referenceTo>
    <relationshipLabel>Timesheets</relationshipLabel>
    <relationshipName>Timesheets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Timesheets</relationshipLabel>
    <relationshipName>Timesheets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Assignment__c/EMS_TM_Assignment__c.object-meta.xml
<CustomObject>
    <label>Assignment</label>
    <nameField>
        <displayFormat>A.ID-{0000}</displayFormat>
        <label>Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_TM_Assignment__c/fields/EMS_TM_EmployeeName__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_EmployeeName__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Employee Name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Resource</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Assignments</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Project__c/EMS_TM_Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_TM_Project__c/fields/Offshore_Project_Manager__c.field-meta.xml
<CustomField>
    <fullName>Offshore_Project_Manager__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Offshore Project Manager</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND (2 OR 3)</booleanFilter>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Resource</value>
        </filterItems>
        <filterItems>
            <field>Contact.Resource_Role__r.Name</field>
            <operation>equals</operation>
            <value>Sr Project Manager</value>
        </filterItems>
        <filterItems>
            <field>Contact.Resource_Role__r.Name</field>
            <operation>equals</operation>
            <value>Project Manager</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Projects (Offshore Project Manager)</relationshipLabel>
    <relationshipName>Projects1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Project__c/fields/Project_Manager__c.field-meta.xml
<CustomField>
    <fullName>Project_Manager__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Onshore Project Manager</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND (2 OR 3)</booleanFilter>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Resource</value>
        </filterItems>
        <filterItems>
            <field>Contact.Resource_Role__r.Name</field>
            <operation>equals</operation>
            <value>Sr Project Manager</value>
        </filterItems>
        <filterItems>
            <field>Contact.Resource_Role__r.Name</field>
            <operation>equals</operation>
            <value>Project Manager</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Project__c/fields/Type_Of_Project__c.field-meta.xml
<CustomField>
    <fullName>Type_Of_Project__c</fullName>
    <label>Type of Project</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Client Projects</fullName>
            </value>
            <value>
                <fullName>Internal Projects</fullName>
            </value>
            <value>
                <fullName>Global Projects</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EMS_TM_Project__c/recordTypes/Client_Projects.recordType-meta.xml
<RecordType>
    <fullName>Client_Projects</fullName>
    <active>false</active>
    <label>Client Projects</label>
</RecordType>

force-app/main/default/objects/EMS_TM_Project__c/recordTypes/Global_Projects.recordType-meta.xml
<RecordType>
    <fullName>Global_Projects</fullName>
    <active>false</active>
    <label>Global Projects</label>
</RecordType>

force-app/main/default/objects/EMS_TM_Project__c/recordTypes/Internal_Projects.recordType-meta.xml
<RecordType>
    <fullName>Internal_Projects</fullName>
    <active>false</active>
    <label>Internal Projects</label>
</RecordType>

force-app/main/default/objects/EMS_TM_Timesheet_Record__c/EMS_TM_Timesheet_Record__c.object-meta.xml
<CustomObject>
    <label>Timesheet Line Items</label>
    <nameField>
        <displayFormat>TLI{00000000}</displayFormat>
        <label>Timesheet Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheet Records</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_TM_Timesheet_Record__c/fields/ApproverLastName__c.field-meta.xml
<CustomField>
    <fullName>ApproverLastName__c</fullName>
    <description>This field is used for storing the Timesheet line item approvers Name</description>
    <label>Approver Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Timesheet_Record__c/fields/Assignment__c.field-meta.xml
<CustomField>
    <fullName>Assignment__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Assignment</label>
    <referenceTo>EMS_TM_Assignment__c</referenceTo>
    <relationshipName>Timesheets1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Timesheet_Record__c/fields/EMS_Timesheet__c.field-meta.xml
<CustomField>
    <fullName>EMS_Timesheet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>EMS_Timesheet</label>
    <referenceTo>EMS_Timesheet__c</referenceTo>
    <relationshipName>Employee_Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Timesheet_Record__c/fields/EMS_TM_Project__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>EMS_TM_Project__c</referenceTo>
    <relationshipLabel>Timesheet Records</relationshipLabel>
    <relationshipName>Timecard_Splits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Timesheet_Record__c/fields/Timesheet_Approver__c.field-meta.xml
<CustomField>
    <fullName>Timesheet_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Timesheet Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Timesheet_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Office_Location__c/Office_Location__c.object-meta.xml
<CustomObject>
    <label>Office Location</label>
    <nameField>
        <label>Office Locations Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Office Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource_Resource_Relationship__c/Resource_Resource_Relationship__c.object-meta.xml
<CustomObject>
    <label>Resource Relationship</label>
    <nameField>
        <displayFormat>RRR-{000000}</displayFormat>
        <label>Resource Resource Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource_Resource_Relationship__c/fields/Relationship_Type__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Type__c</fullName>
    <label>Relationship Type</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mentor</fullName>
            </value>
            <value>
                <fullName>Leave Approver</fullName>
            </value>
            <value>
                <fullName>Resource Manager</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Resource_Resource_Relationship__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <label>Resource</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Resource Relationships (Reports To)</relationshipLabel>
    <relationshipName>Resource_Resource_Relationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Resource_Resource_Relationship__c/fields/Resource_Reports_To__c.field-meta.xml
<CustomField>
    <fullName>Resource_Reports_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Reports To</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Relationships_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/project_manager__c.field-meta.xml
<CustomField>
    <fullName>project_manager__c</fullName>
    <label>Project Manager</label>
    <relationshipName>Users</relationshipName>
    <restrictedAdminField>true</restrictedAdminField>
    <type>Hierarchy</type>
</CustomField>

force-app/main/default/classes/PrepopulateMangersnameClass.cls
public class PrepopulateMangersnameClass implements triggerAction.BeforeInsert { 
    
    private static String HYDERABAD = 'Hyderabad - India';
    private static String USA = 'California - USA';
    private static String Client_Projects = 'Client Projects';
    private static String Global_Projects = 'Global Projects';
    private static String Internal_Projects = 'Internal Projects';

    
    public void beforeInsert(List<EMS_TM_Timesheet_Record__c> timeSheetLineItemrec) {      
        System.debug(LoggingLevel.DEBUG, 'PrepopulateMangersnameClass.beforeInsert() : BEGIN');
        populatingthemanagersMethod(timeSheetLineItemrec);
        System.debug(LoggingLevel.DEBUG, 'PrepopulateMangersnameClass.beforeInsert() : END');       
    }
    
    public  void populatingthemanagersMethod(List<EMS_TM_Timesheet_Record__c> timeSheetLineItemrec){
        System.debug(' *** INSIDE submitAndProcessApprovalRequestHelper ***  ');
       
        for (EMS_TM_Timesheet_Record__c timesheetproject : timeSheetLineItemrec) {
                EMS_TM_Project__c tslProjRec = [SELECT Id,Type_Of_Project__c,Project_Manager__c,Project_Manager__r.EMS_TM_User__c,Offshore_Project_Manager__c,
                                                Offshore_Project_Manager__r.EMS_TM_User__c
                                                From EMS_TM_Project__c
                                                WHERE Id =: timesheetproject.EMS_TM_Project__c];
                System.debug('Project Record' + tslProjRec);
                System.debug('Project Record 1 ' + tslProjRec.Project_Manager__r.EMS_TM_User__c);
                System.debug('Project Record 2 ' + tslProjRec.Offshore_Project_Manager__r.EMS_TM_User__c);
                /*List<User> users = [ SELECT Id, Name, ContactId, SenderEmail 
                                    FROM User 
                                    WHERE Id IN (:tslProjRec.Project_Manager__r.EMS_TM_User__c, :tslProjRec.Offshore_Project_Manager__r.EMS_TM_User__c)];
                System.debug('users' + users.toString()); */
            
            List<Contact> resConList = new List<Contact>();
            if(timesheetproject.Assignment__c != null){
               resConList = [SELECT Id,Name,Work_Location__c,Work_Location__r.Name,
                                            Ems_tm_user__c,
                                            Ems_tm_user__r.Name,
                                            Ems_tm_user__r.Email,
                                            Ems_tm_user__r.UserName
                                            FROM contact
                                            WHERE Id IN ( SELECT EMS_TM_EmployeeName__c FROM EMS_TM_Assignment__c WHERE Id =: timesheetproject.Assignment__c)];
                System.debug('resConList Values :' + resConList); 
            }else{
               
                 resConList = [SELECT Id,Name,Work_Location__c,Work_Location__r.Name,
                                            Ems_tm_user__c,
                                            Ems_tm_user__r.Name,
                                            Ems_tm_user__r.Email,
                                            Ems_tm_user__r.UserName
                                            FROM contact
                                            WHERE Id IN ( Select  Resource__c from EMS_Timesheet__c where Id =: timesheetproject.EMS_Timesheet__c)];
                System.debug('resConList Values1 :' + resConList.toString()); 
            }
            
                
                //resConList iteration end
                For(Contact con : resConList){
                    System.debug('Inside Contact For Loop');
                    Map<Id, Resource_Resource_Relationship__c> resourceMap = new Map<Id, Resource_Resource_Relationship__c>();
                    for (Resource_Resource_Relationship__c resource : [SELECT Id, Resource__r.Name, Resource__r.Email, Resource__c, Resource_Reports_To__r.EMS_TM_User__c, Resource_Reports_To__r.Email, Resource_Reports_To__c, Resource_Reports_To__r.Name, Resource__r.EMS_TM_User__c,Relationship_Type__c
                                                                       FROM Resource_Resource_Relationship__c
                                                                       WHERE Resource__c = :con.Id]) { 
                                                                           //smaske: [25/Sep/2024] :[PM_Def_208] : Replacing 'Leave Approver' with 'Resource Manager'
                                                                         if(resource.Relationship_Type__c.contains('Resource Manager')){
                                                                               resourceMap.put(resource.Resource_Reports_To__r.EMS_TM_User__c, resource);
																			}
                                                                       }
                    System.debug('resourceMap Value 1' + resourceMap.toString());
                    system.debug('thte tsl project type'+tslProjRec.Type_Of_Project__c);
                    system.debug('thte tsl con.Work_Location__r.Name '+con.Work_Location__r.Name);
                    system.debug('thte tsl project type'+con.Work_Location__c);
                    
                    if(tslProjRec.Type_Of_Project__c == Global_Projects && !resourceMap.isEmpty()){
                            List<Id> idList = new List<Id>(resourceMap.Keyset());
                            timesheetproject.Timesheet_Approver__c=idList[0];
                        String approverName = getUserName(timesheetproject.Timesheet_Approver__c);
                        System.debug('## approverName' + approverName);
                            timesheetproject.ApproverLastName__c = getUserName(timesheetproject.Timesheet_Approver__c);
                    }else{
                        //Location Based Approval for CLIENT PROJECTS 
                        if(con.Work_Location__c != null && con.Work_Location__r.Name == HYDERABAD && (tslProjRec.Type_Of_Project__c ==Client_Projects || tslProjRec.Type_Of_Project__c == Internal_Projects)){
                              timesheetproject.Timesheet_Approver__c = tslProjRec.Offshore_Project_Manager__r.EMS_TM_User__c;
                              timesheetproject.ApproverLastName__c = getUserName(timesheetproject.Timesheet_Approver__c);
                        }else if(con.Work_Location__c != null && con.Work_Location__r.Name ==USA && (tslProjRec.Type_Of_Project__c ==Client_Projects || tslProjRec.Type_Of_Project__c == Internal_Projects)){
                               timesheetproject.Timesheet_Approver__c=tslProjRec.Project_Manager__r.EMS_TM_User__c;
                               timesheetproject.ApproverLastName__c = getUserName(timesheetproject.Timesheet_Approver__c);
                        }
                    }
                } 
            
        } 
    } 
    
    public static String getUserName(Id approverId){
    User users1 = [SELECT Id, FirstName, LastName FROM User WHERE Id = :approverId LIMIT 1];
    if (users1 != null) {
        if (!String.isBlank(users1.FirstName)) {
            return users1.FirstName + ' ' + users1.LastName;
        } else {
            return users1.LastName;
        }
    }
    return null;
}
}