force-app/main/default/objects/Contact/fields/EMS_TM_User__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Work_Location__c.field-meta.xml
<CustomField>
    <fullName>Work_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Location</label>
    <referenceTo>Office_Location__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Assignment__c/EMS_TM_Assignment__c.object-meta.xml
<CustomObject>
    <label>Assignment</label>
    <nameField>
        <displayFormat>A.ID-{0000}</displayFormat>
        <label>Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_TM_Assignment__c/fields/EMS_TM_EmployeeName__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_EmployeeName__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Employee Name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Resource</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Assignments</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Assignment__c/fields/EMS_TM_ProjectName_Asgn__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_ProjectName_Asgn__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Name</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>EMS_TM_Project__c.Type_Of_Project__c</field>
            <operation>notEqual</operation>
            <value>Global Projects</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>EMS_TM_Project__c</referenceTo>
    <relationshipLabel>Project Assignees</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Project__c/EMS_TM_Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_TM_Project__c/fields/Project_Manager__c.field-meta.xml
<CustomField>
    <fullName>Project_Manager__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Onshore Project Manager</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND (2 OR 3)</booleanFilter>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Resource</value>
        </filterItems>
        <filterItems>
            <field>Contact.Resource_Role__r.Name</field>
            <operation>equals</operation>
            <value>Sr Project Manager</value>
        </filterItems>
        <filterItems>
            <field>Contact.Resource_Role__r.Name</field>
            <operation>equals</operation>
            <value>Project Manager</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Project__c/fields/Type_Of_Project__c.field-meta.xml
<CustomField>
    <fullName>Type_Of_Project__c</fullName>
    <label>Type of Project</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Client Projects</fullName>
            </value>
            <value>
                <fullName>Internal Projects</fullName>
            </value>
            <value>
                <fullName>Global Projects</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <label>Expense</label>
    <nameField>
        <displayFormat>EXP{000000}</displayFormat>
        <label>Expense Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense__c/fields/Amount1__c.field-meta.xml
<CustomField>
    <fullName>Amount1__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Approval_Manager__c.field-meta.xml
<CustomField>
    <fullName>Approval_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approval Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Expenses (Approval Manager)</relationshipLabel>
    <relationshipName>ExpensesApprovals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Billing_Currency__c.field-meta.xml
<CustomField>
    <fullName>Billing_Currency__c</fullName>
    <label>Billing Currency</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Expense_Amount__c.field-meta.xml
<CustomField>
    <fullName>Expense_Amount__c</fullName>
    <label>Expense Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/is_Reimbursed__c.field-meta.xml
<CustomField>
    <fullName>is_Reimbursed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Reimbursed ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>EMS_TM_Project__c</referenceTo>
    <relationshipLabel>Expenses</relationshipLabel>
    <relationshipName>Expenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Reimbursed_Date__c.field-meta.xml
<CustomField>
    <fullName>Reimbursed_Date__c</fullName>
    <label>Reimbursed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Expenses</relationshipLabel>
    <relationshipName>Expenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Office_Location__c/Office_Location__c.object-meta.xml
<CustomObject>
    <label>Office Location</label>
    <nameField>
        <label>Office Locations Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Office Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Office_Location__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>United States of America</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/project_manager__c.field-meta.xml
<CustomField>
    <fullName>project_manager__c</fullName>
    <label>Project Manager</label>
    <relationshipName>Users</relationshipName>
    <restrictedAdminField>true</restrictedAdminField>
    <type>Hierarchy</type>
</CustomField>

force-app/main/default/classes/myExpenseController.cls
public without sharing class myExpenseController {

@AuraEnabled(cacheable=true)
public static datawrapper getMyExpenseReport(){
      List<Expense__c> expList = new List<Expense__c>();
      List<expense> expNewList = new List<expense>();
      Map<string,string> nameMap = new Map<String,string>();
      User uRec = [SELECT Id,ContactId,Name,Contact.Work_Location__r.Country__c FROM User WHERE Id=:Userinfo.getUserId()];
      system.debug('user name===================================='+uRec.Name);
       system.debug('user ContactId===================================='+uRec.ContactId);
      Decimal pendingAmount = 0;
      expList = [SELECT id,Name,Amount1__c,Resource__r.Work_Location__c,Resource__r.Work_Location__r.Country__c,
                  Expense_Amount__c,Project__c,Project__r.Name,Billing_Currency__c,
                  CreatedDate,Status__c,Reimbursed_Date__c,is_Reimbursed__c FROM Expense__c 
                  WHERE Resource__c=:uRec.ContactId];
    system.debug('expList====================================='+expList);
      Integer defalutCon = Integer.valueOf(Label.Default_Conversion);
      String defalutCurrent = uRec.Contact.Work_Location__r.Country__c == 'India' ? 'INR' : 'USD';
      for(Expense__c exp : expList){
          system.debug('exp================================================'+exp);
          Boolean isConversionRequired = defalutCurrent != exp.Billing_Currency__c;
          
          nameMap.put(exp.Name,exp.id);
          if(exp.Status__c != 'Rejected' && exp.Status__c != 'Draft' && !exp.is_Reimbursed__c && exp.Expense_Amount__c != null){
              decimal expenseAmount = exp.Expense_Amount__c;
              
              if(isConversionRequired){
                  expenseAmount = defalutCurrent == 'INR' ? expenseAmount * defalutCon : expenseAmount/defalutCon;  
              }
              pendingAmount = pendingAmount+expenseAmount; 
          }
          if(exp.Expense_Amount__c != null){
          expense ex = new expense();
          ex.expid = exp.id;
          ex.reimbdate = exp.Reimbursed_Date__c;
          integer expA = integer.valueOf(exp.Expense_Amount__c.setScale(0));
          if(isConversionRequired){
            ex.amount = defalutCurrent == 'INR' ?   '$ '+String.valueOf(expA) + ' ( ₹ ' + String.valueOf(expA * defalutCon) +')' : '₹ '+String.valueOf(expA) + ' ( $ ' + String.valueOf(expA/defalutCon) +')';  
          }else{ 
              ex.amount = defalutCurrent == 'INR' ? '₹ '+ String.valueOf(expA) : '$ ' + String.valueOf(expA);
            }
          
          ex.projectName = exp.Project__r.Name;
          ex.status = exp.Status__c;
          ex.expName = exp.Name;
          
          ex.amountcurrency = exp.Billing_Currency__c;
          expNewList.add(ex);
          }
      }
      datawrapper dw = new datawrapper();
      dw.pendingreim = pendingAmount;
      dw.resourceId = uRec.ContactId;
      dw.expCurrency = defalutCurrent;
      
      dw.expList = expNewList;
      return dw;
  }
  @AuraEnabled
  public static datawrapper updateAndGetData(Id expId, String status){
      expense__c exp = new expense__c();
      exp = [SELECT Id,Project__c,Project__r.Project_Manager__c,Approval_Manager__c FROM expense__c WHERE Id=:expId];
      exp.Status__c = status;
      if(status == 'Submitted'){
          if(String.isEmpty(exp.Project__r.Project_Manager__c)){
              User Urec = [SELECT Id,ContactId,Contact.ReportsTo.Id,Contact.ReportsTo.EMS_TM_User__c FROM User WHERE Id=:userinfo.getUserId()]; 
            exp.Approval_Manager__c = Urec.Contact.ReportsToId;
          }else{
            exp.Approval_Manager__c = exp.Project__r.Project_Manager__c;
          }
        exp.Reimbursed_Date__c =  system.today().adddays(14);            
      }
      
      update exp;
      return getMyExpenseReport();
      
  }
  
@AuraEnabled(cacheable=true)
public static expense checkTheExpense(Id expId){
Expense__c exp = [SELECT Status__c FROM Expense__c Where Id=:expId];
  expense exp2 = new expense();
  exp2.disableApproval = exp.Status__c != 'Draft' ? true : false;
  exp2.disablerecall = exp.Status__c != 'Submitted' ? true : false;
return exp2;
}

  @AuraEnabled
  public static expense updateforApproval(Id expId, String status){
      expense__c exp = new expense__c();
      exp.id = expId;
      exp.Status__c = status;
      try{
          update exp;
          return checkTheExpense(expId);
      }catch(exception ex){
            throw new AuraHandledException(ex.getMessage());
      }
      
  }

  //--------------

    @AuraEnabled
public static String uploadFile(String base64, String filename, String recordId) {
      ContentVersion cv = createContentVersion(base64, filename);
    system.debug('cv----------------'+cv);
    system.debug('recordId----------------'+recordId);
      ContentDocumentLink cdl = createContentLink(cv.Id, recordId);
      if (cv == null || cdl == null) { return null; }
      return cdl.Id;
}
@Testvisible
private static ContentVersion createContentVersion(String base64, String filename) {
     network network=[select id,name from network where Name='Grid'];
    system.debug('base64=========='+base64);
    system.debug('filename================'+filename);
  ContentVersion cv = new ContentVersion();
  cv.VersionData = EncodingUtil.base64Decode(base64);
    system.debug('cv.VersionData================'+cv.VersionData);
  cv.Title = filename;
    system.debug(' cv.Title================'+ cv.Title);
  cv.PathOnClient = filename;
  cv.NetworkId=network.Id;
    system.debug('  cv.PathOnClient================'+cv.PathOnClient);
  try {
    insert cv;
       system.debug('cv123----------------'+cv);
    return cv;
  } catch(DMLException e) {
    System.debug('cv129----------------'+cv);
      System.debug('cv130----------------'+e.getMessage());
    return null;
  }
}

private static ContentDocumentLink createContentLink(String contentVersionId, String recordId) {
            if (contentVersionId == null || recordId == null) { return null; }
  ContentDocumentLink cdl = new ContentDocumentLink();
  cdl.ContentDocumentId = [
    SELECT ContentDocumentId 
    FROM ContentVersion 
    WHERE Id =: contentVersionId
  ].ContentDocumentId;
  cdl.LinkedEntityId = recordId;
  // ShareType is either 'V', 'C', or 'I'
  // V = Viewer, C = Collaborator, I = Inferred
  cdl.ShareType = 'V';
  try {
    insert cdl;
    return cdl;
  } catch(DMLException e) {
    System.debug(e);
    return null;
  }
}

//--------------

@AuraEnabled(cacheable=true)
public static List<EMS_TM_Project__c> getProjectsAssignedToLoggedInContact(Id contactId){

  Set<Id> projectIds = new Set<Id>();

  List<EMS_TM_Assignment__c> assignmentsList = [select id, EMS_TM_ProjectName_Asgn__r.Name, EMS_TM_ProjectName_Asgn__c, EMS_TM_EmployeeName__r.Name from EMS_TM_Assignment__c 
                                            where EMS_TM_EmployeeName__c =: contactId];

  for(EMS_TM_Assignment__c assignment : assignmentsList){
    projectIds.add(assignment.EMS_TM_ProjectName_Asgn__c);
  }

  List<EMS_TM_Project__c> projectsList = [select id, name, Type_Of_Project__c from EMS_TM_Project__c where id IN :projectIds or (Type_Of_Project__c = 'Global Projects' AND name != 'OOO')];


  system.debug('List of projects ==> '+[select id, EMS_TM_ProjectName_Asgn__r.Name, EMS_TM_EmployeeName__r.Name from EMS_TM_Assignment__c 
                                            where EMS_TM_EmployeeName__c =: contactId]);
  return projectsList;
}

  
  public class expense{
      @AuraEnabled
      public string expName;
        @AuraEnabled
      public Date reimbdate;
        @AuraEnabled
      public String amount;
      @AuraEnabled
      public string amountcurrency;
        @AuraEnabled
      public string status;
        @AuraEnabled
      public string projectName;
        @AuraEnabled
      public string expid;
      @AuraEnabled
      public string approvalManager; 
        @AuraEnabled
      public boolean disableApproval; 
        @AuraEnabled
      public boolean disablerecall; 
  }
  
  public class datawrapper{
      @AuraEnabled
      public decimal pendingreim;
      @AuraEnabled
      public string resourceId;
      @AuraEnabled
      public string expCurrency;
      @AuraEnabled
      public List<expense> expList;
      
  }

}