force-app/main/default/objects/Contact/fields/EMS_EM_CA_City__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_CA_City__c</fullName>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_EM_CA_State__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_CA_State__c</fullName>
    <label>State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_EM_CAddress_Line_1__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_CAddress_Line_1__c</fullName>
    <label>Address Line 1</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>EMS_Phone_Number__c</fullName>
    <label>Contact Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_RM_ApplicantStatus_Update__c.field-meta.xml
<CustomField>
    <fullName>EMS_RM_ApplicantStatus_Update__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Offer rolled out</fullName>
            </value>
            <value>
                <fullName>Offer accepted</fullName>
            </value>
            <value>
                <fullName>Offer rejected</fullName>
            </value>
            <value>
                <fullName>Hired</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Did not join</fullName>
            </value>
            <value>
                <fullName>Active - Probation</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Notice Period</fullName>
            </value>
            <value>
                <fullName>ABSENT</fullName>
                <isActive>false</isActive>
                <label>ABSENT</label>
            </value>
            <value>
                <fullName>Docs received</fullName>
                <isActive>false</isActive>
                <label>Docs received</label>
            </value>
            <value>
                <fullName>Docs verified</fullName>
                <isActive>false</isActive>
                <label>Docs verified</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_RM_Employee_Id__c.field-meta.xml
<CustomField>
    <fullName>EMS_RM_Employee_Id__c</fullName>
    <label>Employee ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_TM_User__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Resource_Role__c.field-meta.xml
<CustomField>
    <fullName>Resource_Role__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Role</label>
    <referenceTo>Resource_Role__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Timesheet_NoNeed__c.field-meta.xml
<CustomField>
    <fullName>Timesheet_NoNeed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Timesheet NoNeed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave__c/EMS_LM_Leave__c.object-meta.xml
<CustomObject>
    <description>Used to store types of Leaves available in Organization</description>
    <label>Leave Type</label>
    <nameField>
        <label>Leave Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leave Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_Timesheet__c/EMS_Timesheet__c.object-meta.xml
<CustomObject>
    <label>Timesheet</label>
    <nameField>
        <displayFormat>TS-{0000}</displayFormat>
        <label>Time Sheet ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_Timesheet__c/fields/EMS_TM_Week__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Week__c</fullName>
    <label>Week</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Timesheets</relationshipLabel>
    <relationshipName>Timesheets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/Week_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Week_Start_Date__c</fullName>
    <label>Week Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/WFH_Fri__c.field-meta.xml
<CustomField>
    <fullName>WFH_Fri__c</fullName>
    <defaultValue>false</defaultValue>
    <label>WFH Fri</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/WFH_Mon__c.field-meta.xml
<CustomField>
    <fullName>WFH_Mon__c</fullName>
    <defaultValue>false</defaultValue>
    <label>WFH Mon</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/WFH_Sat__c.field-meta.xml
<CustomField>
    <fullName>WFH_Sat__c</fullName>
    <defaultValue>false</defaultValue>
    <label>WFO Saturday</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/WFH_Sun__c.field-meta.xml
<CustomField>
    <fullName>WFH_Sun__c</fullName>
    <defaultValue>false</defaultValue>
    <label>WFO Sunday</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/WFH_Thu__c.field-meta.xml
<CustomField>
    <fullName>WFH_Thu__c</fullName>
    <defaultValue>false</defaultValue>
    <label>WFO Thursday</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/WFH_Tue__c.field-meta.xml
<CustomField>
    <fullName>WFH_Tue__c</fullName>
    <defaultValue>false</defaultValue>
    <label>WFH Tue</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/WFH_Wed__c.field-meta.xml
<CustomField>
    <fullName>WFH_Wed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>WFH Wed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Office_Location__c/Office_Location__c.object-meta.xml
<CustomObject>
    <label>Office Location</label>
    <nameField>
        <label>Office Locations Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Office Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource_Role__c/Resource_Role__c.object-meta.xml
<CustomObject>
    <label>Resource Role</label>
    <nameField>
        <label>Resource Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resource Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/countWfoDaysForResourceTest.cls
@isTest
public class countWfoDaysForResourceTest {
    
    @testSetup
static void setupTestData() {
    //User userId = [SELECT Id FROM User WHERE IsActive = true AND Profile.Name = 'System Administrator' LIMIT 1];
    User usrConId = [SELECT Id, ContactId FROM User WHERE Id =: LeaveRequestConstant.LOGGEDIN_USERID];

    Resource_Role__c role = TestDataFactory.createResourceRole(true);  
    Office_Location__c hydofficlocRec =TestDataFactory.createOfficeLocation('Hyderabad - India',true);
        Office_Location__c usofficlocRec =TestDataFactory.createOfficeLocation('California - USA',true);
        EMS_LM_Leave__c annualtype = TestDataFactory.createLeaveType('Annual Leave',true);
        EMS_LM_Leave__c loptype = TestDataFactory.createLeaveType('Loss of Pay',true);
        EMS_LM_Leave__c bretype = TestDataFactory.createLeaveType('Maternity Leave',true);
        EMS_LM_Leave__c compofftype = TestDataFactory.createLeaveType('Compensatory Off',true);
        EMS_LM_Leave__c workfromhome = TestDataFactory.createLeaveType('Work From Home',true);
        EMS_LM_Leave__c paidtimeof = TestDataFactory.createLeaveType('Paid time off',true);
        EMS_LM_Leave__c unpaidTimeOff = TestDataFactory.createLeaveType('UnPaid time off',true);
        EMS_LM_Leave__c floatingholiday = TestDataFactory.createLeaveType('Floating Holiday',true);
    Account acc = TestDataFactory.createAccount(true);
    Contact con = TestDataFactory.createResourceContact(acc.Id, false);
    con.EMS_RM_Employee_Id__c = 'CP10288';
    con.EMS_RM_ApplicantStatus_Update__c = 'Active';
    con.EMS_Phone_Number__c = '0123456789';
    con.EMS_EM_CAddress_Line_1__c = 'Hyd';
    con.EMS_EM_CA_City__c = 'Hyd';
    con.EMS_EM_CA_State__c = 'AP';
    con.Timesheet_NoNeed__c = false;
    con.Resource_Role__c = role.Id;
    con.EMS_TM_User__c = usrConId.Id;
    insert con;


Date monthStart = Date.today().toStartOfMonth(); 
Date startOfWeek = monthStart.addDays(2);       
Date endOfWeek = startOfWeek.addDays(5);        

EMS_Timesheet__c ts = new EMS_Timesheet__c(
    Resource__c = usrConId.ContactId,
    Week_Start_Date__c = startOfWeek,
    EMS_TM_Week__c = endOfWeek,
    WFH_Mon__c = true,
    WFH_Tue__c = false,
    WFH_Wed__c = true,
    WFH_Thu__c = false,
    WFH_Fri__c = true,
    WFH_Sat__c = false,
    WFH_Sun__c = false
);
insert ts;
}


    @isTest
    static void testGetWfoDaysForCurrentMonth() {
        Test.startTest();
        Integer result = countWfoDaysForResource.GetWfoDaysForCurrentMonth();
        Test.stopTest();
        System.assert(result >= 0, 'The WFO days should be 0 or more.');
    }

    @isTest
    static void testRunWfoCalculations() {
        Test.startTest();
        Integer wfoDays = countWfoDaysForResource.RunWfoCalculations();
        Test.stopTest();
        System.assertNotEquals(null, wfoDays, 'WFO calculation should return a number.');
    }
}