force-app/main/default/objects/Contact/fields/EMS_RM_Current_Job_Role__c.field-meta.xml
<CustomField>
    <fullName>EMS_RM_Current_Job_Role__c</fullName>
    <label>Designation</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accounts Manager</fullName>
            </value>
            <value>
                <fullName>Associate Business Analyst</fullName>
            </value>
            <value>
                <fullName>Associate Developer</fullName>
            </value>
            <value>
                <fullName>Associate Engineer</fullName>
            </value>
            <value>
                <fullName>Associate Project Manager</fullName>
            </value>
            <value>
                <fullName>Associate Salesforce Business Analyst</fullName>
            </value>
            <value>
                <fullName>Associate Salesforce Developer</fullName>
            </value>
            <value>
                <fullName>Associate Salesforce Quality Analyst</fullName>
            </value>
            <value>
                <fullName>Associate SFMC Developer</fullName>
            </value>
            <value>
                <fullName>Associate Talent Acquisition Partner</fullName>
            </value>
            <value>
                <fullName>Account Executive</fullName>
            </value>
            <value>
                <fullName>Accounts Executive</fullName>
            </value>
            <value>
                <fullName>Associate Architect</fullName>
            </value>
            <value>
                <fullName>Business Systems Analyst</fullName>
            </value>
            <value>
                <fullName>Consultant Architecture</fullName>
            </value>
            <value>
                <fullName>Data Analyst</fullName>
            </value>
            <value>
                <fullName>Data Scientist</fullName>
            </value>
            <value>
                <fullName>Delivery Manager</fullName>
            </value>
            <value>
                <fullName>Director of Sales</fullName>
            </value>
            <value>
                <fullName>HR Executive</fullName>
            </value>
            <value>
                <fullName>HR Manager</fullName>
            </value>
            <value>
                <fullName>Jr. UX Designer</fullName>
            </value>
            <value>
                <fullName>Lead Data Migration Engineer</fullName>
            </value>
            <value>
                <fullName>Lead Salesforce Business System Analyst</fullName>
            </value>
            <value>
                <fullName>Lead Salesforce Developer</fullName>
            </value>
            <value>
                <fullName>Lead Salesforce Quality Analyst</fullName>
            </value>
            <value>
                <fullName>Project Manager</fullName>
            </value>
            <value>
                <fullName>Salesforce Administrator</fullName>
            </value>
            <value>
                <fullName>Salesforce Application Designer</fullName>
            </value>
            <value>
                <fullName>Salesforce Business Analyst</fullName>
            </value>
            <value>
                <fullName>Senior Project Manager - Salesforce</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_RM_Employee_Id__c.field-meta.xml
<CustomField>
    <fullName>EMS_RM_Employee_Id__c</fullName>
    <label>Employee ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_TM_User__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Official_Mail__c.field-meta.xml
<CustomField>
    <fullName>Official_Mail__c</fullName>
    <label>Official Email ID(old)</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/EMS_Timesheet__c.object-meta.xml
<CustomObject>
    <label>Timesheet</label>
    <nameField>
        <displayFormat>TS-{0000}</displayFormat>
        <label>Time Sheet ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_Timesheet__c/fields/Assignment__c.field-meta.xml
<CustomField>
    <fullName>Assignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assignment</label>
    <referenceTo>EMS_TM_Assignment__c</referenceTo>
    <relationshipLabel>Timesheets</relationshipLabel>
    <relationshipName>Timesheets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/EMS_TM_Status__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Not Approved</fullName>
            </value>
            <value>
                <fullName>Reported</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Saved</fullName>
            </value>
            <value>
                <fullName>Locked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/enddate__c.field-meta.xml
<CustomField>
    <fullName>enddate__c</fullName>
    <formula>CASE( 
MOD( EMS_TM_Week__c - DATE(1900, 1, 6),7), 
0, EMS_TM_Week__c + 7, 
1, EMS_TM_Week__c + 6, 
2, EMS_TM_Week__c + 5, 
3, EMS_TM_Week__c + 4, 
4, EMS_TM_Week__c + 3, 
5, EMS_TM_Week__c + 2, 
6, EMS_TM_Week__c + 1,
7, EMS_TM_Week__c + 0, 
NULL 
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>endWeek</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/startweek__c.field-meta.xml
<CustomField>
    <fullName>startweek__c</fullName>
    <formula>CASE(
MOD( EMS_TM_Week__c - DATE(1900, 1, 6),7),
0, EMS_TM_Week__c ,
1, EMS_TM_Week__c ,
2, EMS_TM_Week__c ,
3, EMS_TM_Week__c - 1,
4, EMS_TM_Week__c - 2,
5, EMS_TM_Week__c - 3,
6, EMS_TM_Week__c - 4,
NULL
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>startweek</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/Submitted__c.field-meta.xml
<CustomField>
    <fullName>Submitted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Submitted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Timesheets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/EMS_TM_notifyManger.cls
global class EMS_TM_notifyManger implements Database.Batchable<sObject>{
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
     
      string submitted ='Submitted';
      String soql ='SELECT Id, OwnerId, Submitted__c,startweek__c, enddate__c,User__c, Name, EMS_TM_Status__c, Assignment__c,user__r.contactId FROM EMS_Timesheet__c WHERE EMS_TM_Status__c != : submitted AND CreatedDate = THIS_WEEK';
      System.debug('soql'+soql);
      return Database.getQueryLocator(soql);
  }

  global void execute(Database.BatchableContext bc, List<EMS_Timesheet__c> recs) {
       List<String> toAddresses = new List<String>();
      for(contact c:[SELECT Id, AccountId, LastName, FirstName, EMS_RM_Current_Job_Role__c, Official_Mail__c FROM Contact 
                     where EMS_RM_Current_Job_Role__c= 'Senior Project Manager - Salesforce']){
                         if (c.Official_Mail__c != null){
                            toAddresses.add(c.Official_Mail__c); 
                             System.debug('ofc'+c.Official_Mail__c);
                         }
                     }
      System.debug('recs'+recs);
      System.debug('size'+ recs.size());
       OrgWideEmailAddress emailid = [SELECT Id, Address, DisplayName FROM OrgWideEmailAddress where DisplayName ='Cloud Peritus'];
     // List<String> toAddresses = new List<String>{'viswanath.malayathi@cloudperitus.com'}; 
          System.debug('toaddress'+ toaddresses);
      List<Messaging.SingleEmailMessage> mailList = new List<Messaging.SingleEmailMessage>();
      set<id> contactIds = new set<id>();
      Map<id, EMS_Timesheet__c> notSubmittedData = new Map<id, EMS_Timesheet__c>();
      System.debug('notSubmittedDataSIZE'+notSubmittedData.size());
      for(EMS_Timesheet__c m : recs) {
          if(m.EMS_TM_Status__c != 'Submitted'){
             contactIds.add(m.OwnerId);  
              notSubmittedData.put(m.OwnerId,m);
          }
          
      }
      
      System.debug('contactIds'+contactIds);
     list<Contact> employeeList = new list<Contact>();
      for(contact c: [SELECT Id, LastName,FirstName, Name, EMS_TM_User__c FROM Contact where EMS_TM_User__c IN:notSubmittedData.keyset()]){
          employeeList.add(c);
      }
      System.debug('employeeList'+employeeList);
                 
          Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
         // toAddresses.add(m);
          mail.setToAddresses(toAddresses);
          mail.setOrgWideEmailAddressId(emailid.Id);
          mail.setSubject('Employee timesheets is overdue');
          String messageBody = '';
 //     Dear [Manager's First Name],

      messageBody += 'Dear Manager ,<br/>';
      messageBody +='<br/><table border="1" style="border-collapse: collapse"><caption><b>The weekly timesheets of the following employees are overdue:</b></caption><tr><th>EmployeeId</th><th>EmployeeName</th><th>Week</th></tr>';
      for(contact name : employeeList){
         date weekStartDate = notSubmittedData.get(name.EMS_TM_User__c).startweek__c;
         date weekEndDate = notSubmittedData.get(name.EMS_TM_User__c).enddate__c;
    //  messageBody += '<tr><td>' + name.EMS_RM_Employee_Id__c+ '</td><td>' + name.Name + '</td><td>' + weekStartDate +'-'+weekEndDate+ '</td>';
      }
      
      messageBody += '</table> <br/><br/>';
      
      messageBody +='Regards, <br/>';
      messageBody +='HR Compliance <br/><br/>';
      messageBody +='This is an automatically generated e-mail. Please do not reply.';

          mail.setHtmlBody(messageBody);
          mailList.add(mail);         
      
      Messaging.sendEmail(mailList);
  }

  global void finish(Database.BatchableContext bc) {
  }

}