force-app/main/default/objects/Contact/fields/EMS_LM_No_of_Bereavement_Leaves_Credit__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_No_of_Bereavement_Leaves_Credit__c</fullName>
    <label>No of Bereavement Leaves Credit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_LM_No_Of_Compensatory_Off_Credit__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_No_Of_Compensatory_Off_Credit__c</fullName>
    <label>No Of Compensatory Off Credit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_LM_No_Of_Leaves_Credit__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_No_Of_Leaves_Credit__c</fullName>
    <defaultValue>0</defaultValue>
    <label>No Of Annual Leaves Credit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_LM_No_Of_Maternity_Leaves_Credit__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_No_Of_Maternity_Leaves_Credit__c</fullName>
    <label>No Of Maternity Leaves Credit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_LM_No_Of_Paternity_Leaves_Credit__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_No_Of_Paternity_Leaves_Credit__c</fullName>
    <label>No of Paternity Leaves Credit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_LM_No_Of_Utilized_Bereavement_Leaves__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_No_Of_Utilized_Bereavement_Leaves__c</fullName>
    <defaultValue>0</defaultValue>
    <label>No of Utilized Bereavement Leaves</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_LM_No_OF_Utilized_Compensatory_Off__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_No_OF_Utilized_Compensatory_Off__c</fullName>
    <defaultValue>0</defaultValue>
    <label>No of Utilized Compensatory Off</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_LM_No_Of_Utilized_Leaves__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_No_Of_Utilized_Leaves__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Annual available leaves of employee</description>
    <label>No of Utilized Annual Leaves</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_LM_No_Of_Utilized_Loss_Of_Pay__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_No_Of_Utilized_Loss_Of_Pay__c</fullName>
    <defaultValue>0</defaultValue>
    <label>No of Utilized Loss of Pay</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_LM_No_Of_Utilized_Maternity_Leaves__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_No_Of_Utilized_Maternity_Leaves__c</fullName>
    <label>No Of Utilized Maternity Leaves</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/No_Of_Utilized_Paternity_Leaves__c.field-meta.xml
<CustomField>
    <fullName>No_Of_Utilized_Paternity_Leaves__c</fullName>
    <defaultValue>0</defaultValue>
    <label>No Of Utilized Paternity Leaves</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_Credit__c/EMS_LM_Leave_Credit__c.object-meta.xml
<CustomObject>
    <description>To credit the Leaves to Employees as per Policies</description>
    <label>Leave Credit</label>
    <nameField>
        <displayFormat>LC-{00000}</displayFormat>
        <label>Leave Credit Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leave Credits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_LM_Leave_Credit__c/fields/EMS_LM_Employee__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Employee__c</fullName>
    <label>Employee</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Leave_Credits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_Credit__c/fields/EMS_LM_Leaves_Credited__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Leaves_Credited__c</fullName>
    <label>Leaves Credited</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_Credit__c/fields/EMS_LM_Select_Leave_Type__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Select_Leave_Type__c</fullName>
    <label>Select Leave Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Annual Leave</fullName>
            </value>
            <value>
                <fullName>Paternity Leave</fullName>
            </value>
            <value>
                <fullName>Bereavement Leave</fullName>
            </value>
            <value>
                <fullName>Loss of Pay</fullName>
            </value>
            <value>
                <fullName>Work from Home</fullName>
            </value>
            <value>
                <fullName>Maternity Leave</fullName>
            </value>
            <value>
                <fullName>Compensatory Off</fullName>
            </value>
            <value>
                <fullName>Paid time off</fullName>
            </value>
            <value>
                <fullName>UnPaid time off</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/leaveRecalcuation.cls
public class leaveRecalcuation {
 public static void availableLeaveBalanceCalculation(List<EMS_LM_Leave_Credit__C> lcc){
          List<Contact> clu = new List<Contact> ();
          for(EMS_LM_Leave_Credit__C lc : lcc){
              Decimal availableAnnualLeave = 0;
              Decimal availablecompoffLeave = 0;
              List<EMS_LM_Leave_Credit__C> l1 = new List<EMS_LM_Leave_Credit__C>();
              Contact c = new Contact();
              try{
                  c = [Select Id, EMS_LM_No_of_Bereavement_Leaves_Credit__c,EMS_LM_No_Of_Compensatory_Off_Credit__c,
                      EMS_LM_No_Of_Leaves_Credit__c,EMS_LM_No_Of_Maternity_Leaves_Credit__c,EMS_LM_No_Of_Paternity_Leaves_Credit__c,
                      EMS_LM_No_Of_Utilized_Bereavement_Leaves__c,EMS_LM_No_OF_Utilized_Compensatory_Off__c,EMS_LM_No_Of_Utilized_Leaves__c,
                      EMS_LM_No_Of_Utilized_Loss_Of_Pay__c,EMS_LM_No_Of_Utilized_Maternity_Leaves__c,No_Of_Utilized_Paternity_Leaves__c
                      from Contact where Id =: lc.EMS_LM_Employee__c];
              }
              catch(Exception e){
                  system.debug(e.getMessage());
              }
              try{
                  l1 = [select Id, Name, EMS_LM_Leaves_Credited__c, EMS_LM_Select_Leave_Type__c From EMS_LM_Leave_Credit__C 
                      where EMS_LM_Employee__c=:lc.EMS_LM_Employee__c And  CreatedDate = This_Year AND 
                      (EMS_LM_Select_Leave_Type__c = 'Annual Leave' OR EMS_LM_Select_Leave_Type__c = 'Compensatory Off')];

              for(EMS_LM_Leave_Credit__C l2 : l1){
                  if(l2.EMS_LM_Select_Leave_Type__c == 'Annual Leave'){
                      availableAnnualLeave = availableAnnualLeave + l2.EMS_LM_Leaves_Credited__c;
                  }
                  if(l2.EMS_LM_Select_Leave_Type__c == 'Compensatory Off' ){
                      availablecompoffLeave = availablecompoffLeave + l2.EMS_LM_Leaves_Credited__c;
                      
                  }                    
              }  
}
              catch(Exception e){
                  system.debug(e.getMessage());
    }
 }
 }
}