force-app/main/default/objects/Contact/fields/EMS_LM_No_Of_Availble_Leaves__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_No_Of_Availble_Leaves__c</fullName>
    <formula>EMS_LM_No_Of_Leaves_Credit__c - EMS_LM_No_Of_Utilized_Leaves__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>No Of Availble Leaves</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_History__c/EMS_LM_Leave_History__c.object-meta.xml
<CustomObject>
    <description>It will show the employee Leave and WFH Requests.</description>
    <label>Leave Request</label>
    <nameField>
        <displayFormat>LH-{00000}</displayFormat>
        <label>Leave History Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leaves Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_LM_Leave_History__c/fields/EMS_LM_Contact__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Leaves History</relationshipLabel>
    <relationshipName>Leaves_History</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_History__c/fields/EMS_LM_Leave_Duration__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Leave_Duration__c</fullName>
    <label>Leave Duration</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/restrictAnnualLeavebelow.cls
/**
* @author Sangharsh kamble
* @date 03/30/2023
* @description  restrictAnnualLeavebelow Class to restrict the applying Annual leave below -5
*
*               Test code coverage provided by the following test class:
*               - 
*
* CHANGE HISTORY
* ====================================================================================================
* DATE          NAME                    DESCRIPTION
* N/A           N/A                     N/A
* ====================================================================================================
**/
public class restrictAnnualLeavebelow implements TriggerAction.BeforeInsert,TriggerAction.BeforeUpdate{
    public void beforeInsert(List<EMS_LM_Leave_History__c> newList) {      
        System.debug(LoggingLevel.DEBUG, 'restrictAnnualLeavebelow.beforeInsert() : BEGIN');
        restrictAnnualleave(newList);
        System.debug(LoggingLevel.DEBUG, 'restrictAnnualLeavebelow.beforeInsert() : END');       
    }
    
    public void beforeUpdate(List<EMS_LM_Leave_History__c> newList , List<EMS_LM_Leave_History__c> oldList) {      
        System.debug(LoggingLevel.DEBUG, 'restrictAnnualLeavebelow.beforeUpdate() : BEGIN');
        restrictAnnualleave(newList);
        System.debug(LoggingLevel.DEBUG, 'restrictAnnualLeavebelow.beforeUpdate() : END');       
    }
    
    public void restrictAnnualleave(List<EMS_LM_Leave_History__c> newlist) {
        Set<Id> parentIds = new Set<Id>();
        for (EMS_LM_Leave_History__c child : newlist) {
            parentIds.add(child.EMS_LM_Contact__c);
        }
        
        Map<Id, Contact> parents = new Map<Id, Contact>([SELECT Id,EMS_LM_No_Of_Availble_Leaves__c FROM Contact WHERE Id IN :parentIds]);
        
        for(EMS_LM_Leave_History__c his : newlist){
            Contact parent = parents.get(his.EMS_LM_Contact__c);
            system.debug('parent'+parent);
            Decimal balance =parent.EMS_LM_No_Of_Availble_Leaves__c - his.EMS_LM_Leave_Duration__c;
            system.debug('balance'+balance);
            if (parent != null && balance < -5) {
                his.addError('Sorry!! You do not have enough leave balance. Consider applying for leave of some other type.');
            }
        }
    }
}