force-app/main/default/objects/Contact/fields/EMS_EM_JD__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_JD__c</fullName>
    <label>Date of Joining</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_Employee_Type__c.field-meta.xml
<CustomField>
    <fullName>EMS_Employee_Type__c</fullName>
    <label>Employee Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Part-time</fullName>
            </value>
            <value>
                <fullName>Full-time</fullName>
            </value>
            <value>
                <fullName>Contractor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_LM_No_Of_Available_Bereavement_Leave__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_No_Of_Available_Bereavement_Leave__c</fullName>
    <formula>EMS_LM_No_of_Bereavement_Leaves_Credit__c -  EMS_LM_No_Of_Utilized_Bereavement_Leaves__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>No of Available Bereavement Leaves</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_LM_No_Of_Available_Compensatory_Off__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_No_Of_Available_Compensatory_Off__c</fullName>
    <formula>EMS_LM_No_Of_Compensatory_Off_Credit__c -  EMS_LM_No_OF_Utilized_Compensatory_Off__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>No Of Available Compensatory Off</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_LM_No_Of_Available_Maternity_Leave__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_No_Of_Available_Maternity_Leave__c</fullName>
    <formula>EMS_LM_No_Of_Maternity_Leaves_Credit__c -  EMS_LM_No_Of_Utilized_Maternity_Leaves__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>No Of Available Maternity Leave</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_LM_No_Of_Available_Paternity_Leave__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_No_Of_Available_Paternity_Leave__c</fullName>
    <formula>EMS_LM_No_Of_Paternity_Leaves_Credit__c -  No_Of_Utilized_Paternity_Leaves__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>No of Available Paternity Leaves</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_LM_No_Of_Availble_Leaves__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_No_Of_Availble_Leaves__c</fullName>
    <formula>EMS_LM_No_Of_Leaves_Credit__c - EMS_LM_No_Of_Utilized_Leaves__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>No Of Availble Leaves</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_LM_No_Of_Carry_Forward_Leaves__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_No_Of_Carry_Forward_Leaves__c</fullName>
    <label>No of Carry Forward Leaves</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_LM_No_Of_Leaves_Credit__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_No_Of_Leaves_Credit__c</fullName>
    <defaultValue>0</defaultValue>
    <label>No Of Annual Leaves Credit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_LM_No_Of_Utilized_Leaves__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_No_Of_Utilized_Leaves__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Annual available leaves of employee</description>
    <label>No of Utilized Annual Leaves</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_RM_ApplicantStatus_Update__c.field-meta.xml
<CustomField>
    <fullName>EMS_RM_ApplicantStatus_Update__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Offer rolled out</fullName>
            </value>
            <value>
                <fullName>Offer accepted</fullName>
            </value>
            <value>
                <fullName>Offer rejected</fullName>
            </value>
            <value>
                <fullName>Hired</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Did not join</fullName>
            </value>
            <value>
                <fullName>Active - Probation</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Notice Period</fullName>
            </value>
            <value>
                <fullName>ABSENT</fullName>
                <isActive>false</isActive>
                <label>ABSENT</label>
            </value>
            <value>
                <fullName>Docs received</fullName>
                <isActive>false</isActive>
                <label>Docs received</label>
            </value>
            <value>
                <fullName>Docs verified</fullName>
                <isActive>false</isActive>
                <label>Docs verified</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Work_Location__c.field-meta.xml
<CustomField>
    <fullName>Work_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Location</label>
    <referenceTo>Office_Location__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Office_Location__c/Office_Location__c.object-meta.xml
<CustomObject>
    <label>Office Location</label>
    <nameField>
        <label>Office Locations Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Office Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/BatchToChangeLeavesForUSEmployees.cls
global without sharing class BatchToChangeLeavesForUSEmployees implements Database.Batchable<sObject> {
    global Database.QueryLocator start(Database.BatchableContext BC) {
        Id WORKLOCATION_USA_ID =[select Id, Name From Office_Location__c WHERE Name='California - USA' LIMIT 1].Id;
        return Database.getQueryLocator([SELECT Id,AccountId,EMS_LM_No_Of_Carry_Forward_Leaves__c, EMS_LM_No_Of_Leaves_Credit__c,
                                         EMS_LM_No_Of_Availble_Leaves__c, EMS_LM_No_Of_Available_Paternity_Leave__c,
                                         EMS_LM_No_Of_Available_Maternity_Leave__c, EMS_LM_No_Of_Available_Compensatory_Off__c,EMS_LM_No_Of_Utilized_Leaves__c,
                                         EMS_LM_No_Of_Available_Bereavement_Leave__c,EMS_EM_JD__c,Work_Location__c,Work_Location__r.name,EMS_Employee_Type__c
                                         FROM Contact WHERE RecordTypeId =:ContactConstant.RESOURCE_RECORDTYPEID AND AccountId !=Null AND (EMS_RM_ApplicantStatus_Update__c ='Active' OR EMS_RM_ApplicantStatus_Update__c ='Active - Probation') AND
                                           Work_Location__c =:WORKLOCATION_USA_ID]);
    }
    
    global void execute(Database.BatchableContext BC, List<Contact> conList) {
        List<Contact> contactsNeedToBeUpdateList=new List<Contact>();
        for(Contact conRec:conList){
            Integer monthsSinceJoin = conRec.EMS_EM_JD__c.monthsBetween(System.today());
            if(monthsSinceJoin>=24 && conRec.EMS_LM_No_Of_Availble_Leaves__c >0){
               conRec.EMS_LM_No_Of_Leaves_Credit__c=0;
                conRec.EMS_LM_No_Of_Utilized_Leaves__c=0;
            }
            contactsNeedToBeUpdateList.add(conRec);
        }
        database.update(contactsNeedToBeUpdateList,false);
        
    }
    global void finish(Database.BatchableContext BC) {
        
    }
}