force-app/main/default/objects/Contact/fields/EMS_EM_JD__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_JD__c</fullName>
    <label>Date of Joining</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>EMS_Phone_Number__c</fullName>
    <label>Contact Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_TM_Billable__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Billable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Billable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Official_Mail__c.field-meta.xml
<CustomField>
    <fullName>Official_Mail__c</fullName>
    <label>Official Email ID(old)</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <label>Client</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Resource.recordType-meta.xml
<RecordType>
    <fullName>Resource</fullName>
    <active>true</active>
    <label>Resource</label>
</RecordType>

force-app/main/default/objects/EMS_TM_Assignment__c/EMS_TM_Assignment__c.object-meta.xml
<CustomObject>
    <label>Assignment</label>
    <nameField>
        <displayFormat>A.ID-{0000}</displayFormat>
        <label>Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_TM_Assignment__c/fields/EMS_TM_Billable__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Billable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Billable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Assignment__c/fields/EMS_TM_EmployeeName__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_EmployeeName__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Employee Name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Resource</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Assignments</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Assignment__c/fields/EMS_TM_ProjectName_Asgn__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_ProjectName_Asgn__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Name</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>EMS_TM_Project__c.Type_Of_Project__c</field>
            <operation>notEqual</operation>
            <value>Global Projects</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>EMS_TM_Project__c</referenceTo>
    <relationshipLabel>Project Assignees</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Assignment__c/fields/EMS_TM_StartDate_Asgn__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_StartDate_Asgn__c</fullName>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Assignment__c/fields/EMS_TM_Status_Asgn__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Status_Asgn__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <isActive>false</isActive>
                <label>Cancelled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EMS_TM_Project__c/EMS_TM_Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_TM_Project__c/fields/EMS_TM_StartDate__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_StartDate__c</fullName>
    <label>StartDate</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Project__c/fields/EMS_TM_Status__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ongoing</fullName>
                <default>true</default>
                <label>Ongoing</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EMS_TM_ContactBillableclose_Test.cls
@istest
public class EMS_TM_ContactBillableclose_Test {
   
    public static testmethod void contactBilableClose(){
        recordtype r =[SELECT Id, Name, SobjectType, DeveloperName, IsActive FROM RecordType where name ='Client Projects'];
        EMS_TM_Project__c p = new EMS_TM_Project__c();
        p.EMS_TM_StartDate__c = System.today();
        p.EMS_TM_Status__c = 'ongoing';
        p.Name = 'project1';
        p.RecordTypeId = r.id;
        insert p;
        recordtype r1 =[SELECT Id, Name, SobjectType, DeveloperName, IsActive FROM RecordType where name ='Resource' AND Isactive = true];
        contact c = new contact();
        c.LastName = 'rk';
        c.Official_Mail__c ='rama@rama.com';
        c.Phone = '9652901075';
        c.EMS_Phone_Number__c = '9652901075';
        c.RecordTypeId = r1.Id;
        c.EMS_EM_JD__c = system.today();
        insert c;
        
        
        EMS_TM_Assignment__c a = new EMS_TM_Assignment__c();
        a.EMS_TM_EmployeeName__c = c.id;
        a.EMS_TM_ProjectName_Asgn__c = p.id;
        a.EMS_TM_StartDate_Asgn__c = system.today();
        a.EMS_TM_Billable__c = true;
       // a.Name = 'assign1';
        insert a;
        
        test.startTest();
        EMS_TM_Assignment__c aa =[Select id,EMS_TM_EmployeeName__c,EMS_TM_Status_Asgn__c,EMS_TM_Billable__c from EMS_TM_Assignment__c 
                                       where EMS_TM_EmployeeName__r.lastname  = 'rk'];
        aa.EMS_TM_Billable__c = false;
        update aa;
        test.stopTest();
        
               
    }
}