force-app/main/default/objects/Contact/fields/EMS_LM_No_of_Bereavement_Leaves_Credit__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_No_of_Bereavement_Leaves_Credit__c</fullName>
    <label>No of Bereavement Leaves Credit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_LM_No_Of_Compensatory_Off_Credit__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_No_Of_Compensatory_Off_Credit__c</fullName>
    <label>No Of Compensatory Off Credit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_LM_No_Of_Leaves_Credit__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_No_Of_Leaves_Credit__c</fullName>
    <defaultValue>0</defaultValue>
    <label>No Of Annual Leaves Credit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_LM_No_Of_Maternity_Leaves_Credit__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_No_Of_Maternity_Leaves_Credit__c</fullName>
    <label>No Of Maternity Leaves Credit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_LM_No_Of_Paternity_Leaves_Credit__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_No_Of_Paternity_Leaves_Credit__c</fullName>
    <label>No of Paternity Leaves Credit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_Credit__c/EMS_LM_Leave_Credit__c.object-meta.xml
<CustomObject>
    <description>To credit the Leaves to Employees as per Policies</description>
    <label>Leave Credit</label>
    <nameField>
        <displayFormat>LC-{00000}</displayFormat>
        <label>Leave Credit Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leave Credits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_LM_Leave_Credit__c/fields/EMS_LM_Employee__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Employee__c</fullName>
    <label>Employee</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Leave_Credits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_Credit__c/fields/EMS_LM_Leaves_Credited__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Leaves_Credited__c</fullName>
    <label>Leaves Credited</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_Credit__c/fields/EMS_LM_Select_Leave_Type__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Select_Leave_Type__c</fullName>
    <label>Select Leave Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Annual Leave</fullName>
            </value>
            <value>
                <fullName>Paternity Leave</fullName>
            </value>
            <value>
                <fullName>Bereavement Leave</fullName>
            </value>
            <value>
                <fullName>Loss of Pay</fullName>
            </value>
            <value>
                <fullName>Work from Home</fullName>
            </value>
            <value>
                <fullName>Maternity Leave</fullName>
            </value>
            <value>
                <fullName>Compensatory Off</fullName>
            </value>
            <value>
                <fullName>Paid time off</fullName>
            </value>
            <value>
                <fullName>UnPaid time off</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CalculateAvailableLeaveBalance.cls
/**
* @author Eswar
* @date 11/01/2023
* @description  CalculateAvailableLeaveBalance Class to calculate available leave balance of the employee 
*              
*
*               Test code coverage provided by the following test class:
*               - CalculateAvailableLeaveBalanceTest
*
* CHANGE HISTORY
* ====================================================================================================
* DATE          NAME                    DESCRIPTION
* N/A           N/A                     N/A
* ====================================================================================================
**/
public class CalculateAvailableLeaveBalance implements TriggerAction.AfterInsert{
    /**
* @author Eswar
* @date 11/01/2023
* @description After Insert 
*
* CHANGE HISTORY
* ====================================================================================================
* DATE          NAME                    DESCRIPTION
* N/A           N/A                     N/A
* ====================================================================================================
**/
    public void afterInsert(List<EMS_LM_Leave_Credit__c> newList) {      
        System.debug(LoggingLevel.DEBUG, 'CalculateAvailableLeaveBalance.afterInsert() : BEGIN');
        calculateEmployeeAvailableLeaveBalance(newList);
        System.debug(LoggingLevel.DEBUG, 'CalculateAvailableLeaveBalance.afterInsert() : END');       
    }
    /**
*   {Purpose} - Method for calculate available leave balance of the employee
*
*   CHANGE HISTORY
*   ====================================================================================================
*   Date        Name                    Description
*   N/A         N/A                     N/A
*   ====================================================================================================
**/
    private void calculateEmployeeAvailableLeaveBalance(List<EMS_LM_Leave_Credit__c> leaveCreditList){       
        List<Contact> finalContactList = new List<Contact> ();
        set<string> employeeSet = new set<String>();
        Decimal availableAnnualLeave = 0;
        Decimal availablecompoffLeave = 0;
        Decimal availablePaternityLeave = 0;
        Decimal availableMaternityLeave = 0;
        Decimal availableBereavementLeave = 0; 
        for(EMS_LM_Leave_Credit__c leaveCredit : leaveCreditList){
                employeeSet.add(leaveCredit.EMS_LM_Employee__c); 
        }
        
        Map<Id,Contact> contactMap = new Map<Id,Contact>(
            								[SELECT Id, 
                                                 EMS_LM_No_of_Bereavement_Leaves_Credit__c,
                                                 EMS_LM_No_Of_Compensatory_Off_Credit__c,
                                                 EMS_LM_No_Of_Leaves_Credit__c,
                                                 EMS_LM_No_Of_Maternity_Leaves_Credit__c,
                                                 EMS_LM_No_Of_Paternity_Leaves_Credit__c
                                             FROM Contact
                                             WHERE Id IN: employeeSet]);
       
        for(EMS_LM_Leave_Credit__C leaveCreditRec : leaveCreditList){
            if(contactMap.containsKey(leaveCreditRec.EMS_LM_Employee__c)){
              contact contactRec =  contactMap.get(leaveCreditRec.EMS_LM_Employee__c);
                String leaveTypeRec = leaveCreditRec.EMS_LM_Select_Leave_Type__c;
                Switch on leaveTypeRec{
                    when 'Annual Leave'{
                        contactRec.EMS_LM_No_Of_Leaves_Credit__c = contactRec.EMS_LM_No_Of_Leaves_Credit__c + leaveCreditRec.EMS_LM_Leaves_Credited__c;
                    }
                    when 'Compensatory Off'{
                        contactRec.EMS_LM_No_Of_Compensatory_Off_Credit__c = contactRec.EMS_LM_No_Of_Compensatory_Off_Credit__c + leaveCreditRec.EMS_LM_Leaves_Credited__c;
                    }
                    when 'Maternity Leave'{
                        contactRec.EMS_LM_No_Of_Maternity_Leaves_Credit__c = contactRec.EMS_LM_No_Of_Maternity_Leaves_Credit__c + leaveCreditRec.EMS_LM_Leaves_Credited__c;
                    }
                    when 'Bereavement Leave'{
                        contactRec.EMS_LM_No_of_Bereavement_Leaves_Credit__c = contactRec.EMS_LM_No_of_Bereavement_Leaves_Credit__c + leaveCreditRec.EMS_LM_Leaves_Credited__c;
                    }
                    when 'Paternity Leave'{
                        contactRec.EMS_LM_No_Of_Paternity_Leaves_Credit__c = contactRec.EMS_LM_No_Of_Paternity_Leaves_Credit__c + leaveCreditRec.EMS_LM_Leaves_Credited__c;
                    }
                }
               finalContactList.add(contactRec); 
            }  
        }
        
        try{
            if(finalContactList.size()>0){
                Update finalContactList;   
            }
        }
        Catch(Exception excp){
			LogException.logHandledException(excp, 'CalculateAvailableLeaveBalance', 'calculateEmployeeAvailableLeaveBalance');        
        }  
    }
}