force-app/main/default/objects/Contact/fields/EMS_RM_Employee_Id__c.field-meta.xml
<CustomField>
    <fullName>EMS_RM_Employee_Id__c</fullName>
    <label>Employee ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_History__c/EMS_LM_Leave_History__c.object-meta.xml
<CustomObject>
    <description>It will show the employee Leave and WFH Requests.</description>
    <label>Leave Request</label>
    <nameField>
        <displayFormat>LH-{00000}</displayFormat>
        <label>Leave History Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leaves Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_Timesheet__c/EMS_Timesheet__c.object-meta.xml
<CustomObject>
    <label>Timesheet</label>
    <nameField>
        <displayFormat>TS-{0000}</displayFormat>
        <label>Time Sheet ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_Timesheet__c/fields/EMS_TM_Project__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>EMS_TM_Project__c</referenceTo>
    <relationshipLabel>Timesheets</relationshipLabel>
    <relationshipName>Timesheets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/EMS_TM_Status__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Not Approved</fullName>
            </value>
            <value>
                <fullName>Reported</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Saved</fullName>
            </value>
            <value>
                <fullName>Locked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/EMS_TM_Total__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Total__c</fullName>
    <description>Display the total working hours of employee</description>
    <formula>EMS_TM_Sun__c  +  EMS_TM_Mon__c  +  EMS_TM_Tue__c  +  EMS_TM_Wed__c + EMS_TM_Thu__c+ EMS_TM_Fri__c+ EMS_TM_Sat__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Hours</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Timesheets</relationshipLabel>
    <relationshipName>Timesheets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Timesheets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/Week_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Week_End_Date__c</fullName>
    <label>Week End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/Week_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Week_Start_Date__c</fullName>
    <label>Week Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Assignment__c/EMS_TM_Assignment__c.object-meta.xml
<CustomObject>
    <label>Assignment</label>
    <nameField>
        <displayFormat>A.ID-{0000}</displayFormat>
        <label>Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_TM_Assignment__c/fields/EMS_TM_EmployeeName__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_EmployeeName__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Employee Name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Resource</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Assignments</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Assignment__c/fields/EMS_TM_ProjectName_Asgn__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_ProjectName_Asgn__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Name</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>EMS_TM_Project__c.Type_Of_Project__c</field>
            <operation>notEqual</operation>
            <value>Global Projects</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>EMS_TM_Project__c</referenceTo>
    <relationshipLabel>Project Assignees</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Assignment__c/fields/EMS_TM_Status_Asgn__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Status_Asgn__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <isActive>false</isActive>
                <label>Cancelled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EMS_TM_Assignment__c/fields/Resource_User_Id__c.field-meta.xml
<CustomField>
    <fullName>Resource_User_Id__c</fullName>
    <formula>EMS_TM_EmployeeName__r.EMS_TM_User__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Resource User Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Project__c/EMS_TM_Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_TM_Project__c/fields/EMS_TM_Status__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ongoing</fullName>
                <default>true</default>
                <label>Ongoing</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EMS_TM_Project__c/fields/Project_Manager__c.field-meta.xml
<CustomField>
    <fullName>Project_Manager__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Onshore Project Manager</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND (2 OR 3)</booleanFilter>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Resource</value>
        </filterItems>
        <filterItems>
            <field>Contact.Resource_Role__r.Name</field>
            <operation>equals</operation>
            <value>Sr Project Manager</value>
        </filterItems>
        <filterItems>
            <field>Contact.Resource_Role__r.Name</field>
            <operation>equals</operation>
            <value>Project Manager</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Timesheet_Record__c/EMS_TM_Timesheet_Record__c.object-meta.xml
<CustomObject>
    <label>Timesheet Line Items</label>
    <nameField>
        <displayFormat>TLI{00000000}</displayFormat>
        <label>Timesheet Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheet Records</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_TM_Timesheet_Record__c/fields/EMS_Timesheet__c.field-meta.xml
<CustomField>
    <fullName>EMS_Timesheet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>EMS_Timesheet</label>
    <referenceTo>EMS_Timesheet__c</referenceTo>
    <relationshipName>Employee_Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Timesheet_Record__c/fields/EMS_TM_Project__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>EMS_TM_Project__c</referenceTo>
    <relationshipLabel>Timesheet Records</relationshipLabel>
    <relationshipName>Timecard_Splits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Timesheet_Record__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saved</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Reassign</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EMS_TM_Timesheet_Record__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Employee_Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Timesheet_Record__c/fields/Week_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Week_End_Date__c</fullName>
    <label>Week End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Timesheet_Record__c/fields/Week_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Week_Start_Date__c</fullName>
    <label>Week Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/User/fields/project_manager__c.field-meta.xml
<CustomField>
    <fullName>project_manager__c</fullName>
    <label>Project Manager</label>
    <relationshipName>Users</relationshipName>
    <restrictedAdminField>true</restrictedAdminField>
    <type>Hierarchy</type>
</CustomField>

force-app/main/default/classes/Testingnotify.cls
//This Clss is The orginal backup of BatchToNotifyTCForPM
/**
* @author Subba Kalavala
* @date 2/22/2023
* @description  BatchToNotifyTCForPM Batch to Send an pending timecards to managers 
*              
*               Schedule class 
*               - BatchToNotifyTCForPM_sch
*               Test code coverage provided by the following test class:
*               - BatchToNotifyTCForPM_Test
*
* CHANGE HISTORY
* ====================================================================================================
* DATE          NAME                    DESCRIPTION
* N/A           N/A                     N/A
* ====================================================================================================
**/
global without sharing class Testingnotify implements Database.Batchable<sObject> {
//global static string link = URL.getSalesforceBaseUrl().toExternalForm() + '/';
        global static string link=system.Label.Grid_Portal_Link  + '/';

 /**
* @author Subba
* @date 22/01/2023
* @description start query to get the data of the object that required to process.
*
* CHANGE HISTORY
* ====================================================================================================
* DATE          NAME                    DESCRIPTION
* N/A           N/A                     N/A
* ====================================================================================================
**/
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator([SELECT Id,Email,Name FROM Contact WHERE RecordTypeId=:ContactConstant.RESOURCE_RECORDTYPEID ]);
    }
    
/**
* @author Subba
* @date 22/01/2023
* @description  Execute method to process the business logic.
*
* CHANGE HISTORY
* ====================================================================================================
* DATE          NAME                    DESCRIPTION
* N/A           N/A                     N/A
* ====================================================================================================
**/
    global void execute(Database.BatchableContext BC, List<Contact> conList) {
       set<string> managerIds = new set<string>();
        set<string> prjIds = new set<string>();
       map<string,Contact> pmwithemail = new map<string,Contact>();
        Date todayval = system.today(); 
        Date considerDate = todayval.toStartofWeek().addDays(-2);
        Date weekStart = considerDate.toStartofWeek().addDays(1);
        Date weekEnd = considerDate.toStartofWeek().addDays(7);
        System.debug('===weekStart==='+weekStart);
        System.debug('===weekEnd==='+weekEnd);
        
        for(Contact Urec : conList){
          managerIds.add(Urec.Id); 
         pmwithemail.put(Urec.Id,Urec);
        }
        System.debug('***pmwithemail'+pmwithemail);
         System.debug('***managerIds'+managerIds);
        Map<Id,List<EMS_TM_Project__c>> pmWithProjects = new Map<Id,List<EMS_TM_Project__c>>();
        Map<Id,List<String>> prjWithTimeCards = new Map<Id,List<String>>();
        //timesheet
                Map<Id,set<String>> contactswithtsproject = new Map<Id,set<String>>();
        //testing
        Map<Id,List<EMS_LM_Leave_History__c>> appWithAbseReqts = new Map<Id,List<EMS_LM_Leave_History__c>>();
        Map<String,List<EMS_Timesheet__c>> resourceWithTimeCard = new Map<String,List<EMS_Timesheet__c>>();
        set<string> resourceIds = new set<String>();
        for(EMS_TM_Project__c prj : [SELECT id,Project_Manager__c,
                                     (SELECT Id,EMS_TM_EmployeeName__c,Resource_User_Id__c FROM Assignments__r WHERE EMS_TM_Status_Asgn__c = 'Active' ),
                                     (SELECT Id, Status__c, EMS_TM_Project__c, EMS_Timesheet__c,EMS_Timesheet__r.EMS_TM_Project__r.Name,
                                        EMS_Timesheet__r.Week_Start_Date__c,EMS_Timesheet__r.Week_End_Date__c,EMS_Timesheet__r.User__r.isActive,
                                        EMS_TM_Project__r.Name,EMS_Timesheet__r.Resource__r.Name,
                                        EMS_Timesheet__r.Resource__r.EMS_RM_Employee_Id__c FROM Timecard_Splits__r 
                                      WHERE EMS_Timesheet__r.User__r.isActive = true 
                                      AND EMS_Timesheet__r.Week_Start_Date__c>=:weekStart 
                                      AND EMS_Timesheet__r.Week_End_Date__c<=:weekEnd AND (EMS_Timesheet__r.EMS_TM_Total__c < 40 
                                     OR EMS_Timesheet__r.EMS_TM_Status__c = 'NEW' OR EMS_Timesheet__r.EMS_TM_Status__c = 'Saved' 
                                     OR EMS_Timesheet__r.EMS_TM_Status__c = 'Not Approved'))
                                     FROM EMS_TM_Project__c WHERE Project_Manager__c IN:managerIds AND EMS_TM_Status__c = 'Ongoing']){
                                         System.debug('DATA_Proj'+prj);
            prjIds.add(prj.Id);
            if(pmWithProjects.containsKey(prj.Project_Manager__c)){
                pmWithProjects.get(prj.Project_Manager__c).add(prj);
            }else{
                pmWithProjects.put(prj.Project_Manager__c, new List<EMS_TM_Project__c>{prj}); 
            }
              if(prj.assignments__r.size() >0){
               for(EMS_TM_Assignment__c assig : prj.assignments__r){
                   resourceIds.add(assig.Resource_User_Id__c);
                   }
               }
        }
        SYstem.debug('***pmWithProjects'+pmWithProjects+'.....'+pmWithProjects.size());
        SYstem.debug('***resourceIds'+resourceIds+'.....'+resourceIds.size());
        SYstem.debug('***prjIds'+prjIds+'....'+prjIds);
         Map<Id,List<EMS_TM_Timesheet_Record__c>> prjWithTsheets = new  Map<Id,List<EMS_TM_Timesheet_Record__c>>();
        if(!pmWithProjects.isEmpty()){
            system.debug('pmWithProjects.keySet()========================='+pmWithProjects.keySet());
            for(String pm : pmWithProjects.keySet()){
                System.debug('pm'+pm);
               List<EMS_TM_Timesheet_Record__c> timesheetsList = new List<EMS_TM_Timesheet_Record__c>(); 
             //   List<EMS_TM__Timesheet__c> timesheet=
              if(pmWithProjects.containsKey(pm)){
                    for(EMS_TM_Project__c proj : pmWithProjects.get(pm)){
                        System.debug('proj'+proj);
                        if(proj.Timecard_Splits__r.size() >0){
                           for(EMS_TM_Timesheet_Record__c ts : proj.Timecard_Splits__r){
                               system.debug('ts======================'+ts);
                               if(contactswithtsproject.containskey(ts.EMS_Timesheet__r.Resource__c)){
                                   contactswithtsproject.get(ts.EMS_Timesheet__r.Resource__c).add(ts.EMS_TM_Project__r.Name);
                               }else{
                                   list<string> tslistwithcon=new list<string>();
                                  // tslistwithcon.add(ts.EMS_Timesheet__r.EMS_TM_Project__r.Name);
                               contactswithtsproject.put(ts.EMS_Timesheet__r.Resource__c,new set<String>{ts.EMS_TM_Project__r.Name});
                                   system.debug('contactswithtsproject==========='+contactswithtsproject);
                               }
                               timesheetsList.add(ts);
                               
                              }
                         }
                        
                    } 
                }
                System.debug('timesheetsList'+timesheetsList +'.......'+timesheetsList.size());
             
              prjWithTsheets.put(pm,timesheetsList);  
            }
        }        
        System.debug('====prjWithTsheets==='+prjWithTsheets);
        System.debug('====SIZEprjWithTsheets==='+prjWithTsheets.size());
        List<Messaging.SingleEmailMessage> allMails = new List<Messaging.SingleEmailMessage>();
        if(!prjWithTsheets.isEmpty()){
           Id orgWideAddressId =[SELECT Id, DisplayName, Address FROM OrgWideEmailAddress where DisplayName = 'Grid' LIMIT 1].Id;
            for(Id pmId : prjWithTsheets.keySet()){
                System.debug('***pmId***'+pmId);
                list<string> toaddress = new list<string>();   
                //if(prjWithTsheets.containsKey(pmId) && prjWithTsheets.get(pmId).size() >0 && pmwithemail.containsKey(pmId)){
                if(prjWithTsheets.containsKey(pmId)&& pmwithemail.containsKey(pmId)){
                    System.debug('toadress EMAil'+pmwithemail.get(pmId).Email);
                   toaddress.add(pmwithemail.get(pmId).Email);
                    System.debug('***ToAddress'+toaddress);
                  Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
                  email.setOrgWideEmailAddressId(orgWideAddressId);
                  email.setSubject('Employee timesheets overdue');
                    System.debug('**TimesheetData'+prjWithTsheets.get(pmId));
                   string  emailbody = getTableEmailBody(prjWithTsheets.get(pmId),contactswithtsproject);
                   email.setHtmlBody('Dear '+pmwithemail.get(pmId).Name+',<br/><br/>The weekly timesheets of the following employees are overdue:<br/><br/>'+ emailbody + '<br/><br/><h3 style="text-align: center">DO NOT REPLY TO THIS EMAIL</h3>');
                   email.setToAddresses(toaddress);
                   email.setSaveAsActivity(false);
                   allMails.add(email); 
                }
            }
        }
       system.debug('====allMails===='+allMails);
        try{
            Messaging.sendEmail(allMails); 
        }catch(exception ex){
         LogException.logHandledException(ex, 'BatchToNotifyTCForPM', 'execute');     
        }
        
    } 
    
    public  string getTableEmailBody(list<EMS_TM_Timesheet_Record__c> timesheets,map<Id,set<string>> contactswithtsproject){
        
        System.debug('timesheets'+timesheets);
        
        String sday ;
        String smonth ;
        String syear;
        String eday;
        String emonth ;
        String eyear ;
        
        String htmlBody = '';
        String myName = Null;
        //open table..
        htmlBody = '<table border="1" style="border-collapse: collapse;width:80%;"><caption></caption><tr><th>S.No</th><th>Employee Id</th><th>Employee Name</th><th>Week</th></tr>';
        
        //iterate over list and output columns/data into table rows...
        if(timesheets !=null && timesheets.size()>0)
        {
            for(integer i = 0;i<timesheets.size();i++)
            {
                htmlBody += '<tr><td><center>' + (i+1) + '</center></td><td><center> <a href="'+link+'/'+timesheets[i].Id+'">'+timesheets[i].EMS_Timesheet__r.Resource__r.Name+'</a></center></td><td>'+timesheets[i].EMS_Timesheet__r.Resource__r.Name+'</td><td><center> '+timesheets[i].EMS_Timesheet__r.Week_End_Date__c +'</center> </td><td><center> '+contactswithtsproject.get(timesheets[i].EMS_Timesheet__r.Resource__r.Id)+'</center> </td></tr>';  
            }
        }
        //close table...
        htmlBody += '</table>';
        
        system.debug('Email Body: ' + htmlBody);   
        
        return htmlBody;
        
    }       
    
    
    /**
* @author Subba
* @date 22/01/2023
* @description process the failures.
*
* CHANGE HISTORY
* ====================================================================================================
* DATE          NAME                    DESCRIPTION
* N/A           N/A                     N/A
* ====================================================================================================
**/
    global void finish(Database.BatchableContext BC) {
        
    }
}