force-app/main/default/objects/Contact/fields/EMS_EM_Exp__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_Exp__c</fullName>
    <inlineHelpText>Experience in years</inlineHelpText>
    <label>Work Experience</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_EM_JD__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_JD__c</fullName>
    <label>Date of Joining</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Not_Eligible_For_Annual_Awards__c.field-meta.xml
<CustomField>
    <fullName>Not_Eligible_For_Annual_Awards__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Not Eligible For Annual Awards</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Resource.recordType-meta.xml
<RecordType>
    <fullName>Resource</fullName>
    <active>true</active>
    <label>Resource</label>
</RecordType>

force-app/main/default/objects/Reward_And_Recognition__c/Reward_And_Recognition__c.object-meta.xml
<CustomObject>
    <label>Reward And Recognition</label>
    <nameField>
        <displayFormat>REC{0000000}</displayFormat>
        <label>Nominee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rewards And Recognitions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reward_And_Recognition__c/fields/Award_Type__c.field-meta.xml
<CustomField>
    <fullName>Award_Type__c</fullName>
    <label>Award Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Best Entrepreneur</fullName>
            </value>
            <value>
                <fullName>Most Professional</fullName>
            </value>
            <value>
                <fullName>Rising Star</fullName>
            </value>
            <value>
                <fullName>Rock Star</fullName>
            </value>
            <value>
                <fullName>Service Awards</fullName>
            </value>
            <value>
                <fullName>Recognize</fullName>
            </value>
            <value>
                <fullName>Shout Out</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reward_And_Recognition__c/fields/Lost_Reason__c.field-meta.xml
<CustomField>
    <fullName>Lost_Reason__c</fullName>
    <label>Lost Reason</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Reward_And_Recognition__c/fields/of_Primary_Nominations__c.field-meta.xml
<CustomField>
    <fullName>of_Primary_Nominations__c</fullName>
    <label># of Primary Nominations</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Reward_And_Recognition__c/fields/of_Total_Nominations__c.field-meta.xml
<CustomField>
    <fullName>of_Total_Nominations__c</fullName>
    <formula>of_Primary_Nominations__c +  of_Secondary_Nominations__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label># of Total Nominations</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Reward_And_Recognition__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <label>Resource</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Rewards And Recognitions</relationshipLabel>
    <relationshipName>Rewards_And_Recognitions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reward_And_Recognition__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nominated</fullName>
                <default>true</default>
                <label>Nominated</label>
            </value>
            <value>
                <fullName>Review In Progress</fullName>
            </value>
            <value>
                <fullName>Not Qualified</fullName>
            </value>
            <value>
                <fullName>Winner</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reward_And_Recognition__c/fields/System_Predicted_Status__c.field-meta.xml
<CustomField>
    <fullName>System_Predicted_Status__c</fullName>
    <label>System Predicted Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Might Looser</fullName>
                <label>Most Likely Winner</label>
            </value>
            <value>
                <fullName>Might Winner</fullName>
            </value>
            <value>
                <fullName>Winner</fullName>
            </value>
            <value>
                <fullName>Looser</fullName>
                <label>Potential Winner</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reward_And_Recognition__c/recordTypes/Scoring.recordType-meta.xml
<RecordType>
    <fullName>Scoring</fullName>
    <active>true</active>
    <description>Used  for Annual Awards Scoring</description>
    <label>Scoring</label>
</RecordType>

force-app/main/default/classes/BatchToUpdatePridcation.cls
global class BatchToUpdatePridcation  implements Database.Batchable<sObject> {
    global Database.QueryLocator start(Database.BatchableContext BC) {
         Id scoringRecordTypeId = Schema.SObjectType.Reward_And_Recognition__c.getRecordTypeInfosByName().get('Scoring').getRecordTypeId();
         return Database.getQueryLocator([SELECT Id,Award_Type__c,Resource__c FROM Reward_And_Recognition__c WHERE RecordTypeId=:scoringRecordTypeId and Status__c = 'Review In Progress']);
    }
    global void execute(Database.BatchableContext BC, List<Reward_And_Recognition__c> RRList) {
         set<String> resources = new set<String>();
         Map<Id,Reward_And_Recognition__c> scoringUpdateMap = new Map<Id,Reward_And_Recognition__c>();
         List<Reward_And_Recognition__c> filtered = new List<Reward_And_Recognition__c>();
         Reward_And_Recognition__c rrawrd = RRList[0];
          for(Reward_And_Recognition__c rr : [SELECT Id,Award_Type__c,Resource__c,Resource__r.Not_Eligible_For_Annual_Awards__c,Status__c,System_Predicted_Status__c FROM Reward_And_Recognition__c WHERE Award_Type__c =:rrawrd.Award_Type__c  and Status__c = 'Review In Progress']){
            resources.add(rr.Resource__c); 
             scoringUpdateMap.put(rr.Id,rr);
             if(rr.Resource__r.Not_Eligible_For_Annual_Awards__c){
              scoringUpdateMap.get(rr.Id).Status__c = 'Not Qualified';  
              scoringUpdateMap.get(rr.Id).System_Predicted_Status__c = 'Potential Winner';
              scoringUpdateMap.get(rr.Id).Lost_Reason__c = 'Resource is not eligiable for annual awards.';               
            }
          }
          
        Map<Id,Contact> contacMap = new Map<Id,Contact>([SELECT Id,EMS_EM_JD__c,EMS_EM_Exp__c,Not_Eligible_For_Annual_Awards__c,(Select Id FROM Rewards_And_Recognitions__r WHERE Status__c = 'Winner') FROM Contact WHERE Id IN:resources]);
        Decimal totalNoms = 0;
        String winner = null;
        for(Reward_And_Recognition__c rr : [SELECT Id,Award_Type__c,Resource__c,Comments__c,of_Total_Nominations__c FROM Reward_And_Recognition__c WHERE Award_Type__c =:rrawrd.Award_Type__c  
                                            and Status__c = 'Review In Progress' and Resource__r.Not_Eligible_For_Annual_Awards__c=false ORDER BY of_Primary_Nominations__c DESC]){
            contact resou = contacMap.get(rr.Resource__c);
            Integer oOfdayFromJoining = (resou.EMS_EM_JD__c).daysBetween(System.today()) ;
            if(rr.Award_Type__c == 'Rising Star' && resou.EMS_EM_Exp__c != null && ( resou.EMS_EM_Exp__c > 3 || oOfdayFromJoining < 180 ) ){
               scoringUpdateMap.get(rr.Id).Status__c = 'Not Qualified';  
               scoringUpdateMap.get(rr.Id).System_Predicted_Status__c = 'Potential Winner';
               scoringUpdateMap.get(rr.Id).Lost_Reason__c = 'Resource might have more then 3 years of exp or less than 6 months to cloudperitus.'; 
                continue;
            }
            if(rr.of_Total_Nominations__c > totalNoms){
                totalNoms = rr.of_Total_Nominations__c;
                winner = rr.id;
              scoringUpdateMap.get(rr.Id).System_Predicted_Status__c = 'Potential Winner'; //smaske:[03-July-2024]: Changing "Might Winner" with "Less likely to win" for PM_102 , //smaske:[PM_Def_007] : 'Less likely to win' changed to 'Potential Winner'
              scoringUpdateMap.get(rr.Id).Comments__c = 'Resource got more nomination when compared to other Contenders.'; 
            }else{
              scoringUpdateMap.get(rr.Id).System_Predicted_Status__c = 'Less likely to win'; //smaske:[PM_Def_007] :updating 'Most Likely Winner' to "Less likely to win"
              scoringUpdateMap.get(rr.Id).Comments__c = 'Resource got less nomination when compared to other Contenders.';  
            }     
            
         }
        
        
        
        try{
            update scoringUpdateMap.values();
                     
        }catch(exception ex){
           LogException.logHandledException(ex, 'BatchToCreateKRAforQuaterly', 'execute');  
        }
    }
    
    global void finish(Database.BatchableContext BC) {
        
    }
}