force-app/main/default/objects/Contact/fields/EMS_TM_User__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Resource_Role__c.field-meta.xml
<CustomField>
    <fullName>Resource_Role__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Role</label>
    <referenceTo>Resource_Role__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fiscal_Year__c/Fiscal_Year__c.object-meta.xml
<CustomObject>
    <label>Fiscal Year</label>
    <nameField>
        <label>Fiscal Year Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fiscal Years</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource_Role__c/Resource_Role__c.object-meta.xml
<CustomObject>
    <label>Resource Role</label>
    <nameField>
        <label>Resource Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resource Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource_Role__c/fields/Eligible_for_Nominations__c.field-meta.xml
<CustomField>
    <fullName>Eligible_for_Nominations__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Eligible for Nominations ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Resource_Role__c/fields/Eligible_for_Recognise__c.field-meta.xml
<CustomField>
    <fullName>Eligible_for_Recognise__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Eligible for Recognise ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Reward_And_Recognition__c/Reward_And_Recognition__c.object-meta.xml
<CustomObject>
    <label>Reward And Recognition</label>
    <nameField>
        <displayFormat>REC{0000000}</displayFormat>
        <label>Nominee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rewards And Recognitions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reward_And_Recognition__c/fields/Award_Type__c.field-meta.xml
<CustomField>
    <fullName>Award_Type__c</fullName>
    <label>Award Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Best Entrepreneur</fullName>
            </value>
            <value>
                <fullName>Most Professional</fullName>
            </value>
            <value>
                <fullName>Rising Star</fullName>
            </value>
            <value>
                <fullName>Rock Star</fullName>
            </value>
            <value>
                <fullName>Service Awards</fullName>
            </value>
            <value>
                <fullName>Recognize</fullName>
            </value>
            <value>
                <fullName>Shout Out</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reward_And_Recognition__c/fields/Fiscal_Year__c.field-meta.xml
<CustomField>
    <fullName>Fiscal_Year__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fiscal Year</label>
    <referenceTo>Fiscal_Year__c</referenceTo>
    <relationshipLabel>Rewards And Recognitions</relationshipLabel>
    <relationshipName>Rewards_And_Recognitions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reward_And_Recognition__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>EMS_TM_Project__c.EMS_TM_Status__c</field>
            <operation>equals</operation>
            <value>Ongoing</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>EMS_TM_Project__c</referenceTo>
    <relationshipLabel>Rewards And Recognitions</relationshipLabel>
    <relationshipName>Rewards_And_Recognitions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reward_And_Recognition__c/fields/Reason_for_award__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_award__c</fullName>
    <label>Reason for award</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Reward_And_Recognition__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <label>Resource</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Rewards And Recognitions</relationshipLabel>
    <relationshipName>Rewards_And_Recognitions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reward_And_Recognition__c/recordTypes/Nominations.recordType-meta.xml
<RecordType>
    <fullName>Nominations</fullName>
    <active>true</active>
    <label>Nominations</label>
</RecordType>

force-app/main/default/objects/Reward_And_Recognition__c/recordTypes/Winners.recordType-meta.xml
<RecordType>
    <fullName>Winners</fullName>
    <active>true</active>
    <label>Winners</label>
</RecordType>

force-app/main/default/classes/RRController.cls
public without sharing class RRController {
public static final Id RR_WINNER_RECORDTYPEID = Schema.SObjectType.Reward_And_Recognition__c.getRecordTypeInfosByDeveloperName().get('Winners').getRecordTypeId();
public static final Id RR_NOMINATION_RECORDTYPEID = Schema.SObjectType.Reward_And_Recognition__c.getRecordTypeInfosByDeveloperName().get('Nominations').getRecordTypeId();
   
@AuraEnabled(cacheable=true)
    public static datawrapper getTheCurrentRRTrends(){
        user urecord = [SELECT Id,ContactId,Contact.Resource_Role__r.Eligible_for_Recognise__c,Contact.Resource_Role__r.Eligible_for_Nominations__c FROM User WHERE Id=:Userinfo.getUserId()];
        Boolean disableNom = true;
        Boolean disableRec = true;
                          
        if(urecord.Contact.Resource_Role__r.Eligible_for_Nominations__c){
            if(Boolean.valueOf(Label.Enable_Nominations)){
                disableNom = false;
            } 
        }
        if(urecord.Contact.Resource_Role__r.Eligible_for_Recognise__c){
            disableRec = false;
        }
        
        Map<String,String> fyMap = new Map<String,String>();
        Id currentFY;
        String currentFYName;
        Date currentdate = system.today();
        Map<String,List<Reward_And_Recognition__c>> FywithNominations = new Map<String,List<Reward_And_Recognition__c>>();
        List<winnerdetails> currentList = new List<winnerdetails>();
        
        for(Fiscal_Year__c fy : [SELECT Id,Name,Start_Date__c,End_Date__c FROM Fiscal_Year__c Order BY Start_Date__c ASC]){
            if(fy.Start_Date__c <= currentdate && fy.End_Date__c >= currentdate){
               currentFY = fy.Id;
               currentFYName = fy.Id;
            }
            fyMap.put(fy.Name,fy.Id);
        }
        
        for(Reward_And_Recognition__c rr : [SELECT Id,Name,Resource__r.Name,Resource__r.EMS_TM_User__c,Reason_for_award__c,Resource__r.EMS_TM_User__r.FullPhotoUrl,
                                            Resource__c,Award_Type__c,Fiscal_Year__c,Project__c,RecordTypeId,Fiscal_Year__r.Name,
                                            Comments__c FROM Reward_And_Recognition__c 
                                            WHERE RecordTypeId =:RR_WINNER_RECORDTYPEID
                                            AND Fiscal_Year__c IN:fyMap.values()]){
            if(currentFY == rr.Fiscal_Year__c){
                winnerdetails wd = new winnerdetails();
                wd.awardType = rr.Award_Type__c;
                 wd.currentFYName = rr.Fiscal_Year__r.Name;
                 wd.resourceName = rr.Resource__r.Name;
                 wd.resourcePhotoURL = rr.Resource__r.EMS_TM_User__r.FullPhotoUrl;
                 wd.awardComments = rr.Reason_for_award__c;
                wd.resourceId = rr.Resource__c;
            currentList.add(wd);
            }
            if(FywithNominations.containsKey(rr.Fiscal_Year__c)){
                FywithNominations.get(rr.Fiscal_Year__c).add(rr);
            }else{
                FywithNominations.put(rr.Fiscal_Year__c,new List<Reward_And_Recognition__c>{rr});  
            }
        }
        datawrapper dwrap = new datawrapper();
        dwrap.disableNominations = disableNom;
        dwrap.disableRecognize = disableRec;
        dwrap.currentFYId = currentFY;
        dwrap.currentName = currentFYName;
        dwrap.fyListMap = fyMap;
        dwrap.currentList = currentList;
        dwrap.FywithNominations = FywithNominations;
        return dwrap;
    }
    
    public class datawrapper {
        @AuraEnabled
        public boolean disableNominations;
        @AuraEnabled
        public boolean disableRecognize;
        @AuraEnabled
        public String currentFYId;
        @AuraEnabled
        public String currentName;
        @AuraEnabled
        public Map<String,String> fyListMap;
        @AuraEnabled
        public List<winnerdetails> currentList;
        @AuraEnabled
        public Map<String,List<Reward_And_Recognition__c>> FywithNominations;
    }
    
    public class winnerdetails{
        @AuraEnabled
        public String awardType;
        @AuraEnabled
        public String currentFYName;
        @AuraEnabled
        public String resourceName;
        @AuraEnabled
        public String resourcePhotoURL;
        @AuraEnabled
        public String awardComments;
         @AuraEnabled
        public String resourceId;
    }

}