force-app/main/default/objects/Contact/fields/EMS_LM_No_Of_Availble_Leaves__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_No_Of_Availble_Leaves__c</fullName>
    <formula>EMS_LM_No_Of_Leaves_Credit__c - EMS_LM_No_Of_Utilized_Leaves__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>No Of Availble Leaves</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_History__c/EMS_LM_Leave_History__c.object-meta.xml
<CustomObject>
    <description>It will show the employee Leave and WFH Requests.</description>
    <label>Leave Request</label>
    <nameField>
        <displayFormat>LH-{00000}</displayFormat>
        <label>Leave History Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leaves Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_LM_Leave_History__c/fields/EMS_LM_Contact__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Leaves History</relationshipLabel>
    <relationshipName>Leaves_History</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_History__c/fields/EMS_LM_Leave_End_Date__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Leave_End_Date__c</fullName>
    <label>Leave End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_History__c/fields/EMS_LM_Leave_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Leave_Start_Date__c</fullName>
    <label>Leave Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_History__c/fields/EMS_LM_Status__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Approver 2 Pending</fullName>
            </value>
            <value>
                <fullName>Approver 1 Pending</fullName>
            </value>
            <value>
                <fullName>Auto Approved</fullName>
            </value>
            <value>
                <fullName>Waiting For Approver 3</fullName>
                <isActive>false</isActive>
                <label>Waiting For Approver 3</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/ContactId__c.field-meta.xml
<CustomField>
    <fullName>ContactId__c</fullName>
    <formula>ContactId</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ContactId</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Hr_Access__c.field-meta.xml
<CustomField>
    <fullName>Hr_Access__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Hr Access</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/LeaveManagementApexController.cls
/**
* @author Pavan
* @date 10/01/2023
* @description  Getting the latest 5 Leave Request data based on the loggedIn user.
*            
*
*               Test code coverage provided by the following test class:
*               - LeaveRequestApexControllerTest
*
* CHANGE HISTORY
* ====================================================================================================
* DATE          NAME                    DESCRIPTION
* N/A           N/A                     N/A
* ====================================================================================================
**/
public Without Sharing class LeaveManagementApexController {
    /**
*   {Purpose} - Method used to display latest 5 leave request data based on the loggedIn User.
*
*   CHANGE HISTORY
*   ====================================================================================================
*   Date        Name                    Description
*   N/A         N/A                     N/A
*   ====================================================================================================
**/
    @AuraEnabled(Cacheable=true)
    public static List<EMS_LM_Leave_History__c> getLeaveRequest(){
        User usrConId = [SELECT Id, ContactId__c,Hr_Access__c FROM User WHERE Id =: LeaveRequestConstant.LOGGEDIN_USERID];
        List<EMS_LM_Leave_History__c> leaveReqList = [SELECT Id,
                                                            EMS_LM_Contact__c,
                                                            EMS_LM_Leave_Start_Date__c,
                                                            EMS_LM_Leave_End_Date__c,
                                                            CreatedDate,
                                                            EMS_LM_Status__c
                                                      FROM EMS_LM_Leave_History__c
                                                      WHERE EMS_LM_Contact__c =:usrConId.ContactId__c
                                                      ORDER BY CreatedDate DESC  LIMIT 5];
        return leaveReqList;
    }

/**
*   {Purpose} - Method used to display ALL leave request data to HR.
*
*   CHANGE HISTORY
*   ====================================================================================================
*   Date        Name                    Description
*   N/A         N/A                     N/A
*   ====================================================================================================
**/
    @AuraEnabled(Cacheable=true)
    public static List<EMS_LM_Leave_History__c> getLeaveRequestHr(){
        List<EMS_LM_Leave_History__c> leaveReqListHr = [SELECT Id,
                                                                EMS_LM_Contact__c,
                                                                EMS_LM_Leave_Start_Date__c,
                                                                EMS_LM_Leave_End_Date__c,
                                                                CreatedDate,
                                                                EMS_LM_Status__c
                                                      FROM EMS_LM_Leave_History__c
                                                      ORDER BY CreatedDate ];
        return leaveReqListHr;
    }
    /**
*   {Purpose} - Method used to display current leave balance based upon loggedIn user.
*
*   CHANGE HISTORY
*   ====================================================================================================
*   Date        Name                    Description
*   N/A         N/A                     N/A
*   ====================================================================================================
**/
    @AuraEnabled(Cacheable = true)
    public static Contact leaveBanlance(){
        User usrConId = [SELECT Id, ContactId FROM User WHERE Id =: LeaveRequestConstant.LOGGEDIN_USERID];
        List<Contact> empLeaveBalance = [SELECT Id,
                                          EMS_LM_No_Of_Availble_Leaves__c
                                   FROM Contact
                                   WHERE Id =:usrConId.ContactId LIMIT 1 ];
        return empLeaveBalance.isEmpty() ? null : empLeaveBalance[0];
    }
    
    /**
*   {Purpose} - Method used to handle the cancle leave request data based on the loggedIn user.
*
*   CHANGE HISTORY
*   ====================================================================================================
*   Date        Name                    Description
*   N/A         N/A                     N/A
*   ====================================================================================================
**/
    @AuraEnabled
    public static void cancleLeaveRequest(String leaveReqCancelId) {
        System.debug('### leaveReqCancelId ' + leaveReqCancelId);
        List<EMS_LM_Leave_History__c> updateCancelLeaveReqList = new List<EMS_LM_Leave_History__c>();
        for(EMS_LM_Leave_History__c leaveReqcancle : [SELECT Id,
                                                             EMS_LM_Status__c
                                                      FROM EMS_LM_Leave_History__c
                                                      WHERE Id =:leaveReqCancelId
                                                   ]) {
                                                   		leaveReqcancle.EMS_LM_Status__c = LeaveRequestConstant.CANCELLED;
                                                        updateCancelLeaveReqList.add(leaveReqcancle);
                                                   } 
        
        System.debug('### Before updateCancelLeaveReqList  '+ updateCancelLeaveReqList);
        update updateCancelLeaveReqList;
        System.debug('### updateCancelLeaveReqList  '+ updateCancelLeaveReqList);
    }
}