force-app/main/default/objects/Contact/fields/EMS_TM_User__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Project__c/EMS_TM_Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_TM_Project__c/fields/Project_Manager__c.field-meta.xml
<CustomField>
    <fullName>Project_Manager__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Onshore Project Manager</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND (2 OR 3)</booleanFilter>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Resource</value>
        </filterItems>
        <filterItems>
            <field>Contact.Resource_Role__r.Name</field>
            <operation>equals</operation>
            <value>Sr Project Manager</value>
        </filterItems>
        <filterItems>
            <field>Contact.Resource_Role__r.Name</field>
            <operation>equals</operation>
            <value>Project Manager</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Timesheet_Record__c/EMS_TM_Timesheet_Record__c.object-meta.xml
<CustomObject>
    <label>Timesheet Line Items</label>
    <nameField>
        <displayFormat>TLI{00000000}</displayFormat>
        <label>Timesheet Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheet Records</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_TM_Timesheet_Record__c/fields/EMS_TM_Project__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>EMS_TM_Project__c</referenceTo>
    <relationshipLabel>Timesheet Records</relationshipLabel>
    <relationshipName>Timecard_Splits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Timesheet_Record__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saved</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Reassign</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/timesheetRecordApprovalProcess.cls
/**
    * @author Ramakrishna 
    * @date 24/01/2023
    * @description  timesheetRecordApprovalProcess to Send  TimesheetRecord  to related Project Manager for Approval.
    *
    *               Test code coverage provided by the following test class:
    *               - timesheetRecordApprovalProcessTest
    *
    * CHANGE HISTORY
    * ====================================================================================================
    * DATE          NAME                    DESCRIPTION
    * N/A           N/A                     N/A
    * ====================================================================================================
    **/
public class timesheetRecordApprovalProcess implements TriggerAction.AfterUpdate,TriggerAction.AfterInsert {
      /**
    * @author Ramakrishna
    * @date 24/01/2023
    * @description After Update 
    *
    * CHANGE HISTORY
    * ====================================================================================================
    * DATE          NAME                    DESCRIPTION
    * N/A           N/A                     N/A
    * ====================================================================================================
    **/
    public void afterUpdate(List<EMS_TM_Timesheet_Record__c> newList,List<EMS_TM_Timesheet_Record__c> oldList) {      
        System.debug(LoggingLevel.DEBUG, 'submitAndProcessApprovalRequest.afterUpdate() : BEGIN');
        Map<id,EMS_TM_Timesheet_Record__c> timesheetOldMap = new Map<id,EMS_TM_Timesheet_Record__c>(oldList);
        submitAndProcessApprovalRequest(newList,timesheetOldMap);
        System.debug(LoggingLevel.DEBUG, 'submitAndProcessApprovalRequest.afterUpdate() : END');       
    }
    
   /**
    * @author Ramakrishna
    * @date 24/01/2023
    * @description After Insert 
    *
    * CHANGE HISTORY
    * ====================================================================================================
    * DATE          NAME                    DESCRIPTION
    * N/A           N/A                     N/A
    * ====================================================================================================
    **/
    
    public void afterInsert(List<EMS_TM_Timesheet_Record__c> newList) {      
        System.debug(LoggingLevel.DEBUG, 'submitAndProcessApprovalRequest.afterInsert() : BEGIN');
        submitAndProcessApprovalRequest(newList,Null);
        System.debug(LoggingLevel.DEBUG, 'submitAndProcessApprovalRequest.afterInsert() : END');       
    }
    /**
    * @author Ramakrishna
    * @date 24/01/2023
    * @description In this method we send timsheet record for approval for respective Manager 
    *
    * CHANGE HISTORY
    * ====================================================================================================
    * DATE          NAME                    DESCRIPTION
    * N/A           N/A                     N/A
    * ====================================================================================================
    **/
    public void submitAndProcessApprovalRequest(List<EMS_TM_Timesheet_Record__c> newList,Map<Id,EMS_TM_Timesheet_Record__c> oldMap) {
        Set<Id> projectIdsSet = new Set<Id>();
        Map<Id,EMS_TM_Timesheet_Record__c> projectRecMap = new Map<Id,EMS_TM_Timesheet_Record__c>();
        for(EMS_TM_Timesheet_Record__c timesheetRec: newList){
            if((oldMap != null && oldMap.get(timesheetRec.Id).Status__c != timesheetRec.Status__c && timesheetRec.Status__c != 'Saved' && timesheetRec.Status__c != 'Approved'  && timesheetRec.Status__c !='Rejected' && timesheetRec.Status__c != null ) || (oldmap ==null && timesheetRec.Status__c != 'Saved' && timesheetRec.Status__c != 'Approved'  && timesheetRec.Status__c !='Rejected' && timesheetRec.Status__c != null )){
                System.debug('If Passed');
                projectIdsSet.add(timesheetRec.EMS_TM_Project__c); 
                projectRecMap.put(timesheetRec.EMS_TM_Project__c,timesheetRec);                
            }           
        }
        Map<Id,EMS_TM_Timesheet_Record__c> timeSheetRecMap = new Map<Id,EMS_TM_Timesheet_Record__c>();
        System.debug('projectRecMap'+projectRecMap);
        
        for(EMS_TM_Project__c projectRec:[SELECT Id, 
                                                   Project_Manager__c 
                                                   FROM EMS_TM_Project__c 
                                                   WHERE Id IN:projectRecMap.keyset()]){
                                                       if(projectRec.Project_Manager__c !=null){
            timeSheetRecMap.put(projectRec.Project_Manager__c,projectRecMap.get(projectRec.Id));
                                                       }
        }
         System.debug('timeSheetRecMap'+timeSheetRecMap);
        for(contact contactRec:[SELECT Id,
                                         Ems_tm_user__c 
                                         FROM contact 
                                         WHERE Id IN:timeSheetRecMap.keySet()]){
            if(contactRec.Ems_tm_user__c != null){
                System.debug('contactRec.Ems_tm_user__c'+contactRec.Ems_tm_user__c);
                Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
                req1.setComments('Submitting request for approval.');
                req1.setObjectId(timeSheetRecMap.get(contactRec.Id).Id);
                System.debug('contactId'+timeSheetRecMap.get(contactRec.Id).Id+'>>>>>OwnerId'+timeSheetRecMap.get(contactRec.Id).OwnerId);
                req1.setSubmitterId(timeSheetRecMap.get(contactRec.Id).OwnerId);
                req1.setNextApproverIds(new Id[] {contactRec.EMS_TM_User__c});

                req1.setProcessDefinitionNameOrId('Timesheet_Records_Approval');
                req1.setSkipEntryCriteria(false);
                try{
               Approval.ProcessResult result = Approval.process(req1);
                }catch(Exception e){
                    System.debug('timesheetRecordApprovalProcess'+e.getMessage()+e.getLineNumber());
                     LogException.logHandledException(e, 'timesheetRecordApprovalProcess', 'submitAndProcessApprovalRequest');
                }               
            }
            
        }
        
    }    
}