force-app/main/default/objects/Contact/fields/EMS_TM_Billable__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Billable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Billable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_TM_User__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Assignment__c/EMS_TM_Assignment__c.object-meta.xml
<CustomObject>
    <label>Assignment</label>
    <nameField>
        <displayFormat>A.ID-{0000}</displayFormat>
        <label>Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_TM_Assignment__c/fields/Employee_Name__c.field-meta.xml
<CustomField>
    <fullName>Employee_Name__c</fullName>
    <formula>EMS_TM_EmployeeName__r.FirstName +&apos; &apos;+ EMS_TM_EmployeeName__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Employee Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Assignment__c/fields/EMS_TM_Billable__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Billable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Billable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Assignment__c/fields/EMS_TM_EmployeeName__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_EmployeeName__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Employee Name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Resource</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Assignments</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Assignment__c/fields/EMS_TM_EndDate_Asgn__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_EndDate_Asgn__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Assignment__c/fields/EMS_TM_ProjectName_Asgn__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_ProjectName_Asgn__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Name</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>EMS_TM_Project__c.Type_Of_Project__c</field>
            <operation>notEqual</operation>
            <value>Global Projects</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>EMS_TM_Project__c</referenceTo>
    <relationshipLabel>Project Assignees</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Assignment__c/fields/EMS_TM_StartDate_Asgn__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_StartDate_Asgn__c</fullName>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Assignment__c/fields/EMS_TM_Status_Asgn__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Status_Asgn__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <isActive>false</isActive>
                <label>Cancelled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EMS_TM_Project__c/EMS_TM_Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_TM_Project__c/fields/EMS_TM_EndDate__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_EndDate__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Project__c/fields/EMS_TM_StartDate__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_StartDate__c</fullName>
    <label>StartDate</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Project__c/fields/EMS_TM_Status__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ongoing</fullName>
                <default>true</default>
                <label>Ongoing</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Lead_Access__c.field-meta.xml
<CustomField>
    <fullName>Lead_Access__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Lead Access</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/GetProjectsController.cls
public class GetProjectsController {
    @AuraEnabled(cacheable=true)
    public static List<EMS_TM_Project__c> getProjects(){
        List<EMS_TM_Project__c> projectsList = new List<EMS_TM_Project__c>();
        Contact contactRecord = new Contact();
        List<EMS_TM_Assignment__c> leadAssignmentRecList = new List<EMS_TM_Assignment__c>();
        User currentUser =[SELECT Id, Lead_Access__c FROM User WHERE Lead_Access__c = true AND Id =: UserInfo.getUserId()];
        if(currentUser != null){
            contactRecord = [SELECT Id, EMS_TM_User__c FROM Contact WHERE EMS_TM_User__c =: currentUser.Id];
        }
        System.debug('-----contactRecord ---->'+contactRecord);
        Set<Id> teamLeadAssignmentIdSet = new Set<Id>();
        Set<Id> projectsId = new Set<Id>();
        if(contactRecord != null){
            
        for(EMS_TM_Assignment__c assignRec : [SELECT Id,
                                              EMS_TM_ProjectName_Asgn__c,
                                              EMS_TM_EmployeeName__c,
                                              Employee_Name__c,
                                              EMS_TM_StartDate_Asgn__c,
                                              EMS_TM_EndDate_Asgn__c,
                                              EMS_TM_Status_Asgn__c
                                              FROM EMS_TM_Assignment__c
                                              WHERE EMS_TM_EmployeeName__c =: contactRecord.Id]){
                                                  teamLeadAssignmentIdSet.add(assignRec.Id);
                                                  projectsId.add(assignRec.EMS_TM_ProjectName_Asgn__c);
                                              } 
        }
        
        if(!projectsId.isEmpty()){
                     projectsList = [SELECT Id,Name,
                                            EMS_TM_Billable__c,
                                            EMS_TM_EndDate__c,
                                            EMS_TM_StartDate__c,
                                            EMS_TM_Status__c,
                                            (SELECT Id,Name,
                                                    EMS_TM_ProjectName_Asgn__c,
                                                    EMS_TM_EmployeeName__c,
                                                    Employee_Name__c,
                                                    EMS_TM_StartDate_Asgn__c,
                                                    EMS_TM_EndDate_Asgn__c,
                                                    EMS_TM_Status_Asgn__c
                                             FROM Assignments__r)
                                     FROM EMS_TM_Project__c 
                                     WHERE Id IN : projectsId];
        }
//){  
                                            //     projectsList.add(projectRec);
                                            //     leadAssignmentRecList.add(projectRec.Assignments__r);
                                            // }
        
        //System.debug('-----assignmentRecList ---->'+leadAssignmentRecList);
        
        
        
        System.debug('-----project List ---->'+projectsList);
        return projectsList;
    }
    
}