force-app/main/default/objects/Contact/fields/EMS_RM_ApplicantStatus_Update__c.field-meta.xml
<CustomField>
    <fullName>EMS_RM_ApplicantStatus_Update__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Offer rolled out</fullName>
            </value>
            <value>
                <fullName>Offer accepted</fullName>
            </value>
            <value>
                <fullName>Offer rejected</fullName>
            </value>
            <value>
                <fullName>Hired</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Did not join</fullName>
            </value>
            <value>
                <fullName>Active - Probation</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Notice Period</fullName>
            </value>
            <value>
                <fullName>ABSENT</fullName>
                <isActive>false</isActive>
                <label>ABSENT</label>
            </value>
            <value>
                <fullName>Docs received</fullName>
                <isActive>false</isActive>
                <label>Docs received</label>
            </value>
            <value>
                <fullName>Docs verified</fullName>
                <isActive>false</isActive>
                <label>Docs verified</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_RM_Employee_Id__c.field-meta.xml
<CustomField>
    <fullName>EMS_RM_Employee_Id__c</fullName>
    <label>Employee ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_TM_Billable__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Billable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Billable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Resource_Role__c.field-meta.xml
<CustomField>
    <fullName>Resource_Role__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Role</label>
    <referenceTo>Resource_Role__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Work_Location__c.field-meta.xml
<CustomField>
    <fullName>Work_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Location</label>
    <referenceTo>Office_Location__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Resource.recordType-meta.xml
<RecordType>
    <fullName>Resource</fullName>
    <active>true</active>
    <label>Resource</label>
</RecordType>

force-app/main/default/objects/EMS_TM_Assignment__c/EMS_TM_Assignment__c.object-meta.xml
<CustomObject>
    <label>Assignment</label>
    <nameField>
        <displayFormat>A.ID-{0000}</displayFormat>
        <label>Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_TM_Assignment__c/fields/EMS_TM_Billable__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Billable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Billable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Assignment__c/fields/EMS_TM_EmployeeName__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_EmployeeName__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Employee Name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Resource</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Assignments</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Assignment__c/fields/EMS_TM_ProjectName_Asgn__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_ProjectName_Asgn__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Name</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>EMS_TM_Project__c.Type_Of_Project__c</field>
            <operation>notEqual</operation>
            <value>Global Projects</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>EMS_TM_Project__c</referenceTo>
    <relationshipLabel>Project Assignees</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Assignment__c/fields/EMS_TM_StartDate_Asgn__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_StartDate_Asgn__c</fullName>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Project__c/EMS_TM_Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_TM_Project__c/fields/EMS_TM_EndDate__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_EndDate__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Project__c/fields/EMS_TM_StartDate__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_StartDate__c</fullName>
    <label>StartDate</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Project__c/fields/EMS_TM_Status__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ongoing</fullName>
                <default>true</default>
                <label>Ongoing</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EMS_TM_Project__c/fields/Project_Manager__c.field-meta.xml
<CustomField>
    <fullName>Project_Manager__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Onshore Project Manager</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND (2 OR 3)</booleanFilter>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Resource</value>
        </filterItems>
        <filterItems>
            <field>Contact.Resource_Role__r.Name</field>
            <operation>equals</operation>
            <value>Sr Project Manager</value>
        </filterItems>
        <filterItems>
            <field>Contact.Resource_Role__r.Name</field>
            <operation>equals</operation>
            <value>Project Manager</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Project__c/fields/Type_Of_Project__c.field-meta.xml
<CustomField>
    <fullName>Type_Of_Project__c</fullName>
    <label>Type of Project</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Client Projects</fullName>
            </value>
            <value>
                <fullName>Internal Projects</fullName>
            </value>
            <value>
                <fullName>Global Projects</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <label>Expense</label>
    <nameField>
        <displayFormat>EXP{000000}</displayFormat>
        <label>Expense Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense__c/fields/Billing_Currency__c.field-meta.xml
<CustomField>
    <fullName>Billing_Currency__c</fullName>
    <label>Billing Currency</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Expense_Amount__c.field-meta.xml
<CustomField>
    <fullName>Expense_Amount__c</fullName>
    <label>Expense Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Expense_Type__c.field-meta.xml
<CustomField>
    <fullName>Expense_Type__c</fullName>
    <label>Expense Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Airfare</fullName>
            </value>
            <value>
                <fullName>Business Meals</fullName>
            </value>
            <value>
                <fullName>Car Rental</fullName>
            </value>
            <value>
                <fullName>Certification</fullName>
            </value>
            <value>
                <fullName>Employee Relations</fullName>
            </value>
            <value>
                <fullName>Gasoline</fullName>
            </value>
            <value>
                <fullName>General and Admin Expenses</fullName>
            </value>
            <value>
                <fullName>IT Equipment and Services</fullName>
            </value>
            <value>
                <fullName>Lodging (Room and Tax)</fullName>
            </value>
            <value>
                <fullName>Miscellaneous</fullName>
            </value>
            <value>
                <fullName>Office Supplies and Services</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Personal Meals</fullName>
            </value>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>Postage and Shipping</fullName>
            </value>
            <value>
                <fullName>Recruiting</fullName>
            </value>
            <value>
                <fullName>Taxi</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>EMS_TM_Project__c</referenceTo>
    <relationshipLabel>Expenses</relationshipLabel>
    <relationshipName>Expenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Expenses</relationshipLabel>
    <relationshipName>Expenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/project_manager__c.field-meta.xml
<CustomField>
    <fullName>project_manager__c</fullName>
    <label>Project Manager</label>
    <relationshipName>Users</relationshipName>
    <restrictedAdminField>true</restrictedAdminField>
    <type>Hierarchy</type>
</CustomField>

force-app/main/default/classes/myExpenseControllerTest.cls
@Istest
public class myExpenseControllerTest {

    /*public static void getMyExpenseRepo(){
        user adminuser;
        System.runAs ( new User(Id = UserInfo.getUserId()) ) {
            user adminuser2 = TestDataFactory.createAdminUser(true);
          adminuser = TestDataFactory.createAdminUser(true);
        }
        EMS_LM_Leave__c annualtype = TestDataFactory.createLeaveType('Annual Leave',true);
        EMS_LM_Leave__c loptype = TestDataFactory.createLeaveType('Loss of Pay',true);
        EMS_LM_Leave__c bretype = TestDataFactory.createLeaveType('Maternity Leave',true);
        EMS_LM_Leave__c compofftype = TestDataFactory.createLeaveType('Compensatory Off',true);
        EMS_LM_Leave__c workfromhome = TestDataFactory.createLeaveType('Work From Home',true);
        EMS_LM_Leave__c paidTimeOff = TestDataFactory.createLeaveType('Paid time off',true);
        Office_Location__c officlocRec =TestDataFactory.createOfficeLocation('Hhyderabad',true);
        account acc=Testdatafactory.createAccount(True);
        
        Contact con2=  TestDataFactory.createResourceContact(acc.id, false);
        con2.EMS_RM_Employee_Id__c = 'CP10236';
        //con2.Resource_Role__c = role.Id;
         //con2.ReportsToId=adminuser2.contactId;
        con2.EMS_RM_ApplicantStatus_Update__c='active';
        con2.Email = 'testEmail+test1@cloudperitus1.com';
        con2.Work_Location__c=officlocRec.Id;
        insert con2;
        
      // system.debug('userid==================================='+userid);
        EMS_TM_Project__c projectRec = new EMS_TM_Project__c();
        projectRec.EMS_TM_StartDate__c = System.today();
        projectRec.EMS_TM_EndDate__c = System.today()+10;
        projectRec.EMS_TM_Status__c = 'ongoing';
        projectRec.Name = 'project1';
        projectRec.Project_Manager__c = con2.Id;
        projectRec.Type_Of_Project__c ='global Projects';
        INSERT projectRec;
        EMS_TM_Project__c projectRec1 = new EMS_TM_Project__c();
        projectRec1.EMS_TM_StartDate__c = System.today();
        projectRec1.EMS_TM_EndDate__c = System.today()+11;
        projectRec1.EMS_TM_Status__c = 'ongoing';
        projectRec1.Name = 'project3';
        projectRec1.Project_Manager__c = con2.Id;
        projectRec1.Type_Of_Project__c ='global Projects';
        INSERT projectRec1;
        expense__c exp=new expense__c();
        exp.Resource__c=con2.Id;
        exp.Project__c=projectRec.Id;
        exp.Expense_Type__c='Certification';
        exp.Expense_Amount__c=10000;
        exp.Status__c='Submitted';
        exp.Billing_Currency__c='INR';
        insert exp;
           system.runAs(adminuser){
             EMS_TM_Assignment__c assignmentRec = new EMS_TM_Assignment__c();
        assignmentRec.EMS_TM_EmployeeName__c = con2.Id;
        assignmentRec.EMS_TM_ProjectName_Asgn__c = projectRec.Id;
        assignmentRec.EMS_TM_StartDate_Asgn__c = system.today();
        assignmentRec.EMS_TM_Billable__c = true;
        assignmentRec.EMS_TM_AssignedAs__c='Administrator';
        assignmentRec.Project_Allocation__c=1;
               system.debug('EMS_TM_ProjectName_Asgn__c id iss========='+assignmentRec.EMS_TM_ProjectName_Asgn__c);
               system.debug('EMS_TM_ProjectName_Asgn__c id iss========='+assignmentRec.EMS_TM_EmployeeName__c);
        INSERT assignmentRec;
           }
             string getexpid= exp.Id;
            String base64 = EncodingUtil.base64Encode(Blob.valueOf('Test file contents'));
            String filename = 'TestFile.txt';
            
            
        try{
             myExpenseController.uploadFile(base64,filename,getexpid);
             myExpenseController.getMyExpenseReport();
        myExpenseController.updateAndGetData(exp.Id,'Submitted');
        myExpenseController.checkTheExpense(exp.Id);
        myExpenseController.updateforApproval(exp.Id,'Approved');
        
        //myExpenseController.getProjectsAssignedToLoggedInContact(con.Id);
        }catch(exception e){
            system.debug('error============='+e.getMessage());
        }
       
    } */
    public static testmethod void getMyExpenseReportTest(){
        user user;
             EMS_LM_Leave__c  annualtype = TestDataFactory.createLeaveType('Annual Leave',true);
            EMS_LM_Leave__c loptype = TestDataFactory.createLeaveType('Loss of Pay',true);
            EMS_LM_Leave__c bretype = TestDataFactory.createLeaveType('Maternity Leave',true);
            EMS_LM_Leave__c compofftype = TestDataFactory.createLeaveType('Compensatory Off',true);
            EMS_LM_Leave__c wfhtype = TestDataFactory.createLeaveType('Work From Home',true);
            EMS_LM_Leave__c paidTimeOff = TestDataFactory.createLeaveType('Paid time off',true);
          EMS_LM_Leave__c paidtimeof = TestDataFactory.createLeaveType('Paid time off',true);
               EMS_LM_Leave__c unpaidTimeOff = TestDataFactory.createLeaveType('UnPaid time off',true);
               EMS_LM_Leave__c floatingholiday = TestDataFactory.createLeaveType('Floating Holiday',true);
         Resource_Role__c role = TestDataFactory.createResourceRole(true);
        Account acc = TestDataFactory.createAccount(true);
         Contact contac=  TestDataFactory.createResourceContact(acc.id, false);
        contac.EMS_RM_Employee_Id__c = 'CP10234';
        contac.Resource_Role__c = role.Id;
        insert contac;
         
            
//            User u = Testdatafactory.createCommunityUserWithAccAndContact(acc.id,con.Id,true);
        
        Contact con2=  TestDataFactory.createResourceContact(acc.id, false);
        con2.EMS_RM_Employee_Id__c = 'CP10236';
        con2.Resource_Role__c = role.Id;
        con2.EMS_RM_ApplicantStatus_Update__c='active';
        con2.Email = 'testEmail+test1@cloudperitus1.com';
        con2.Work_Location__c=TestDataFactory.createOfficeLocation(true).Id;
        insert con2;
       EMS_TM_Project__c projectRec = new EMS_TM_Project__c();
        projectRec.EMS_TM_StartDate__c = System.today();
        projectRec.EMS_TM_EndDate__c = System.today()+10;
        projectRec.EMS_TM_Status__c = 'ongoing';
        projectRec.Name = 'project1';
        projectRec.Project_Manager__c = con2.Id;
        projectRec.Type_Of_Project__c ='global Projects';
        INSERT projectRec;
        EMS_TM_Project__c projectRec1 = new EMS_TM_Project__c();
        projectRec1.EMS_TM_StartDate__c = System.today();
        projectRec1.EMS_TM_EndDate__c = System.today()+12;
        projectRec1.EMS_TM_Status__c = 'ongoing';
        projectRec1.Name = 'project1';
        projectRec1.Project_Manager__c = con2.id;
        projectRec1.Type_Of_Project__c ='global Projects';
        INSERT projectRec1;
        expense__c exp=new expense__c();
        exp.Resource__c=con2.Id;
        exp.Amount1__c=100000;
        //exp.CreatedDate=System.now();
        exp.Reimbursed_Date__c=System.today()+1;
        exp.Project__c=projectRec.Id;
        exp.Expense_Type__c='Certification';
        exp.Expense_Amount__c=10000;
        exp.Status__c='Submitted';
        exp.Billing_Currency__c='INR';
        exp.is_Reimbursed__c=true;
        insert exp;
        expense__c exp1=new expense__c();
        exp1.Resource__c=con2.Id;
        exp1.Amount1__c=100000;
        //exp.CreatedDate=System.now();
        exp1.Reimbursed_Date__c=System.today()+1;
        exp1.Project__c=null;
        exp1.Expense_Type__c='Certification';
        exp1.Expense_Amount__c=10000;
        exp1.Status__c='Submitted';
        exp1.Billing_Currency__c='INR';
        exp1.is_Reimbursed__c=true;
        insert exp1;
        system.debug('the ===== ***'+exp);
            //  user userid=Userinfo.getUserId();
                User currentUser = [SELECT Id FROM User WHERE Profile.name ='System Administrator' AND IsActive =: TRUE LIMIT 1];

            system.runAs(currentUser){
       // User currentUser = [SELECT Id FROM User WHERE Profile.name ='System Administrator' AND IsActive =: TRUE LIMIT 1];
          contact contact=[select ID,Name from contact where EMS_RM_Employee_Id__c='CP10236'];
               Profile pf= [Select Id from profile where Name='Employee - Resource(Community)']; 
                             UserRole portalRole = [Select Id From UserRole Limit 1]; 
                String orgId=UserInfo.getOrganizationId(); 
                String dateString=String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','');
                    network network=[select id,name from network where Name='Grid'];
                 Integer RandomId=Integer.valueOf(Math.rint(Math.random()*1000000)); 
                String uniqueName=orgId+dateString+RandomId; 
                        contact con=new contact();
                         user=new User(firstname = 'ABC', 
                                 lastName = 'XYZ', 
                                 email = uniqueName + '@test' + orgId + '.org', 
                                 Username = uniqueName + '@test' + orgId + '.org', 
                                 EmailEncodingKey = 'ISO-8859-1', 
                                 Alias = uniqueName.substring(18, 23), 
                                 TimeZoneSidKey = 'America/Los_Angeles', 
                                 LocaleSidKey = 'en_US', 
                                 LanguageLocaleKey = 'en_US', 
                                 ProfileId = pf.Id, 
                                  contactid=contact.Id,
                                 Hr_Access__c =true,Manager_Access__c=True); 
                   insert user;
    }
            
        string getexpid= exp.Id;
            String base64 = EncodingUtil.base64Encode(Blob.valueOf('Test file contents'));
            String filename = 'TestFile.txt';
        system.debug('getexpid=================================='+getexpid);
        system.debug('base64=================================='+base64);
        system.debug('filename=================================='+filename);
        system.runAs(user){
            Test.startTest();
       
        myExpenseController.getMyExpenseReport();
        myExpenseController.updateAndGetData(exp.Id,'Submitted');
        myExpenseController.checkTheExpense(exp.Id);
        myExpenseController.updateforApproval(exp.Id,'Approved');
        myExpenseController.getProjectsAssignedToLoggedInContact(con2.id);
            try{
                 myExpenseController.uploadFile(base64,filename,getexpid);
            }catch(exception e){
                system.debug('error======='+e.getMessage());
            }
        Test.stopTest(); 
        }
    }
       

    }