force-app/main/default/objects/Contact/fields/EMS_EM_JD__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_JD__c</fullName>
    <label>Date of Joining</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>EMS_Phone_Number__c</fullName>
    <label>Contact Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_RM_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>EMS_RM_Phone_Number__c</fullName>
    <label>Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_TM_User__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Official_Mail__c.field-meta.xml
<CustomField>
    <fullName>Official_Mail__c</fullName>
    <label>Official Email ID(old)</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Resource.recordType-meta.xml
<RecordType>
    <fullName>Resource</fullName>
    <active>true</active>
    <label>Resource</label>
</RecordType>

force-app/main/default/classes/EMS_TM_ContactuserUpdateTest.cls
@istest
public class EMS_TM_ContactuserUpdateTest {
     @testSetup
    public static void  contactUpdate(){
        Account acc = new Account();
        acc.Name ='rama';
        acc.Phone='96529015';
      //  acc.IsCustomerPortal = true;
        insert acc;
        System.debug('acc'+acc);
        Contact con = new contact();
        con.Email ='ramakrishna@gmail.com';
        con.AccountId = acc.id;
        con.FirstName ='rama111';
        con.LastName ='krishna11';
        con.EMS_Phone_Number__c ='965210752';
        con.EMS_RM_Phone_Number__c ='9652901075';
        con.RecordTypeId = [SELECT Id FROM RecordType where name = 'Resource'].Id;
        con.EMS_EM_JD__c = system.today();
        insert con;
          System.debug('con'+con);
        
    }
    
    public static testmethod void chaneuser(){
        contact con = [Select id,FirstName from Contact where FirstName ='rama111'];
        System.debug('con'+con);
        Account a =[Select id,name  from Account where name ='rama'];
        System.debug('a'+a);
            test.startTest();
         Profile p = [Select id from profile where name='TM Customer Community'];
         User u = new User(Alias = 'Rk0', Email='Ramauser@testmethod.com', 
                          EmailEncodingKey='UTF-8', LastName='Testing111',FirstName = 'one', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = p.Id, 
                          TimeZoneSidKey='America/Los_Angeles', UserName='standarduser@testuser.com', 
                           IsActive = true ,ContactId=con.id );   /*,UserType ='CspLitePortal' AccountId =a.Id*/        
        insert u;
        System.debug('u'+u);  
          test.stopTest();
        user uu =[Select id,lastname from user where lastname ='Testing111'];
        System.debug('uu'+uu);
        contact con1 = [Select id,FirstName,EMS_TM_User__c,Official_Mail__c from Contact where FirstName ='rama111'];
        con1.Official_Mail__c ='rk@rk.com';
        update con1;
     //    Contact c =[SELECT Id, FirstName, EMS_TM_User__c FROM Contact where EMS_TM_User__c =: uu.id];
         System.debug('c'+con1);
        
        //System.assertEquals(uu.id, con1.EMS_TM_User__c);
    }

}