force-app/main/default/objects/Contact/fields/EMS_RM_ApplicantStatus_Update__c.field-meta.xml
<CustomField>
    <fullName>EMS_RM_ApplicantStatus_Update__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Offer rolled out</fullName>
            </value>
            <value>
                <fullName>Offer accepted</fullName>
            </value>
            <value>
                <fullName>Offer rejected</fullName>
            </value>
            <value>
                <fullName>Hired</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Did not join</fullName>
            </value>
            <value>
                <fullName>Active - Probation</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Notice Period</fullName>
            </value>
            <value>
                <fullName>ABSENT</fullName>
                <isActive>false</isActive>
                <label>ABSENT</label>
            </value>
            <value>
                <fullName>Docs received</fullName>
                <isActive>false</isActive>
                <label>Docs received</label>
            </value>
            <value>
                <fullName>Docs verified</fullName>
                <isActive>false</isActive>
                <label>Docs verified</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_RM_Employee_Id__c.field-meta.xml
<CustomField>
    <fullName>EMS_RM_Employee_Id__c</fullName>
    <label>Employee ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Resource_Role__c.field-meta.xml
<CustomField>
    <fullName>Resource_Role__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Role</label>
    <referenceTo>Resource_Role__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Timesheet_NoNeed__c.field-meta.xml
<CustomField>
    <fullName>Timesheet_NoNeed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Timesheet NoNeed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave__c/EMS_LM_Leave__c.object-meta.xml
<CustomObject>
    <description>Used to store types of Leaves available in Organization</description>
    <label>Leave Type</label>
    <nameField>
        <label>Leave Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leave Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_TM_Project__c/EMS_TM_Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_TM_Project__c/fields/Project_Manager__c.field-meta.xml
<CustomField>
    <fullName>Project_Manager__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Onshore Project Manager</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND (2 OR 3)</booleanFilter>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Resource</value>
        </filterItems>
        <filterItems>
            <field>Contact.Resource_Role__r.Name</field>
            <operation>equals</operation>
            <value>Sr Project Manager</value>
        </filterItems>
        <filterItems>
            <field>Contact.Resource_Role__r.Name</field>
            <operation>equals</operation>
            <value>Project Manager</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contract_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Start_Date__c</fullName>
    <label>Contract Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project_Manager__c.field-meta.xml
<CustomField>
    <fullName>Project_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Resource_Role__c/Resource_Role__c.object-meta.xml
<CustomObject>
    <label>Resource Role</label>
    <nameField>
        <label>Resource Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resource Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/createProjectAfterOppWonTest.cls
@isTest
public class createProjectAfterOppWonTest {
    public static testmethod void oppclosedcreateProj(){
         Resource_Role__c role = TestDataFactory.createResourceRole(false);
         role.Name ='Sr Project Manager';
        insert role;
         EMS_LM_Leave__c annualtype = TestDataFactory.createLeaveType('Annual Leave',true);
        EMS_LM_Leave__c loptype = TestDataFactory.createLeaveType('Loss of Pay',true);
        EMS_LM_Leave__c bretype = TestDataFactory.createLeaveType('Maternity Leave',true);
        EMS_LM_Leave__c compofftype = TestDataFactory.createLeaveType('Compensatory Off',true);
        EMS_LM_Leave__c workfromhome = TestDataFactory.createLeaveType('Work From Home',true);
          EMS_LM_Leave__c paidtimeof = TestDataFactory.createLeaveType('Paid time off',true);
               EMS_LM_Leave__c unpaidTimeOff = TestDataFactory.createLeaveType('UnPaid time off',true);
               EMS_LM_Leave__c floatingholiday = TestDataFactory.createLeaveType('Floating Holiday',true);
         Account acc = TestDataFactory.createAccount(true);
		 Contact con=  TestDataFactory.createResourceContact(acc.id, false);
         con.EMS_RM_Employee_Id__c = 'CP10235';
         con.EMS_RM_ApplicantStatus_Update__c ='Active';
         con.Timesheet_NoNeed__c =false;
         con.Resource_Role__c = role.Id;
         INSERT con;
        Integer count =1;
        List<Opportunity> oppList =TestDataFactory.createOpportunity(acc.id,count,false);
       Date newDate = System.today();
       Date futureDate = myDate.addDays(5);
        oppList[0].Project_Manager__c =con.Id;
        oppList[0].Contract_Start_Date__c = System.today();
          oppList[0].ACV__c='Yes';
            oppList[0].Lead_Generation__c='referral';
            oppList[0].Identify_Target_Market__c='Advisory Services';
            oppList[0].Final_Agreement_Date__c=system.today();
            oppList[0].Expected_Kick_off_Date__c=futureDate;
        INSERT oppList;
        
        test.startTest();
        Opportunity opp =[SELECT Id, StageName FROM Opportunity LIMIT 1];
        opp.StageName ='Closed Won';
        UPDATE opp;
        test.stopTest();
        
       List<EMS_TM_Project__c> projectRec =[SELECT Id FROM EMS_TM_Project__c WHERE Opportunity__c =:opp.Id];
        System.assertEquals(1, projectRec.size());
    }

}