force-app/main/default/objects/Contact/fields/EMS_TM_Billable__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Billable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Billable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_TM_In_Billing__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_In_Billing__c</fullName>
    <defaultValue>false</defaultValue>
    <label>In Billing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Official_Mail__c.field-meta.xml
<CustomField>
    <fullName>Official_Mail__c</fullName>
    <label>Official Email ID(old)</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Assignment__c/EMS_TM_Assignment__c.object-meta.xml
<CustomObject>
    <label>Assignment</label>
    <nameField>
        <displayFormat>A.ID-{0000}</displayFormat>
        <label>Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_TM_Assignment__c/fields/EMS_TM_Billable__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Billable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Billable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Assignment__c/fields/EMS_TM_EmployeeName__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_EmployeeName__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Employee Name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Resource</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Assignments</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Assignment__c/fields/EMS_TM_Status_Asgn__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Status_Asgn__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <isActive>false</isActive>
                <label>Cancelled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/enableAndDisableBillableOnContact.cls
/**
    * @author RK & SAI
    * @date 10/01/2023
    * @description  enableAndDisableBillableOnContact to check the Active & Billable  on assignments for Employees at the time of craete or update any  
    *               record then update the Contact and inbilling check box will be true.
    *
    *               Test code coverage provided by the following test class:
    *               - enableAndDisableBillableOnContactTest
    *
    * CHANGE HISTORY
    * ====================================================================================================
    * DATE          NAME                    DESCRIPTION
    * N/A           N/A                     N/A
    * ====================================================================================================
    **/
public without sharing class enableAndDisableBillableOnContact implements TriggerAction.AfterUpdate,TriggerAction.AfterInsert{
    /**
    * @author RK & SAI
    * @date 10/01/2023 
    * @description After Update 
    *
    * CHANGE HISTORY
    * ====================================================================================================
    * DATE          NAME                    DESCRIPTION
    * N/A           N/A                     N/A
    * ====================================================================================================
    **/
    public void afterUpdate(List<EMS_TM_Assignment__c> newList,List<EMS_TM_Assignment__c> oldList) {      
        System.debug(LoggingLevel.DEBUG, 'enableAndDisableBillableOnContact.afterUpdate() : BEGIN');
        Map<id,EMS_TM_Assignment__c> assignmentOldMap = new Map<id,EMS_TM_Assignment__c>(oldList);
        enableAndDisableBillable(newList,assignmentOldMap);
        System.debug(LoggingLevel.DEBUG, 'enableAndDisableBillableOnContact.afterUpdate() : END');       
    }
    
   /**
    * @author RK & SAI
    * @date 10/01/2023
    * @description After Insert 
    *
    * CHANGE HISTORY
    * ====================================================================================================
    * DATE          NAME                    DESCRIPTION
    * N/A           N/A                     N/A
    * ====================================================================================================
    **/
    
    public void afterInsert(List<EMS_TM_Assignment__c> newList) {      
        System.debug(LoggingLevel.DEBUG, 'enableAndDisableBillableOnContact.afterInsert() : BEGIN');
        enableAndDisableBillable(newList,Null);
        System.debug(LoggingLevel.DEBUG, 'enableAndDisableBillableOnContact.afterInsert() : END');       
    }
    
    /**
    *   {Purpose} - Method to check the Active & Billable  on assignments for Employees at the time of craete or update any  
    *               record then update the Contact and inbilling check box will be true. 
    *
    *   CHANGE HISTORY
    *   ====================================================================================================
    *   Date        Name                    Description
    *   N/A         N/A                     N/A
    *   ====================================================================================================
    **/
        
    private void enableAndDisableBillable(List<EMS_TM_Assignment__c> newAssignment,Map<Id,EMS_TM_Assignment__c> oldMap){

        Set<id> contactIds = new Set<id>();
        for(EMS_TM_Assignment__c assignRec: newAssignment){
            if((oldMap != null && (oldMap.get(assignRec.id).EMS_TM_Status_Asgn__c != assignRec.EMS_TM_Status_Asgn__c || oldMap.get(assignRec.id).EMS_TM_Billable__c != assignRec.EMS_TM_Billable__c)) || oldmap ==null ){
                contactIds.add(assignRec.EMS_TM_EmployeeName__c);                
            }
        }
        Set<Id> updatedAssignmentContactIds  = new Set<Id>();
        for(EMS_TM_Assignment__c assignRecord : [SELECT id,
                                                          EMS_TM_EmployeeName__c,
                                                          EMS_TM_Status_Asgn__c,
                                                          EMS_TM_Billable__c 
                                                          FROM EMS_TM_Assignment__c 
                                                          WHERE EMS_TM_Status_Asgn__c = 'Active' 
                                                          AND EMS_TM_Billable__c = true 
                                                          AND EMS_TM_EmployeeName__c IN : contactIds]){                                                            
                                                            updatedAssignmentContactIds.add(assignRecord.EMS_TM_EmployeeName__c);                                                                                                                
                                                         }
        list<contact> updatedConList = new list<contact>();
        for(contact contactRec :[SELECT Id, 
                                          Official_Mail__c, 
                                          EMS_TM_In_Billing__c 
                                          FROM Contact 
                                          WHERE id IN:contactIds ]){                                     
                                             if (updatedAssignmentContactIds.contains(contactRec.Id)){                                           
                                                 contactRec.EMS_TM_In_Billing__c = true;                                                
                                             }
                                             else{                                                
                                                 contactRec.EMS_TM_In_Billing__c = false ;
                                             }                                             
                                             updatedConList.add(contactRec);
                               		  	  }
                                           try{
                                                    if(!updatedConList.isEmpty()){
                                                        update updatedConList;
                                                    }
                                               }catch(Exception e){
                                                LogException.logHandledException(e, 'enableAndDisableBillableOnContact', 'enableAndDisableBillable');
                                               }
    }
    
}