force-app/main/default/objects/Contact/fields/EMS_TM_User__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Assignment__c/EMS_TM_Assignment__c.object-meta.xml
<CustomObject>
    <label>Assignment</label>
    <nameField>
        <displayFormat>A.ID-{0000}</displayFormat>
        <label>Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_TM_Assignment__c/fields/EMS_TM_EmployeeName__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_EmployeeName__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Employee Name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Resource</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Assignments</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Resource_Resource_Relationship__c/Resource_Resource_Relationship__c.object-meta.xml
<CustomObject>
    <label>Resource Relationship</label>
    <nameField>
        <displayFormat>RRR-{000000}</displayFormat>
        <label>Resource Resource Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource_Resource_Relationship__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <label>Resource</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Resource Relationships (Reports To)</relationshipLabel>
    <relationshipName>Resource_Resource_Relationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Resource_Resource_Relationship__c/fields/Resource_Reports_To__c.field-meta.xml
<CustomField>
    <fullName>Resource_Reports_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Reports To</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Relationships_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Resource_Resource_Relationship__c/fields/Resource_Reports_To_User__c.field-meta.xml
<CustomField>
    <fullName>Resource_Reports_To_User__c</fullName>
    <formula>Resource_Reports_To__r.EMS_TM_User__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Resource Reports To User</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AssignmentShare.cls
public class AssignmentShare {
    
    public static void assignemntSharetoLead(List<EMS_TM_Assignment__c> newList){
        Set<Id> contactIds = new Set<Id>();
        Map<Id,EMS_TM_Assignment__c> assignmentMap = new  Map<Id,EMS_TM_Assignment__c>();
        for(EMS_TM_Assignment__c assignrec : newList){
            assignmentMap.put(assignrec.EMS_TM_EmployeeName__c,assignrec);
        }
        SYstem.debug('assignmentMap'+assignmentMap);
        List<EMS_TM_Assignment__Share> assignShareRec = new List<EMS_TM_Assignment__Share>();
        for(Resource_Resource_Relationship__c rrrRecod:[SELECT Id, 
                                                        		Resource__c,
                                                        		Resource_Reports_To__c,
                                                                Resource_Reports_To__r.EMS_TM_user__c,
                                                                Resource_Reports_To_User__c
                                                        		FROM Resource_Resource_Relationship__c
                                                       			WHERE Resource__c IN:assignmentMap.keyset()]){
                                                System.debug('rrrRecod'+rrrRecod+'..........'+rrrRecod.Resource_Reports_To__r.EMS_TM_user__c);
                           EMS_TM_Assignment__Share assignmentShare = new EMS_TM_Assignment__Share();
                           assignmentShare.ParentId = assignmentMap.get(rrrRecod.Resource__c).Id;
                           assignmentShare.UserOrGroupId = '00552000007YXDRAA4';
                           assignmentShare.AccessLevel = 'Read';
                           assignShareRec.add(assignmentShare);                                                                                                                   
        }
         SYstem.debug('assignShareRec'+assignShareRec);
        try{
        if(!assignShareRec.IsEmpty()){
            insert assignShareRec;
            // Database.SaveResult[] jobShareInsertResult = Database.insert(assignShareRec,false);
        }
        }catch(Exception e){
            System.debug('assinmentshare'+e.getMessage());
        }
    }

}