force-app/main/default/objects/Contact/fields/EMS_LM_No_of_Bereavement_Leaves_Credit__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_No_of_Bereavement_Leaves_Credit__c</fullName>
    <label>No of Bereavement Leaves Credit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_LM_No_Of_Compensatory_Off_Credit__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_No_Of_Compensatory_Off_Credit__c</fullName>
    <label>No Of Compensatory Off Credit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_LM_No_Of_Leaves_Credit__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_No_Of_Leaves_Credit__c</fullName>
    <defaultValue>0</defaultValue>
    <label>No Of Annual Leaves Credit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_LM_No_Of_Maternity_Leaves_Credit__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_No_Of_Maternity_Leaves_Credit__c</fullName>
    <label>No Of Maternity Leaves Credit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_LM_No_Of_Paternity_Leaves_Credit__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_No_Of_Paternity_Leaves_Credit__c</fullName>
    <label>No of Paternity Leaves Credit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>EMS_Phone_Number__c</fullName>
    <label>Contact Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Official_Mail__c.field-meta.xml
<CustomField>
    <fullName>Official_Mail__c</fullName>
    <label>Official Email ID(old)</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_Credit__c/EMS_LM_Leave_Credit__c.object-meta.xml
<CustomObject>
    <description>To credit the Leaves to Employees as per Policies</description>
    <label>Leave Credit</label>
    <nameField>
        <displayFormat>LC-{00000}</displayFormat>
        <label>Leave Credit Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leave Credits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_LM_Leave_Credit__c/fields/EMS_LM_Employee__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Employee__c</fullName>
    <label>Employee</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Leave_Credits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_Credit__c/fields/EMS_LM_Leaves_Credited__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Leaves_Credited__c</fullName>
    <label>Leaves Credited</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_Credit__c/fields/EMS_LM_Select_Leave_Type__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Select_Leave_Type__c</fullName>
    <label>Select Leave Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Annual Leave</fullName>
            </value>
            <value>
                <fullName>Paternity Leave</fullName>
            </value>
            <value>
                <fullName>Bereavement Leave</fullName>
            </value>
            <value>
                <fullName>Loss of Pay</fullName>
            </value>
            <value>
                <fullName>Work from Home</fullName>
            </value>
            <value>
                <fullName>Maternity Leave</fullName>
            </value>
            <value>
                <fullName>Compensatory Off</fullName>
            </value>
            <value>
                <fullName>Paid time off</fullName>
            </value>
            <value>
                <fullName>UnPaid time off</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CalculateAvailableLeaveBalanceTest.cls
/**
* @author Eswar
* @date 11/01/2023
* @description This test class to calculate available leave balance of the employee 
*            
*
*               
* CHANGE HISTORY
* ====================================================================================================
* DATE          NAME                    DESCRIPTION
* N/A           N/A                     N/A
* ====================================================================================================
**/
@isTest
public class CalculateAvailableLeaveBalanceTest {
    @TestSetup static void setupData(){
        Contact contactRec = new Contact();
        contactRec.lastName = 'Test';
        contactRec.EMS_Phone_Number__c = '9898989898';
        contactRec.Official_Mail__c = null;
        contactRec.Email = 'test@gmail.com';
        contactRec.EMS_LM_No_Of_Leaves_Credit__c = 20;
        contactRec.EMS_LM_No_Of_Compensatory_Off_Credit__c = 1;
        contactRec.EMS_LM_No_Of_Maternity_Leaves_Credit__c = 120;
        contactRec.EMS_LM_No_of_Bereavement_Leaves_Credit__c = 2;
        contactRec.EMS_LM_No_Of_Paternity_Leaves_Credit__c = 4;
        insert contactRec;
    }
	public static testmethod void calculateAvailableLeaveBalanceAnnualLeaveTest(){
        
        Contact contactRec = [select id, lastName from Contact where lastName = 'Test'];
        
        Test.startTest();
        EMS_LM_Leave_Credit__C leavesCredit = new EMS_LM_Leave_Credit__C();
        leavesCredit.EMS_LM_Employee__c = contactRec.id;
        leavesCredit.EMS_LM_Leaves_Credited__c = 20;
        leavesCredit.EMS_LM_Select_Leave_Type__c = 'Annual Leave';
        insert leavesCredit;
        Test.stopTest();
        
        System.assertEquals([SELECT Id,EMS_LM_No_Of_Leaves_Credit__c FROM Contact].EMS_LM_No_Of_Leaves_Credit__c, 40);
		
    }
    
    public static testmethod void calculateAvailableLeaveBalanceCompensatoryOffTest(){
        
        Contact contactRec = [select id, lastName from Contact where lastName = 'Test'];
        
        Test.startTest();
        EMS_LM_Leave_Credit__C leavesCredit = new EMS_LM_Leave_Credit__C();
        leavesCredit.EMS_LM_Employee__c = contactRec.id;
        leavesCredit.EMS_LM_Leaves_Credited__c = 2;
        leavesCredit.EMS_LM_Select_Leave_Type__c = 'Compensatory Off';
        insert leavesCredit;
        Test.stopTest();
        
        System.assertEquals([SELECT Id,EMS_LM_No_Of_Compensatory_Off_Credit__c FROM Contact].EMS_LM_No_Of_Compensatory_Off_Credit__c, 3);

    }
    
    public static testmethod void calculateAvailableLeaveBalanceMaternityLeaveTest(){
        
        Contact contactRec = [select id, lastName from Contact where lastName = 'Test'];
        
        Test.startTest();
        EMS_LM_Leave_Credit__C leavesCredit = new EMS_LM_Leave_Credit__C();
        leavesCredit.EMS_LM_Employee__c = contactRec.id;
        leavesCredit.EMS_LM_Leaves_Credited__c = 182;
        leavesCredit.EMS_LM_Select_Leave_Type__c = 'Maternity Leave';
        insert leavesCredit;
        Test.stopTest();
        
        System.assertEquals([SELECT Id,EMS_LM_No_Of_Maternity_Leaves_Credit__c FROM Contact].EMS_LM_No_Of_Maternity_Leaves_Credit__c, 302);

    }
    
    public static testmethod void calculateAvailableLeaveBalanceBereavementLeaveTest(){
        
        Contact contactRec = [select id, lastName from Contact where lastName = 'Test'];
        
        Test.startTest();
        EMS_LM_Leave_Credit__C leavesCredit = new EMS_LM_Leave_Credit__C();
        leavesCredit.EMS_LM_Employee__c = contactRec.id;
        leavesCredit.EMS_LM_Leaves_Credited__c = 2;
        leavesCredit.EMS_LM_Select_Leave_Type__c = 'Bereavement Leave';
        insert leavesCredit;
        Test.stopTest();
        
        System.assertEquals([SELECT Id,EMS_LM_No_of_Bereavement_Leaves_Credit__c FROM Contact].EMS_LM_No_of_Bereavement_Leaves_Credit__c, 4);

    }
    
    public static testmethod void calculateAvailableLeaveBalancePaternityLeaveTest(){
        
        Contact contactRec = [select id, lastName from Contact where lastName = 'Test'];
        
        Test.startTest();
        EMS_LM_Leave_Credit__C leavesCredit = new EMS_LM_Leave_Credit__C();
        leavesCredit.EMS_LM_Employee__c = contactRec.id;
        leavesCredit.EMS_LM_Leaves_Credited__c = 5;
        leavesCredit.EMS_LM_Select_Leave_Type__c = 'Paternity Leave';
        insert leavesCredit;
        Test.stopTest();
        
        System.assertEquals([SELECT Id,EMS_LM_No_Of_Paternity_Leaves_Credit__c FROM Contact].EMS_LM_No_Of_Paternity_Leaves_Credit__c, 9);

    }
}