force-app/main/default/objects/Contact/fields/EMS_EM_DOB__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_DOB__c</fullName>
    <label>Date of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>EMS_Phone_Number__c</fullName>
    <label>Contact Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_RM_ApplicantStatus_Update__c.field-meta.xml
<CustomField>
    <fullName>EMS_RM_ApplicantStatus_Update__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Offer rolled out</fullName>
            </value>
            <value>
                <fullName>Offer accepted</fullName>
            </value>
            <value>
                <fullName>Offer rejected</fullName>
            </value>
            <value>
                <fullName>Hired</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Did not join</fullName>
            </value>
            <value>
                <fullName>Active - Probation</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Notice Period</fullName>
            </value>
            <value>
                <fullName>ABSENT</fullName>
                <isActive>false</isActive>
                <label>ABSENT</label>
            </value>
            <value>
                <fullName>Docs received</fullName>
                <isActive>false</isActive>
                <label>Docs received</label>
            </value>
            <value>
                <fullName>Docs verified</fullName>
                <isActive>false</isActive>
                <label>Docs verified</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_RM_Employee_Id__c.field-meta.xml
<CustomField>
    <fullName>EMS_RM_Employee_Id__c</fullName>
    <label>Employee ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Resource_Role__c.field-meta.xml
<CustomField>
    <fullName>Resource_Role__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Role</label>
    <referenceTo>Resource_Role__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave__c/EMS_LM_Leave__c.object-meta.xml
<CustomObject>
    <description>Used to store types of Leaves available in Organization</description>
    <label>Leave Type</label>
    <nameField>
        <label>Leave Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leave Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource_Role__c/Resource_Role__c.object-meta.xml
<CustomObject>
    <label>Resource Role</label>
    <nameField>
        <label>Resource Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resource Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/BatchToSendBirthdayWishesTest.cls
@isTest

public class BatchToSendBirthdayWishesTest {
    
      public static testMethod void testscheduleclass() {
		Test.StartTest();
		 BatchToSendBirthdayWishes_sch testsche = new BatchToSendBirthdayWishes_sch();
		 String sch = '0 0 23 * * ?';
		 system.schedule('Test BatchToSendBirthdayWishes', sch, testsche );
		Test.stopTest();
	}
        public testMethod static void testBatchclass() {
        
            user adminuser = TestDataFactory.createAdminUser(true);
            system.runAs(adminuser){
            Resource_Role__c role = TestDataFactory.createResourceRole(true);
            EMS_LM_Leave__c annualtype = TestDataFactory.createLeaveType('Annual Leave',true);
            EMS_LM_Leave__c loptype = TestDataFactory.createLeaveType('Loss of Pay',true);
            EMS_LM_Leave__c bretype = TestDataFactory.createLeaveType('Maternity Leave',true);
            EMS_LM_Leave__c compofftype = TestDataFactory.createLeaveType('Compensatory Off',true);
            EMS_LM_Leave__c workfromhome = TestDataFactory.createLeaveType('Work From Home',true);
            
            Date birthday = system.today();


            Account acc = TestDataFactory.createAccount(true);
		    Contact con=  TestDataFactory.createResourceContact(acc.id, false);
			con.EMS_RM_Employee_Id__c = 'CP10236';
            con.EMS_RM_ApplicantStatus_Update__c ='Active';
            con.EMS_Phone_Number__c ='1345635678';
            con.Email = 'Test@gmail.com';
         	con.EMS_EM_DOB__c = birthday;
         	con.RecordTypeId = ContactConstant.RESOURCE_RECORDTYPEID;
         	insert con;
      
         Test.startTest();
            List<Contact> conRec = [SELECT id, EMS_EM_DOB__c FROM Contact WHERE Email != NULL];
             BatchToSendBirthdayWishes batchExecute = new BatchToSendBirthdayWishes(); 
             Database.executeBatch(batchExecute,10);
             System.assertEquals(True,conRec.size()>0);
         Test.stopTest();
            
            }
        }
    }