force-app/main/default/objects/Contact/fields/EMS_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>EMS_Phone_Number__c</fullName>
    <label>Contact Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>USA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_History__c/EMS_LM_Leave_History__c.object-meta.xml
<CustomObject>
    <description>It will show the employee Leave and WFH Requests.</description>
    <label>Leave Request</label>
    <nameField>
        <displayFormat>LH-{00000}</displayFormat>
        <label>Leave History Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leaves Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_LM_Leave_History__c/fields/Approver_3__c.field-meta.xml
<CustomField>
    <fullName>Approver_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver 3</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Leaves_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_History__c/fields/EMS_LM_2nd_Approver__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_2nd_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>2nd Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Leaves_History1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_History__c/fields/EMS_LM_Approver__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Leaves_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_History__c/fields/EMS_LM_Contact__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Leaves History</relationshipLabel>
    <relationshipName>Leaves_History</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_History__c/fields/EMS_LM_Leave_Duration__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Leave_Duration__c</fullName>
    <label>Leave Duration</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_History__c/fields/EMS_LM_Leave_End_Date__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Leave_End_Date__c</fullName>
    <label>Leave End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_History__c/fields/EMS_LM_Leave_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Leave_Start_Date__c</fullName>
    <label>Leave Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_History__c/fields/EMS_LM_Reason__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Reason__c</fullName>
    <label>Reason</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_History__c/fields/EMS_LM_Status__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Approver 2 Pending</fullName>
            </value>
            <value>
                <fullName>Approver 1 Pending</fullName>
            </value>
            <value>
                <fullName>Auto Approved</fullName>
            </value>
            <value>
                <fullName>Waiting For Approver 3</fullName>
                <isActive>false</isActive>
                <label>Waiting For Approver 3</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LeaveRequestApexControllerTest.cls
/**
* @author Pavan 
* @date 11/01/2023
* @description  Method used to display leave request data based on the loggedIn approver user
*            
*
*               
* CHANGE HISTORY
* ====================================================================================================
* DATE          NAME                    DESCRIPTION
* N/A           N/A                     N/A
* ====================================================================================================
**/

@isTest
public class LeaveRequestApexControllerTest {
    @testSetup
    static void testDataSetup(){
        //Contact Data
        List<Contact> testConList = new List<Contact>();
        for (Integer i=0; i < 3; i++){
            contact testConData = new Contact(LastName = 'Test con' +i,
                                              Location__c = 'India',
                                              EMS_Phone_Number__c = '123647890',
                                              Email = 'test@gmail.com');
            testConList.add(testConData);
        }
        insert testConList;
        //Leave Request Data
        List<EMS_LM_Leave_History__c> testLeaveRequestPendingList = new List<EMS_LM_Leave_History__c>();
        List<EMS_LM_Leave_History__c> testLeaveRequestApprover2List = new List<EMS_LM_Leave_History__c>();
        List<EMS_LM_Leave_History__c> testLeaveRequestApprover3List = new List<EMS_LM_Leave_History__c>();
        for (Integer i = 0; i < 2; i++) {
            EMS_LM_Leave_History__c testLeaveRequest = new EMS_LM_Leave_History__c(EMS_LM_Contact__c = testConList[0].Id, 
                                                                                   EMS_LM_Reason__c = 'Test Reason'+i, 
                                                                                   EMS_LM_Leave_Start_Date__c = Date.today(), 
                                                                                   EMS_LM_Leave_End_Date__c = Date.today()+1, 
                                                                                   EMS_LM_Leave_Duration__c = 1,
                                                                                   EMS_LM_Approver__c = UserInfo.getUserId(), 
                                                                                   EMS_LM_2nd_Approver__c = UserInfo.getUserId(),
                                                                                   Approver_3__c = UserInfo.getUserId(),
                                                                                   EMS_LM_Status__c = 'Pending');
            testLeaveRequestPendingList.add(testLeaveRequest);
        }
        for (Integer i = 0; i < 2; i++) {
            EMS_LM_Leave_History__c testLeaveRequest = new EMS_LM_Leave_History__c(EMS_LM_Contact__c = testConList[1].Id, 
                                                                                   EMS_LM_Reason__c = 'Test Reason'+i, 
                                                                                   EMS_LM_Leave_Start_Date__c = Date.today(), 
                                                                                   EMS_LM_Leave_End_Date__c = Date.today()+3, 
                                                                                   EMS_LM_Leave_Duration__c = 3,
                                                                                   EMS_LM_Approver__c = UserInfo.getUserId(), 
                                                                                   EMS_LM_2nd_Approver__c = UserInfo.getUserId(),
                                                                                   Approver_3__c = UserInfo.getUserId(),
                                                                                   EMS_LM_Status__c = 'Waiting For Approver 2');
            testLeaveRequestApprover2List.add(testLeaveRequest);
        }
        for (Integer i = 0; i < 2; i++) {
            EMS_LM_Leave_History__c testLeaveRequest = new EMS_LM_Leave_History__c(EMS_LM_Contact__c = testConList[1].Id, 
                                                                                   EMS_LM_Reason__c = 'Test Reason'+i, 
                                                                                   EMS_LM_Leave_Start_Date__c = Date.today(), 
                                                                                   EMS_LM_Leave_End_Date__c = Date.today()+3, 
                                                                                   EMS_LM_Leave_Duration__c = 3,
                                                                                   EMS_LM_Approver__c = UserInfo.getUserId(), 
                                                                                   EMS_LM_2nd_Approver__c = UserInfo.getUserId(),
                                                                                   Approver_3__c = UserInfo.getUserId(),
                                                                                   EMS_LM_Status__c = 'Waiting For Approver 3');
            testLeaveRequestApprover3List.add(testLeaveRequest);
        }
        insert testLeaveRequestPendingList;
        insert testLeaveRequestApprover2List;
        insert testLeaveRequestApprover3List;
    }
    static testMethod void testGetLeaveReqData() {
        LeaveRequestApexController.LeaveRequestStatus result = LeaveRequestApexController.getLeaveReqData();
        System.assertEquals(result.pendingList.size(), 2, 'Failed in pendingList LeaveRequestApexController');
        System.assertEquals(result.approver2List.size(), 2, 'Failed in approver2List LeaveRequestApexController');
        System.assertEquals(result.approver3List.size(), 2 , 'Failed in approver3List LeaveRequestApexController');
    }
}