force-app/main/default/objects/Contact/fields/EMS_TM_User__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fiscal_Year__c/Fiscal_Year__c.object-meta.xml
<CustomObject>
    <label>Fiscal Year</label>
    <nameField>
        <label>Fiscal Year Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fiscal Years</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Goal__c/Goal__c.object-meta.xml
<CustomObject>
    <label>Goal</label>
    <nameField>
        <displayFormat>GOAL{000000}</displayFormat>
        <label>Goal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Goals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Goal__c/fields/Career_Development_Rating__c.field-meta.xml
<CustomField>
    <fullName>Career_Development_Rating__c</fullName>
    <formula>IMAGE(
IF( Career_Development__c &lt;1 , &quot;/img/samples/stars_000.gif&quot;,
IF(Career_Development__c&lt;2, &quot;/img/samples/stars_100.gif&quot;,
IF(Career_Development__c&lt;3, &quot;/img/samples/stars_200.gif&quot;,
IF(Career_Development__c&lt;4, &quot;/img/samples/stars_300.gif&quot;,
IF(Career_Development__c&lt;5, &quot;/img/samples/stars_400.gif&quot;, &quot;/img/samples/stars_500.gif&quot;
))))),
&quot;Rating&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Career Development Rating</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Goal__c/fields/Check_In_By__c.field-meta.xml
<CustomField>
    <fullName>Check_In_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Check In By</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Goals (Check In With ?)</relationshipLabel>
    <relationshipName>Goals1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Goal__c/fields/Check_in_Date__c.field-meta.xml
<CustomField>
    <fullName>Check_in_Date__c</fullName>
    <label>Check in Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Goal__c/fields/Communication_Rating__c.field-meta.xml
<CustomField>
    <fullName>Communication_Rating__c</fullName>
    <formula>IMAGE(
IF( Communication__c &lt;1 , &quot;/img/samples/stars_000.gif&quot;,
IF(Communication__c&lt;2, &quot;/img/samples/stars_100.gif&quot;,
IF(Communication__c&lt;3, &quot;/img/samples/stars_200.gif&quot;,
IF(Communication__c&lt;4, &quot;/img/samples/stars_300.gif&quot;,
IF(Communication__c&lt;5, &quot;/img/samples/stars_400.gif&quot;, &quot;/img/samples/stars_500.gif&quot;
))))),
&quot;Rating&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Communication Rating</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Goal__c/fields/Feedback_and_Comments__c.field-meta.xml
<CustomField>
    <fullName>Feedback_and_Comments__c</fullName>
    <label>Feedback and Comments</label>
    <length>130000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Goal__c/fields/Feedback_and_Recognition_Rating__c.field-meta.xml
<CustomField>
    <fullName>Feedback_and_Recognition_Rating__c</fullName>
    <formula>IMAGE(
IF( Feedback_and_Recognition__c &lt;1 , &quot;/img/samples/stars_000.gif&quot;,
IF(Feedback_and_Recognition__c&lt;2, &quot;/img/samples/stars_100.gif&quot;,
IF(Feedback_and_Recognition__c&lt;3, &quot;/img/samples/stars_200.gif&quot;,
IF(Feedback_and_Recognition__c&lt;4, &quot;/img/samples/stars_300.gif&quot;,
IF(Feedback_and_Recognition__c&lt;5, &quot;/img/samples/stars_400.gif&quot;, &quot;/img/samples/stars_500.gif&quot;
))))),
&quot;Rating&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Feedback and Recognition Rating</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Goal__c/fields/Goal_Name__c.field-meta.xml
<CustomField>
    <fullName>Goal_Name__c</fullName>
    <label>Goal Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Goal__c/fields/Job_Satisfaction_Rating__c.field-meta.xml
<CustomField>
    <fullName>Job_Satisfaction_Rating__c</fullName>
    <formula>IMAGE(
IF(Job_Satisfaction__c&lt;1 , &quot;/img/samples/stars_000.gif&quot;,
IF(Job_Satisfaction__c&lt;2, &quot;/img/samples/stars_100.gif&quot;,
IF(Job_Satisfaction__c&lt;3, &quot;/img/samples/stars_200.gif&quot;,
IF(Job_Satisfaction__c&lt;4, &quot;/img/samples/stars_300.gif&quot;,
IF(Job_Satisfaction__c&lt;5, &quot;/img/samples/stars_400.gif&quot;, &quot;/img/samples/stars_500.gif&quot;
))))),
&quot;Rating&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Job Satisfaction Rating</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Goal__c/fields/Leadership_and_Management_Rating__c.field-meta.xml
<CustomField>
    <fullName>Leadership_and_Management_Rating__c</fullName>
    <formula>IMAGE(
IF( Leadership_and_Management__c &lt;1 , &quot;/img/samples/stars_000.gif&quot;,
IF(Leadership_and_Management__c&lt;2, &quot;/img/samples/stars_100.gif&quot;,
IF(Leadership_and_Management__c&lt;3, &quot;/img/samples/stars_200.gif&quot;,
IF(Leadership_and_Management__c&lt;4, &quot;/img/samples/stars_300.gif&quot;,
IF(Leadership_and_Management__c&lt;5, &quot;/img/samples/stars_400.gif&quot;, &quot;/img/samples/stars_500.gif&quot;
))))),
&quot;Rating&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Leadership and Management Rating</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Goal__c/fields/Overall_Pulse_Rating__c.field-meta.xml
<CustomField>
    <fullName>Overall_Pulse_Rating__c</fullName>
    <description>Show the Overall average rating of pulse based on the value of the Average Pulse Rating field</description>
    <formula>IMAGE(
IF( Pulse_Average_Rating__c &lt;1 , &quot;/img/samples/stars_000.gif&quot;,
IF(Pulse_Average_Rating__c &lt;2, &quot;/img/samples/stars_100.gif&quot;,
IF(Pulse_Average_Rating__c &lt;3, &quot;/img/samples/stars_200.gif&quot;,
IF(Pulse_Average_Rating__c &lt;4, &quot;/img/samples/stars_300.gif&quot;,
IF(Pulse_Average_Rating__c &lt;5, &quot;/img/samples/stars_400.gif&quot;, &quot;/img/samples/stars_500.gif&quot;
))))),
&quot;Rating&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Overall Average Pulse Rating</inlineHelpText>
    <label>Overall Pulse Rating</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Goal__c/fields/Overall_Rating__c.field-meta.xml
<CustomField>
    <fullName>Overall_Rating__c</fullName>
    <formula>IMAGE(
IF( Rating__c &lt;1 , &quot;/img/samples/stars_000.gif&quot;,
IF(Rating__c&lt;2, &quot;/img/samples/stars_100.gif&quot;,
IF(Rating__c&lt;3, &quot;/img/samples/stars_200.gif&quot;,
IF(Rating__c&lt;4, &quot;/img/samples/stars_300.gif&quot;,
IF(Rating__c&lt;5, &quot;/img/samples/stars_400.gif&quot;, &quot;/img/samples/stars_500.gif&quot;
))))),
&quot;Rating&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Overall Rating</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Goal__c/fields/Pulse_Id__c.field-meta.xml
<CustomField>
    <fullName>Pulse_Id__c</fullName>
    <displayFormat>PULSE-{00000}</displayFormat>
    <label>Pulse Id</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Goal__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <label>Rating</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Goal__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Goals</relationshipLabel>
    <relationshipName>Goals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Goal__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Missed</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>KRA Inreview</fullName>
            </value>
            <value>
                <fullName>KRA Completed</fullName>
            </value>
            <value>
                <fullName>Pulse Submitted</fullName>
            </value>
            <value>
                <fullName>Pulse Requested</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>HR KRA Completed</fullName>
            </value>
            <value>
                <fullName>Completed - OnTime</fullName>
                <isActive>false</isActive>
                <label>Completed - OnTime</label>
            </value>
            <value>
                <fullName>Completed - PostTime</fullName>
                <isActive>false</isActive>
                <label>Completed - PostTime</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Goal__c/fields/Work_Environment_Rating__c.field-meta.xml
<CustomField>
    <fullName>Work_Environment_Rating__c</fullName>
    <formula>IMAGE(
IF(Work_Environment__c&lt;1 , &quot;/img/samples/stars_000.gif&quot;,
IF(Work_Environment__c&lt;2, &quot;/img/samples/stars_100.gif&quot;,
IF(Work_Environment__c&lt;3, &quot;/img/samples/stars_200.gif&quot;,
IF(Work_Environment__c&lt;4, &quot;/img/samples/stars_300.gif&quot;,
IF(Work_Environment__c&lt;5, &quot;/img/samples/stars_400.gif&quot;, &quot;/img/samples/stars_500.gif&quot;
))))),
&quot;Rating&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Work Environment Rating</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Goal__c/fields/Work_Life_Balance_Rating__c.field-meta.xml
<CustomField>
    <fullName>Work_Life_Balance_Rating__c</fullName>
    <formula>IMAGE(
IF( Work_Life_Balance__c &lt;1 , &quot;/img/samples/stars_000.gif&quot;,
IF(Work_Life_Balance__c&lt;2, &quot;/img/samples/stars_100.gif&quot;,
IF(Work_Life_Balance__c&lt;3, &quot;/img/samples/stars_200.gif&quot;,
IF(Work_Life_Balance__c&lt;4, &quot;/img/samples/stars_300.gif&quot;,
IF(Work_Life_Balance__c&lt;5, &quot;/img/samples/stars_400.gif&quot;, &quot;/img/samples/stars_500.gif&quot;
))))),
&quot;Rating&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Work-Life Balance Rating</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Goal__c/recordTypes/checkin.recordType-meta.xml
<RecordType>
    <fullName>checkin</fullName>
    <active>true</active>
    <label>checkin</label>
</RecordType>

force-app/main/default/objects/Goal__c/recordTypes/pulse.recordType-meta.xml
<RecordType>
    <fullName>pulse</fullName>
    <active>true</active>
    <label>pulse</label>
</RecordType>

force-app/main/default/classes/checkInController.cls
public without sharing class checkInController {
    
    @AuraEnabled
    public static List<checkinWrapper> getThePulseInfo(String resourceId,String fyId){
        List<checkinWrapper> cList = new List<checkinWrapper>();
         Id checkinRecordTypeId = Schema.SObjectType.Goal__c.getRecordTypeInfosByName().get('pulse').getRecordTypeId();
        List<Goal__c> glist = new List<Goal__c>();
            Date startdate = null;
            Date enddate = null;
            if(String.isEmpty(fyId)){
                 Date currentdate = system.today();
                for(Fiscal_Year__c fy : [SELECT Id,Name,Start_Date__c,End_Date__c FROM Fiscal_Year__c Order BY Start_Date__c ASC]){
                    if(fy.Start_Date__c <= currentdate && fy.End_Date__c >= currentdate){
                        startdate =  fy.Start_Date__c;
                         enddate = fy.End_Date__c;
                         break;
                    }
                  
                }
            }else{
                Fiscal_Year__c fy = [SELECT Id,Name,Start_Date__c,End_Date__c FROM Fiscal_Year__c WHERE Id=:fyId];
                startdate =  fy.Start_Date__c;
                enddate = fy.End_Date__c;
            }
            if(String.isNotBlank(resourceId)){
                glist = [SELECT Id,Check_In_By__c,Check_In_By__r.Name,Pulse_Id__c,Check_in_Date__c,Feedback_and_Comments__c,
                         Career_Development_Rating__c,Communication_Rating__c,Feedback_and_Recognition_Rating__c,Job_Satisfaction_Rating__c,
                         Leadership_and_Management_Rating__c,Work_Environment_Rating__c,Work_Life_Balance_Rating__c,Rating__c,Overall_Rating__c,Goal_Name__c,Status__c,
                         //Smaske : Added Overall_Pulse_Rating__c for PM_027
                         Overall_Pulse_Rating__c FROM Goal__c 
                         WHERE RecordTypeId=:checkinRecordTypeId AND Resource__c=:resourceId AND CreatedDate >=:startdate and CreatedDate <=:enddate ORDER BY CreatedDate DESC];
            }else{
                 glist = [SELECT Id,Check_In_By__c,Check_In_By__r.Name,Pulse_Id__c,Check_in_Date__c,Feedback_and_Comments__c,
                         Career_Development_Rating__c,Communication_Rating__c,Feedback_and_Recognition_Rating__c,Job_Satisfaction_Rating__c,
                         Leadership_and_Management_Rating__c,Work_Environment_Rating__c,Work_Life_Balance_Rating__c,Rating__c,Overall_Rating__c,Goal_Name__c,Status__c,
                         //Smaske : Added Overall_Pulse_Rating__c for PM_027
                         Overall_Pulse_Rating__c FROM Goal__c 
                         WHERE RecordTypeId=:checkinRecordTypeId AND Resource__r.EMS_TM_User__c=:Userinfo.getUserId()  AND CreatedDate >=:startdate and CreatedDate <=:enddate ORDER BY CreatedDate DESC ];
            }
        for(Goal__c gc : glist){
            checkinWrapper cw = new checkinWrapper();
             cw.goalname = gc.Pulse_Id__c;
             cw.goalid = gc.Pulse_Id__c;
             cw.checkbyName = gc.Check_In_By__r.Name;
             cw.CheckinDate = gc.Check_in_Date__c;
             cw.Comments = gc.Feedback_and_Comments__c;
             cw.Status = gc.Status__c;
             cw.carrerRating = gc.Career_Development_Rating__c;
            cw.JobStatRating = gc.Job_Satisfaction_Rating__c;
            cw.WorkEnvRating = gc.Work_Environment_Rating__c;
            cw.commRating = gc.Communication_Rating__c;
            cw.workLifeRating = gc.Work_Life_Balance_Rating__c;
            cw.FeedbackRating = gc.Feedback_and_Recognition_Rating__c;
            cw.LeadershipRating = gc.Leadership_and_Management_Rating__c;
            cw.overallRating = gc.Overall_Rating__c;
            //Smaske : Added for PM_027
            cw.overallPulseRating = gc.Overall_Pulse_Rating__c;
             cList.add(cw);
        }  
            
        return cList;
        
    }
    
    @AuraEnabled
    public static List<checkinWrapper> getTheCheckInInfo(String resourceId,String fyId){
        List<checkinWrapper> cList = new List<checkinWrapper>();
         Id checkinRecordTypeId = Schema.SObjectType.Goal__c.getRecordTypeInfosByName().get('checkin').getRecordTypeId();
        List<Goal__c> glist = new List<Goal__c>();
            Date startdate = null;
            Date enddate = null;
            if(String.isEmpty(fyId)){
                 Date currentdate = system.today();
                for(Fiscal_Year__c fy : [SELECT Id,Name,Start_Date__c,End_Date__c FROM Fiscal_Year__c Order BY Start_Date__c ASC]){
                    if(fy.Start_Date__c <= currentdate && fy.End_Date__c >= currentdate){
                        startdate =  fy.Start_Date__c;
                         enddate = fy.End_Date__c;
                         break;
                    }
                  
                }
            }else{
                Fiscal_Year__c fy = [SELECT Id,Name,Start_Date__c,End_Date__c FROM Fiscal_Year__c WHERE Id=:fyId];
                startdate =  fy.Start_Date__c;
                enddate = fy.End_Date__c;
            }
        
            if(String.isNotBlank(resourceId)){
                //smaske : updated query to return data in DESC order based on createdDate
                glist = [SELECT Id,Check_In_By__c,Check_In_By__r.Name,Check_in_Date__c,Feedback_and_Comments__c,Goal_Name__c,Status__c,CreatedDate FROM Goal__c 
                         WHERE RecordTypeId=:checkinRecordTypeId AND Resource__c=:resourceId  AND Check_in_Date__c >=:startdate and Check_in_Date__c <=:enddate ORDER BY CreatedDate DESC ];
            }else{
                //smaske : updated query to return data in DESC order based on createdDate
                 glist = [SELECT Id,Check_In_By__c,Check_In_By__r.Name,Check_in_Date__c,Feedback_and_Comments__c,Goal_Name__c,Status__c,CreatedDate FROM Goal__c 
                         WHERE RecordTypeId=:checkinRecordTypeId AND Resource__r.EMS_TM_User__c=:Userinfo.getUserId()  AND Check_in_Date__c >=:startdate and Check_in_Date__c <=:enddate ORDER BY CreatedDate DESC ];
            }
        for(Goal__c gc : glist){
            checkinWrapper cw = new checkinWrapper();
             cw.goalname = gc.Goal_Name__c;
             cw.goalid = gc.Id;
             cw.checkbyName = gc.Check_In_By__r.Name;
             cw.CheckinDate = gc.Check_in_Date__c;
             cw.Comments = gc.Feedback_and_Comments__c;
             cw.Status = gc.Status__c;
             cList.add(cw);
        }  
            
        return cList;
        
    }
    
    
     @AuraEnabled
    public static String createCheckIn(String resourceId,String mentorId, String checkInComments){
        Id checkinRecordTypeId = Schema.SObjectType.Goal__c.getRecordTypeInfosByName().get('checkin').getRecordTypeId();
        Contact resourceCon = [SELECT Id,Name FROM Contact WHERE Id=:resourceId];
        Contact mentorCon = [SELECT Id,Name FROM Contact WHERE Id=:mentorId];
        Goal__c checkInGoal = new Goal__c();
        checkInGoal.Goal_Name__c = 'Check-In On '+String.valueOf(System.today());
        checkInGoal.Check_In_By__c = mentorCon.Id;
        checkInGoal.Resource__c = resourceCon.Id;
        checkInGoal.Check_in_Date__c = System.today();
        checkInGoal.Feedback_and_Comments__c = checkInComments;
        checkInGoal.RecordTypeId = checkinRecordTypeId;
        checkInGoal.Status__c = 'Completed';
        insert checkInGoal;
        return 'success';
    }
    
    @AuraEnabled
    public static checkinWrapper getTheCheckInRecord(String checkiin){
        Goal__c gc = [SELECT Id,Check_In_By__c,Check_In_By__r.Name,Check_in_Date__c,Feedback_and_Comments__c,Goal_Name__c,Status__c FROM Goal__c WHERE Id=:checkiin];
           checkinWrapper cw = new checkinWrapper();
             cw.goalname = gc.Goal_Name__c;
             cw.goalid = gc.Id;
             cw.checkbyName = gc.Check_In_By__r.Name;
             cw.CheckinDate = gc.Check_in_Date__c;
             cw.Comments = gc.Feedback_and_Comments__c;
             cw.Status = gc.Status__c;
        return cw;
    }
    
    
    
    
        public class checkinWrapper {
        @AuraEnabled
        public String goalname;
         @AuraEnabled
        public String goalid;
         @AuraEnabled
        public String checkbyName;
         @AuraEnabled
        public Date CheckinDate;
         @AuraEnabled
        public String Comments;
         @AuraEnabled
        public String Status;
        @AuraEnabled
        public String carrerRating;
       @AuraEnabled
        public String JobStatRating;
        @AuraEnabled
        public String WorkEnvRating;
         @AuraEnabled
        public String commRating;
         @AuraEnabled
        public String workLifeRating;
          @AuraEnabled
        public String FeedbackRating;
          @AuraEnabled
        public String LeadershipRating;
         @AuraEnabled
        public String overallRating;
        //smaske :Added for PM_027 
        @AuraEnabled
        public String overallPulseRating;
         
        
    }

}