force-app/main/default/objects/Contact/fields/EMS_EM_JD__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_JD__c</fullName>
    <label>Date of Joining</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_LM_Gender__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_LM_Marital_Status__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Marital_Status__c</fullName>
    <label>Marital Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Single</fullName>
            </value>
            <value>
                <fullName>Married</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_LM_Maternity_Leave__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Maternity_Leave__c</fullName>
    <defaultValue>false</defaultValue>
    <description>For HR to enable Maternity Leave</description>
    <label>Maternity Leave</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_LM_No_of_Bereavement_Leaves_Credit__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_No_of_Bereavement_Leaves_Credit__c</fullName>
    <label>No of Bereavement Leaves Credit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_LM_No_Of_Compensatory_Off_Credit__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_No_Of_Compensatory_Off_Credit__c</fullName>
    <label>No Of Compensatory Off Credit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_LM_No_Of_Leaves_Credit__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_No_Of_Leaves_Credit__c</fullName>
    <defaultValue>0</defaultValue>
    <label>No Of Annual Leaves Credit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_LM_No_Of_Maternity_Leaves_Credit__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_No_Of_Maternity_Leaves_Credit__c</fullName>
    <label>No Of Maternity Leaves Credit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_LM_No_Of_Paternity_Leaves_Credit__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_No_Of_Paternity_Leaves_Credit__c</fullName>
    <label>No of Paternity Leaves Credit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_LM_No_Of_Utilized_Bereavement_Leaves__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_No_Of_Utilized_Bereavement_Leaves__c</fullName>
    <defaultValue>0</defaultValue>
    <label>No of Utilized Bereavement Leaves</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_LM_No_OF_Utilized_Compensatory_Off__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_No_OF_Utilized_Compensatory_Off__c</fullName>
    <defaultValue>0</defaultValue>
    <label>No of Utilized Compensatory Off</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_LM_No_Of_Utilized_Leaves__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_No_Of_Utilized_Leaves__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Annual available leaves of employee</description>
    <label>No of Utilized Annual Leaves</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_LM_No_Of_Utilized_Loss_Of_Pay__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_No_Of_Utilized_Loss_Of_Pay__c</fullName>
    <defaultValue>0</defaultValue>
    <label>No of Utilized Loss of Pay</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_LM_No_Of_Utilized_Maternity_Leaves__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_No_Of_Utilized_Maternity_Leaves__c</fullName>
    <label>No Of Utilized Maternity Leaves</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_LM_User2__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_User2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Second approver for Approval Process.</description>
    <label>Approver2</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_LM_User_1__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_User_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver 1</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>EMS_Phone_Number__c</fullName>
    <label>Contact Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_TM_User__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>USA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/No_Of_Utilized_Paternity_Leaves__c.field-meta.xml
<CustomField>
    <fullName>No_Of_Utilized_Paternity_Leaves__c</fullName>
    <defaultValue>0</defaultValue>
    <label>No Of Utilized Paternity Leaves</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Official_Mail__c.field-meta.xml
<CustomField>
    <fullName>Official_Mail__c</fullName>
    <label>Official Email ID(old)</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Resource.recordType-meta.xml
<RecordType>
    <fullName>Resource</fullName>
    <active>true</active>
    <label>Resource</label>
</RecordType>

force-app/main/default/objects/EMS_LM_Leave_History__c/EMS_LM_Leave_History__c.object-meta.xml
<CustomObject>
    <description>It will show the employee Leave and WFH Requests.</description>
    <label>Leave Request</label>
    <nameField>
        <displayFormat>LH-{00000}</displayFormat>
        <label>Leave History Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leaves Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_LM_Leave_History__c/fields/Approver_3__c.field-meta.xml
<CustomField>
    <fullName>Approver_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver 3</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Leaves_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_History__c/fields/EMS_LM_2nd_Approver__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_2nd_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>2nd Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Leaves_History1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_History__c/fields/EMS_LM_Approver__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Leaves_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_History__c/fields/EMS_LM_Contact__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Leaves History</relationshipLabel>
    <relationshipName>Leaves_History</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_History__c/fields/EMS_LM_Leave_Duration__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Leave_Duration__c</fullName>
    <label>Leave Duration</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_History__c/fields/EMS_LM_Leave_End_Date__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Leave_End_Date__c</fullName>
    <label>Leave End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_History__c/fields/EMS_LM_Leave_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Leave_Start_Date__c</fullName>
    <label>Leave Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_History__c/fields/EMS_LM_Leave_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Leave_Type_Name__c</fullName>
    <label>Leave Type Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Annual Leave</fullName>
            </value>
            <value>
                <fullName>Paternity Leave</fullName>
            </value>
            <value>
                <fullName>Bereavement Leave</fullName>
            </value>
            <value>
                <fullName>Loss of Pay</fullName>
            </value>
            <value>
                <fullName>Work From Home</fullName>
            </value>
            <value>
                <fullName>Maternity Leave</fullName>
            </value>
            <value>
                <fullName>Compensatory Off</fullName>
            </value>
            <value>
                <fullName>Marriage Leave</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_History__c/fields/EMS_LM_Status__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Approver 2 Pending</fullName>
            </value>
            <value>
                <fullName>Approver 1 Pending</fullName>
            </value>
            <value>
                <fullName>Auto Approved</fullName>
            </value>
            <value>
                <fullName>Waiting For Approver 3</fullName>
                <isActive>false</isActive>
                <label>Waiting For Approver 3</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LeaveRequestApproveHandlerTest.cls
@IsTest
public class LeaveRequestApproveHandlerTest {
@isTest
    public static void leaverequestmethod(){
        
         UserRole r =[Select Id from UserRole where Name = 'leadership'];
        Id sysAdminId = [select Id From Profile where Name ='System Administrator'].Id;
        Id communityId = [select Id From Profile where Name ='TM Customer Community'].Id;
        User u = [select Id, contactId, Email From User WHERE IsActive =True and ProfileId = :sysAdminId limit 1];
        system.debug(u);        
        System.runAs(u){
        contact c2 = new Contact();
        c2.FirstName = 'abcd';
        c2.LastName = 'efgh';
        c2.Official_Mail__c = u.Email;
        c2.EMS_Phone_Number__c = '8615748575';
        c2.Location__c ='India';
        c2.RecordTypeId = [SELECT Id FROM RecordType where name = 'Resource'].Id;
        c2.EMS_LM_User_1__c = u.Id;
        c2.EMS_LM_User2__c = u.Id;
        c2.EMS_TM_User__c = u.Id;
        c2.EMS_LM_Gender__c = 'Female';
        c2.EMS_LM_Marital_Status__c = 'Married';
        c2.EMS_EM_JD__c = system.today();
        c2.EMS_LM_No_of_Bereavement_Leaves_Credit__c = c2.EMS_LM_No_Of_Compensatory_Off_Credit__c = c2.EMS_LM_No_Of_Leaves_Credit__c = c2.EMS_LM_No_Of_Maternity_Leaves_Credit__c=c2.EMS_LM_No_Of_Paternity_Leaves_Credit__c = c2.EMS_LM_No_Of_Utilized_Bereavement_Leaves__c = c2.EMS_LM_No_OF_Utilized_Compensatory_Off__c = c2.EMS_LM_No_Of_Utilized_Leaves__c = c2.EMS_LM_No_Of_Utilized_Loss_Of_Pay__c = c2.EMS_LM_No_Of_Utilized_Maternity_Leaves__c = c2.No_Of_Utilized_Paternity_Leaves__c = 0;
        insert c2;  
        String cId = c2.Id;
        user us =new user();
        us.FirstName='bvhg';
        us.LastName='nbv';
        us.Email='bvhgnbv@gmail.com';
        us.Username='bvhgnbv@gmail.com.check';
        us.Alias='bvhgn'; 
        us.TimeZoneSidKey='America/Los_Angeles';
        us.LocaleSidKey='en_US'; 
        us.EmailEncodingKey='UTF-8'; 
        us.ProfileId= sysAdminId; 
        us.LanguageLocaleKey='en_US';
        us.UserRoleId = r.Id;
        insert us;
        Account acc = new Account(Name ='sriytbngvuoi',Phone='9457898547',ownerid = us.id);
        insert acc;
        /*acc = [select Id from Account where Name ='CP Test'];
        acc.Name ='sri12323434';
        acc.Phone='9652901511';
        acc.ownerid = us.id;
        insert acc;*/
        Contact c1 = new Contact();
        c1.FirstName = 'bvhg';
        c1.LastName = 'nbv';
        c1.Official_Mail__c = 'bvhgnbv@gmail.com';
        c1.EMS_Phone_Number__c = '8552748575';
        c1.Location__c ='India';
        c1.RecordTypeId = [SELECT Id FROM RecordType where name = 'Resource'].Id;
        c1.EMS_LM_User_1__c = us.Id;
        c1.EMS_LM_User2__c = us.Id;
        c1.EMS_TM_User__c = us.Id;
        c1.EMS_LM_Gender__c = 'Female';
        c1.EMS_LM_Marital_Status__c = 'Married';
        c1.EMS_EM_JD__c = system.today();
        c1.EMS_LM_Maternity_Leave__c = true;
        c1.EMS_LM_No_of_Bereavement_Leaves_Credit__c = c1.EMS_LM_No_Of_Compensatory_Off_Credit__c = c1.EMS_LM_No_Of_Leaves_Credit__c = c1.EMS_LM_No_Of_Maternity_Leaves_Credit__c=c1.EMS_LM_No_Of_Paternity_Leaves_Credit__c = c1.EMS_LM_No_Of_Utilized_Bereavement_Leaves__c = c1.EMS_LM_No_OF_Utilized_Compensatory_Off__c = c1.EMS_LM_No_Of_Utilized_Leaves__c = c1.EMS_LM_No_Of_Utilized_Loss_Of_Pay__c = c1.EMS_LM_No_Of_Utilized_Maternity_Leaves__c = c1.No_Of_Utilized_Paternity_Leaves__c = 0;
        insert c1;        
        Contact c = new Contact();
        c.FirstName = 'nbk';
        c.AccountId = acc.id;
        c.LastName = 'jj';
        c.Official_Mail__c = 'nbkjj121@gmail.com';
        c.EMS_Phone_Number__c = '8484158575';
        c.Location__c ='India';
        c.RecordTypeId = [SELECT Id FROM RecordType where name = 'Resource'].Id;
        c.EMS_LM_User_1__c = us.Id;
        c.EMS_LM_User2__c = us.Id;
        c.EMS_LM_Gender__c = 'Male';
        c.EMS_LM_Marital_Status__c = 'Married';
        c.EMS_EM_JD__c = system.today();
        c.EMS_LM_No_of_Bereavement_Leaves_Credit__c = c.EMS_LM_No_Of_Compensatory_Off_Credit__c = c.EMS_LM_No_Of_Leaves_Credit__c = c.EMS_LM_No_Of_Maternity_Leaves_Credit__c=c.EMS_LM_No_Of_Paternity_Leaves_Credit__c = c.EMS_LM_No_Of_Utilized_Bereavement_Leaves__c = c.EMS_LM_No_OF_Utilized_Compensatory_Off__c = c.EMS_LM_No_Of_Utilized_Leaves__c = c.EMS_LM_No_Of_Utilized_Loss_Of_Pay__c = c.EMS_LM_No_Of_Utilized_Maternity_Leaves__c = c.No_Of_Utilized_Paternity_Leaves__c = 0;
        insert c;
        user us1 =new user();
        us1.FirstName='nbk';
        us1.LastName='jj';
        us1.Email='nbkjj121@gmail.com';
        us1.Username='nbkjj121@gmail.com.check123';
        us1.Alias='nbkjj1'; 
        us1.TimeZoneSidKey='America/Los_Angeles';
        us1.LocaleSidKey='en_US'; 
        us1.EmailEncodingKey='UTF-8'; 
        us1.ProfileId= communityId; 
        us1.LanguageLocaleKey='en_US';
        us1.ContactId = c.Id;
        insert us1;
        c.EMS_TM_User__c = us1.Id;
        update c;
            
             Date startdate = system.today() + 5 ;
        String startd = string.valueOf(startdate);
        Date enddate = startdate + 4;
        String endd = string.valueOf(enddate);
        list<EMS_LM_Leave_History__c> leaveList =New list<EMS_LM_Leave_History__c>();
        list<Id> LeaveId =New List<Id>();
            
        EMS_LM_Leave_History__c lh2 = new EMS_LM_Leave_History__c();
        lh2.EMS_LM_Approver__c = us1.Id;
        lh2.EMS_LM_2nd_Approver__c = us1.Id;
        lh2.Approver_3__c = us1.Id;
        lh2.EMS_LM_Contact__c = c2.Id;
        lh2.EMS_LM_Leave_Duration__c = 2;
        lh2.EMS_LM_Leave_End_Date__c = enddate;
        lh2.EMS_LM_Leave_Start_Date__c = startdate;
        lh2.EMS_LM_Leave_Type_Name__c = 'Annual Leave';
        lh2.EMS_LM_Status__c='Pending';
        insert lh2;
        leaveList.add(lh2);
        LeaveId.add(lh2.Id);
        string LeaveRequestId2=lh2.Id;
            
        EMS_LM_Leave_History__c lh3 = new EMS_LM_Leave_History__c();
        lh3.EMS_LM_Approver__c = us1.Id;
        lh3.EMS_LM_2nd_Approver__c = us1.Id;
        lh3.Approver_3__c = us1.Id;
        lh3.EMS_LM_Contact__c = c2.Id;
        lh3.EMS_LM_Leave_Duration__c = 2;
        lh3.EMS_LM_Leave_End_Date__c = enddate;
        lh3.EMS_LM_Leave_Start_Date__c = startdate;
        lh3.EMS_LM_Leave_Type_Name__c = 'Annual Leave';
        lh3.EMS_LM_Status__c='Waiting For Approver 2';
        insert lh3;
        leaveList.add(lh3);
        LeaveId.add(lh3.Id);
        string LeaveRequestId3=lh3.Id;
            
        EMS_LM_Leave_History__c lh4 = new EMS_LM_Leave_History__c();
        lh4.EMS_LM_Approver__c = us1.Id;
        lh4.EMS_LM_2nd_Approver__c =us1.Id;
        lh4.Approver_3__c = us1.Id;
        lh4.EMS_LM_Contact__c = c2.Id;
        lh4.EMS_LM_Leave_Duration__c = 2;
        lh4.EMS_LM_Leave_End_Date__c = enddate;
        lh4.EMS_LM_Leave_Start_Date__c = startdate;
        lh4.EMS_LM_Leave_Type_Name__c = 'Annual Leave';
        lh4.EMS_LM_Status__c='Waiting For Approver 3';
        insert lh4;
        LeaveId.add(lh4.Id);
        string LeaveRequestId4=lh4.Id;
        test.startTest();
             
     //   LeaveRequestRejectHandler.updateRejecteStatusAndComments(leaveRequestId2, 'comments');
     //   LeaveRequestRejectHandler.updateRejecteStatusAndComments(LeaveRequestId3, 'comments');
     //   LeaveRequestRejectHandler.updateRejecteStatusAndComments(LeaveRequestId4, 'comments');
      //      LeaveRequestRejectHandler.bulkLeaveReqReject(LeaveId, 'comments');
            
            
        LeaveRequestApproveHandler.updateApproveStatusAndComments(leaveRequestId2, 'comments');
        LeaveRequestApproveHandler.updateApproveStatusAndComments(LeaveRequestId3, 'comments');
     //  List<LeaveRequestApproveHandler.LeaveRequestConstant> wrapperList = LeaveRequestApproveHandler.updateApproveStatusAndComments(LeaveRequestId4, 'comments');
        LeaveRequestApproveHandler.updateApproveStatusAndComments(LeaveRequestId4, 'comments');
        LeaveRequestApproveHandler.bulkLeaveReqApproval(LeaveId, 'comments');
        test.stopTest();
    	} 
}
}