force-app/main/default/objects/Contact/fields/EMS_RM_Employee_Id__c.field-meta.xml
<CustomField>
    <fullName>EMS_RM_Employee_Id__c</fullName>
    <label>Employee ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_TM_User__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Resource_Role__c.field-meta.xml
<CustomField>
    <fullName>Resource_Role__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Role</label>
    <referenceTo>Resource_Role__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Work_Location__c.field-meta.xml
<CustomField>
    <fullName>Work_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Location</label>
    <referenceTo>Office_Location__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Resource.recordType-meta.xml
<RecordType>
    <fullName>Resource</fullName>
    <active>true</active>
    <label>Resource</label>
</RecordType>

force-app/main/default/objects/EMS_EM_Benefits__c/EMS_EM_Benefits__c.object-meta.xml
<CustomObject>
    <label>Benefits</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Benefits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_EM_Benefits__c/fields/EMS_EM_Nominee__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_Nominee__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Beneficiary Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Benefits</relationshipLabel>
    <relationshipName>Benefits</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_EM_Benefits__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Medical Insurence</fullName>
                <label>Medical Insurance</label>
            </value>
            <value>
                <fullName>PF</fullName>
            </value>
            <value>
                <fullName>Phone Expense</fullName>
                <label>Phone Expenses</label>
            </value>
            <value>
                <fullName>Internet Bills</fullName>
            </value>
            <value>
                <fullName>Petrol and Gas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Grid_Configuration__c/Grid_Configuration__c.object-meta.xml
<CustomObject>
    <label>Grid Configuration</label>
    <nameField>
        <label>Grid Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grid Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Grid_Configuration__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Grid_Configuration__c/fields/Goal_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Goal_End_Date__c</fullName>
    <label>Goal End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Grid_Configuration__c/fields/Goal_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Goal_Start_Date__c</fullName>
    <label>Goal Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Grid_Configuration__c/fields/Grid_Configuration_Type__c.field-meta.xml
<CustomField>
    <fullName>Grid_Configuration_Type__c</fullName>
    <label>Grid Configuration Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Welcome aboard</fullName>
            </value>
            <value>
                <fullName>PF Forms</fullName>
            </value>
            <value>
                <fullName>Documents</fullName>
            </value>
            <value>
                <fullName>Company Policies</fullName>
            </value>
            <value>
                <fullName>Company Information - EMP- Onboarding</fullName>
            </value>
            <value>
                <fullName>Company Information - Pre-Onboarding</fullName>
            </value>
            <value>
                <fullName>Org Level Goal</fullName>
            </value>
            <value>
                <fullName>Resource Role Level Goal</fullName>
            </value>
            <value>
                <fullName>Org Level Alert</fullName>
            </value>
            <value>
                <fullName>Resource Role Alert</fullName>
            </value>
            <value>
                <fullName>KRA</fullName>
            </value>
            <value>
                <fullName>Annual Award</fullName>
            </value>
            <value>
                <fullName>Annual Award Result</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Grid_Configuration__c/fields/is_Navigation_Required__c.field-meta.xml
<CustomField>
    <fullName>is_Navigation_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Navigation Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Grid_Configuration__c/fields/Navigation_address__c.field-meta.xml
<CustomField>
    <fullName>Navigation_address__c</fullName>
    <label>Navigation Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grid_Configuration__c/fields/Notification_Type__c.field-meta.xml
<CustomField>
    <fullName>Notification_Type__c</fullName>
    <label>Notification Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alert</fullName>
            </value>
            <value>
                <fullName>Notification</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Grid_Configuration__c/fields/Resource_Role__c.field-meta.xml
<CustomField>
    <fullName>Resource_Role__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Role</label>
    <referenceTo>Resource_Role__c</referenceTo>
    <relationshipLabel>Grid Configurations</relationshipLabel>
    <relationshipName>Grid_Configurations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Office_Location__c/Office_Location__c.object-meta.xml
<CustomObject>
    <label>Office Location</label>
    <nameField>
        <label>Office Locations Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Office Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Office_Location__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>United States of America</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pay_Period__c/Pay_Period__c.object-meta.xml
<CustomObject>
    <label>Pay Period</label>
    <nameField>
        <displayFormat>PP{000000}</displayFormat>
        <label>Pay Period Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pay Periods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Pay_Period__c/fields/Office_Location__c.field-meta.xml
<CustomField>
    <fullName>Office_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Office Location</label>
    <referenceTo>Office_Location__c</referenceTo>
    <relationshipLabel>Pay Periods</relationshipLabel>
    <relationshipName>Pay_Periods</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pay_Period__c/fields/Pay_Date__c.field-meta.xml
<CustomField>
    <fullName>Pay_Date__c</fullName>
    <label>Pay Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Pay_Period__c/fields/Pay_Period_Type__c.field-meta.xml
<CustomField>
    <fullName>Pay_Period_Type__c</fullName>
    <label>Pay Period Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Bi-Weekly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Annually</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PayRoll__c/PayRoll__c.object-meta.xml
<CustomObject>
    <label>Payroll</label>
    <nameField>
        <displayFormat>PAY{0000000}</displayFormat>
        <label>PayRoll Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payrolls</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PayRoll__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PayRolls</relationshipLabel>
    <relationshipName>PayRolls</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PayRoll__c/fields/Pay_Period__c.field-meta.xml
<CustomField>
    <fullName>Pay_Period__c</fullName>
    <label>Pay Period</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Bi-Weekly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Annually</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Resource_Resource_Relationship__c/Resource_Resource_Relationship__c.object-meta.xml
<CustomObject>
    <label>Resource Relationship</label>
    <nameField>
        <displayFormat>RRR-{000000}</displayFormat>
        <label>Resource Resource Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource_Resource_Relationship__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <label>Resource</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Resource Relationships (Reports To)</relationshipLabel>
    <relationshipName>Resource_Resource_Relationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Resource_Resource_Relationship__c/fields/Resource_Reports_To__c.field-meta.xml
<CustomField>
    <fullName>Resource_Reports_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Reports To</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Relationships_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Resource_Resource_Relationship__c/fields/Resource_Role__c.field-meta.xml
<CustomField>
    <fullName>Resource_Role__c</fullName>
    <formula>Resource__r.Resource_Role__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Resource Role</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Resource_Role__c/Resource_Role__c.object-meta.xml
<CustomObject>
    <label>Resource Role</label>
    <nameField>
        <label>Resource Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resource Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User/fields/Employee_Id__c.field-meta.xml
<CustomField>
    <fullName>Employee_Id__c</fullName>
    <label>Employee Id</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/resourceTileController.cls
/**
* @author Subba Kalavala
* @date 01/03/2023
* @description  resourceTileController Class to show the data on Home page Resource details
*
*               Test code coverage provided by the following test class:
*               - resourceTileControllerTest
*
* CHANGE HISTORY
* ====================================================================================================
* DATE          NAME                    DESCRIPTION
* N/A           N/A                     N/A
* ====================================================================================================
**/
public without sharing class resourceTileController {
@AuraEnabled(cacheable=true)
    public static datawrapper getUserInfo(Id userId) {
      
        User urecord = [SELECT FullPhotoUrl,Id,Name,Employee_Id__c,Contact.EMS_RM_Employee_Id__c,ContactId,
                        Contact.ReportsTo.Name,Contact.Resource_Role__r.Name FROM User WHERE Id = :Userinfo.getUserId() and ContactId != null];
       
        Contact conRec = [SELECT Id,Work_Location__c,Work_Location__r.Country__c,(SELECT Id FROM PayRolls__r),(Select Id,Amount__c FROM Benefits__r WHERE Type__c = 'Medical Insurence') FROM Contact WHERE Id=:urecord.contactId];
        datawrapper dwrap = new datawrapper();
        dwrap.resourceName = urecord.Name;
        dwrap.resourcePhotoURL = urecord.FullPhotoUrl;
        dwrap.resourceCpId = urecord.Contact.EMS_RM_Employee_Id__c;
        dwrap.resourceRole = urecord.Contact.Resource_Role__r.Name;
        dwrap.nextpaydate = lastdayoftheMonth(conRec);
        dwrap.resourceReportTo = urecord.Contact.ReportsTo.Name;
        dwrap.resourceUserId = urecord.Id;
        dwrap.resourceContactId = urecord.ContactId;
        dwrap.resourceInsurence = getMyInsurenceBenf(conRec);
        dwrap.rescodecurrency = conRec.Work_Location__r.Country__c == 'United States of America' ? 'USD' : 'INR';
        return dwrap;
    }
    
    public static decimal getMyInsurenceBenf(Contact conRec){
        if(!conRec.Benefits__r.isEmpty()){
           return  conRec.Benefits__r[0].Amount__c;
        }
        return 300000;
    }
    @AuraEnabled(cacheable=true)
    public static date lastdayoftheMonth(Contact conRec){
        
        List<Pay_Period__c> paylist = new List<Pay_Period__c>();
        Date dt = system.today();
        String payperoid = 'Monthly';
        if(conRec.Work_Location__r.Country__c == 'United States of America'){
           payperoid = 'Bi-Weekly'; 
        }
        paylist = [SELECT Id,Pay_Date__c FROM Pay_Period__c Where Pay_Date__c >=:dt and Pay_Period_Type__c=:payperoid and Office_Location__c =:conRec.Work_Location__c ORDER BY Pay_Date__c ASC ];
        
        // Return the last working day of the current month
        return paylist.size() > 0 ? paylist[0].Pay_Date__c : system.today();
    }
    @AuraEnabled(cacheable=true)
    public static List<datawrapper> getTheCurrentAlerts(){
        
        Date dt = Test.isRunningTest() ? system.today().adddays(1) : system.today();
       
        List<datawrapper> dwrap = new List<datawrapper>();
        User urecord = [SELECT FullPhotoUrl,Id,Name,Employee_Id__c,Contact.EMS_RM_Employee_Id__c,ContactId,
                        Contact.ReportsTo.Name,Contact.Resource_Role__r.Name,Contact.Resource_Role__c FROM User WHERE Id = :Userinfo.getUserId()];
        for(Grid_Configuration__c gridc : [SELECT Id,Description__c,Notification_Type__c,Name,Goal_End_Date__c,Goal_Start_Date__c,Grid_Configuration_Type__c,
                                         Navigation_address__c,is_Navigation_Required__c,Resource_Role__c 
                                         FROM Grid_Configuration__c 
                                         WHERE (Goal_Start_Date__c <=:dt AND Goal_End_Date__c>=:dt) AND (Grid_Configuration_Type__c = 'Org Level Alert' OR Grid_Configuration_Type__c = 'Resource Role Alert')]){
          if(gridc.Grid_Configuration_Type__c == 'Org Level Alert'){
          datawrapper dw = new datawrapper();
          dw.isAlert = gridc.Notification_Type__c == 'Alert' ? true:false;
          dw.alertTitle = gridc.Name;
          dw.alertDesc = gridc.Description__c;
          dwrap.add(dw);
          }else if(gridc.Grid_Configuration_Type__c == 'Resource Role Alert' && urecord.Contact.Resource_Role__c == gridc.Resource_Role__c){
             datawrapper dw = new datawrapper();
          dw.isAlert = gridc.Notification_Type__c == 'Alert' ? true:false;
          dw.alertTitle = gridc.Name;
          dw.alertDesc = gridc.Description__c;
          dwrap.add(dw);  
          }  
       
       }
        
        return dwrap; 
     }
    
    @AuraEnabled(cacheable=true)
    public static List<fileWrapper> getRelatedFilesByRecordId() {
        Map<Id,fileWrapper> fileWrapMap = new Map<Id,fileWrapper>();
        User urec = [SELECT Id,Contact.AccountId FROM User WHERE Id=:Userinfo.getUserId()];
        String accountId = urec.Contact.AccountId != null ? urec.Contact.AccountId : null;
        // Get record file IDs        
        List<ContentDocumentLink> files = [SELECT ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId = '00152000010lJfYAAU'];
        List<ID> fileIDs = new List<ID>();
        for (ContentDocumentLink docLink : files) {
            fileIDs.add(docLink.ContentDocumentId);
        }

        
        List<ContentVersion> docs = [SELECT ContentDocumentId, FileExtension, Title 
            FROM ContentVersion WHERE ContentDocumentId IN: fileIDs ];
       
        for (ContentVersion docLink : docs) {
           fileWrapper fw = new fileWrapper();
           fw.fileName = docLink.Title;
           fw.fileExtension = docLink.FileExtension + accountId;
           fw.fileId = docLink.ContentDocumentId;
           fileWrapMap.put(docLink.ContentDocumentId,fw);
        }
        
        for(ContentDistribution cdoc : [Select Id,ContentDocumentId,ContentDownloadUrl,DistributionPublicUrl from ContentDistribution where ContentDocumentId IN:fileWrapMap.keySet()]){
            if(fileWrapMap.containsKey(cdoc.ContentDocumentId)){
                fileWrapMap.get(cdoc.ContentDocumentId).filePublicURL = cdoc.DistributionPublicUrl;
            }
        }

        return fileWrapMap.values();
    }
    
    
    @AuraEnabled(cacheable=true)
    public static datawrapper getUserHiearchyInfo(Id userId) {
        
           
        User urecord = [SELECT FullPhotoUrl,Id,Name,Employee_Id__c,Contact.EMS_RM_Employee_Id__c,ContactId,contact.ReportsToId,
                        Contact.ReportsTo.Name,Contact.Resource_Role__r.Name FROM User WHERE Id = :Userinfo.getUserId() and ContactId != null];
       
        Contact conRec = [SELECT Id,Work_Location__c,Work_Location__r.Country__c,ReportsTo.Resource_Role__r.Name,
                          ReportsTo.EMS_RM_Employee_Id__c,ReportsTo.EMS_TM_User__c,
                          ReportsTo.EMS_TM_User__r.FullPhotoUrl,ReportsTo.Name,ReportsToId FROM Contact WHERE Id=:urecord.contactId];
        List<Contact> mydirectReports = new List<Contact>();
        Set<Id> myrepotiescontids = new Set<Id>();
         Set<Id> mereportsTo = new Set<Id>();
        for(Resource_Resource_Relationship__c rrr : [SELECT Id,Resource__c,Resource_Reports_To__c FROM Resource_Resource_Relationship__c WHERE ( Resource_Reports_To__c=:urecord.contactId OR Resource__c=:urecord.contactId)]){
            if(rrr.Resource__c == urecord.contactId){
                myrepotiescontids.add(rrr.Resource__c); 
            }
             if(rrr.Resource_Reports_To__c == urecord.contactId){
                mereportsTo.add(rrr.Resource__c); 
            }
            
        }
        List<datawrapper> dwrapList = new List<datawrapper>();
        List<datawrapper> directReportsList = new List<datawrapper>();
        List<datawrapper> meReportsToList = new List<datawrapper>();
         datawrapper dwrap = new datawrapper();
        dwrap.resourceName = urecord.Name;
        dwrap.resourcePhotoURL = urecord.FullPhotoUrl;
        dwrap.resourceCpId = urecord.Contact.EMS_RM_Employee_Id__c;
        dwrap.resourceRole = urecord.Contact.Resource_Role__r.Name;
        dwrap.resourceReportTo = urecord.Contact.ReportsTo.Name;
        dwrap.resourceUserId = urecord.Id;
        dwrap.resourceContactId = urecord.ContactId;
       
        
        for(Contact myreporties : [SELECT Id,Name,EMS_TM_User__r.FullPhotoUrl,EMS_RM_Employee_Id__c,Resource_Role__r.Name,ReportsTo.Name
                                  ,EMS_TM_User__c FROM Contact WHERE Id IN: mereportsTo]){
        datawrapper dwrap2 = new datawrapper();
        dwrap2.resourceName = myreporties.Name;
        dwrap2.resourcePhotoURL = myreporties.EMS_TM_User__r.FullPhotoUrl;
        dwrap2.resourceCpId = myreporties.EMS_RM_Employee_Id__c;
        dwrap2.resourceRole = myreporties.Resource_Role__r.Name;
        dwrap2.resourceReportTo = myreporties.ReportsTo.Name;
        dwrap2.resourceUserId = myreporties.EMS_TM_User__c;
        dwrap2.resourceContactId = myreporties.id;
        directReportsList.add(dwrap2);
        }
        
        for(Contact myreporties : [SELECT Id,Name,EMS_TM_User__r.FullPhotoUrl,EMS_RM_Employee_Id__c,Resource_Role__r.Name,ReportsTo.Name
                                  ,EMS_TM_User__c FROM Contact WHERE Id=:urecord.contact.ReportsToId]){
        datawrapper dwrap2 = new datawrapper();
        dwrap2.resourceName = myreporties.Name;
        dwrap2.resourcePhotoURL = myreporties.EMS_TM_User__r.FullPhotoUrl;
        dwrap2.resourceCpId = myreporties.EMS_RM_Employee_Id__c;
        dwrap2.resourceRole = myreporties.Resource_Role__r.Name;
        dwrap2.resourceReportTo = myreporties.ReportsTo.Name;
        dwrap2.resourceUserId = myreporties.EMS_TM_User__c;
        dwrap2.resourceContactId = myreporties.id;
        meReportsToList.add(dwrap2);
        }
        
        
        
        
        dwrap.directReportesUnderme = directReportsList;
        dwrap.meReportsToList = meReportsToList;
      
        return dwrap;  
    }
    
    public class fileWrapper{
        @AuraEnabled
        public string fileName;
         @AuraEnabled
        public string fileExtension;
         @AuraEnabled
        public string filePublicURL;
         @AuraEnabled
        public string fileId;
    }
    
    
    public class datawrapper{
        @AuraEnabled
        public string resourceUserId;
        @AuraEnabled
        public string resourceName;
        @AuraEnabled
        public string resourcePhotoURL;
        @AuraEnabled
        public string resourceCpId;
        @AuraEnabled
        public string resourceRole;
        @AuraEnabled
        public Date nextpaydate;
        @AuraEnabled
        public string resourceReportTo;
        @AuraEnabled
        public decimal resourceInsurence;
         @AuraEnabled
        public string rescodecurrency;
        @AuraEnabled
        public string resourceContactId;
         @AuraEnabled
        public Boolean isAlert;
         @AuraEnabled
        public string alertTitle;
         @AuraEnabled
        public string alertDesc; 
        @AuraEnabled
        public List<datawrapper> directReportesUnderme;
        @AuraEnabled
        public List<datawrapper> meReportsToList;
    }   
}