force-app/main/default/objects/Contact/fields/EMS_RM_ApplicantStatus_Update__c.field-meta.xml
<CustomField>
    <fullName>EMS_RM_ApplicantStatus_Update__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Offer rolled out</fullName>
            </value>
            <value>
                <fullName>Offer accepted</fullName>
            </value>
            <value>
                <fullName>Offer rejected</fullName>
            </value>
            <value>
                <fullName>Hired</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Did not join</fullName>
            </value>
            <value>
                <fullName>Active - Probation</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Notice Period</fullName>
            </value>
            <value>
                <fullName>ABSENT</fullName>
                <isActive>false</isActive>
                <label>ABSENT</label>
            </value>
            <value>
                <fullName>Docs received</fullName>
                <isActive>false</isActive>
                <label>Docs received</label>
            </value>
            <value>
                <fullName>Docs verified</fullName>
                <isActive>false</isActive>
                <label>Docs verified</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_TM_User__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Assignment__c/EMS_TM_Assignment__c.object-meta.xml
<CustomObject>
    <label>Assignment</label>
    <nameField>
        <displayFormat>A.ID-{0000}</displayFormat>
        <label>Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_TM_Assignment__c/fields/EMS_TM_EmployeeName__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_EmployeeName__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Employee Name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Resource</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Assignments</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Assignment__c/fields/EMS_TM_EndDate_Asgn__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_EndDate_Asgn__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Assignment__c/fields/EMS_TM_ProjectName_Asgn__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_ProjectName_Asgn__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Name</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>EMS_TM_Project__c.Type_Of_Project__c</field>
            <operation>notEqual</operation>
            <value>Global Projects</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>EMS_TM_Project__c</referenceTo>
    <relationshipLabel>Project Assignees</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Assignment__c/fields/EMS_TM_Status_Asgn__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Status_Asgn__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <isActive>false</isActive>
                <label>Cancelled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EMS_TM_Assignment__c/fields/Project_Allocation__c.field-meta.xml
<CustomField>
    <fullName>Project_Allocation__c</fullName>
    <inlineHelpText>Percentage of effort allocated for this project</inlineHelpText>
    <label>Project Allocation %</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Project__c/EMS_TM_Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_TM_Project__c/fields/EMS_TM_EndDate__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_EndDate__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Project__c/fields/EMS_TM_StartDate__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_StartDate__c</fullName>
    <label>StartDate</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/ContactUserUpdater.cls
/**
* @author Shubham Maske
* @date 11/08/2023
* @description  Update Contacts Assigned User based on contact status field change
*
*               Test code coverage provided by the following test class: ContactUserUpdaterTest
*               - 
*
* CHANGE HISTORY
* ====================================================================================================
* DATE          		NAME                    DESCRIPTION
* 11/08/2023           Sahubham Maske           Initial Version
* ====================================================================================================
**/
public without sharing class ContactUserUpdater implements TriggerAction.AfterUpdate {
	
    /**
     * @author Shubham Maske
     * @date 11/08/2023
     * @description After Update 
     *
     * CHANGE HISTORY
     * ====================================================================================================
     * DATE          NAME                    DESCRIPTION
     * N/A           N/A                     N/A
     * ====================================================================================================
     **/
     public void afterUpdate(List<Contact> newList,List<Contact> oldList) {      
         System.debug(LoggingLevel.DEBUG, 'updateUsersAsync: BEGIN');
         
         Set<Id> contactIdsToUpdate = new Set<Id>();
         Map<Id,Contact> oldContactMap = new Map<Id,Contact>();
         
         for(Contact oldContact : oldList){
             oldContactMap.put(oldContact.Id, oldContact);
         }

        for (Contact newContact : newList) {
            Contact oldContact = oldContactMap.get(newContact.Id);

            if (newContact.EMS_RM_ApplicantStatus_Update__c == 'Inactive' && newContact.EMS_RM_ApplicantStatus_Update__c != oldContact.EMS_RM_ApplicantStatus_Update__c) {
                contactIdsToUpdate.add(newContact.Id);
            }
        }
         System.debug(' ** contactIdsToUpdate ** ' + contactIdsToUpdate);

        if (!contactIdsToUpdate.isEmpty()) {
            updateUsersAsync(contactIdsToUpdate);
            UpdateRelatedProjectAssignment(contactIdsToUpdate);
        }
         
     }
    
    @future
    public static void updateUsersAsync(Set<Id> contactIds) {
        updateUsers(contactIds);
    }
    
    public static void updateUsers(Set<Id> contactIds) {
        System.debug(' ** IN updateUsers method ** ');
        List<User> usersToUpdate = new List<User>();

        for (Id contactId : contactIds) {
            Contact contact = [SELECT Id, EMS_TM_User__c FROM Contact WHERE Id = :contactId LIMIT 1];
            if (contact.EMS_TM_User__c != null) {
                usersToUpdate.add(new User(Id = contact.EMS_TM_User__c, IsActive = false));
            }
        }
        if (!usersToUpdate.isEmpty()) {
            try {
                update usersToUpdate;
            } catch (DmlException excp) {
                LogException.logHandledException(excp, 'ContactUserUpdater', 'updateUsers');
            }
        }
    }
    
    //Method to Update the Related Project Assignee records Status Value
    public static void UpdateRelatedProjectAssignment(Set<Id> contactIds){
        System.debug(' ** IN updateUsers method ** ');
        List<EMS_TM_Assignment__c> projectAssignesToUpdate = new List<EMS_TM_Assignment__c>();

        List<EMS_TM_Assignment__c> projectAssignee = [SELECT Id, Name,EMS_TM_ProjectName_Asgn__c,EMS_TM_ProjectName_Asgn__r.EMS_TM_EndDate__c,EMS_TM_ProjectName_Asgn__r.EMS_TM_StartDate__c ,EMS_TM_EndDate_Asgn__c, EMS_TM_Status_Asgn__c, EMS_TM_EmployeeName__c,
                                                	EMS_TM_EmployeeName__r.LastModifiedDate 
                                                    FROM EMS_TM_Assignment__c 
                                                    WHERE ( EMS_TM_EmployeeName__c IN:contactIds AND EMS_TM_Status_Asgn__c != 'Closed' AND Project_Allocation__c != NULL) ];
        
        for(EMS_TM_Assignment__c pa : projectAssignee){
            pa.EMS_TM_Status_Asgn__c = 'Closed';
            Date projEndDate = pa.EMS_TM_ProjectName_Asgn__r.EMS_TM_EndDate__c;
            Date projStartDate = pa.EMS_TM_ProjectName_Asgn__r.EMS_TM_StartDate__c;
            Date conModDate = Date.today();
            if( conModDate < projEndDate && conModDate > projStartDate ){
                pa.EMS_TM_EndDate_Asgn__c = pa.EMS_TM_EmployeeName__r.LastModifiedDate.date();
            }else{
                pa.EMS_TM_EndDate_Asgn__c = projEndDate;
            }
            projectAssignesToUpdate.add(pa);
        }
        
        if(projectAssignesToUpdate.size() > 0 && projectAssignesToUpdate != null){
            update projectAssignesToUpdate;
        }
        
    }
}