force-app/main/default/objects/Contact/fields/EMS_RM_ApplicantStatus_Update__c.field-meta.xml
<CustomField>
    <fullName>EMS_RM_ApplicantStatus_Update__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Offer rolled out</fullName>
            </value>
            <value>
                <fullName>Offer accepted</fullName>
            </value>
            <value>
                <fullName>Offer rejected</fullName>
            </value>
            <value>
                <fullName>Hired</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Did not join</fullName>
            </value>
            <value>
                <fullName>Active - Probation</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Notice Period</fullName>
            </value>
            <value>
                <fullName>ABSENT</fullName>
                <isActive>false</isActive>
                <label>ABSENT</label>
            </value>
            <value>
                <fullName>Docs received</fullName>
                <isActive>false</isActive>
                <label>Docs received</label>
            </value>
            <value>
                <fullName>Docs verified</fullName>
                <isActive>false</isActive>
                <label>Docs verified</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_RM_Employee_Id__c.field-meta.xml
<CustomField>
    <fullName>EMS_RM_Employee_Id__c</fullName>
    <label>Employee ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_TM_User__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Resource_Role__c.field-meta.xml
<CustomField>
    <fullName>Resource_Role__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Role</label>
    <referenceTo>Resource_Role__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Goal__c/Goal__c.object-meta.xml
<CustomObject>
    <label>Goal</label>
    <nameField>
        <displayFormat>GOAL{000000}</displayFormat>
        <label>Goal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Goals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Goal__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Goals</relationshipLabel>
    <relationshipName>Goals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Goal__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Missed</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>KRA Inreview</fullName>
            </value>
            <value>
                <fullName>KRA Completed</fullName>
            </value>
            <value>
                <fullName>Pulse Submitted</fullName>
            </value>
            <value>
                <fullName>Pulse Requested</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>HR KRA Completed</fullName>
            </value>
            <value>
                <fullName>Completed - OnTime</fullName>
                <isActive>false</isActive>
                <label>Completed - OnTime</label>
            </value>
            <value>
                <fullName>Completed - PostTime</fullName>
                <isActive>false</isActive>
                <label>Completed - PostTime</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Goal__c/recordTypes/Goal.recordType-meta.xml
<RecordType>
    <fullName>Goal</fullName>
    <active>true</active>
    <label>Goal</label>
</RecordType>

force-app/main/default/objects/PM_Configure__c/PM_Configure__c.object-meta.xml
<CustomObject>
    <label>PM Configure</label>
    <nameField>
        <displayFormat>PM - {000000}</displayFormat>
        <label>PM Configure Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PM Configure</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PM_Configure__c/fields/KRA__c.field-meta.xml
<CustomField>
    <fullName>KRA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>KRA</label>
    <referenceTo>Goal__c</referenceTo>
    <relationshipLabel>PM Configure</relationshipLabel>
    <relationshipName>PM_Answer_Configure</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PM_Configure__c/fields/Mentee__c.field-meta.xml
<CustomField>
    <fullName>Mentee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mentee</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PM Configure (Mentee)</relationshipLabel>
    <relationshipName>PM_Configure1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PM_Configure__c/fields/Mentor__c.field-meta.xml
<CustomField>
    <fullName>Mentor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mentor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PM Configure (Mentor)</relationshipLabel>
    <relationshipName>PM_Configure</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PM_Configure__c/fields/Reporting_Contact__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reporting Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PM Configure (Reporting Contact)</relationshipLabel>
    <relationshipName>PM_Configures1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PM_Configure__c/fields/Resource_Role__c.field-meta.xml
<CustomField>
    <fullName>Resource_Role__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Role</label>
    <referenceTo>Resource_Role__c</referenceTo>
    <relationshipLabel>PM Configure</relationshipLabel>
    <relationshipName>PM_Configure</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PM_Configure__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Awaiting Response</fullName>
            </value>
            <value>
                <fullName>Response Recorded</fullName>
            </value>
            <value>
                <fullName>Saved</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Resource_Resource_Relationship__c/Resource_Resource_Relationship__c.object-meta.xml
<CustomObject>
    <label>Resource Relationship</label>
    <nameField>
        <displayFormat>RRR-{000000}</displayFormat>
        <label>Resource Resource Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource_Resource_Relationship__c/fields/Relationship_Type__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Type__c</fullName>
    <label>Relationship Type</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mentor</fullName>
            </value>
            <value>
                <fullName>Leave Approver</fullName>
            </value>
            <value>
                <fullName>Resource Manager</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Resource_Resource_Relationship__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <label>Resource</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Resource Relationships (Reports To)</relationshipLabel>
    <relationshipName>Resource_Resource_Relationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Resource_Resource_Relationship__c/fields/Resource_Reports_To__c.field-meta.xml
<CustomField>
    <fullName>Resource_Reports_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Reports To</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Relationships_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Resource_Resource_Relationship__c/fields/Resource_Role__c.field-meta.xml
<CustomField>
    <fullName>Resource_Role__c</fullName>
    <formula>Resource__r.Resource_Role__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Resource Role</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Resource_Role__c/Resource_Role__c.object-meta.xml
<CustomObject>
    <label>Resource Role</label>
    <nameField>
        <label>Resource Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resource Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/sendEmailToMentorTest.cls
@IsTest
public class sendEmailToMentorTest {
    
    @testSetup
    static void setupTestData() {
        User adminuser = TestDataFactory.createAdminUser(true);         
        System.runAs(adminuser) {
            
            Account acc = TestDataFactory.createAccount(true);
            
            List<Contact> contactsToInsert = new List<Contact>();
            List<User> usersToInsert = new List<User>();
            
            for (Integer i = 1; i <= 3; i++) {
                Contact con = TestDataFactory.createResourceContact(acc.Id, false);
                con.EMS_RM_Employee_Id__c = 'CP10234 '+ i;
                con.Resource_Role__c = TestDataFactory.createResourceRole(true).Id;
                con.EMS_RM_ApplicantStatus_Update__c = 'Active';
                contactsToInsert.add(con);
            }
            insert contactsToInsert;
            
            for (Integer i = 0; i < contactsToInsert.size(); i++) {
                User u = TestDataFactory.createMultipleCommunityUserWithAccAndContact(acc.Id, contactsToInsert[i].Id, true);
                usersToInsert.add(u);
            }
            update usersToInsert;
            
            
            for (Integer i = 0; i < contactsToInsert.size(); i++) {
                contactsToInsert[i].EMS_TM_User__c = usersToInsert[i].Id;
            }
            update contactsToInsert;
            
            Goal__c goal = new Goal__c(
                Resource__c = contactsToInsert[0].Id
            );
            insert goal;
            
            Resource_Resource_Relationship__c rrr = new Resource_Resource_Relationship__c(
                Resource__c = contactsToInsert[0].Id,
                Resource_Reports_To__c = contactsToInsert[1].Id,
                Relationship_Type__c = 'Mentor'
            );
            insert rrr;
            
            PM_Configure__c pmConfig1 = new PM_Configure__c(
                Mentee__c = contactsToInsert[0].Id,
                Mentor__c = contactsToInsert[1].Id,
                Status__c = 'Awaiting Response',
                KRA__c = goal.Id,
                Reporting_Contact__c = contactsToInsert[2].Id
            );
            insert pmConfig1;
            
            PM_Configure__c pmConfig2 = new PM_Configure__c(
                Mentee__c = contactsToInsert[0].Id,
                Mentor__c = contactsToInsert[1].Id,
                Status__c = 'Awaiting Response',
                KRA__c = goal.Id,
                Reporting_Contact__c = contactsToInsert[2].Id
            );
            insert pmConfig2;
            
            List<PM_Configure__c> pmConfigs = [
                SELECT Id, Status__c 
                FROM PM_Configure__c 
                WHERE Id IN :new Set<Id>{pmConfig1.Id, pmConfig2.Id}
            ];
            
            if (!pmConfigs.isEmpty()) {
                pmConfigs[0].Status__c = 'Submitted';
                pmConfigs[1].Status__c = 'Rejected';
                
                update pmConfigs;
            }
        }
    }
    
    @isTest
    static void testSendEmail() {
        
        Contact mentor = [SELECT Id, Email FROM Contact WHERE EMS_RM_Employee_Id__c = 'CP10234 2' LIMIT 1];
        PM_Configure__c pmConfig = [SELECT Id, Status__c FROM PM_Configure__c WHERE Status__c = 'Submitted' LIMIT 1];
        
        Test.StartTest();
        sendEmailToMentor.sendEmail(mentor, pmConfig);
        Test.stopTest();
    }
    
    @isTest
    static void testOffshoreOnshoresendEmail() {
        
        PM_Configure__c pmConfig = [SELECT Id, Status__c FROM PM_Configure__c WHERE Status__c = 'Rejected' LIMIT 1];
        
        Test.StartTest();
        sendEmailToMentor.OffshoreOnshoresendEmail(pmConfig);
        Test.stopTest();
    }
}