force-app/main/default/objects/Contact/fields/EMS_EM_JD__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_JD__c</fullName>
    <label>Date of Joining</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_LM_Gender__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_LM_Marital_Status__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Marital_Status__c</fullName>
    <label>Marital Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Single</fullName>
            </value>
            <value>
                <fullName>Married</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_LM_Maternity_Leave__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Maternity_Leave__c</fullName>
    <defaultValue>false</defaultValue>
    <description>For HR to enable Maternity Leave</description>
    <label>Maternity Leave</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_LM_No_Of_Availble_Leaves__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_No_Of_Availble_Leaves__c</fullName>
    <formula>EMS_LM_No_Of_Leaves_Credit__c - EMS_LM_No_Of_Utilized_Leaves__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>No Of Availble Leaves</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_LM_User2__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_User2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Second approver for Approval Process.</description>
    <label>Approver2</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_LM_User_1__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_User_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver 1</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>EMS_Phone_Number__c</fullName>
    <label>Contact Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_TM_User__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>USA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Official_Mail__c.field-meta.xml
<CustomField>
    <fullName>Official_Mail__c</fullName>
    <label>Official Email ID(old)</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Resource.recordType-meta.xml
<RecordType>
    <fullName>Resource</fullName>
    <active>true</active>
    <label>Resource</label>
</RecordType>

force-app/main/default/objects/EMS_LM_Leave_History__c/EMS_LM_Leave_History__c.object-meta.xml
<CustomObject>
    <description>It will show the employee Leave and WFH Requests.</description>
    <label>Leave Request</label>
    <nameField>
        <displayFormat>LH-{00000}</displayFormat>
        <label>Leave History Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leaves Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_LM_Leave_History__c/fields/EMS_LM_2nd_Approver__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_2nd_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>2nd Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Leaves_History1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_History__c/fields/EMS_LM_Approver__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Leaves_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_History__c/fields/EMS_LM_Contact__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Leaves History</relationshipLabel>
    <relationshipName>Leaves_History</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_History__c/fields/EMS_LM_Leave_Duration__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Leave_Duration__c</fullName>
    <label>Leave Duration</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_History__c/fields/EMS_LM_Leave_End_Date__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Leave_End_Date__c</fullName>
    <label>Leave End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_History__c/fields/EMS_LM_Leave_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Leave_Start_Date__c</fullName>
    <label>Leave Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_History__c/fields/EMS_LM_Leave_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Leave_Type_Name__c</fullName>
    <label>Leave Type Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Annual Leave</fullName>
            </value>
            <value>
                <fullName>Paternity Leave</fullName>
            </value>
            <value>
                <fullName>Bereavement Leave</fullName>
            </value>
            <value>
                <fullName>Loss of Pay</fullName>
            </value>
            <value>
                <fullName>Work From Home</fullName>
            </value>
            <value>
                <fullName>Maternity Leave</fullName>
            </value>
            <value>
                <fullName>Compensatory Off</fullName>
            </value>
            <value>
                <fullName>Marriage Leave</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/ContactId__c.field-meta.xml
<CustomField>
    <fullName>ContactId__c</fullName>
    <formula>ContactId</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ContactId</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LeaveManagementApexControllerTest.cls
@isTest
public class LeaveManagementApexControllerTest {
    
    public static testMethod void testGetLeaveManagement() {
        
          UserRole r =[Select Id from UserRole where Name = 'leadership'];
        Id sysAdminId = [select Id From Profile where Name ='System Administrator'].Id;
        Id communityId = [select Id From Profile where Name ='TM Customer Community'].Id;
        User u = [select Id, contactId,ContactId__c, Email From User WHERE IsActive =True and ProfileId = :communityId limit 1];
     //   Contact empLeaveBalance = [SELECT Id,EMS_LM_No_Of_Availble_Leaves__c FROM Contact WHERE Id =: u.ContactId__c ];
       
        contact c2 = new Contact();
        c2.FirstName = 'ab123';
        c2.LastName = 'efgh';
        c2.Official_Mail__c = u.Email;
        c2.EMS_Phone_Number__c = '8615748522';
        c2.Location__c ='India';
        c2.RecordTypeId = [SELECT Id FROM RecordType where name = 'Resource'].Id;
        c2.EMS_LM_User_1__c = u.Id;
        c2.EMS_LM_User2__c = u.Id;
        c2.EMS_TM_User__c = u.Id;
        c2.EMS_LM_Gender__c = 'Female';
        c2.EMS_LM_Marital_Status__c = 'Married';
        c2.EMS_LM_Maternity_Leave__c = true;
        c2.EMS_EM_JD__c = system.today();
        insert c2;  
        Date startdate = system.today() + 5 ;
        String startd = string.valueOf(startdate);
        Date enddate = startdate + 4;
        String endd = string.valueOf(enddate);
        EMS_LM_Leave_History__c lh2 = new EMS_LM_Leave_History__c();
        lh2.EMS_LM_2nd_Approver__c = u.Id;
        lh2.EMS_LM_Approver__c = u.Id;
        lh2.EMS_LM_Contact__c = c2.Id;
        lh2.EMS_LM_Leave_Duration__c = 5;
        lh2.EMS_LM_Leave_End_Date__c = enddate;
        lh2.EMS_LM_Leave_Start_Date__c = startdate;
        lh2.EMS_LM_Leave_Type_Name__c = 'Compensatory Off';
        insert lh2;
        string leaveId =lh2.Id;
        test.startTest();
        LeaveManagementApexController.getLeaveRequest();
        LeaveManagementApexController.getLeaveRequestHr();
       LeaveManagementApexController.cancleLeaveRequest(leaveId);
        // LeaveManagementApexController.leaveBanlance();
        test.stopTest();
    }

}