force-app/main/default/objects/Contact/fields/EMS_EM_JD__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_JD__c</fullName>
    <label>Date of Joining</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>EMS_Phone_Number__c</fullName>
    <label>Contact Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_RM_Current_Job_Role__c.field-meta.xml
<CustomField>
    <fullName>EMS_RM_Current_Job_Role__c</fullName>
    <label>Designation</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accounts Manager</fullName>
            </value>
            <value>
                <fullName>Associate Business Analyst</fullName>
            </value>
            <value>
                <fullName>Associate Developer</fullName>
            </value>
            <value>
                <fullName>Associate Engineer</fullName>
            </value>
            <value>
                <fullName>Associate Project Manager</fullName>
            </value>
            <value>
                <fullName>Associate Salesforce Business Analyst</fullName>
            </value>
            <value>
                <fullName>Associate Salesforce Developer</fullName>
            </value>
            <value>
                <fullName>Associate Salesforce Quality Analyst</fullName>
            </value>
            <value>
                <fullName>Associate SFMC Developer</fullName>
            </value>
            <value>
                <fullName>Associate Talent Acquisition Partner</fullName>
            </value>
            <value>
                <fullName>Account Executive</fullName>
            </value>
            <value>
                <fullName>Accounts Executive</fullName>
            </value>
            <value>
                <fullName>Associate Architect</fullName>
            </value>
            <value>
                <fullName>Business Systems Analyst</fullName>
            </value>
            <value>
                <fullName>Consultant Architecture</fullName>
            </value>
            <value>
                <fullName>Data Analyst</fullName>
            </value>
            <value>
                <fullName>Data Scientist</fullName>
            </value>
            <value>
                <fullName>Delivery Manager</fullName>
            </value>
            <value>
                <fullName>Director of Sales</fullName>
            </value>
            <value>
                <fullName>HR Executive</fullName>
            </value>
            <value>
                <fullName>HR Manager</fullName>
            </value>
            <value>
                <fullName>Jr. UX Designer</fullName>
            </value>
            <value>
                <fullName>Lead Data Migration Engineer</fullName>
            </value>
            <value>
                <fullName>Lead Salesforce Business System Analyst</fullName>
            </value>
            <value>
                <fullName>Lead Salesforce Developer</fullName>
            </value>
            <value>
                <fullName>Lead Salesforce Quality Analyst</fullName>
            </value>
            <value>
                <fullName>Project Manager</fullName>
            </value>
            <value>
                <fullName>Salesforce Administrator</fullName>
            </value>
            <value>
                <fullName>Salesforce Application Designer</fullName>
            </value>
            <value>
                <fullName>Salesforce Business Analyst</fullName>
            </value>
            <value>
                <fullName>Senior Project Manager - Salesforce</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_RM_Resource_Mobile_no__c.field-meta.xml
<CustomField>
    <fullName>EMS_RM_Resource_Mobile_no__c</fullName>
    <label>Mobile no</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_TM_User__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>USA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Official_Mail__c.field-meta.xml
<CustomField>
    <fullName>Official_Mail__c</fullName>
    <label>Official Email ID(old)</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Resource.recordType-meta.xml
<RecordType>
    <fullName>Resource</fullName>
    <active>true</active>
    <label>Resource</label>
</RecordType>

force-app/main/default/objects/EMS_Timesheet__c/EMS_Timesheet__c.object-meta.xml
<CustomObject>
    <label>Timesheet</label>
    <nameField>
        <displayFormat>TS-{0000}</displayFormat>
        <label>Time Sheet ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_Timesheet__c/fields/EMS_TM_Fri__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Fri__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Fri</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/EMS_TM_Mon__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Mon__c</fullName>
    <label>Mon</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/EMS_TM_Sat__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Sat__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Sat</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/EMS_TM_Status__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Not Approved</fullName>
            </value>
            <value>
                <fullName>Reported</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Saved</fullName>
            </value>
            <value>
                <fullName>Locked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/EMS_TM_Thu__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Thu__c</fullName>
    <label>Thu</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/EMS_TM_Tue__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Tue__c</fullName>
    <label>Tue</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/EMS_TM_Wed__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Wed__c</fullName>
    <label>Wed</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/EMS_TM_Week__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Week__c</fullName>
    <label>Week</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Timesheets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/EMS_TM_notifyMangerTest.cls
@isTest public class EMS_TM_notifyMangerTest {
  @testsetup
  public static void rtestmethod() {
      profile adminProfile=[SELECT Id, Name FROM Profile WHERE Name =:'System Administrator'];
   //   UserRole roleId =[SELECT Id, Name, ParentRoleId, PortalType, PortalRole FROM UserRole where Name ='Project Manager'];
      user us =new user();
      us.FirstName='Ram';
      us.LastName='kumar';
      us.Email='ramkumar@gmail.com';
      us.Username='ramkumar123@gmail.com.testfdgj';
    //  us.UserRoleId = roleId.Id;
      us.Alias='Rkumar'; 
      us.TimeZoneSidKey='America/Los_Angeles';
      us.LocaleSidKey='en_US'; 
      us.EmailEncodingKey='UTF-8'; 
      us.ProfileId=adminProfile.Id; 
      us.LanguageLocaleKey='en_US';
      insert us;  
  }
  
  public static testmethod void testmanager(){
      recordtype rt =[SELECT Id, Name, DeveloperName, IsActive, SobjectType FROM RecordType where name ='Resource'];
      contact c1 = new contact();
      c1.lastname ='olask';
      c1.Official_Mail__c ='olaskoka@test.com';
      c1.EMS_RM_Resource_Mobile_no__c ='5647258899';
      c1.Phone ='1234567890';
      c1.EMS_Phone_Number__c = '9648573210';
      c1.Location__c ='india';
      c1.RecordTypeId = rt.id;
      c1.EMS_EM_JD__c = system.today();
      //c1.EMS_TM_User__c = u.id;
      c1.EMS_RM_Current_Job_Role__c ='Senior Project Manager - Salesforce';
      insert c1;
      user u =[select id,lastname from user where LastName ='kumar'];
        contact c = new contact();
      c.lastname ='rkolsdh';
      c.Official_Mail__c ='rkolsdh12@gmail.com';
      c.EMS_RM_Resource_Mobile_no__c ='9412584455';
      c.Phone ='1234567890';
      c.EMS_Phone_Number__c = '9341586210';
      c.Location__c ='india';
      c.EMS_TM_User__c = u.id;
      insert c;
      
      Test.startTest();
      EMS_Timesheet__c emsts = new EMS_Timesheet__c();
      emsts.EMS_TM_Status__c='New';
      emsts.User__c= u.id;
      emsts.EMS_TM_Mon__c=8;
      emsts.EMS_TM_Tue__c=8;
      emsts.EMS_TM_Wed__c=8;
      emsts.EMS_TM_Thu__c=8;
      emsts.EMS_TM_Fri__c=8;
      emsts.EMS_TM_Sat__c=8;
      emsts.EMS_TM_Week__c=date.newInstance(2022, 8, 26);
      
      insert emsts;
    
      String sch = '0 0 0 * * ?';
      EMS_TM_EscalationMailSchedule tsc = new EMS_TM_EscalationMailSchedule();
      system.schedule('Test status', sch, tsc );
      Test.stopTest();
  }
}