force-app/main/default/objects/Contact/fields/EMS_TM_User__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Resource_Manager__c.field-meta.xml
<CustomField>
    <fullName>Resource_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Manager</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Resource</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contacts (Resource Manager)</relationshipLabel>
    <relationshipName>Contacts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Resource.recordType-meta.xml
<RecordType>
    <fullName>Resource</fullName>
    <active>true</active>
    <label>Resource</label>
</RecordType>

force-app/main/default/objects/Off_boarding_Request__c/Off_boarding_Request__c.object-meta.xml
<CustomObject>
    <label>Offboarding Request</label>
    <nameField>
        <displayFormat>OBR{000000}</displayFormat>
        <label>Off boarding Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offboarding Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Off_boarding_Request__c/fields/Exit_Interview_Date__c.field-meta.xml
<CustomField>
    <fullName>Exit_Interview_Date__c</fullName>
    <label>Exit Interview Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Off_boarding_Request__c/fields/Feedback_From_Resource__c.field-meta.xml
<CustomField>
    <fullName>Feedback_From_Resource__c</fullName>
    <label>Feedback From Resource</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Off_boarding_Request__c/fields/Last_Day_Of_Work__c.field-meta.xml
<CustomField>
    <fullName>Last_Day_Of_Work__c</fullName>
    <label>Last Day Of Work</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Off_boarding_Request__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <label>Resource</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Off boarding Requests</relationshipLabel>
    <relationshipName>Off_boarding_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Off_boarding_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Request Initiated</fullName>
                <default>true</default>
                <label>Request Initiated</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Offboarding Due</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Feedback Request Initiated</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/offboarding_Tasks__mdt/offboarding_Tasks__mdt.object-meta.xml
<CustomObject>
    <label>Offboarding Tasks</label>
    <pluralLabel>Offboarding Tasks</pluralLabel>
</CustomObject>

force-app/main/default/objects/offboarding_Tasks__mdt/fields/Due_Date_Days__c.field-meta.xml
<CustomField>
    <fullName>Due_Date_Days__c</fullName>
    <label>Due Date (Days)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/offboarding_Tasks__mdt/fields/Notification_Required_HR__c.field-meta.xml
<CustomField>
    <fullName>Notification_Required_HR__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Notification Required (HR)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/offboarding_Tasks__mdt/fields/Owner_Type__c.field-meta.xml
<CustomField>
    <fullName>Owner_Type__c</fullName>
    <label>Owner Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Queue</fullName>
                <default>true</default>
                <label>Queue</label>
            </value>
            <value>
                <fullName>User</fullName>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
            <value>
                <fullName>Resource Manager</fullName>
            </value>
            <value>
                <fullName>Reporting Manager</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/offboarding_Tasks__mdt/fields/Task_Subject__c.field-meta.xml
<CustomField>
    <fullName>Task_Subject__c</fullName>
    <label>Task Subject</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/offboarding_Tasks__mdt/fields/Unique_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Unique_Identifier__c</fullName>
    <label>Unique Identifier</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/BatchToAssignTasksForOffboarding.cls
/**
* @author Subba Kalavala
* @date 2/10/2023
* @description  BatchToAssignTasksForOffboarding Batch to create the task for onbording on DOJ 
*              
*               Schedule class 
*               - BatchToAssignTasksForOffboarding_sch
*               Test code coverage provided by the following test class:
*               - BatchToAssignTasksForOffboarding_test
*
* CHANGE HISTORY
* ====================================================================================================
* DATE          NAME                    DESCRIPTION
* N/A           N/A                     N/A
* ====================================================================================================
**/
global class BatchToAssignTasksForOffboarding implements Database.Batchable<sObject> {
 /**
* @author Subba
* @date 22/01/2023
* @description start query to get the data of the object that required to process.
*
* CHANGE HISTORY
* ====================================================================================================
* DATE          NAME                    DESCRIPTION
* N/A           N/A                     N/A
* ====================================================================================================
**/
    global Database.QueryLocator start(Database.BatchableContext BC) {
        Date dt = system.today();
        return Database.getQueryLocator([SELECT Id,Exit_Interview_Date__c,Feedback_From_Resource__c,Last_Day_Of_Work__c,
                                         Resource__c,Status__c,Resource__r.EMS_TM_User__c,Resource__r.ReportsTo.EMS_TM_User__c
                                         ,Resource__r.Resource_Manager__r.EMS_TM_User__c FROM Off_boarding_Request__c 
                                         WHERE Status__c = 'Approved' ]);
    }
  
/**
* @author Subba
* @date 22/01/2023
* @description  Execute method to process the business logic.
*
* CHANGE HISTORY
* ====================================================================================================
* DATE          NAME                    DESCRIPTION
* N/A           N/A                     N/A
* ====================================================================================================
**/
    global void execute(Database.BatchableContext BC, List<Off_boarding_Request__c> offboardingList) {
         List<Task> finalTaskList = new List<Task>();
         List<offboarding_Tasks__mdt> metaList = new List<offboarding_Tasks__mdt>();
        metaList = [SELECT Id,Assigned_To__c,Due_Date_Days__c,Notification_Required_HR__c,
                    Task_Subject__c,Owner_Type__c,Unique_Identifier__c, Navigation_Required__c, Navigation_address__c 
                    FROM offboarding_Tasks__mdt];
        System.debug('**metaList'+metaList);
         Map<String,Id> QueueWithId = new Map<String,Id>();
         Set<String> queueNames = new Set<String>();
         Map<String,Id> queueMap = new Map<String,Id>();
        for(offboarding_Tasks__mdt ptm : metaList){
            if(ptm.Owner_Type__c == 'Queue'){
            queueNames.add(ptm.Assigned_To__c);
            }
        }
        System.debug('*queueNames'+queueNames);
        for(Group grp : [SELECT Id,NAME FROM Group WHERE Type='Queue' And NAME IN:queueNames]){
          QueueWithId.put(grp.Name,grp.Id);  
        }
        System.debug('*QueueWithId'+QueueWithId);
        system.debug('===offboardingList=='+offboardingList);
         Set<String> defalutOwners = new Set<String>();
         defalutOwners.add(Label.Default_HR_Support_Request_Owner);
         for(User grp : [SELECT Id,Name,contactId,Email FROM User WHERE Email IN : defalutOwners and contactId != null]){
            queueMap.put(grp.Email,grp.id);
        }
        System.debug('**queueMap'+queueMap);
        for(Off_boarding_Request__c con : offboardingList){
            for(offboarding_Tasks__mdt ptm : metaList){
              Task t = new Task();
                if(ptm.Owner_Type__c == 'Queue' && queueMap.containsKey(Label.Default_HR_Support_Request_Owner)){
                 t.OwnerId =  queueMap.get(Label.Default_HR_Support_Request_Owner); 
                }else if(ptm.Owner_Type__c == 'Contact' && con.Resource__r.EMS_TM_User__c != null ){
                t.OwnerId = con.Resource__r.EMS_TM_User__c;    
                }else if(ptm.Owner_Type__c == 'Reporting Manager' && con.Resource__r.ReportsTo.EMS_TM_User__c != null ){
                t.OwnerId = con.Resource__r.ReportsTo.EMS_TM_User__c;    
                }else if(ptm.Owner_Type__c == 'Resource Manager' && con.Resource__r.Resource_Manager__r.EMS_TM_User__c != null ){
                t.OwnerId = con.Resource__r.Resource_Manager__r.EMS_TM_User__c;    
                }else{
                t.OwnerId = userinfo.getUserId();
                }
                if(ptm.Navigation_Required__c){
                 t.Navigation_address__c = ptm.Navigation_address__c;
                 t.Requires_Navigation__c =  ptm.Navigation_Required__c;
                }
                t.Subject = ptm.Task_Subject__c;
                t.Status = 'Open';
                t.Priority = 'High';
                t.IsReminderSet = true;
                t.IsVisibleInSelfService = True;
                t.Offboarding_UniqueKey__c  = ptm.Unique_Identifier__c;
                t.WhoId = con.Resource__c;
                t.whatId = con.Id;
                Date duedate = ptm.Due_Date_Days__c != null ? system.today().adddays(integer.valueOf(ptm.Due_Date_Days__c)) : system.today();
                t.ActivityDate = duedate;
                t.Notification_Required_HR__c = ptm.Notification_Required_HR__c;
                t.ReminderDateTime = DateTime.newInstance(duedate.year(), duedate.month(), duedate.day(), 20, 00, 00);
                finalTaskList.add(t); 
                con.Status__c ='Offboarding In Progress';
            }  
        }
         
       try{
            if(finalTaskList.size()>0){
                system.debug('===finalContactList==='+finalTaskList);
                insert finalTaskList; 
                update offboardingList;
            }
        }
        Catch(Exception excp){
            System.debug('MESSAGE'+excp.getMessage());
			LogException.logHandledException(excp, 'BatchToCreateOnboardingTasksOnDOJ', 'execute');        
        } 
    }
    
/**
* @author Subba
* @date 22/01/2023
* @description process the failures.
*
* CHANGE HISTORY
* ====================================================================================================
* DATE          NAME                    DESCRIPTION
* N/A           N/A                     N/A
* ====================================================================================================
**/
    global void finish(Database.BatchableContext BC) {
        
    }
}