force-app/main/default/objects/Contact/fields/EMS_TM_User__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave__c/EMS_LM_Leave__c.object-meta.xml
<CustomObject>
    <description>Used to store types of Leaves available in Organization</description>
    <label>Leave Type</label>
    <nameField>
        <label>Leave Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leave Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_LM_Leave__c/fields/EMS_LM_Leave_Type__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Leave_Type__c</fullName>
    <label>Leave Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Annual Leave</fullName>
            </value>
            <value>
                <fullName>Paternity Leave</fullName>
            </value>
            <value>
                <fullName>Bereavement Leave</fullName>
            </value>
            <value>
                <fullName>Loss of Pay</fullName>
            </value>
            <value>
                <fullName>Work from Home</fullName>
            </value>
            <value>
                <fullName>Maternity Leave</fullName>
            </value>
            <value>
                <fullName>Compensatory Off</fullName>
            </value>
            <value>
                <fullName>Marriage Leave</fullName>
            </value>
            <value>
                <fullName>Paid time off</fullName>
            </value>
            <value>
                <fullName>UnPaid time off</fullName>
            </value>
            <value>
                <fullName>Floating Holiday</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_Credit__c/EMS_LM_Leave_Credit__c.object-meta.xml
<CustomObject>
    <description>To credit the Leaves to Employees as per Policies</description>
    <label>Leave Credit</label>
    <nameField>
        <displayFormat>LC-{00000}</displayFormat>
        <label>Leave Credit Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leave Credits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_LM_Leave_Credit__c/fields/CompOff_Week__c.field-meta.xml
<CustomField>
    <fullName>CompOff_Week__c</fullName>
    <label>CompOff Week</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_Credit__c/fields/EMS_LM_Employee__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Employee__c</fullName>
    <label>Employee</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Leave_Credits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_Credit__c/fields/EMS_LM_Leave_Credited_Date__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Leave_Credited_Date__c</fullName>
    <description>Total No of Leaves Credited to employee</description>
    <label>Leave Credited Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_Credit__c/fields/EMS_LM_Leave_Type__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Leave_Type__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Leave Type</label>
    <referenceTo>EMS_LM_Leave__c</referenceTo>
    <relationshipName>Leave_Credits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_Credit__c/fields/EMS_LM_Leaves_Credited__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Leaves_Credited__c</fullName>
    <label>Leaves Credited</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_Credit__c/fields/EMS_LM_Select_Leave_Type__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Select_Leave_Type__c</fullName>
    <label>Select Leave Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Annual Leave</fullName>
            </value>
            <value>
                <fullName>Paternity Leave</fullName>
            </value>
            <value>
                <fullName>Bereavement Leave</fullName>
            </value>
            <value>
                <fullName>Loss of Pay</fullName>
            </value>
            <value>
                <fullName>Work from Home</fullName>
            </value>
            <value>
                <fullName>Maternity Leave</fullName>
            </value>
            <value>
                <fullName>Compensatory Off</fullName>
            </value>
            <value>
                <fullName>Paid time off</fullName>
            </value>
            <value>
                <fullName>UnPaid time off</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/createCompoffThroughTimesheet.cls
public without sharing class createCompoffThroughTimesheet {
  /*
    @AuraEnabled
    public static EMS_LM_Leave_Credit__c createCompOff(Id userId, Decimal compoffhours,Date compOffweek){
    EMS_LM_Leave__c leaveType = [SELECT Id FROM EMS_LM_Leave__c where Name ='Compensatory Off' LIMIT 1];
        System.debug('compOffweek'+compOffweek);
      System.debug('userId'+userId);
       Contact contactRec =[SELECT Id,
                                     EMS_TM_User__c 
                                     FROM contact 
                                     WHERE EMS_TM_User__c =: userId];
       List<EMS_LM_Leave_Credit__c> compOffRecordData=[Select Id 
                                                    FROM EMS_LM_Leave_Credit__c 
                                                    WHERE EMS_LM_Employee__c =: contactRec.Id 
                                                    AND CompOff_Week__c =:compOffweek 
                                                    ];
        SYstem.debug('compOffRecordData'+compOffRecordData);
   If(compOffRecordData.isEmpty()){
  try{
        EMS_LM_Leave_Credit__c comoffRecord = new EMS_LM_Leave_Credit__c();
        comoffRecord.EMS_LM_Select_Leave_Type__c ='Compensatory Off';
        comoffRecord.EMS_LM_Employee__c =contactRec.Id;
        comoffRecord.EMS_LM_Leave_Credited_Date__c= System.today();
        comoffRecord.EMS_LM_Leaves_Credited__c = compoffhours/8;
        comoffRecord.CompOff_Week__c = compOffweek;
        comoffRecord.EMS_LM_Leave_Type__c = leaveType.Id;

        insert comoffRecord;
        return comoffRecord;
  }catch(Exception e){
      String errorOccuredWith = e.getMessage();
     throw new AuraHandledException(errorOccuredWith);

  }
   }else{
                  compOffRecordData[0].EMS_LM_Leaves_Credited__c = compoffhours/8;
                  Update compOffRecordData[0];
       return compOffRecordData[0];

   } 

    }
    @AuraEnabled
     public static Boolean  checkCompOff(Id userId,Date compOffweek){
         date weekStart;
         System.debug('userId'+userId);
        System.debug('compOffweek'+compOffweek);
         if (compOffweek == null){
            Date today = Date.today();
            weekStart = today.toStartofWeek().addDays(1);
         System.debug('weekStart'+weekStart);
         }else{
             weekStart= compOffweek;
             System.debug('else weekStart'+weekStart);
         }
        boolean compOffAlredyExist = false;
       List<Contact> contactRec =[SELECT Id,
                                     EMS_TM_User__c 
                                     FROM contact 
                                     WHERE EMS_TM_User__c =: userId];
                                     List<EMS_LM_Leave_Credit__c> compOffRecord;
        if(!contactRec.isEmpty()){         
        compOffRecord=[Select Id 
                                FROM EMS_LM_Leave_Credit__c 
                                WHERE EMS_LM_Employee__c =: contactRec[0].Id 
                                AND CompOff_Week__c =: weekStart];
        }
         System.debug('compOffRecord'+compOffRecord);
         If(!compOffRecord.isEmpty()){
              compOffAlredyExist = True;
             return compOffAlredyExist;
         }else{
             compOffAlredyExist = false;
               return compOffAlredyExist;
         }
     }*/

}