force-app/main/default/objects/Contact/fields/EMS_EM_CA_City__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_CA_City__c</fullName>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_EM_CA_State__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_CA_State__c</fullName>
    <label>State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_EM_CA_Zip__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_CA_Zip__c</fullName>
    <label>Zip</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_EM_CAddress_Line_1__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_CAddress_Line_1__c</fullName>
    <label>Address Line 1</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_EM_CAddress_Line_2__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_CAddress_Line_2__c</fullName>
    <label>Address Line 2</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_EM_Mstatus__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_Mstatus__c</fullName>
    <label>Marital Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Single</fullName>
            </value>
            <value>
                <fullName>Married</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>EMS_Phone_Number__c</fullName>
    <label>Contact Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Resource.recordType-meta.xml
<RecordType>
    <fullName>Resource</fullName>
    <active>true</active>
    <label>Resource</label>
</RecordType>

force-app/main/default/objects/EMS_EM_Request__c/EMS_EM_Request__c.object-meta.xml
<CustomObject>
    <label>Request</label>
    <nameField>
        <displayFormat>R_{00000}</displayFormat>
        <label>Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_EM_Request__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Requests</relationshipLabel>
    <relationshipName>Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_EM_Request__c/fields/EMS_EM_CA_City__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_CA_City__c</fullName>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EMS_EM_Request__c/fields/EMS_EM_CA_State__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_CA_State__c</fullName>
    <label>State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EMS_EM_Request__c/fields/EMS_EM_CA_Zip__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_CA_Zip__c</fullName>
    <label>Zip</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EMS_EM_Request__c/fields/EMS_EM_CAddress_Line_1__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_CAddress_Line_1__c</fullName>
    <label>Address Line 1</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/EMS_EM_Request__c/fields/EMS_EM_CAddress_Line_2__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_CAddress_Line_2__c</fullName>
    <label>Address Line 2</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/EMS_EM_Request__c/fields/EMS_EM_Request_Type__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_Request_Type__c</fullName>
    <label>Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Address Details</fullName>
            </value>
            <value>
                <fullName>Bank Details</fullName>
            </value>
            <value>
                <fullName>Education Details</fullName>
            </value>
            <value>
                <fullName>Emergency Details</fullName>
            </value>
            <value>
                <fullName>Personal Details</fullName>
            </value>
            <value>
                <fullName>Vehicle Details</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave__c/EMS_LM_Leave__c.object-meta.xml
<CustomObject>
    <description>Used to store types of Leaves available in Organization</description>
    <label>Leave Type</label>
    <nameField>
        <label>Leave Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leave Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Office_Location__c/Office_Location__c.object-meta.xml
<CustomObject>
    <label>Office Location</label>
    <nameField>
        <label>Office Locations Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Office Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/EMS_EM_Request_Test.cls
@isTest
public class EMS_EM_Request_Test {
    
    @isTest
    public static void  testMethod1(){
          EMS_LM_Leave__c  annualtype = TestDataFactory.createLeaveType('Annual Leave',true);
            EMS_LM_Leave__c loptype = TestDataFactory.createLeaveType('Loss of Pay',true);
            EMS_LM_Leave__c bretype = TestDataFactory.createLeaveType('Maternity Leave',true);
            EMS_LM_Leave__c compofftype = TestDataFactory.createLeaveType('Compensatory Off',true);
            EMS_LM_Leave__c wfhtype = TestDataFactory.createLeaveType('Work From Home',true);
            EMS_LM_Leave__c paidtimeof = TestDataFactory.createLeaveType('Paid time off',true);
        
        Office_Location__c officlocRec =TestDataFactory.createOfficeLocation('Hyderabad - India',true);
        Office_Location__c officlocRec2 =TestDataFactory.createOfficeLocation('California - USA',true);
        
        user Testuser=TestDataFactory.createCommunityUserWithOutAccAndContact(True);
        system.debug('Testuser ============================='+Testuser);
        Account acc = new Account();
        acc.Name ='rama';
        acc.Phone='96529015';
      //  acc.IsCustomerPortal = true;
        insert acc;
        System.debug('acc'+acc);
        Contact con = new contact();
        con.Email ='ramakrishna@gmail.com';
        con.AccountId = acc.id;
        con.FirstName ='rama111';
        con.LastName ='krishna11';
        con.EMS_Phone_Number__c ='9652107520';
        con.EMS_EM_Mstatus__c  = 'Single';
        // clinicRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get(‘Resource Active’).getRecordTypeId();
        con.RecordTypeId = [SELECT Id FROM RecordType where name = 'Resource'].Id;
        
       //n.RecordTypeId=clinicRecordTypeId;
        insert con;

        
        
        
        EMS_EM_Request__c req = new EMS_EM_Request__c();
        req.EMS_EM_Request_Type__c = 'Address Details';
        req.EMS_EM_CAddress_Line_1__c = 'Line1';
        req.EMS_EM_CAddress_Line_2__c = 'Line 2';
        req.EMS_EM_CA_City__c = 'Hyderabad';
        req.EMS_EM_CA_State__c = 'Telangana';
        req.EMS_EM_CA_Zip__c = '500082';
        req.Contact__c = con.id;
        
        insert req;

        EMS_EM_Request.getUserContactInfo(Testuser.Id);
        EMS_EM_Request.getContactInfo(req.Id);
    }
    
    @isTest
    public static void  testMethod2(){
          EMS_LM_Leave__c  annualtype = TestDataFactory.createLeaveType('Annual Leave',true);
            EMS_LM_Leave__c loptype = TestDataFactory.createLeaveType('Loss of Pay',true);
            EMS_LM_Leave__c bretype = TestDataFactory.createLeaveType('Maternity Leave',true);
            EMS_LM_Leave__c compofftype = TestDataFactory.createLeaveType('Compensatory Off',true);
            EMS_LM_Leave__c wfhtype = TestDataFactory.createLeaveType('Work From Home',true);
         EMS_LM_Leave__c paidtimeof = TestDataFactory.createLeaveType('Paid time off',true);
        
        Office_Location__c officlocRec =TestDataFactory.createOfficeLocation('Hyderabad - India',true);
        Office_Location__c officlocRec2 =TestDataFactory.createOfficeLocation('California - USA',true);
            
        
        Account acc = new Account();
        acc.Name ='rama';
        acc.Phone='96529015';
      //  acc.IsCustomerPortal = true;
        insert acc;
        System.debug('acc'+acc);
        Contact con = new contact();
        con.Email ='ramakrishna@gmail.com';
        con.AccountId = acc.id;
        con.FirstName ='rama111';
        con.LastName ='krishna11';
        con.EMS_Phone_Number__c ='965210752';
        con.EMS_Phone_Number__c ='9652901075';
        con.EMS_EM_Mstatus__c  = 'Single';
       // con.RecordTypeId = [SELECT Id FROM RecordType where name = 'Resource Active'].Id;
        insert con;
        
	
        EMS_EM_Request__c req = new EMS_EM_Request__c();
        req.EMS_EM_Request_Type__c = 'Address Details';
        req.EMS_EM_CAddress_Line_1__c = 'Line1';
        req.EMS_EM_CAddress_Line_2__c = 'Line 2';
        req.EMS_EM_CA_City__c = 'Hyderabad';
        req.EMS_EM_CA_State__c = 'Telangana';
        req.EMS_EM_CA_Zip__c = '500082';
        req.Contact__c = con.id;
		
        
        EMS_EM_Request.createRequest(req);
    }
    @isTest
    public static void  testMethod3(){
        
        EMS_EM_Request__c req = new EMS_EM_Request__c();
        req.EMS_EM_Request_Type__c = 'Address Details';
        req.EMS_EM_CAddress_Line_1__c = 'Line1';
        req.EMS_EM_CAddress_Line_2__c = 'Line 2';
        req.EMS_EM_CA_City__c = 'Hyderabad';
        req.EMS_EM_CA_State__c = 'Telangana';
        req.EMS_EM_CA_Zip__c = '500082';
        
        insert req;
        
        
        
        ContentVersion cv1 = new ContentVersion(
            Title = 'Penguins',
            PathOnClient = 'Penguins.pdf',
            VersionData = Blob.valueOf('Test Content'),
            IsMajorVersion = true
        );
        
        EMS_EM_Request.uploadFile(EncodingUtil.base64Encode(cv1.VersionData), 'sample.pdf', req.Id);
        
        
        
    }
}