force-app/main/default/objects/Contact/fields/EMS_TM_User__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Resource_Resource_Relationship__c/Resource_Resource_Relationship__c.object-meta.xml
<CustomObject>
    <label>Resource Relationship</label>
    <nameField>
        <displayFormat>RRR-{000000}</displayFormat>
        <label>Resource Resource Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource_Resource_Relationship__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <label>Resource</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Resource Relationships (Reports To)</relationshipLabel>
    <relationshipName>Resource_Resource_Relationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Resource_Resource_Relationship__c/fields/Resource_Reports_To__c.field-meta.xml
<CustomField>
    <fullName>Resource_Reports_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Reports To</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Relationships_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/managerSeeEmployeeRec.cls
public without sharing class managerSeeEmployeeRec {
    
    @AuraEnabled(cacheable=true)
    public static List<User> serchUser(Id userId){
        System.debug('userID'+userId);
        Contact conRec =[Select Id,
                         EMS_TM_user__c 
                         FROM Contact 
                         WHERE EMS_TM_user__c =:userId];
        System.debug('conRec'+conRec);
        Set<Id> userIds = new Set<Id>();
        Set<Id> contactIds = new Set<Id>();
        for(Resource_Resource_Relationship__c relationShipRec :[SELECT Resource__r.EMS_TM_user__c,
                                                                Resource__c,
                                                                Resource_Reports_To__c 
                                                                FROM Resource_Resource_Relationship__c
                                                                WHERE Resource_Reports_To__c =:conRec.Id]){
                                                                    userIds.add(relationShipRec.Resource__r.EMS_TM_user__c);
                                                                    contactIds.add(relationShipRec.Resource__c);
                                                                }
        System.debug('contactIds'+contactIds+'>..>>>>'+userIds.size());
        for(Resource_Resource_Relationship__c relationShipempRec :[SELECT Resource__r.EMS_TM_user__c,
                                                                   Resource__c,
                                                                   Resource_Reports_To__c 
                                                                   FROM Resource_Resource_Relationship__c
                                                                   WHERE Resource_Reports_To__c IN:contactIds]){
                                                                       userIds.add(relationShipempRec.Resource__r.EMS_TM_user__c);
                                                                       
                                                                   }
                        System.debug('contactIds>..>>>>'+userIds.size());
                        List<User> userList = new List<User>();
                        
                        for(User userRec: [Select Id,
                                           Name 
                                           FROM User 
                                           WHERE Id IN:userIds]){
                                               userList.add(userRec);
                                           }
                        
                        System.debug('userList'+userList);
                        try{
                            return userList;
                        }catch(Exception e){
                            String errorOccuredWith = e.getMessage();
                            throw new AuraHandledException(errorOccuredWith);
                        }
    }
}