force-app/main/default/objects/Contact/fields/EMS_TM_User__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_Credit__c/EMS_LM_Leave_Credit__c.object-meta.xml
<CustomObject>
    <description>To credit the Leaves to Employees as per Policies</description>
    <label>Leave Credit</label>
    <nameField>
        <displayFormat>LC-{00000}</displayFormat>
        <label>Leave Credit Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leave Credits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_LM_Leave_Credit__c/fields/CompOff_Week__c.field-meta.xml
<CustomField>
    <fullName>CompOff_Week__c</fullName>
    <label>CompOff Week</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_Credit__c/fields/EMS_LM_Employee__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Employee__c</fullName>
    <label>Employee</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Leave_Credits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/EMS_Timesheet__c.object-meta.xml
<CustomObject>
    <label>Timesheet</label>
    <nameField>
        <displayFormat>TS-{0000}</displayFormat>
        <label>Time Sheet ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_Timesheet__c/fields/EMS_TM_Sat__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Sat__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Sat</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/EMS_TM_Sun__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Sun__c</fullName>
    <label>Sun</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/startweek__c.field-meta.xml
<CustomField>
    <fullName>startweek__c</fullName>
    <formula>CASE(
MOD( EMS_TM_Week__c - DATE(1900, 1, 6),7),
0, EMS_TM_Week__c ,
1, EMS_TM_Week__c ,
2, EMS_TM_Week__c ,
3, EMS_TM_Week__c - 1,
4, EMS_TM_Week__c - 2,
5, EMS_TM_Week__c - 3,
6, EMS_TM_Week__c - 4,
NULL
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>startweek</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Timesheets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/deleteCompOffRecord.cls
/**
    * @author Ramakrishna 
    * @date 27/01/2023
    * @description  deleteCompOffRecord to check the TimesheetRecord weekend values updated to null then delete the   
    *               comOffRecord related to timesheet.
    *
    *               Test code coverage provided by the following test class:
    *               - deleteCompOffRecordTest
    *
    * CHANGE HISTORY
    * ====================================================================================================
    * DATE          NAME                    DESCRIPTION
    * N/A           N/A                     N/A
    * ====================================================================================================
    **/
public class deleteCompOffRecord implements TriggerAction.AfterUpdate{
       /**
    * @author Ramakrishna
    * @date 27/01/2023
    * @description After Update 
    *
    * CHANGE HISTORY
    * ====================================================================================================
    * DATE          NAME                    DESCRIPTION
    * N/A           N/A                     N/A
    * ====================================================================================================
    **/
    public void afterUpdate(List<EMS_Timesheet__c> newList,List<EMS_Timesheet__c> oldList) {      
        System.debug(LoggingLevel.DEBUG, 'deleteCompOffRecord.afterUpdate() : BEGIN');
        Map<id,EMS_Timesheet__c> timesheetOldMap = new Map<id,EMS_Timesheet__c>(oldList);
        deleteCompoff(newList,timesheetOldMap);
        System.debug(LoggingLevel.DEBUG, 'deleteCompOffRecord.afterUpdate() : END');       
    }
    /**
    *   {Purpose} - Method to check the TimesheetRecord weekend values updated to null then delete the   
    *               comOffRecord related to timesheet 
    *
    *   CHANGE HISTORY
    *   ====================================================================================================
    *   Date        Name                    Description
    *   N/A         N/A                     N/A
    *   ====================================================================================================
    **/
    private void deleteCompoff(List<EMS_Timesheet__c> newTimesheetList,Map<Id,EMS_Timesheet__c> oldTimesheetMap){
        Map<Id,Date> newtimesheetMap = new Map<Id,Date>();
        for(EMS_Timesheet__c timesheetRec:newTimesheetList){
            if((timesheetRec.EMS_TM_Sat__c != oldTimesheetMap.get(timesheetRec.Id).EMS_TM_Sat__c && timesheetRec.EMS_TM_Sat__c ==0)||
               (timesheetRec.EMS_TM_Sun__c != oldTimesheetMap.get(timesheetRec.Id).EMS_TM_Sun__c && timesheetRec.EMS_TM_Sun__c ==0)
              ) {
                 newtimesheetMap.put(timesheetRec.User__c,timesheetRec.startweek__c);
            }
        }
        System.debug('newtimesheetMap'+newtimesheetMap);
        Map<Id,Date> contactMap = new Map<Id,Date>();
        for(Contact contactRec:[SELECT Id,EMS_TM_User__c from contact WHERE EMS_TM_User__c IN: newtimesheetMap.keyset()]){
            if(contactRec.EMS_TM_User__c != null){
                contactMap.put(contactRec.Id,newtimesheetMap.get(contactRec.EMS_TM_User__c));
            }           
        }
        System.debug('contactMap'+contactMap);
        List<EMS_LM_Leave_Credit__c> compOffList =[Select Id 
                                                           FROM EMS_LM_Leave_Credit__c 
                                                           WHERE EMS_LM_Employee__c IN :contactMap.keyset()
                                                           AND CompOff_Week__c IN: contactMap.values()];  
        System.debug('compOffList'+compOffList);
        try{
            if(!compOffList.IsEmpty()){
                delete compOffList;
            }            
        }catch(Exception e){
            LogException.logHandledException(e, 'deleteCompOffRecord', 'deleteCompoff');
         System.debug('Deletecompoff'+e.getMessage());  
         System.debug('Deletecompoff'+e.getLineNumber());
        }
    }
}