force-app/main/default/objects/Contact/fields/EMS_RM_ApplicantStatus_Update__c.field-meta.xml
<CustomField>
    <fullName>EMS_RM_ApplicantStatus_Update__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Offer rolled out</fullName>
            </value>
            <value>
                <fullName>Offer accepted</fullName>
            </value>
            <value>
                <fullName>Offer rejected</fullName>
            </value>
            <value>
                <fullName>Hired</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Did not join</fullName>
            </value>
            <value>
                <fullName>Active - Probation</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Notice Period</fullName>
            </value>
            <value>
                <fullName>ABSENT</fullName>
                <isActive>false</isActive>
                <label>ABSENT</label>
            </value>
            <value>
                <fullName>Docs received</fullName>
                <isActive>false</isActive>
                <label>Docs received</label>
            </value>
            <value>
                <fullName>Docs verified</fullName>
                <isActive>false</isActive>
                <label>Docs verified</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_RM_Employee_Id__c.field-meta.xml
<CustomField>
    <fullName>EMS_RM_Employee_Id__c</fullName>
    <label>Employee ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Resource_Role__c.field-meta.xml
<CustomField>
    <fullName>Resource_Role__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Role</label>
    <referenceTo>Resource_Role__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Resource.recordType-meta.xml
<RecordType>
    <fullName>Resource</fullName>
    <active>true</active>
    <label>Resource</label>
</RecordType>

force-app/main/default/objects/EMS_TM_Project__c/EMS_TM_Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_TM_Project__c/fields/EMS_TM_EndDate__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_EndDate__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Project__c/fields/EMS_TM_StartDate__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_StartDate__c</fullName>
    <label>StartDate</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Project__c/fields/EMS_TM_Status__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ongoing</fullName>
                <default>true</default>
                <label>Ongoing</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EMS_TM_Project__c/fields/Offshore_Project_Manager__c.field-meta.xml
<CustomField>
    <fullName>Offshore_Project_Manager__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Offshore Project Manager</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND (2 OR 3)</booleanFilter>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Resource</value>
        </filterItems>
        <filterItems>
            <field>Contact.Resource_Role__r.Name</field>
            <operation>equals</operation>
            <value>Sr Project Manager</value>
        </filterItems>
        <filterItems>
            <field>Contact.Resource_Role__r.Name</field>
            <operation>equals</operation>
            <value>Project Manager</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Projects (Offshore Project Manager)</relationshipLabel>
    <relationshipName>Projects1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Project__c/fields/Project_Manager__c.field-meta.xml
<CustomField>
    <fullName>Project_Manager__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Onshore Project Manager</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND (2 OR 3)</booleanFilter>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Resource</value>
        </filterItems>
        <filterItems>
            <field>Contact.Resource_Role__r.Name</field>
            <operation>equals</operation>
            <value>Sr Project Manager</value>
        </filterItems>
        <filterItems>
            <field>Contact.Resource_Role__r.Name</field>
            <operation>equals</operation>
            <value>Project Manager</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Project__c/fields/Type_Of_Project__c.field-meta.xml
<CustomField>
    <fullName>Type_Of_Project__c</fullName>
    <label>Type of Project</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Client Projects</fullName>
            </value>
            <value>
                <fullName>Internal Projects</fullName>
            </value>
            <value>
                <fullName>Global Projects</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fulfillment__c/Fulfillment__c.object-meta.xml
<CustomObject>
    <label>Fulfillment</label>
    <nameField>
        <displayFormat>FP{00000}</displayFormat>
        <label>Fulfillment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fulfillments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fulfillment__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Resource</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Fulfillments</relationshipLabel>
    <relationshipName>Fulfillments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fulfillment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Goal__c/Goal__c.object-meta.xml
<CustomObject>
    <label>Goal</label>
    <nameField>
        <displayFormat>GOAL{000000}</displayFormat>
        <label>Goal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Goals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Goal__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Goals</relationshipLabel>
    <relationshipName>Goals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Goal__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Missed</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>KRA Inreview</fullName>
            </value>
            <value>
                <fullName>KRA Completed</fullName>
            </value>
            <value>
                <fullName>Pulse Submitted</fullName>
            </value>
            <value>
                <fullName>Pulse Requested</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>HR KRA Completed</fullName>
            </value>
            <value>
                <fullName>Completed - OnTime</fullName>
                <isActive>false</isActive>
                <label>Completed - OnTime</label>
            </value>
            <value>
                <fullName>Completed - PostTime</fullName>
                <isActive>false</isActive>
                <label>Completed - PostTime</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Goal__c/recordTypes/KRA.recordType-meta.xml
<RecordType>
    <fullName>KRA</fullName>
    <active>true</active>
    <label>KRA</label>
</RecordType>

force-app/main/default/objects/PM_Configure__c/PM_Configure__c.object-meta.xml
<CustomObject>
    <label>PM Configure</label>
    <nameField>
        <displayFormat>PM - {000000}</displayFormat>
        <label>PM Configure Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PM Configure</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PM_Configure__c/fields/Resource_Role__c.field-meta.xml
<CustomField>
    <fullName>Resource_Role__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Role</label>
    <referenceTo>Resource_Role__c</referenceTo>
    <relationshipLabel>PM Configure</relationshipLabel>
    <relationshipName>PM_Configure</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PM_Configure__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Awaiting Response</fullName>
            </value>
            <value>
                <fullName>Response Recorded</fullName>
            </value>
            <value>
                <fullName>Saved</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PM_Configure__c/recordTypes/Answer.recordType-meta.xml
<RecordType>
    <fullName>Answer</fullName>
    <active>true</active>
    <label>Answer</label>
</RecordType>

force-app/main/default/objects/Resource_Resource_Relationship__c/Resource_Resource_Relationship__c.object-meta.xml
<CustomObject>
    <label>Resource Relationship</label>
    <nameField>
        <displayFormat>RRR-{000000}</displayFormat>
        <label>Resource Resource Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource_Resource_Relationship__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <label>Resource</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Resource Relationships (Reports To)</relationshipLabel>
    <relationshipName>Resource_Resource_Relationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Resource_Resource_Relationship__c/fields/Resource_Reports_To__c.field-meta.xml
<CustomField>
    <fullName>Resource_Reports_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Reports To</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Relationships_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Resource_Resource_Relationship__c/fields/Resource_Role__c.field-meta.xml
<CustomField>
    <fullName>Resource_Role__c</fullName>
    <formula>Resource__r.Resource_Role__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Resource Role</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/project_manager__c.field-meta.xml
<CustomField>
    <fullName>project_manager__c</fullName>
    <label>Project Manager</label>
    <relationshipName>Users</relationshipName>
    <restrictedAdminField>true</restrictedAdminField>
    <type>Hierarchy</type>
</CustomField>

force-app/main/default/classes/viewPmRequestsControllerTEST.cls
/**
* @author Sangharsh Kamble 
* @date 02/09/2024
* @description  Test class for viewPmRequestsController

* CHANGE HISTORY
* ====================================================================================================
* DATE          NAME                    DESCRIPTION
* N/A           N/A                     N/A
* ====================================================================================================
**/
@isTest
public class viewPmRequestsControllerTEST {
    @testSetup
    static void setupTestData() {
        EMS_LM_Leave__c  annualtype = TestDataFactory.createLeaveType('Annual Leave',true);
        EMS_LM_Leave__c loptype = TestDataFactory.createLeaveType('Loss of Pay',true);
        EMS_LM_Leave__c bretype = TestDataFactory.createLeaveType('Maternity Leave',true);
        EMS_LM_Leave__c compofftype = TestDataFactory.createLeaveType('Compensatory Off',true);
        EMS_LM_Leave__c wfhtype = TestDataFactory.createLeaveType('Work From Home',true);
        EMS_LM_Leave__c paidTimeOff = TestDataFactory.createLeaveType('Paid time off',true);
        Resource_Role__c role = TestDataFactory.createResourceRole(true);
        System.debug('role created ' + role.Name);
        
        //create Questions Records
        List<PM_Configure__c> Questions =  TestDataFactory.createPMConfigQuestionRec(role.Id,true);
        
        Account acc = TestDataFactory.createAccount(true);
        Contact con=  TestDataFactory.createResourceContact(acc.id, false);
        con.EMS_RM_Employee_Id__c = 'CP10234';
        con.Resource_Role__c = role.Id;
    	con.Email ='test@cloudperitus.com';
        con.EMS_RM_ApplicantStatus_Update__c = 'Active';
        insert con;
        
        Contact con1=  TestDataFactory.createResourceContact(acc.id, false);
        con1.EMS_RM_Employee_Id__c = 'CP10235';
        con1.Resource_Role__c = role.Id;
        con1.Email = 'testEmail+test1@cloudperitus.com';
        con1.EMS_RM_ApplicantStatus_Update__c = 'Active';
        insert con1;
    
       		EMS_TM_Project__c project = new EMS_TM_Project__c();
            project.Name ='Grid Test';
            project.EMS_TM_StartDate__c = system.today();
            project.EMS_TM_EndDate__c =system.today() + 365;
            project.EMS_TM_Status__c = 'Ongoing';
            project.Type_Of_Project__c ='Internal Projects';
            project.Account__c = acc.Id;
            project.Offshore_Project_Manager__c = con1.Id;
            project.Project_Manager__c = con1.id;
            Insert project;
        
        
        Resource_Role__c role2 = TestDataFactory.createResourceRole(true);
        
        Resource_Resource_Relationship__c resourceRelationship = new Resource_Resource_Relationship__c();
        resourceRelationship.Resource__c = con.Id;
        resourceRelationship.Resource_Reports_To__c=con.Id;
        resourceRelationship.Relationship_Type__c = 'Mentor';
        insert resourceRelationship;
        
        User u = Testdatafactory.createCommunityUserWithAccAndContact(acc.id,con.Id,true);
        system.debug('u-->'+u);
        Fiscal_Year__c FiscalYear = Testdatafactory.createFiscalYear(true);
        
        TriggerBase.bypass('Contact');
        con.EMS_TM_User__c = u.Id;
        con.Resource_Role__c = role.Id;
        update con;
        TriggerBase.clearBypass('Contact');
        
        Fulfillment__c full = Testdatafactory.createFulfillment(con.Id,true);
        
        User u1 = Testdatafactory.createCommunityUserWithAccAndContact(acc.id,con1.Id,false);
        u1.Username='test001@admin.com';
        insert u1;
        
        Goal__c Kra = Testdatafactory.createKRARecords(con.Id, con.Id, full, false);
        Kra.Resource__c = full.Resource__c;
        insert Kra;
    
    Contact kraChaCon = [Select Id,Name,Resource_Role__c,Resource_Role__r.Name from Contact Where Id =: Kra.Resource__c ];
     System.debug('Kra Resource ResourceRole :: ' + kraChaCon );
        Resource_Role__c roleContact = [Select Id,name from Resource_Role__c WHERE Id =:kraChaCon.Resource_Role__c ];
        System.debug('Kra roleContact :: ' + roleContact );
        
        
        List<PM_Configure__c> gridPmConfigAns = [SELECT Id, Status__c, KRA__c FROM PM_Configure__c WHERE KRA__c =:Kra.Id ];
        // Create a Set to store the Ids
        Set<Id> pmConfigIds = new Set<Id>();
        List<String> pmConfigIdList = new List<String>();
        for (PM_Configure__c pmConfig : gridPmConfigAns) {
            pmConfigIds.add(pmConfig.Id);
        }
        for (Id id : pmConfigIds) {
            pmConfigIdList.add(id);
        }
    
    List<PM_Configure__c> createPMConfigRecords = TestDataFactory.createPMConfigRecords(role.Id,con.Id,con.Id,project.Id,KRA.Id,true);    
    }
    
public static testMethod void testClassForquarterlyKRAViewCtrl() {
    //User u =[Select id from User ]
    Goal__c Kra =[Select Id from Goal__c limit 1];
    List<PM_Configure__c> createPMConfigRecords =[Select id from PM_Configure__c];
  Test.startTest();
       // system.runAs(u){
            viewPmRequestsController.viewPMRequestsTable(Kra.Id);   
          //  viewPmRequestsController.recallPmRequests(Kra.Id,con.Id,'Grid Test','Recalled');
            //viewPmRequestsController.sendEmailToPmForRecallRecords(createPMConfigRecords);
       // } 
        Test.stopTest();       
}
    
    public static testMethod void viewPMRequestsTableForSubmitted() {
    //User u =[Select id from User ]
    Goal__c Kra =[Select Id from Goal__c limit 1];
    Id answerRecordTypeId = Schema.SObjectType.PM_Configure__c.getRecordTypeInfosByName().get('Answer').getRecordTypeId();

    List<PM_Configure__c> createPMConfigRecords =[Select id,Status__c,KRA__c from PM_Configure__c WHERE RecordTypeId =: answerRecordTypeId and KRA__c =:Kra.Id ];
         List<PM_Configure__c> updateAnswer = new  List<PM_Configure__c>();
        for(PM_Configure__c ans : createPMConfigRecords){
            ans.Status__c = 'Submitted';
			updateAnswer.add(ans);            
        }
        TriggerBase.bypass('PM_Configure__c');
        update updateAnswer;
        TriggerBase.clearBypass('PM_Configure__c');
  Test.startTest();
            viewPmRequestsController.viewPMRequestsTable(Kra.Id);
        Test.stopTest();       
}
    
    public static testMethod void viewPMRequestsTableForAccepted() {
    //User u =[Select id from User ]
    Goal__c Kra =[Select Id from Goal__c limit 1];
    Id answerRecordTypeId = Schema.SObjectType.PM_Configure__c.getRecordTypeInfosByName().get('Answer').getRecordTypeId();

    List<PM_Configure__c> createPMConfigRecords =[Select id,Status__c,KRA__c from PM_Configure__c WHERE RecordTypeId =: answerRecordTypeId and KRA__c =:Kra.Id ];
         List<PM_Configure__c> updateAnswer = new  List<PM_Configure__c>();
        for(PM_Configure__c ans : createPMConfigRecords){
            ans.Status__c = 'Accepted';
			updateAnswer.add(ans);            
        }
        TriggerBase.bypass('PM_Configure__c');
        update updateAnswer;
        TriggerBase.clearBypass('PM_Configure__c');
  Test.startTest();
            viewPmRequestsController.viewPMRequestsTable(Kra.Id);
        Test.stopTest();       
}
    
    public static testMethod void viewPMRequestsTableForRejected() {
    //User u =[Select id from User ]
    Goal__c Kra =[Select Id from Goal__c limit 1];
    Id answerRecordTypeId = Schema.SObjectType.PM_Configure__c.getRecordTypeInfosByName().get('Answer').getRecordTypeId();

    List<PM_Configure__c> createPMConfigRecords =[Select id,Status__c,KRA__c from PM_Configure__c WHERE RecordTypeId =: answerRecordTypeId and KRA__c =:Kra.Id ];
         List<PM_Configure__c> updateAnswer = new  List<PM_Configure__c>();
        for(PM_Configure__c ans : createPMConfigRecords){
            ans.Status__c = 'Rejected';
			updateAnswer.add(ans);            
        }
        TriggerBase.bypass('PM_Configure__c');
        update updateAnswer;
        TriggerBase.clearBypass('PM_Configure__c');
  Test.startTest();
            viewPmRequestsController.viewPMRequestsTable(Kra.Id);
        Test.stopTest();       
}
    
    public static testMethod void viewPMRequestsTableForCancelled() {
    //User u =[Select id from User ]
    Goal__c Kra =[Select Id from Goal__c limit 1];
    Id answerRecordTypeId = Schema.SObjectType.PM_Configure__c.getRecordTypeInfosByName().get('Answer').getRecordTypeId();

    List<PM_Configure__c> createPMConfigRecords =[Select id,Status__c,KRA__c from PM_Configure__c WHERE RecordTypeId =: answerRecordTypeId and KRA__c =:Kra.Id ];
         List<PM_Configure__c> updateAnswer = new  List<PM_Configure__c>();
        for(PM_Configure__c ans : createPMConfigRecords){
            ans.Status__c = 'Cancelled';
			updateAnswer.add(ans);            
        }
        TriggerBase.bypass('PM_Configure__c');
        update updateAnswer;
        TriggerBase.clearBypass('PM_Configure__c');
  Test.startTest();
            viewPmRequestsController.viewPMRequestsTable(Kra.Id);
        Test.stopTest();       
}
    
    public static testMethod void recallPmRequests() {
        //User u =[Select id from User ]
        Goal__c Kra =[Select Id,Resource__c from Goal__c limit 1];
        Id answerRecordTypeId = Schema.SObjectType.PM_Configure__c.getRecordTypeInfosByName().get('Answer').getRecordTypeId();
        List<PM_Configure__c> createPMConfigRecords =[Select id,Status__c,Reporting_Contact__c,KRA__c from PM_Configure__c WHERE RecordTypeId =: answerRecordTypeId and KRA__c =:Kra.Id and Reporting_Contact__c != null ];
        EMS_TM_Project__c project = [Select Id,Name from EMS_TM_Project__c];
        Test.startTest();
        viewPmRequestsController.recallPmRequests(Kra.Id,kra.Resource__c,project.Id,'Test');
        Test.stopTest();       
    }
    
}