force-app/main/default/objects/Contact/fields/EMS_Domain_Technology__c.field-meta.xml
<CustomField>
    <fullName>EMS_Domain_Technology__c</fullName>
    <label>Domain/Technology</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Salesforce</fullName>
            </value>
            <value>
                <fullName>HR</fullName>
            </value>
            <value>
                <fullName>TA</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_EM_Degree__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_Degree__c</fullName>
    <label>Diploma / Degree</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_EM_Job_Title1__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_Job_Title1__c</fullName>
    <label>Job Title</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_EM_Previous_Company_HR_EmailId__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_Previous_Company_HR_EmailId__c</fullName>
    <label>Previous Company HR EmailId</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_EM_Previous_Company_Name1__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_Previous_Company_Name1__c</fullName>
    <label>Previous Company Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_RM_Current_Job_Role__c.field-meta.xml
<CustomField>
    <fullName>EMS_RM_Current_Job_Role__c</fullName>
    <label>Designation</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accounts Manager</fullName>
            </value>
            <value>
                <fullName>Associate Business Analyst</fullName>
            </value>
            <value>
                <fullName>Associate Developer</fullName>
            </value>
            <value>
                <fullName>Associate Engineer</fullName>
            </value>
            <value>
                <fullName>Associate Project Manager</fullName>
            </value>
            <value>
                <fullName>Associate Salesforce Business Analyst</fullName>
            </value>
            <value>
                <fullName>Associate Salesforce Developer</fullName>
            </value>
            <value>
                <fullName>Associate Salesforce Quality Analyst</fullName>
            </value>
            <value>
                <fullName>Associate SFMC Developer</fullName>
            </value>
            <value>
                <fullName>Associate Talent Acquisition Partner</fullName>
            </value>
            <value>
                <fullName>Account Executive</fullName>
            </value>
            <value>
                <fullName>Accounts Executive</fullName>
            </value>
            <value>
                <fullName>Associate Architect</fullName>
            </value>
            <value>
                <fullName>Business Systems Analyst</fullName>
            </value>
            <value>
                <fullName>Consultant Architecture</fullName>
            </value>
            <value>
                <fullName>Data Analyst</fullName>
            </value>
            <value>
                <fullName>Data Scientist</fullName>
            </value>
            <value>
                <fullName>Delivery Manager</fullName>
            </value>
            <value>
                <fullName>Director of Sales</fullName>
            </value>
            <value>
                <fullName>HR Executive</fullName>
            </value>
            <value>
                <fullName>HR Manager</fullName>
            </value>
            <value>
                <fullName>Jr. UX Designer</fullName>
            </value>
            <value>
                <fullName>Lead Data Migration Engineer</fullName>
            </value>
            <value>
                <fullName>Lead Salesforce Business System Analyst</fullName>
            </value>
            <value>
                <fullName>Lead Salesforce Developer</fullName>
            </value>
            <value>
                <fullName>Lead Salesforce Quality Analyst</fullName>
            </value>
            <value>
                <fullName>Project Manager</fullName>
            </value>
            <value>
                <fullName>Salesforce Administrator</fullName>
            </value>
            <value>
                <fullName>Salesforce Application Designer</fullName>
            </value>
            <value>
                <fullName>Salesforce Business Analyst</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_RM_Domain_Technology__c.field-meta.xml
<CustomField>
    <fullName>EMS_RM_Domain_Technology__c</fullName>
    <label>Domain/Technology</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Salesforce</fullName>
            </value>
            <value>
                <fullName>HR</fullName>
            </value>
            <value>
                <fullName>TA</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_RM_Industry__c.field-meta.xml
<CustomField>
    <fullName>EMS_RM_Industry__c</fullName>
    <label>Department Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Information Technology</fullName>
            </value>
            <value>
                <fullName>Human Resource</fullName>
            </value>
            <value>
                <fullName>Technology</fullName>
            </value>
            <value>
                <fullName>Talent Acquisition</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ems_EM_Additional_Detail__c/ems_EM_Additional_Detail__c.object-meta.xml
<CustomObject>
    <label>Professional Proficiency</label>
    <nameField>
        <displayFormat>PP-{00000}</displayFormat>
        <label>Professional Proficiency Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Professional Proficiency</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ems_EM_Additional_Detail__c/fields/ContactId__c.field-meta.xml
<CustomField>
    <fullName>ContactId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Additional_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ems_EM_Additional_Detail__c/fields/EMS_EM_Degree__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_Degree__c</fullName>
    <label>Degree</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/ems_EM_Additional_Detail__c/fields/EMS_EM_Job_Title1__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_Job_Title1__c</fullName>
    <label>Job Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ems_EM_Additional_Detail__c/fields/EMS_EM_Previous_Company_HR_EmailId__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_Previous_Company_HR_EmailId__c</fullName>
    <label>Previous Company HR Email ID</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/ems_EM_Additional_Detail__c/fields/Onboarding_Request__c.field-meta.xml
<CustomField>
    <fullName>Onboarding_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Onboarding Request</label>
    <referenceTo>EMS_EM_Onboarding_Request__c</referenceTo>
    <relationshipName>Additional_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_EM_Onboarding_Request__c/EMS_EM_Onboarding_Request__c.object-meta.xml
<CustomObject>
    <label>Onboarding Request</label>
    <nameField>
        <displayFormat>O-{00000}</displayFormat>
        <label>Onboarding Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Onboarding Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_EM_Onboarding_Request__c/fields/EMS_EM_Degree__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_Degree__c</fullName>
    <label>Degree</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EMS_EM_Onboarding_Request__c/fields/EMS_EM_First_Name__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_First_Name__c</fullName>
    <label>First Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EMS_EM_Onboarding_Request__c/fields/EMS_EM_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_Last_Name__c</fullName>
    <label>Last Name</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EMS_EM_Onboarding_Request__c/fields/EMS_EM_Previous_Company_Name1__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_Previous_Company_Name1__c</fullName>
    <label>Previous Company Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/EMS_EM_Onboarding_Request__c/fields/Google_Drive_ID__c.field-meta.xml
<CustomField>
    <fullName>Google_Drive_ID__c</fullName>
    <label>Google Drive ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EMS_EM_Onboarding_Request__c/fields/Is_Inegration_Needed__c.field-meta.xml
<CustomField>
    <fullName>Is_Inegration_Needed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Inegration Needed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/ContactId__c.field-meta.xml
<CustomField>
    <fullName>ContactId__c</fullName>
    <formula>ContactId</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ContactId</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EMS_TM_GetmyInfoTestClass.cls
@isTest
public class EMS_TM_GetmyInfoTestClass {
    
     private class RestMock implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            String fullJson = '{"name" : "","mimeType" : "application/vnd.google-apps.folder"}';
            HTTPResponse res = new HTTPResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setBody(fullJson);
            res.setStatusCode(200);
            return res;
        }
    }   
    static testMethod void testcreateDriveFornewRequest(){
        Test.setMock(HttpCalloutMock.class, new RestMock());
        List<EMS_EM_Onboarding_Request__c> RequestList = new List<EMS_EM_Onboarding_Request__c>();
        EMS_EM_Onboarding_Request__c onboard =new EMS_EM_Onboarding_Request__c();
        Account accobj = new Account(
        Name ='test acc',
        phone ='1122334455');
          insert accobj;
        Contact contactObj = new Contact (
			FirstName = 'test value',
            Lastname='rdg',
            AccountId = accobj.id,
			EMS_Domain_Technology__c ='Salesforce', 
			//EMS_RM_Current_Job_Role__c ='Accountant', 
			EMS_RM_Domain_Technology__c ='Salesforce', 
			EMS_RM_Industry__c ='Information Technology', 
			email = 'testEmail@gmail.com',  
			phone = '1234567890'
		);
		insert contactObj;
        string contactId=contactObj.Id;
        onboard.EMS_EM_First_Name__c='test';
        onboard.EMS_EM_Last_Name__c='last';
        onboard.Is_Inegration_Needed__c=true;
        onboard.Google_Drive_ID__c = '';
        insert onboard;
        ems_EM_Additional_Detail__c additionalList=New ems_EM_Additional_Detail__c();
        additionalList.EMS_EM_Degree__c='BE';
        additionalList.EMS_EM_Job_Title1__c='Salesforce Dev';
        additionalList.EMS_EM_Previous_Company_HR_EmailId__c='san@gmail.com';
        additionalList.EMS_EM_Previous_Company_Name1__c='Cp';
        additionalList.ContactId__c=contactObj.Id;
        additionalList.Onboarding_Request__c=onboard.Id;
        test.startTest();
        Insert additionalList;
        RequestList.add(onboard);
        
        EMS_TM_GetmyInfo.getContactAdditionalInfo(contactId);
        test.stopTest();
    }

    @isTest static void testMethod1() {
        Account accobj = new Account(
        Name ='test acc',
        phone ='1122334455');
          insert accobj;
        Contact contactObj = new Contact (
			FirstName = 'test value',
            Lastname='rdg',
            AccountId = accobj.id,
			EMS_Domain_Technology__c ='Salesforce', 
			//EMS_RM_Current_Job_Role__c ='Accountant', 
			EMS_RM_Domain_Technology__c ='Salesforce', 
			EMS_RM_Industry__c ='Information Technology', 
			email = 'testEmail@gmail.com',  
			phone = '1234567890'
		);
        
		insert contactObj;    
       
        string contactObjId =contactObj.Id;
         Profile p = [Select id from profile where name='TM Customer Community'];
		User userObj = new User (
			ContactId = contactObj.id, 
			Username = 'trt3@gmail.com', 
			LastName = 'test', 
            firstName='te',
			Email = 'testEmail@gmail.com', 
			EmailPreferencesAutoBcc = TRUE, 
			EmailPreferencesAutoBccStayInTouch = TRUE, 
			EmailPreferencesStayInTouchReminder = TRUE, 
			Alias = 'test',
            isActive = true,
			CommunityNickname = 'test value', 
			TimeZoneSidKey ='Pacific/Kiritimati', 
			LocaleSidKey ='af_ZA', 
			EmailEncodingKey ='UTF-8', 
			ProfileId = p.id, 
            PortalRole = 'Manager',
			LanguageLocaleKey ='en_US'
			
		);
		
		 test.startTest();
        insert userObj;
         EMS_TM_GetmyInfo.getUserContactInfo(userObj.id); 
        EMS_TM_GetmyInfo.getUserInfo(contactObjId,'7767987565'); 
        test.stopTest();
	}
}