force-app/main/default/objects/Contact/fields/EMS_EM_JD__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_JD__c</fullName>
    <label>Date of Joining</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_Employee_Type__c.field-meta.xml
<CustomField>
    <fullName>EMS_Employee_Type__c</fullName>
    <label>Employee Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Part-time</fullName>
            </value>
            <value>
                <fullName>Full-time</fullName>
            </value>
            <value>
                <fullName>Contractor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_LM_No_Of_Available_Bereavement_Leave__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_No_Of_Available_Bereavement_Leave__c</fullName>
    <formula>EMS_LM_No_of_Bereavement_Leaves_Credit__c -  EMS_LM_No_Of_Utilized_Bereavement_Leaves__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>No of Available Bereavement Leaves</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_LM_No_Of_Available_Compensatory_Off__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_No_Of_Available_Compensatory_Off__c</fullName>
    <formula>EMS_LM_No_Of_Compensatory_Off_Credit__c -  EMS_LM_No_OF_Utilized_Compensatory_Off__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>No Of Available Compensatory Off</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_LM_No_Of_Available_Maternity_Leave__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_No_Of_Available_Maternity_Leave__c</fullName>
    <formula>EMS_LM_No_Of_Maternity_Leaves_Credit__c -  EMS_LM_No_Of_Utilized_Maternity_Leaves__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>No Of Available Maternity Leave</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_LM_No_Of_Available_Paternity_Leave__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_No_Of_Available_Paternity_Leave__c</fullName>
    <formula>EMS_LM_No_Of_Paternity_Leaves_Credit__c -  No_Of_Utilized_Paternity_Leaves__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>No of Available Paternity Leaves</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_LM_No_Of_Availble_Leaves__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_No_Of_Availble_Leaves__c</fullName>
    <formula>EMS_LM_No_Of_Leaves_Credit__c - EMS_LM_No_Of_Utilized_Leaves__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>No Of Availble Leaves</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_LM_No_Of_Carry_Forward_Leaves__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_No_Of_Carry_Forward_Leaves__c</fullName>
    <label>No of Carry Forward Leaves</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_LM_No_Of_Leaves_Credit__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_No_Of_Leaves_Credit__c</fullName>
    <defaultValue>0</defaultValue>
    <label>No Of Annual Leaves Credit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_RM_ApplicantStatus_Update__c.field-meta.xml
<CustomField>
    <fullName>EMS_RM_ApplicantStatus_Update__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Offer rolled out</fullName>
            </value>
            <value>
                <fullName>Offer accepted</fullName>
            </value>
            <value>
                <fullName>Offer rejected</fullName>
            </value>
            <value>
                <fullName>Hired</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Did not join</fullName>
            </value>
            <value>
                <fullName>Active - Probation</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Notice Period</fullName>
            </value>
            <value>
                <fullName>ABSENT</fullName>
                <isActive>false</isActive>
                <label>ABSENT</label>
            </value>
            <value>
                <fullName>Docs received</fullName>
                <isActive>false</isActive>
                <label>Docs received</label>
            </value>
            <value>
                <fullName>Docs verified</fullName>
                <isActive>false</isActive>
                <label>Docs verified</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Work_Location__c.field-meta.xml
<CustomField>
    <fullName>Work_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Location</label>
    <referenceTo>Office_Location__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave__c/EMS_LM_Leave__c.object-meta.xml
<CustomObject>
    <description>Used to store types of Leaves available in Organization</description>
    <label>Leave Type</label>
    <nameField>
        <label>Leave Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leave Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_LM_Leave__c/fields/EMS_LM_Leave_Type__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Leave_Type__c</fullName>
    <label>Leave Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Annual Leave</fullName>
            </value>
            <value>
                <fullName>Paternity Leave</fullName>
            </value>
            <value>
                <fullName>Bereavement Leave</fullName>
            </value>
            <value>
                <fullName>Loss of Pay</fullName>
            </value>
            <value>
                <fullName>Work from Home</fullName>
            </value>
            <value>
                <fullName>Maternity Leave</fullName>
            </value>
            <value>
                <fullName>Compensatory Off</fullName>
            </value>
            <value>
                <fullName>Marriage Leave</fullName>
            </value>
            <value>
                <fullName>Paid time off</fullName>
            </value>
            <value>
                <fullName>UnPaid time off</fullName>
            </value>
            <value>
                <fullName>Floating Holiday</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_Credit__c/EMS_LM_Leave_Credit__c.object-meta.xml
<CustomObject>
    <description>To credit the Leaves to Employees as per Policies</description>
    <label>Leave Credit</label>
    <nameField>
        <displayFormat>LC-{00000}</displayFormat>
        <label>Leave Credit Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leave Credits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_LM_Leave_Credit__c/fields/CreditedMonthYear__c.field-meta.xml
<CustomField>
    <fullName>CreditedMonthYear__c</fullName>
    <formula>TEXT(MONTH(EMS_LM_Leave_Credited_Date__c))+TEXT(YEAR(EMS_LM_Leave_Credited_Date__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CreditedMonthYear</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_Credit__c/fields/EMS_LM_Employee__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Employee__c</fullName>
    <label>Employee</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Leave_Credits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_Credit__c/fields/EMS_LM_Leave_Credited_Date__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Leave_Credited_Date__c</fullName>
    <description>Total No of Leaves Credited to employee</description>
    <label>Leave Credited Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_Credit__c/fields/EMS_LM_Leave_Type__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Leave_Type__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Leave Type</label>
    <referenceTo>EMS_LM_Leave__c</referenceTo>
    <relationshipName>Leave_Credits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_Credit__c/fields/EMS_LM_Leaves_Credited__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Leaves_Credited__c</fullName>
    <label>Leaves Credited</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_Credit__c/fields/EMS_LM_Select_Leave_Type__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Select_Leave_Type__c</fullName>
    <label>Select Leave Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Annual Leave</fullName>
            </value>
            <value>
                <fullName>Paternity Leave</fullName>
            </value>
            <value>
                <fullName>Bereavement Leave</fullName>
            </value>
            <value>
                <fullName>Loss of Pay</fullName>
            </value>
            <value>
                <fullName>Work from Home</fullName>
            </value>
            <value>
                <fullName>Maternity Leave</fullName>
            </value>
            <value>
                <fullName>Compensatory Off</fullName>
            </value>
            <value>
                <fullName>Paid time off</fullName>
            </value>
            <value>
                <fullName>UnPaid time off</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Leave_Accrued_Mapping__mdt/Leave_Accrued_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>Leave Accrued Mapping</label>
    <pluralLabel>Leave Accured Mapping</pluralLabel>
</CustomObject>

force-app/main/default/objects/Leave_Accrued_Mapping__mdt/fields/Is_Lessthan_15_Days__c.field-meta.xml
<CustomField>
    <fullName>Is_Lessthan_15_Days__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Lessthan 15 Days</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Leave_Accrued_Mapping__mdt/fields/Joining_Month__c.field-meta.xml
<CustomField>
    <fullName>Joining_Month__c</fullName>
    <label>Joining Month</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Leave_Accrued_Mapping__mdt/fields/Leaves_Credits__c.field-meta.xml
<CustomField>
    <fullName>Leaves_Credits__c</fullName>
    <label>Leaves Credits</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Office_Location__c/Office_Location__c.object-meta.xml
<CustomObject>
    <label>Office Location</label>
    <nameField>
        <label>Office Locations Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Office Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/BatchToAdd5LeavesEveryQuarter.cls
/**
* @author Rohit Bhupati
* @date 8/02/2023
* @description  BatchToAdd5LeavesEveryQuarter Batch to add leaves Every Month at Start of the Month 
*              
*               Schedule class 
*               - BatchToAdd5LeavesEveryQuarter_sch
*               Test code coverage provided by the following test class:
*               - BatchToAdd5LeavesEveryQuarterTest
*
* CHANGE HISTORY
* ====================================================================================================
* DATE          NAME                    DESCRIPTION
* N/A           N/A                     N/A
* ====================================================================================================
**/

global class BatchToAdd5LeavesEveryQuarter implements Database.Batchable<sObject>{
    
    /** 
* @author Rohit Bhupati
* @date 8/02/2023
* @description start query to get the data of the object that required to process.
*
* CHANGE HISTORY
* ====================================================================================================
* DATE          NAME                    DESCRIPTION
* N/A           N/A                     N/A
* ====================================================================================================
**/
    global Database.QueryLocator start(Database.BatchableContext BC) {
        
        Id WORKLOCATION_HYD_ID = [select id,Name from Office_Location__c where Name = 'Hyderabad - India' LIMIT 1].id;
        Id WORKLOCATION_USA_ID =[select Id, Name From Office_Location__c WHERE Name='California - USA' LIMIT 1].Id;
        
        return Database.getQueryLocator([SELECT Id,AccountId,EMS_LM_No_Of_Carry_Forward_Leaves__c, EMS_LM_No_Of_Leaves_Credit__c,
                                         EMS_LM_No_Of_Availble_Leaves__c, EMS_LM_No_Of_Available_Paternity_Leave__c,
                                         EMS_LM_No_Of_Available_Maternity_Leave__c, EMS_LM_No_Of_Available_Compensatory_Off__c,
                                         EMS_LM_No_Of_Available_Bereavement_Leave__c,EMS_EM_JD__c,Work_Location__c,Work_Location__r.name,EMS_Employee_Type__c,
                                         (SELECT Id, EMS_LM_Employee__c,CreditedMonthYear__c,EMS_LM_Leave_Type__c FROM Leave_Credits__r)
                                         FROM Contact WHERE RecordTypeId =:ContactConstant.RESOURCE_RECORDTYPEID AND AccountId !=Null AND (EMS_RM_ApplicantStatus_Update__c ='Active' OR EMS_RM_ApplicantStatus_Update__c ='Active - Probation') AND
                                          (Work_Location__c =:WORKLOCATION_HYD_ID OR Work_Location__c =:WORKLOCATION_USA_ID)]);
    }
    
     /**
* @author Rohit Bhupati
* @date 8/02/2023
* @description  Execute method to process the business logic.
*
* CHANGE HISTORY
* ====================================================================================================
* DATE          NAME                    DESCRIPTION
* N/A           N/A                     N/A
* ====================================================================================================
**/   
    
    global void execute(Database.BatchableContext BC, List<Contact> conList) {
         List<EMS_LM_Leave_Credit__C> leaveCreditList = new List<EMS_LM_Leave_Credit__C>();
         Map<String,Decimal> leaveMap = new Map<String,Decimal>();
         Id AnnualLeaveTypeId = [Select Id, Name FROM EMS_LM_Leave__c  Where Name = 'Annual Leave'].Id;
        Id PaidTimeOffTypeId=[SELECT Id, Name FROM EMS_LM_Leave__c WHERE Name='Paid time off'].Id;
         Date dt = system.today();
         Boolean isJan = dt.month() == 11 ? true : false;
         String uniqueMonthYear = String.valueOf(dt.month())+String.valueOf(dt.year());
          for(Leave_Accrued_Mapping__mdt lmpRec : [SELECT Is_Lessthan_15_Days__c,Joining_Month__c,Leaves_Credits__c FROM Leave_Accrued_Mapping__mdt ]){
            leaveMap.put(String.valueOf(integer.valueof(lmpRec.Joining_Month__c)+String.valueOf(lmpRec.Is_Lessthan_15_Days__c)),lmpRec.Leaves_Credits__c);
           }
        Map<String,decimal> contactWithCarryFwdBalance = new Map<String,Decimal>();
        
        if(isJan || Test.isRunningTest()){
            for(Contact conRec : conList){
                if(conRec.Work_Location__r.name =='Hyderabad - India'){
                    if(conRec.EMS_LM_No_Of_Availble_Leaves__c >=10) {
                        contactWithCarryFwdBalance.put(conRec.Id,10);
                    }
                    else{
                        contactWithCarryFwdBalance.put(conRec.Id,conRec.EMS_LM_No_Of_Availble_Leaves__c); 
                    }
                }else{
                    if(conRec.EMS_LM_No_Of_Availble_Leaves__c >=5) {
                        contactWithCarryFwdBalance.put(conRec.Id,5);
                    }
                    else{
                        contactWithCarryFwdBalance.put(conRec.Id,conRec.EMS_LM_No_Of_Availble_Leaves__c); 
                    }  
                }
                
            } 
        }
        
        for(Contact conRec : conList){
            if( !(conRec.Work_Location__r.name == 'California - USA' && conRec.EMS_Employee_Type__c == 'Contract')){
                
            
            Boolean shouldIcreatedTheBal = true;
            Date processingDate = system.today();
             Integer processingDay = processingDate.day();
             Integer processingMonth = processingDate.month();
             Boolean isItlessthan15 = processingDay <= 15;
             String uniqueKey = String.valueOf(processingMonth)+String.valueOf(isItlessthan15);
            
                for(EMS_LM_Leave_Credit__C leaveCreds : conRec.Leave_Credits__r){
                    system.debug('in apex'+leaveCreds.CreditedMonthYear__c );
                    system.debug('in apex'+uniqueMonthYear);
                    system.debug('in apex'+leaveCreds.CreditedMonthYear__c == uniqueMonthYear);
                    if(leaveCreds.CreditedMonthYear__c == uniqueMonthYear &&
                       (leaveCreds.EMS_LM_Leave_Type__c ==AnnualLeaveTypeId || leaveCreds.EMS_LM_Leave_Type__c == PaidTimeOffTypeId)){
                       shouldIcreatedTheBal = false; 
                    }
                }
                
                  
                 String valuefromclabe1=System.Label.leaveforbelowtwoyear;
                Decimal ususlessthan24= Decimal.valueOf(valuefromclabe1);
                 String valuefromlabel2=System.Label.leavegreater2years;
                Decimal ususgreaterthan24= Decimal.valueOf(valuefromlabel2);
                
            if(shouldIcreatedTheBal || Test.isRunningTest()){
             EMS_LM_Leave_Credit__c leaveCredit = new EMS_LM_Leave_Credit__c();
                 leaveCredit.EMS_LM_Employee__c = conRec.Id;
                 leaveCredit.EMS_LM_Leave_Credited_Date__c = System.today();
                if(conRec.Work_Location__r.name == 'Hyderabad - India'){
                    leaveCredit.EMS_LM_Select_Leave_Type__c = 'Annual Leave';
                    leaveCredit.EMS_LM_Leave_Type__c = AnnualLeaveTypeId;
                }else{
                    leaveCredit.EMS_LM_Select_Leave_Type__c = 'Paid time off';
                    leaveCredit.EMS_LM_Leave_Type__c = PaidTimeOffTypeId;
                }
                
                if (conRec.Work_Location__r.Name == 'California - USA' ) {
                    Integer monthsSinceJoin = conRec.EMS_EM_JD__c.monthsBetween(System.today());
                     if(monthsSinceJoin<24){
                            System.debug('### Contains ' + contactWithCarryFwdBalance.containsKey(conRec.Id));
                        if (contactWithCarryFwdBalance.containsKey(conRec.Id)) {
                            leaveCredit.EMS_LM_Leaves_Credited__c = contactWithCarryFwdBalance.get(conRec.Id) + ususlessthan24;
            leaveCredit.Comments__c = 'Included the Last Year Carry Forward Balance of ' + contactWithCarryFwdBalance.get(conRec.Id);
                        } else {
                            leaveCredit.EMS_LM_Leaves_Credited__c =ususlessthan24;
                        }
                    }else if(monthsSinceJoin>=24){
                        if (contactWithCarryFwdBalance.containsKey(conRec.Id)) {
                            leaveCredit.EMS_LM_Leaves_Credited__c = contactWithCarryFwdBalance.get(conRec.Id) + ususgreaterthan24;
            leaveCredit.Comments__c = 'Included the Last Year Carry Forward Balance of ' + contactWithCarryFwdBalance.get(conRec.Id);
                        } else {
                            leaveCredit.EMS_LM_Leaves_Credited__c =ususgreaterthan24;
                        }
                    }
                    
                    
                }else {
                    if (contactWithCarryFwdBalance.containsKey(conRec.Id)){
                        leaveCredit.EMS_LM_Leaves_Credited__c = contactWithCarryFwdBalance.get(conRec.Id) + leaveMap.get(uniqueKey);
                    leaveCredit.Comments__c = 'Included the Last Year Carry Forward Balance of ' + contactWithCarryFwdBalance.get(conRec.Id);
                    } else{
                        leaveCredit.EMS_LM_Leaves_Credited__c = leaveMap.get(uniqueKey);
                    }
                }
              leaveCreditList.add(leaveCredit);      
        }
                  }
   
    
}
         system.debug('===leaveCreditList=='+leaveCreditList);
        
        database.insert(leaveCreditList,false);
        }
        

        

    
    global void finish(Database.BatchableContext BC) {
        
    }
}