force-app/main/default/objects/Contact/fields/EMS_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>EMS_Phone_Number__c</fullName>
    <label>Contact Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Official_Mail__c.field-meta.xml
<CustomField>
    <fullName>Official_Mail__c</fullName>
    <label>Official Email ID(old)</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Resource_Role__c.field-meta.xml
<CustomField>
    <fullName>Resource_Role__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Role</label>
    <referenceTo>Resource_Role__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave__c/EMS_LM_Leave__c.object-meta.xml
<CustomObject>
    <description>Used to store types of Leaves available in Organization</description>
    <label>Leave Type</label>
    <nameField>
        <label>Leave Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leave Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_LM_Leave__c/fields/EMS_LM_Leave_Type__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Leave_Type__c</fullName>
    <label>Leave Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Annual Leave</fullName>
            </value>
            <value>
                <fullName>Paternity Leave</fullName>
            </value>
            <value>
                <fullName>Bereavement Leave</fullName>
            </value>
            <value>
                <fullName>Loss of Pay</fullName>
            </value>
            <value>
                <fullName>Work from Home</fullName>
            </value>
            <value>
                <fullName>Maternity Leave</fullName>
            </value>
            <value>
                <fullName>Compensatory Off</fullName>
            </value>
            <value>
                <fullName>Marriage Leave</fullName>
            </value>
            <value>
                <fullName>Paid time off</fullName>
            </value>
            <value>
                <fullName>UnPaid time off</fullName>
            </value>
            <value>
                <fullName>Floating Holiday</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_History__c/EMS_LM_Leave_History__c.object-meta.xml
<CustomObject>
    <description>It will show the employee Leave and WFH Requests.</description>
    <label>Leave Request</label>
    <nameField>
        <displayFormat>LH-{00000}</displayFormat>
        <label>Leave History Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leaves Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_LM_Leave_History__c/fields/EMS_LM_Contact__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Leaves History</relationshipLabel>
    <relationshipName>Leaves_History</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_History__c/fields/EMS_LM_Day__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Day__c</fullName>
    <label>Day</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full Day</fullName>
            </value>
            <value>
                <fullName>First Half</fullName>
            </value>
            <value>
                <fullName>Second Half</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_History__c/fields/EMS_LM_Leave_Duration__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Leave_Duration__c</fullName>
    <label>Leave Duration</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_History__c/fields/EMS_LM_Leave_End_Date__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Leave_End_Date__c</fullName>
    <label>Leave End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_History__c/fields/EMS_LM_Leave_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Leave_Start_Date__c</fullName>
    <label>Leave Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_History__c/fields/EMS_LM_Leave_Type__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Leave_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Leave Type</label>
    <referenceTo>EMS_LM_Leave__c</referenceTo>
    <relationshipLabel>Leaves History</relationshipLabel>
    <relationshipName>Leaves_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_History__c/fields/EMS_LM_Leave_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Leave_Type_Name__c</fullName>
    <label>Leave Type Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Annual Leave</fullName>
            </value>
            <value>
                <fullName>Paternity Leave</fullName>
            </value>
            <value>
                <fullName>Bereavement Leave</fullName>
            </value>
            <value>
                <fullName>Loss of Pay</fullName>
            </value>
            <value>
                <fullName>Work From Home</fullName>
            </value>
            <value>
                <fullName>Maternity Leave</fullName>
            </value>
            <value>
                <fullName>Compensatory Off</fullName>
            </value>
            <value>
                <fullName>Marriage Leave</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_History__c/fields/EMS_LM_Reason__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Reason__c</fullName>
    <label>Reason</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_History__c/fields/EMS_LM_Status__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Approver 2 Pending</fullName>
            </value>
            <value>
                <fullName>Approver 1 Pending</fullName>
            </value>
            <value>
                <fullName>Auto Approved</fullName>
            </value>
            <value>
                <fullName>Waiting For Approver 3</fullName>
                <isActive>false</isActive>
                <label>Waiting For Approver 3</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Resource_Role__c/Resource_Role__c.object-meta.xml
<CustomObject>
    <label>Resource Role</label>
    <nameField>
        <label>Resource Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resource Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CP_utilizedLeaveBalanceTest.cls
/**
* @author Suneel and Rakshitha 
* @date 11/01/2023
* @description  This Test class is used for leave balance updating after utilized leaves
*            
*
*               
* CHANGE HISTORY
* ====================================================================================================
* DATE          NAME                    DESCRIPTION
* N/A           N/A                     N/A
* ====================================================================================================
**/
@isTest
public class CP_utilizedLeaveBalanceTest {

    public static testmethod void utilizedLeaveBalanceCalculationTest(){
        /*
        Resource_Role__c role = TestDataFactory.createResourceRole(true);
        Account acc = TestDataFactory.createAccount(true);
        
        
        
         EMS_LM_Leave__c  annualtype = TestDataFactory.createLeaveType('Annual Leave',true);
            EMS_LM_Leave__c loptype = TestDataFactory.createLeaveType('Loss of Pay',true);
            EMS_LM_Leave__c bretype = TestDataFactory.createLeaveType('Maternity Leave',true);
            EMS_LM_Leave__c compofftype = TestDataFactory.createLeaveType('Compensatory Off',true);
            EMS_LM_Leave__c wfhtype = TestDataFactory.createLeaveType('Work From Home',true);
            EMS_LM_Leave__c paidTimeOff = TestDataFactory.createLeaveType('Paid time off',true);
            EMS_LM_Leave__c Bereavement = TestDataFactory.createLeaveType('Bereavement Leave',true);
       Contact con = new Contact();
        con.lastName = 'Test';
        con.EMS_Phone_Number__c = '8645823254';
        con.Official_Mail__c = null;
        con.Email = 'test@gmail.com';
        insert con;
        List<EMS_LM_Leave_History__c> leaveHistoryList = new List<EMS_LM_Leave_History__c>();
        List<EMS_LM_Leave_History__c> leaveHistoryOldList = new List<EMS_LM_Leave_History__c>();
         EMS_LM_Leave_History__c leaveHistory = new EMS_LM_Leave_History__c(); 
            leaveHistory.EMS_LM_Contact__c = con.Id;
            leaveHistory.EMS_LM_Day__c = 'Full Day';
            leaveHistory.EMS_LM_Leave_Start_Date__c = date.parse('1/23/2024');
            leaveHistory.EMS_LM_Leave_End_Date__c = date.parse('1/23/2024');
            leaveHistory.EMS_LM_Leave_Type__c = [SELECT Id FROM EMS_LM_Leave__c WHERE Name = 'Annual Leave'].Id;
            leaveHistory.EMS_LM_Leave_Duration__c = 1;
            leaveHistory.EMS_LM_Reason__c = 'Test Reason';
            leaveHistory.EMS_LM_Status__c =  'Pending';
            leaveHistory.EMS_LM_Leave_Type_Name__c = 'Annual Leave';
            insert leaveHistory;
              Test.setCreatedDate(leaveHistory.Id, DateTime.newInstance(2024,01,01));
                system.debug('leaveHistory leaveHistory '+leaveHistory);

        system.debug('leaveHistory creadted '+leaveHistory.CreatedDate);
         system.debug('leaveHistory type '+leaveHistory.Leave_Type_Name__c);
        
        EMS_LM_Leave_History__c leaveHistoryOld = new EMS_LM_Leave_History__c();
        leaveHistoryOld.EMS_LM_Leave_Type_Name__c = 'Paid time off';
        leaveHistoryOld.EMS_LM_Status__c = 'Pending';
        leaveHistoryOld.EMS_LM_Leave_Duration__c = 5;
        leaveHistoryOld.EMS_LM_Contact__c = con.Id;
        leaveHistoryOld.EMS_LM_Leave_End_Date__c = date.parse('1/5/2024');
        leaveHistoryOld.EMS_LM_Leave_Start_Date__c = date.parse('5/5/2024');
        insert leaveHistoryOld;
        EMS_LM_Leave_History__c leaveHistory1 = new EMS_LM_Leave_History__c();
        leaveHistory1.EMS_LM_Leave_Type_Name__c = 'Bereavement Leave';
        leaveHistory1.EMS_LM_Status__c = 'Approved';
        leaveHistory1.EMS_LM_Leave_Duration__c = 5;
        leaveHistory1.EMS_LM_Contact__c = con.Id;
        leaveHistory1.EMS_LM_Leave_End_Date__c = date.parse('6/5/2024');
        leaveHistory1.EMS_LM_Leave_Start_Date__c = date.parse('7/5/2024');
        insert leaveHistory1;
        leaveHistoryOldList.add(leaveHistoryOld);
        leaveHistoryList.add(leaveHistory);
        leaveHistoryList.add(leaveHistory1);
        test.startTest();
        CP_utilizedLeaveBalance.utilizedLeaveBalanceCalculation(leaveHistoryList);
        CP_utilizedLeaveBalance.afterUpdate(leaveHistoryList,leaveHistoryOldList);
        CP_utilizedLeaveBalance.leaveCheck();
        test.stopTest(); 
       */ 
        
    }

}