force-app/main/default/objects/Contact/fields/EMS_TM_User__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/EMS_Timesheet__c.object-meta.xml
<CustomObject>
    <label>Timesheet</label>
    <nameField>
        <displayFormat>TS-{0000}</displayFormat>
        <label>Time Sheet ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_Timesheet__c/fields/EMS_TM_Status__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Not Approved</fullName>
            </value>
            <value>
                <fullName>Reported</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Saved</fullName>
            </value>
            <value>
                <fullName>Locked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/enddate__c.field-meta.xml
<CustomField>
    <fullName>enddate__c</fullName>
    <formula>CASE( 
MOD( EMS_TM_Week__c - DATE(1900, 1, 6),7), 
0, EMS_TM_Week__c + 7, 
1, EMS_TM_Week__c + 6, 
2, EMS_TM_Week__c + 5, 
3, EMS_TM_Week__c + 4, 
4, EMS_TM_Week__c + 3, 
5, EMS_TM_Week__c + 2, 
6, EMS_TM_Week__c + 1,
7, EMS_TM_Week__c + 0, 
NULL 
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>endWeek</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EMS_Timesheet__c/fields/startweek__c.field-meta.xml
<CustomField>
    <fullName>startweek__c</fullName>
    <formula>CASE(
MOD( EMS_TM_Week__c - DATE(1900, 1, 6),7),
0, EMS_TM_Week__c ,
1, EMS_TM_Week__c ,
2, EMS_TM_Week__c ,
3, EMS_TM_Week__c - 1,
4, EMS_TM_Week__c - 2,
5, EMS_TM_Week__c - 3,
6, EMS_TM_Week__c - 4,
NULL
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>startweek</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/EMS_TM_EmployeeescalationBatch.cls
/**
* @author Ramakrishna Papana
* @date 27/02/2023
* @description  Schedule class to schedule EMS_TM_EmployeeescalationBatch
*              
*                 Schedule class 
*               - EMS_TM_EmployeeescalationBatch_Sch
*               Test code coverage provided by the following test class:
*               - EMS_TM_EmployeeescalationBatch_test
*
* CHANGE HISTORY
* ====================================================================================================
* DATE          NAME                    DESCRIPTION
* N/A           N/A                     N/A
* ====================================================================================================
**/
global class EMS_TM_EmployeeescalationBatch implements Database.Batchable<sObject>{
    
    /**
* @author Ramakrishna
* @date 27/02/2023
* @description start query to get the data of the object that required to process.
*
* CHANGE HISTORY
* ====================================================================================================
* DATE          NAME                    DESCRIPTION
* N/A           N/A                     N/A
* ====================================================================================================
**/ 
    global Database.QueryLocator start(Database.BatchableContext bc) {
        
        String submitted ='Submitted';
        String soql ='SELECT Id, OwnerId, owner.name,owner.email,enddate__c, startweek__c FROM EMS_Timesheet__c where EMS_TM_Status__c !=:submitted AND (createddate = This_week OR createddate = Last_week)';
        System.debug('soql'+soql);
        return Database.getQueryLocator(soql);
    }
    
    /**
* @author Ramakrishna
* @date 27/02/2023
* @description  Execute method to process the business logic.
*
* CHANGE HISTORY
* ====================================================================================================
* DATE          NAME                    DESCRIPTION
* N/A           N/A                     N/A
* ====================================================================================================
**/
    global void execute(Database.BatchableContext bc, List<EMS_Timesheet__c> timesheetList) {
        System.debug('timesheetList'+timesheetList);
        
        map<id,EMS_Timesheet__c> userMap = new map<id,EMS_Timesheet__c>();
        for(EMS_Timesheet__c timesheetRec : timesheetList){
            userMap.put(timesheetRec.OwnerId,timesheetRec);
            
        }
        List<Messaging.SingleEmailMessage> mailsList =  new List<Messaging.SingleEmailMessage>(); 
        EmailTemplate emailTemplate =[Select Id,
                                      Subject,
                                      Description,
                                      HtmlValue,
                                      DeveloperName,
                                      Body 
                                      FROM EmailTemplate
                                      WHERE name ='Escalation Mail Send To Employee'];
        OrgWideEmailAddress emailid = [SELECT Id, 
                                       Address, 
                                       DisplayName 
                                       FROM OrgWideEmailAddress 
                                       WHERE DisplayName ='Grid'];
        for(contact contactRec :[SELECT Id,
                                         LastName,
                                         FirstName, 
                                         Email,
                                         EMS_TM_USER__C FROM contact 
                                         WHERE EMS_TM_USER__C =: userMap.keyset() 
                                         AND Email != null
                                         AND IsEmailBounced = false]){              
                                             Messaging.SingleEmailMessage mail =  new Messaging.SingleEmailMessage();               
                                             mail.setToAddresses(new list<string>{contactRec.Email});                
                                             mail.setOrgWideEmailAddressId(emailid.Id);
                                             mail.setTemplateID(emailTemplate.Id);
                                             mail.setTargetObjectId(contactRec.id);
                                             mail.setSaveAsActivity(false);         
                                             // mail.setTreatTargetObjectAsRecipient(true);      
                                             System.debug('mail '+mail); 
                                             mailsList.add(mail);                           
                                 }
        System.debug('mailsList'+mailsList);
        System.debug('mailssize'+mailsList.size());
        try{
        Messaging.sendEmail(mailsList);
        }catch(Exception e){
            
        }
        
    }
    
    global void finish(Database.BatchableContext bc) {
        
    }
    
    
}