force-app/main/default/objects/Contact/fields/EMS_LM_No_Of_Availble_Leaves__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_No_Of_Availble_Leaves__c</fullName>
    <formula>EMS_LM_No_Of_Leaves_Credit__c - EMS_LM_No_Of_Utilized_Leaves__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>No Of Availble Leaves</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_LM_No_Of_Leaves_Credit__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_No_Of_Leaves_Credit__c</fullName>
    <defaultValue>0</defaultValue>
    <label>No Of Annual Leaves Credit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_LM_No_Of_Utilized_Leaves__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_No_Of_Utilized_Leaves__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Annual available leaves of employee</description>
    <label>No of Utilized Annual Leaves</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_LM_No_Of_Utilized_Loss_Of_Pay__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_No_Of_Utilized_Loss_Of_Pay__c</fullName>
    <defaultValue>0</defaultValue>
    <label>No of Utilized Loss of Pay</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/No_of_Avilable_floatLeave_credits__c.field-meta.xml
<CustomField>
    <fullName>No_of_Avilable_floatLeave_credits__c</fullName>
    <label>No of Avilable floatLeave credits</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/No_OF_Utilized_Work_from_Home__c.field-meta.xml
<CustomField>
    <fullName>No_OF_Utilized_Work_from_Home__c</fullName>
    <defaultValue>0</defaultValue>
    <label>No of Utilized Work from Home</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/UtlizedFloatLeaves__c.field-meta.xml
<CustomField>
    <fullName>UtlizedFloatLeaves__c</fullName>
    <label>No Of UtlizedFloatLeaves</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ContactInformationController.cls
public without sharing class ContactInformationController {
  @AuraEnabled(Cacheable=true)
    Public static Contact contctInfoMethod(ID userId){
        Contact conDetails=new Contact();
        User usr=[SELECT Id,ContactId FROM User Where Id =: userId];
        if(usr.ContactId != null){
             conDetails=[SELECT Id,EMS_LM_No_Of_Utilized_Leaves__c,EMS_LM_No_Of_Leaves_Credit__c,EMS_LM_No_Of_Availble_Leaves__c,
                               No_of_Avilable_floatLeave_credits__c,UtlizedFloatLeaves__c,EMS_LM_No_Of_Utilized_Loss_Of_Pay__c,No_OF_Utilized_Work_from_Home__c
                               FROM Contact WHERE ID =: usr.ContactId Limit 1];
            
        }
        return conDetails;
    }
}