force-app/main/default/objects/Contact/fields/HR_Email__c.field-meta.xml
<CustomField>
    <fullName>HR_Email__c</fullName>
    <label>HR Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/TA_Email__c.field-meta.xml
<CustomField>
    <fullName>TA_Email__c</fullName>
    <label>TA Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Employee_Details__mdt/Employee_Details__mdt.object-meta.xml
<CustomObject>
    <label>Employee Details</label>
    <pluralLabel>Employee Details</pluralLabel>
</CustomObject>

force-app/main/default/classes/CP_AutoFillHrTaMails.cls
public class CP_AutoFillHrTaMails implements TriggerAction.BeforeInsert{
    
	public void beforeInsert(List<Contact> newList) {      
         System.debug(LoggingLevel.DEBUG, 'CP_AutoFillHrTaMails.beforeInsert() : BEGIN');
         updateEmails(newList);
         System.debug(LoggingLevel.DEBUG, 'CP_AutoFillHrTaMails.beforeInsert() : END');       
     }
    
    private void updateEmails(List<Contact> contactList){
        String hrTeamEmail = [SELECT id, DeveloperName, Email__c from Employee_Details__mdt WHERE DeveloperName = 'HR_Team'].Email__c;
        String taTeamEmail = [SELECT id, DeveloperName, Email__c from Employee_Details__mdt WHERE DeveloperName = 'TA_Team'].Email__c;        
        for(Contact contactRec : contactList){
            if(hrTeamEmail != NULL){
                contactRec.HR_Email__c = hrTeamEmail;
            }
            if(taTeamEmail != NULL){
                contactRec.TA_Email__c = taTeamEmail;
            }
        }
    }
}