force-app/main/default/objects/Contact/fields/LeaveApprover__c.field-meta.xml
<CustomField>
    <fullName>LeaveApprover__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This lookup field will store the contact value, which is the Leave approver for the contact.
The leave approver will be decided by the relationship type field on the Resource relationship object record.</description>
    <label>Leave Approver</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contacts (Leave Approver)</relationshipLabel>
    <relationshipName>LeaveApprover</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Resource.recordType-meta.xml
<RecordType>
    <fullName>Resource</fullName>
    <active>true</active>
    <label>Resource</label>
</RecordType>

force-app/main/default/objects/Resource_Resource_Relationship__c/Resource_Resource_Relationship__c.object-meta.xml
<CustomObject>
    <label>Resource Relationship</label>
    <nameField>
        <displayFormat>RRR-{000000}</displayFormat>
        <label>Resource Resource Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource_Resource_Relationship__c/fields/Relationship_Type__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Type__c</fullName>
    <label>Relationship Type</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mentor</fullName>
            </value>
            <value>
                <fullName>Leave Approver</fullName>
            </value>
            <value>
                <fullName>Resource Manager</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Resource_Resource_Relationship__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <label>Resource</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Resource Relationships (Reports To)</relationshipLabel>
    <relationshipName>Resource_Resource_Relationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Resource_Resource_Relationship__c/fields/Resource_Reports_To__c.field-meta.xml
<CustomField>
    <fullName>Resource_Reports_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Reports To</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Relationships_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/updateReportOnResource.cls
/**
* @author Subba Kalavala
* @date 10/01/2023
* @description  updateReportOnResource Class to populat the Reports TO value on Contact
*
*               Test code coverage provided by the following test class:
*               - updateReportOnResourceTest
*
* CHANGE HISTORY
* ====================================================================================================
* DATE          NAME                    DESCRIPTION
* N/A           N/A                     N/A
* ====================================================================================================
**/
public without sharing class updateReportOnResource implements TriggerAction.AfterInsert, TriggerAction.AfterUpdate {
 /**
    * @author Subba Kalavala
    * @date 10/01/2023
    * @description Before Insert 
    *
    * CHANGE HISTORY
    * ====================================================================================================
    * DATE          NAME                    DESCRIPTION
    * N/A           N/A                     N/A
    * ====================================================================================================
    **/
    public void AfterInsert(List<Resource_Resource_Relationship__c> newList) {      
        System.debug(LoggingLevel.DEBUG, 'updateReportOnResource.AfterInsert() : BEGIN');
        populateTheReportsTo(newList);
        System.debug(LoggingLevel.DEBUG, 'updateReportOnResource.AfterInsert() : END');       
    }
    
    public void AfterUpdate(List<Resource_Resource_Relationship__c> newList, List<Resource_Resource_Relationship__c> oldList) {      
        System.debug(LoggingLevel.DEBUG, 'updateReportOnResource.AfterUpdate() : BEGIN');
        populateTheReportsTo(newList);
        System.debug(LoggingLevel.DEBUG, 'updateReportOnResource.AfterUpdate() : END');       
    }
    
    
    /**
    *   {Purpose} - Method to populate the Reports to Value 
    *
    *   CHANGE HISTORY
    *   ====================================================================================================
    *   Date        Name                    Description
    *   N/A         N/A                     N/A
    *   ====================================================================================================
    **/
    private void populateTheReportsTo(List<Resource_Resource_Relationship__c> newlist) {
        List<Contact> contactUpdate = new List<Contact>();
        
        for (Resource_Resource_Relationship__c newRec : newlist) {
            System.debug('RelationshipRecord :::' + newRec.Relationship_Type__c);
            
            if (newRec.Resource_Reports_To__c != null) {
                Contact contactToUpdate = new Contact(Id=newRec.Resource__c);
                
                // Check if 'Leave Approver' is in the multi-select picklist
                if (newRec.Relationship_Type__c.contains('Leave Approver')) {
                    contactToUpdate.LeaveApprover__c = newRec.Resource_Reports_To__c;
                }
                
                // Check if 'Resource Manager' is in the multi-select picklist
                if (newRec.Relationship_Type__c.contains('Resource Manager')) {
                    contactToUpdate.ReportsToId = newRec.Resource_Reports_To__c;
                }
                                
                // Add the updated contact to the list
                contactUpdate.add(contactToUpdate);
            }
        }
        
        try{
           TriggerBase.bypass('Contact');
           System.debug('contactUpdate :::' +  contactUpdate);
           // Perform the update
            if (!contactUpdate.isEmpty()) {
                update contactUpdate;
            }
            System.debug('contactUpdate :::' +  contactUpdate);
           TriggerBase.clearBypass('Contact');
        }catch(exception ex){
          LogException.logHandledException(ex, 'updateReportOnResource', 'populateTheReportsTo');  
        }
        
        
    }
}