force-app/main/default/objects/Contact/fields/Probationary_Period_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Probationary_Period_End_Date__c</fullName>
    <label>Probationary Period End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Resource_Role__c.field-meta.xml
<CustomField>
    <fullName>Resource_Role__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Role</label>
    <referenceTo>Resource_Role__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave__c/EMS_LM_Leave__c.object-meta.xml
<CustomObject>
    <description>Used to store types of Leaves available in Organization</description>
    <label>Leave Type</label>
    <nameField>
        <label>Leave Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leave Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_LM_Leave__c/fields/EMS_LM_Leave_Type__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Leave_Type__c</fullName>
    <label>Leave Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Annual Leave</fullName>
            </value>
            <value>
                <fullName>Paternity Leave</fullName>
            </value>
            <value>
                <fullName>Bereavement Leave</fullName>
            </value>
            <value>
                <fullName>Loss of Pay</fullName>
            </value>
            <value>
                <fullName>Work from Home</fullName>
            </value>
            <value>
                <fullName>Maternity Leave</fullName>
            </value>
            <value>
                <fullName>Compensatory Off</fullName>
            </value>
            <value>
                <fullName>Marriage Leave</fullName>
            </value>
            <value>
                <fullName>Paid time off</fullName>
            </value>
            <value>
                <fullName>UnPaid time off</fullName>
            </value>
            <value>
                <fullName>Floating Holiday</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_History__c/EMS_LM_Leave_History__c.object-meta.xml
<CustomObject>
    <description>It will show the employee Leave and WFH Requests.</description>
    <label>Leave Request</label>
    <nameField>
        <displayFormat>LH-{00000}</displayFormat>
        <label>Leave History Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leaves Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_LM_Leave_History__c/fields/EMS_LM_Contact__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Leaves History</relationshipLabel>
    <relationshipName>Leaves_History</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_History__c/fields/EMS_LM_Leave_Duration__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Leave_Duration__c</fullName>
    <label>Leave Duration</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_History__c/fields/EMS_LM_Leave_End_Date__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Leave_End_Date__c</fullName>
    <label>Leave End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_History__c/fields/EMS_LM_Leave_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Leave_Start_Date__c</fullName>
    <label>Leave Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_History__c/fields/EMS_LM_Leave_Type__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Leave_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Leave Type</label>
    <referenceTo>EMS_LM_Leave__c</referenceTo>
    <relationshipLabel>Leaves History</relationshipLabel>
    <relationshipName>Leaves_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_History__c/fields/EMS_LM_Status__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Approver 2 Pending</fullName>
            </value>
            <value>
                <fullName>Approver 1 Pending</fullName>
            </value>
            <value>
                <fullName>Auto Approved</fullName>
            </value>
            <value>
                <fullName>Waiting For Approver 3</fullName>
                <isActive>false</isActive>
                <label>Waiting For Approver 3</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Resource_Role__c/Resource_Role__c.object-meta.xml
<CustomObject>
    <label>Resource Role</label>
    <nameField>
        <label>Resource Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resource Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/restrictOnlyOneDayOnProbation.cls
/**
* @author Subba Kalavala
* @date 2/22/2023
* @description  restrictOnlyOneDayOnProbation Class to restrict the leave as only one
*
*               Test code coverage provided by the following test class:
*               - 
*
* CHANGE HISTORY
* ====================================================================================================
* DATE          NAME                    DESCRIPTION
* N/A           N/A                     N/A
* ====================================================================================================
**/
public class restrictOnlyOneDayOnProbation implements TriggerAction.BeforeInsert,TriggerAction.BeforeUpdate {
    /**
* @author Subba Kalavala
* @date 2/22/2023
* @description Before Insert 
*
* CHANGE HISTORY
* ====================================================================================================
* DATE          NAME                    DESCRIPTION
* N/A           N/A                     N/A
* ====================================================================================================
**/
    public void beforeInsert(List<EMS_LM_Leave_History__c> newList) {      
        System.debug(LoggingLevel.DEBUG, 'restrictOnlyOneDayOnProbation.beforeInsert() : BEGIN');
        restrictTheProbLeave(newList);
        System.debug(LoggingLevel.DEBUG, 'restrictOnlyOneDayOnProbation.beforeInsert() : END');       
    }
    
     public void beforeUpdate(List<EMS_LM_Leave_History__c> newList , List<EMS_LM_Leave_History__c> oldList) {      
        System.debug(LoggingLevel.DEBUG, 'restrictOnlyOneDayOnProbation.beforeUpdate() : BEGIN');
        restrictTheProbLeave(newList);
        System.debug(LoggingLevel.DEBUG, 'restrictOnlyOneDayOnProbation.beforeUpdate() : END');       
    }
    
    
    /**
*   {Purpose} - Method to restrict the same date leaves 
*
*   CHANGE HISTORY
*   ====================================================================================================
*   Date        Name                    Description
*   N/A         N/A                     N/A
*   ====================================================================================================
**/
    public void restrictTheProbLeave(List<EMS_LM_Leave_History__c> newlist) {
        set<String> resourcId = new set<String>();
        Map<Id,Contact> contactMap = new Map<Id,Contact>();
        for(EMS_LM_Leave_History__c his : newlist){
                resourcId.add(his.EMS_LM_Contact__c);
        }
        
        for(Contact con : [SELECT Id,Resource_Role__c,Probationary_Period_End_Date__c,(SELECT Id,Leave_Type_Name__c,EMS_LM_Leave_Duration__c,EMS_LM_Leave_End_Date__c,EMS_LM_Leave_Start_Date__c FROM Leaves_History__r 
                                      WHERE EMS_LM_Leave_End_Date__c = THIS_YEAR AND EMS_LM_Status__c != 'Cancelled' AND EMS_LM_Status__c != 'Rejected' AND
                                                                                      EMS_LM_Leave_Type__r.EMS_LM_Leave_Type__c !=:LeaveRequestConstant.WORK_FROM_HOME) 
                           FROM Contact WHERE Id IN:resourcId AND Probationary_Period_End_Date__c != null AND Probationary_Period_End_Date__c > Today]){
          contactMap.put(con.Id,con);  
        }
        
        for(EMS_LM_Leave_History__c his : newlist){
            if(contactMap.containsKey(his.EMS_LM_Contact__c)){
                
                Integer numberDaysDue = his.EMS_LM_Leave_Start_Date__c.daysBetween(his.EMS_LM_Leave_End_Date__c )+1;
                system.debug('numberDaysDue-->'+numberDaysDue);
                if(numberDaysDue > 1){
                    his.addError('During Probation, only one day PTO is allowed per month. Please check the duration and try again.');
                }else{
                    String uniqueMonthYear = String.valueOf((his.EMS_LM_Leave_Start_Date__c).month())+String.valueOf((his.EMS_LM_Leave_Start_Date__c).year());
                    for(EMS_LM_Leave_History__c leave : contactMap.get(his.EMS_LM_Contact__c).Leaves_History__r){
                      String existingUniqueMonthYear = String.valueOf((leave.EMS_LM_Leave_Start_Date__c).month())+String.valueOf((leave.EMS_LM_Leave_Start_Date__c).year());   
                        if(uniqueMonthYear == existingUniqueMonthYear){
                            his.addError('During Probation, only one PTO is allowed Per month. Seems you already availed allowed PTO for this month.');
                            break;
                        }
                    }
                }
            }
        }
        
    }
}