force-app/main/default/objects/Contact/fields/Resource_Role__c.field-meta.xml
<CustomField>
    <fullName>Resource_Role__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Role</label>
    <referenceTo>Resource_Role__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Goal__c/Goal__c.object-meta.xml
<CustomObject>
    <label>Goal</label>
    <nameField>
        <displayFormat>GOAL{000000}</displayFormat>
        <label>Goal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Goals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Goal__c/fields/Average_Goals_And_Result_Rating__c.field-meta.xml
<CustomField>
    <fullName>Average_Goals_And_Result_Rating__c</fullName>
    <label>Average Goals And Result Rating</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Goal__c/fields/Average_Professional_Skills_Rating__c.field-meta.xml
<CustomField>
    <fullName>Average_Professional_Skills_Rating__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Average Professional Skills Rating</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Goal__c/fields/Average_Strategic_Impact_Rating__c.field-meta.xml
<CustomField>
    <fullName>Average_Strategic_Impact_Rating__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Average Strategic Impact Rating</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Goal__c/fields/Average_Technical_Skills_Rating__c.field-meta.xml
<CustomField>
    <fullName>Average_Technical_Skills_Rating__c</fullName>
    <label>Average Technical Skills Rating</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Goal__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <label>Rating</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Goal__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Goals</relationshipLabel>
    <relationshipName>Goals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Goal__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Missed</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>KRA Inreview</fullName>
            </value>
            <value>
                <fullName>KRA Completed</fullName>
            </value>
            <value>
                <fullName>Pulse Submitted</fullName>
            </value>
            <value>
                <fullName>Pulse Requested</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>HR KRA Completed</fullName>
            </value>
            <value>
                <fullName>Completed - OnTime</fullName>
                <isActive>false</isActive>
                <label>Completed - OnTime</label>
            </value>
            <value>
                <fullName>Completed - PostTime</fullName>
                <isActive>false</isActive>
                <label>Completed - PostTime</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Goal__c/recordTypes/Goal.recordType-meta.xml
<RecordType>
    <fullName>Goal</fullName>
    <active>true</active>
    <label>Goal</label>
</RecordType>

force-app/main/default/objects/Goal__c/recordTypes/KRA.recordType-meta.xml
<RecordType>
    <fullName>KRA</fullName>
    <active>true</active>
    <label>KRA</label>
</RecordType>

force-app/main/default/objects/PM_Configure__c/PM_Configure__c.object-meta.xml
<CustomObject>
    <label>PM Configure</label>
    <nameField>
        <displayFormat>PM - {000000}</displayFormat>
        <label>PM Configure Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PM Configure</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PM_Configure__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Area</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>KRA_Area</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PM_Configure__c/fields/KRA__c.field-meta.xml
<CustomField>
    <fullName>KRA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>KRA</label>
    <referenceTo>Goal__c</referenceTo>
    <relationshipLabel>PM Configure</relationshipLabel>
    <relationshipName>PM_Answer_Configure</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PM_Configure__c/fields/Mentor_Mentee__c.field-meta.xml
<CustomField>
    <fullName>Mentor_Mentee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mentor/Mentee</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PM Answer Configures (Mentor/Mentee)</relationshipLabel>
    <relationshipName>PM_Answer_Configure</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PM_Configure__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <label>Rating</label>
    <precision>2</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PM_Configure__c/fields/Related_Question__c.field-meta.xml
<CustomField>
    <fullName>Related_Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Question</label>
    <referenceTo>PM_Configure__c</referenceTo>
    <relationshipLabel>PM Ans Configure</relationshipLabel>
    <relationshipName>PM_Configure</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PM_Configure__c/fields/Resource_Role__c.field-meta.xml
<CustomField>
    <fullName>Resource_Role__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Role</label>
    <referenceTo>Resource_Role__c</referenceTo>
    <relationshipLabel>PM Configure</relationshipLabel>
    <relationshipName>PM_Configure</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PM_Configure__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Awaiting Response</fullName>
            </value>
            <value>
                <fullName>Response Recorded</fullName>
            </value>
            <value>
                <fullName>Saved</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PM_Configure__c/recordTypes/Answer.recordType-meta.xml
<RecordType>
    <fullName>Answer</fullName>
    <active>true</active>
    <label>Answer</label>
</RecordType>

force-app/main/default/objects/Resource_Role__c/Resource_Role__c.object-meta.xml
<CustomObject>
    <label>Resource Role</label>
    <nameField>
        <label>Resource Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resource Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource_Role__c/fields/goals_and_results__c.field-meta.xml
<CustomField>
    <fullName>goals_and_results__c</fullName>
    <description>This field is used to decide how much Goals and Results will be considered for rating</description>
    <label>Goals and Results</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Resource_Role__c/fields/professional_skills__c.field-meta.xml
<CustomField>
    <fullName>professional_skills__c</fullName>
    <description>This field is used to decide how much Professional Skills will be considered for rating</description>
    <label>Professional Skills</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Resource_Role__c/fields/strategic_impact__c.field-meta.xml
<CustomField>
    <fullName>strategic_impact__c</fullName>
    <description>This field is used to decide how much Strategic Impact will be considered for rating</description>
    <label>Strategic Impact</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Resource_Role__c/fields/technical_acumen__c.field-meta.xml
<CustomField>
    <fullName>technical_acumen__c</fullName>
    <description>This field is used to decide how much technical acumen will be considered for rating</description>
    <label>Technical Acumen</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/globalValueSets/KRA_Area.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>FUNCTIONAL ACUME</fullName>
    </customValue>
    <customValue>
        <fullName>GOALS AND RESULTS</fullName>
    </customValue>
    <customValue>
        <fullName>PROFESSIONAL SKILLS</fullName>
    </customValue>
    <customValue>
        <fullName>PROJECT MANAGEMENT ACUMEN</fullName>
    </customValue>
    <customValue>
        <fullName>STRATEGIC IMPACT</fullName>
    </customValue>
    <customValue>
        <fullName>TECHNICAL SKILLS</fullName>
    </customValue>
    <masterLabel>KRA Area</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/UpdateAverageRatingsOnKRA.cls
/**
* @author Ravitheja
* @date 09/07/2024
* @description Update the Average Ratings on the Goal Object
*
* CHANGE HISTORY
* ====================================================================================================
* DATE          NAME                    DESCRIPTION
* N/A           N/A                     N/A
* ====================================================================================================
**/

public class UpdateAverageRatingsOnKRA implements TriggerAction.BeforeUpdate {

    public void beforeUpdate(List<Goal__c> newList, List<Goal__c> oldList) {
        updateAverageRatings(newList, new Map<Id, Goal__c>(oldList));
    }
    
    public void updateAverageRatings(List<Goal__c> newList, Map<Id, Goal__c> oldMap) {
        
        Set<Id> completedKRAIds = new Set<Id>(); 
        
        for (Goal__c gl : newList) {
            if (gl.Status__c != oldMap.get(gl.Id).Status__c && gl.Status__c == 'KRA Completed') {
                completedKRAIds.add(gl.Id);
                System.debug('completedKRAIds '+completedKRAIds);
            }
        }
        
        List<PM_Configure__c> filteredPmConfigList = getFilteredPMConfigList(completedKRAIds);
        
        calculateAndSetAverageRatings(newList, filteredPmConfigList);
    }
    
    private List<PM_Configure__c> getFilteredPMConfigList(Set<Id> completedKRAIds) {
        List<PM_Configure__c> filteredPmConfigList = new List<PM_Configure__c>();
        Id answerRecordTypeId = Schema.SObjectType.PM_Configure__c.getRecordTypeInfosByName().get('Answer').getRecordTypeId();
        
        List<PM_Configure__c> pmConfigList = [
            SELECT Id, Name, KRA__c, Related_Question__r.Area__c, Mentor_Mentee__c, KRA__r.Resource__c, Rating__c 
            FROM PM_Configure__c 
            WHERE RecordTypeId = :answerRecordTypeId AND KRA__c IN :completedKRAIds
        ];
        System.debug('pmConfigList '+pmConfigList);
        for (PM_Configure__c pmConfig : pmConfigList) {
            if (pmConfig.Mentor_Mentee__c != pmConfig.KRA__r.Resource__c) {
                filteredPmConfigList.add(pmConfig);
            }
        }
        
        return filteredPmConfigList;
    }
    
    private void calculateAndSetAverageRatings(List<Goal__c> newList, List<PM_Configure__c> filteredPmConfigList) {
        Decimal techSkillSum = 0;
        Integer techSkillNo = 0;
        Decimal profSkillSum = 0;
        Integer profSkillNo = 0;
        Decimal strategicSum = 0;
        Integer strategicNo = 0;
        Decimal goalResultSum = 0;
        Integer goalResultNo = 0;
        
        for (PM_Configure__c pmAns : filteredPmConfigList) {
            if (pmAns.Related_Question__r != null && pmAns.Related_Question__r.Area__c != null && pmAns.Rating__c != null) {
                if (pmAns.Related_Question__r.Area__c == 'TECHNICAL SKILLS') {
                    techSkillSum += pmAns.Rating__c;
                    techSkillNo++;
                } else if (pmAns.Related_Question__r.Area__c == 'PROFESSIONAL SKILLS') {
                    profSkillSum += pmAns.Rating__c;
                    profSkillNo++;
                } else if (pmAns.Related_Question__r.Area__c == 'STRATEGIC IMPACT') {
                    strategicSum += pmAns.Rating__c;
                    strategicNo++;
                } else if (pmAns.Related_Question__r.Area__c == 'GOALS AND RESULTS') {
                    goalResultSum += pmAns.Rating__c;
                    System.debug('Rating '+ pmAns.Rating__c);
                    System.debug('techSkillSum '+goalResultSum);
                    goalResultNo++;
                    System.debug('goalResultNo '+goalResultNo);
                }
            }
        }
        
        Decimal avgTechSkillRating = techSkillNo > 0 ? techSkillSum / techSkillNo : 0;
        Decimal avgProfSkillRating = profSkillNo > 0 ? profSkillSum / profSkillNo : 0;
        Decimal avgStrategicRating = strategicNo > 0 ? strategicSum / strategicNo : 0;
        Decimal avgGoalResultRating = goalResultNo > 0 ? goalResultSum / goalResultNo : 0;
        System.debug('avgGoalResultRating '+avgGoalResultRating);
        
       	avgTechSkillRating = avgTechSkillRating.setScale(1);
        avgProfSkillRating = avgProfSkillRating.setScale(1);
        avgStrategicRating = avgStrategicRating.setScale(1);
        avgGoalResultRating = avgGoalResultRating.setScale(1);
        System.debug('avgGoalResultRating '+avgGoalResultRating);
        
        Set<Id> resourceIds = new Set<Id>();
        for (Goal__c goal : newList) {
            if (goal.Resource__c != null) {
                resourceIds.add(goal.Resource__c);
            }
        }
        
        List<Contact> conList = [SELECT Id, Name, Resource_Role__c FROM Contact WHERE Id IN :resourceIds];
      
        for (Contact con : conList) {
            if (con.Resource_Role__c != null) {
                resourceIds.add(con.Resource_Role__c);
            }
        }
        
        List<Resource_Role__c> resourceRoleList = [
            SELECT Id, technical_acumen__c, strategic_impact__c, professional_skills__c, goals_and_results__c 
            FROM Resource_Role__c 
            WHERE Id IN :resourceIds
            LIMIT 1
        ];
        
        if (!resourceRoleList.isEmpty()) {
            for (Goal__c goal : newList) {
                Resource_Role__c role = resourceRoleList[0];
                
                goal.Average_Technical_Skills_Rating__c = (avgTechSkillRating * (role.technical_acumen__c / 100)).setScale(1);
                goal.Average_Professional_Skills_Rating__c = (avgProfSkillRating * (role.professional_skills__c / 100)).setScale(1);
                goal.Average_Strategic_Impact_Rating__c = (avgStrategicRating * (role.strategic_impact__c / 100)).setScale(1);
                goal.Average_Goals_And_Result_Rating__c = (avgGoalResultRating * (role.goals_and_results__c / 100));//.setScale(2)
                 System.debug('goalnresult '+goal.Average_Goals_And_Result_Rating__c);
            }
        }
    }
}