force-app/main/default/objects/Contact/fields/Resource_Role__c.field-meta.xml
<CustomField>
    <fullName>Resource_Role__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Role</label>
    <referenceTo>Resource_Role__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Project__c/EMS_TM_Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Goal__c/Goal__c.object-meta.xml
<CustomObject>
    <label>Goal</label>
    <nameField>
        <displayFormat>GOAL{000000}</displayFormat>
        <label>Goal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Goals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Goal__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Goals</relationshipLabel>
    <relationshipName>Goals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Goal__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Missed</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>KRA Inreview</fullName>
            </value>
            <value>
                <fullName>KRA Completed</fullName>
            </value>
            <value>
                <fullName>Pulse Submitted</fullName>
            </value>
            <value>
                <fullName>Pulse Requested</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>HR KRA Completed</fullName>
            </value>
            <value>
                <fullName>Completed - OnTime</fullName>
                <isActive>false</isActive>
                <label>Completed - OnTime</label>
            </value>
            <value>
                <fullName>Completed - PostTime</fullName>
                <isActive>false</isActive>
                <label>Completed - PostTime</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PM_Configure__c/PM_Configure__c.object-meta.xml
<CustomObject>
    <label>PM Configure</label>
    <nameField>
        <displayFormat>PM - {000000}</displayFormat>
        <label>PM Configure Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PM Configure</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PM_Configure__c/fields/KRA__c.field-meta.xml
<CustomField>
    <fullName>KRA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>KRA</label>
    <referenceTo>Goal__c</referenceTo>
    <relationshipLabel>PM Configure</relationshipLabel>
    <relationshipName>PM_Answer_Configure</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PM_Configure__c/fields/Mentee__c.field-meta.xml
<CustomField>
    <fullName>Mentee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mentee</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PM Configure (Mentee)</relationshipLabel>
    <relationshipName>PM_Configure1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PM_Configure__c/fields/Mentor__c.field-meta.xml
<CustomField>
    <fullName>Mentor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mentor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PM Configure (Mentor)</relationshipLabel>
    <relationshipName>PM_Configure</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PM_Configure__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Name</label>
    <referenceTo>EMS_TM_Project__c</referenceTo>
    <relationshipLabel>PM Answer Configures</relationshipLabel>
    <relationshipName>PM_Answer_Configure</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PM_Configure__c/fields/Recall_FeedBack_Comments__c.field-meta.xml
<CustomField>
    <fullName>Recall_FeedBack_Comments__c</fullName>
    <label>Recall FeedBack Comments</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/PM_Configure__c/fields/Reporting_Contact__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reporting Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PM Configure (Reporting Contact)</relationshipLabel>
    <relationshipName>PM_Configures1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PM_Configure__c/fields/Resource_Role__c.field-meta.xml
<CustomField>
    <fullName>Resource_Role__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Role</label>
    <referenceTo>Resource_Role__c</referenceTo>
    <relationshipLabel>PM Configure</relationshipLabel>
    <relationshipName>PM_Configure</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PM_Configure__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Awaiting Response</fullName>
            </value>
            <value>
                <fullName>Response Recorded</fullName>
            </value>
            <value>
                <fullName>Saved</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PM_Configure__c/recordTypes/Answer.recordType-meta.xml
<RecordType>
    <fullName>Answer</fullName>
    <active>true</active>
    <label>Answer</label>
</RecordType>

force-app/main/default/objects/Resource_Role__c/Resource_Role__c.object-meta.xml
<CustomObject>
    <label>Resource Role</label>
    <nameField>
        <label>Resource Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resource Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/viewPmRequestsController.cls
public without sharing class viewPmRequestsController {
    
    public class viewPMTableWrapper {
        
        @AuraEnabled
        public String mentee{get;set;}
        @AuraEnabled
        public String menteeRole{get;set;}
        @AuraEnabled
        public String project{get;set;}
        @AuraEnabled
        public String projectManager{get;set;}
        @AuraEnabled
        public String kraStatus{get;set;}
        @AuraEnabled
        public string projectConId{get;set;}
         @AuraEnabled
        public String projectManagerId{get;set;}
        @AuraEnabled
        public String projectId{get;set;}
        @AuraEnabled
        public String kraId{get;set;}
        @AuraEnabled
        public boolean hideRecallButton{get;set;}
    }
    
    @AuraEnabled(cacheable=true)
    public static List<viewPMTableWrapper> viewPMRequestsTable(String KraId){
        
        Id answerRecordTypeId = Schema.SObjectType.PM_Configure__c.getRecordTypeInfosByName().get('Answer').getRecordTypeId();
        List<PM_Configure__c> pmConfiglist = [Select Id,
                                              name,
                                              Mentee__r.name,
                                              Mentee__r.Resource_Role__r.name,
                                              Mentor__r.name,
                                              Reporting_Contact__r.name,
                                              Reporting_Contact__c,
                                              Status__c,
                                              KRA__c,KRA__r.Resource__c,
                                              Project_Name__r.name,
                                              Project_Name__c From PM_Configure__c
                                              where recordtypeId =: answerRecordTypeId and Kra__c =:KraId  and Reporting_Contact__c != null
                                              and Status__c IN('Awaiting Response','Accepted','Rejected','Submitted','Cancelled')];
        system.debug('KraId---'+KraId);
        system.debug('pmConfiglist---'+pmConfiglist.size());

        Map<String, List<PM_Configure__c>> projectPMConfigData = new Map<String, List<PM_Configure__c>>();
         Map<String, Map<String, List<PM_Configure__c>>> managerProjPmAnsRecMap = new Map<String, Map<String, List<PM_Configure__c>>>();
        
          for(PM_Configure__c pm : pmConfiglist){
                if (!projectPMConfigData.containsKey(pm.Project_Name__c)) {
                    projectPMConfigData.put(pm.Project_Name__c, new List<PM_Configure__c>());
                }
                projectPMConfigData.get(pm.Project_Name__c).add(pm);
            }

           for (String projName : projectPMConfigData.keySet()) {
                List<PM_Configure__c> pmConfigRecs = projectPMConfigData.get(projName);
                for (PM_Configure__c pmRec : pmConfigRecs) {
                    if (!managerProjPmAnsRecMap.containsKey(pmRec.Reporting_Contact__c)) {
                        managerProjPmAnsRecMap.put(pmRec.Reporting_Contact__c, new Map<String, List<PM_Configure__c>>());
                    }
                    if (!managerProjPmAnsRecMap.get(pmRec.Reporting_Contact__c).containsKey(projName)) {
                        managerProjPmAnsRecMap.get(pmRec.Reporting_Contact__c).put(projName, new List<PM_Configure__c>());
                    }
                    managerProjPmAnsRecMap.get(pmRec.Reporting_Contact__c).get(projName).add(pmRec);
                }
            }
            system.debug('managerProjPmAnsRecMap-----'+managerProjPmAnsRecMap);

       /* for(PM_Configure__c pm : pmConfiglist){
              String projectConId = pm.Reporting_Contact__c + ' ' + pm.Project_Name__c; 
            if( pmRequestMap.containskey(projectConId)){
                pmRequestMap.get(projectConId).add(pm);
                
            }
            else{
                pmRequestMap.put(projectConId,new list<PM_Configure__c>{pm});
                
            }
        }*/
        
        
        List<viewPMTableWrapper> updatedPMConfigList = new List<viewPMTableWrapper>();
        
         for (String managerId : managerProjPmAnsRecMap.keySet()) {
            Map<String, List<PM_Configure__c>> projectMap = managerProjPmAnsRecMap.get(managerId);
            for (String projectName : projectMap.keySet()) {
                List<PM_Configure__c> pmConfigRecs = projectMap.get(projectName);
                               
                         viewPMTableWrapper vpt = new viewPMTableWrapper();    
                         vpt.mentee = pmConfigRecs[0].Mentee__r.name;
                         vpt.menteeRole = pmConfigRecs[0].Mentee__r.Resource_Role__r.name;
                         vpt.project = pmConfigRecs[0].Project_Name__r.name;
                          if(pmConfigRecs[0].Status__c == 'Awaiting Response'){
                         vpt.kraStatus = 'Request Sent';
                         vpt.hideRecallButton = false;
                            }
                        else if(pmConfigRecs[0].Status__c == 'Accepted'){                       
                         vpt.kraStatus = 'Request Accepted';
                         vpt.hideRecallButton = false;
                            }
                       else if(pmConfigRecs[0].Status__c == 'Rejected'){
                         vpt.kraStatus = 'Request Rejected';
                         vpt.hideRecallButton = false;
                            }
                         else if(pmConfigRecs[0].Status__c == 'Submitted'){
                         vpt.kraStatus = 'Feedback Submitted';
                          vpt.hideRecallButton = false;
                            }
                        else if(pmConfigRecs[0].Status__c == 'Cancelled'){
                         vpt.kraStatus = 'Feedback Cancelled';
                         vpt.hideRecallButton = true;
                            }
                      
                         vpt.projectManager =pmConfigRecs[0].Reporting_Contact__r.name;
                         vpt.projectConId = pmConfigRecs[0].Reporting_Contact__r.name +''+pmConfigRecs[0].Project_Name__r.name;
                         vpt.projectManagerId = pmConfigRecs[0].Reporting_Contact__c;
                         vpt.projectId = pmConfigRecs[0].Project_Name__c;
                         vpt.kraId = pmConfigRecs[0].KRA__c;

                         updatedPMConfigList.add(vpt);
                    
               
            }
         }

         system.debug('updatedPMConfigList---'+updatedPMConfigList);
         system.debug('updatedPMConfigList---'+updatedPMConfigList.size());
          return updatedPMConfigList;
       
    }

@AuraEnabled
    Public static void recallPmRequests(String KraId,String projectManager,String projectName, string rejectionReason){
       
       List<PM_Configure__c> updatedPmConfiglist = new List<PM_Configure__c>();
      Id answerRecordTypeId = Schema.SObjectType.PM_Configure__c.getRecordTypeInfosByName().get('Answer').getRecordTypeId();   
       List<PM_Configure__c> pmConfiglist1 = [Select Id,
                                              name,
                                              Mentee__r.name,
                                              Mentee__r.Resource_Role__r.name,
                                              Mentor__r.name,
                                              Reporting_Contact__r.name,
                                              Reporting_Contact__c,
                                              Status__c,
                                              KRA__c,KRA__r.Resource__c,
                                              Project_Name__r.name,
                                              Recall_FeedBack_Comments__c,
                                              Project_Name__c From PM_Configure__c
                                              where recordtypeId =: answerRecordTypeId and Kra__c =:KraId  
                                              and Reporting_Contact__c != null                                               
                                              and Reporting_Contact__c =:projectManager
                                              and Project_Name__c =: projectName];
          system.debug('pmConfiglist1------'+pmConfiglist1);
        if(!pmConfiglist1.IsEmpty()){
        for(PM_Configure__c pm : pmConfiglist1){           
           pm.Status__c = 'Cancelled';
           pm.Recall_FeedBack_Comments__c = rejectionReason;
           updatedPmConfiglist.add(pm);
          }
        }
          system.debug('updatedPmConfiglist---'+updatedPmConfiglist);
        if(!updatedPmConfiglist.isEmpty()){
            update updatedPmConfiglist;
        }


      }

     
    
}