force-app/main/default/objects/Contact/fields/UtlizedFloatLeaves__c.field-meta.xml
<CustomField>
    <fullName>UtlizedFloatLeaves__c</fullName>
    <label>No Of UtlizedFloatLeaves</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Work_Location__c.field-meta.xml
<CustomField>
    <fullName>Work_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Location</label>
    <referenceTo>Office_Location__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Office_Location__c/Office_Location__c.object-meta.xml
<CustomObject>
    <label>Office Location</label>
    <nameField>
        <label>Office Locations Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Office Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/BatchforFloatLeaves.cls
global class BatchforFloatLeaves implements Database.Batchable<sObject> {
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator([SELECT Id, Name,UtlizedFloatLeaves__c FROM contact where Work_Location__r.Name='California - USA']);
    }
    global void execute(Database.BatchableContext bc, List<contact> records){
        for(contact con:records){
            con.UtlizedFloatLeaves__c=0;
        }
        try{
           update records;
        }catch(exception e){
             System.debug('error=========================='+e.getMessage());
        }
    }    
    global void finish(Database.BatchableContext bc){
        // execute any post-processing operations
    }  
}