force-app/main/default/objects/Contact/fields/Work_Location__c.field-meta.xml
<CustomField>
    <fullName>Work_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Location</label>
    <referenceTo>Office_Location__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_History__c/EMS_LM_Leave_History__c.object-meta.xml
<CustomObject>
    <description>It will show the employee Leave and WFH Requests.</description>
    <label>Leave Request</label>
    <nameField>
        <displayFormat>LH-{00000}</displayFormat>
        <label>Leave History Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leaves Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_LM_Leave_History__c/fields/EMS_LM_Contact__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Leaves History</relationshipLabel>
    <relationshipName>Leaves_History</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_History__c/fields/EMS_LM_Day__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Day__c</fullName>
    <label>Day</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full Day</fullName>
            </value>
            <value>
                <fullName>First Half</fullName>
            </value>
            <value>
                <fullName>Second Half</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_History__c/fields/EMS_LM_Leave_Duration__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Leave_Duration__c</fullName>
    <label>Leave Duration</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_History__c/fields/EMS_LM_Leave_End_Date__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Leave_End_Date__c</fullName>
    <label>Leave End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_History__c/fields/EMS_LM_Leave_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Leave_Start_Date__c</fullName>
    <label>Leave Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Calendar__c/EMS_TM_Calendar__c.object-meta.xml
<CustomObject>
    <description>This Calendar is for Organization Holidays</description>
    <label>Holiday Calendar</label>
    <nameField>
        <label>Holiday Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Holiday Calendars</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_TM_Calendar__c/fields/EMS_TM_Calendar_Date__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Calendar_Date__c</fullName>
    <label>Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Calendar__c/fields/Office_Location__c.field-meta.xml
<CustomField>
    <fullName>Office_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Office Location</label>
    <referenceTo>Office_Location__c</referenceTo>
    <relationshipName>Holiday_Calenders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Office_Location__c/Office_Location__c.object-meta.xml
<CustomObject>
    <label>Office Location</label>
    <nameField>
        <label>Office Locations Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Office Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Office_Location__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>United States of America</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Cp_CalculateLeaveDuration.cls
/**
* @author Sangharsh Kamble
* @date 31/01/2023
* @description Calculate duration of start date and end date.
*
*               Test code coverage provided by the following test class: 
*               - LeaveCalculateHandler_Test
*
* CHANGE HISTORY
* ====================================================================================================
* DATE          NAME                    DESCRIPTION
* N/A           N/A                     N/A
* ====================================================================================================
**/
public without sharing class Cp_CalculateLeaveDuration implements TriggerAction.BeforeInsert,TriggerAction.BeforeUpdate{
    
    
    public void beforeInsert(List<EMS_LM_Leave_History__c> leaveHistoryList) {      
        leavedurationmethod(leaveHistoryList);     
    }
    
    public void beforeupdate(List<EMS_LM_Leave_History__c> leaveHistoryList,List<EMS_LM_Leave_History__c> oldList) {      
        leavedurationmethod(leaveHistoryList);     
    }
    
    
    @TestVisible
   	private void leavedurationmethod(list<EMS_LM_Leave_History__c> leaveHistoryList){
        
    Date startDate = leaveHistoryList[0].EMS_LM_Leave_Start_Date__c;
	Date endDate = leaveHistoryList[0].EMS_LM_Leave_End_Date__c;
    String daycheck = leaveHistoryList[0].EMS_LM_Day__c;
    String leaveTypeName = leaveHistoryList[0].Leave_Type_Name__c;  
    String ContactId =leaveHistoryList[0].EMS_LM_Contact__c;
       
    Id locationId = [SELECT Id, Work_Location__c FROM Contact Where Id =: ContactId].Work_Location__c;
        Set<Date> holidaysSet = new Set<Date>();
        
        for(EMS_TM_Calendar__c currHoliday : [Select ID,EMS_TM_Calendar_Date__c ,Office_Location__r.Country__c 
                                              from EMS_TM_Calendar__c 
                                              where Office_Location__c = :locationId])  
        {  
            holidaysSet.add(currHoliday.EMS_TM_Calendar_Date__c);  
            system.debug('duration cal'+currHoliday.EMS_TM_Calendar_Date__c);
        }
	
        Decimal Duration = 0;
        if (startDate != null && endDate != null) {
        
           for(integer i=0; i <= startDate.daysBetween(endDate); i++)  
        {  
            Date dt = startDate + i;  
            DateTime currDate = DateTime.newInstance(dt.year(), dt.month(), dt.day());  
            String todayDay = currDate.format('EEEE');  
            if(todayDay != 'Saturday' && todayDay !='Sunday' && daycheck =='Full Day' && (!holidaysSet.contains(dt)) && leaveTypeName!=LeaveRequestConstant.LOSS_OF_PAY && leaveTypeName!=LeaveRequestConstant.UNPAID_TIMEOFF )  
                {  
                  //  Duration = Duration + 1;  
                    Duration += 1;
                    system.debug(Duration);
               }
            if((leaveTypeName == LeaveRequestConstant.LOSS_OF_PAY || leaveTypeName == LeaveRequestConstant.UNPAID_TIMEOFF ) && daycheck =='Full Day'){
                Duration += 1;
            }
            if(daycheck !='Full Day'){
                Duration = 0.5 - Duration;
            }
        }
        for(EMS_LM_Leave_History__c leaveHistory:leaveHistoryList){
            leaveHistory.EMS_LM_Leave_Duration__c = Duration;
        }
    }
    for(EMS_LM_Leave_History__c leaveHistory:leaveHistoryList){
        leaveHistory.EMS_LM_Leave_Duration__c = Duration;
    }      
        
    }
    
}