force-app/main/default/objects/Contact/fields/Work_Location__c.field-meta.xml
<CustomField>
    <fullName>Work_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Location</label>
    <referenceTo>Office_Location__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Calendar__c/EMS_TM_Calendar__c.object-meta.xml
<CustomObject>
    <description>This Calendar is for Organization Holidays</description>
    <label>Holiday Calendar</label>
    <nameField>
        <label>Holiday Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Holiday Calendars</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_TM_Calendar__c/fields/EMS_TM_Calendar_Date__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Calendar_Date__c</fullName>
    <label>Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Calendar__c/fields/EMS_TM_Type_Of_Holiday__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_Type_Of_Holiday__c</fullName>
    <label>Type of Holiday</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Regional</fullName>
            </value>
            <value>
                <fullName>National</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EMS_TM_Calendar__c/fields/Office_Location__c.field-meta.xml
<CustomField>
    <fullName>Office_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Office Location</label>
    <referenceTo>Office_Location__c</referenceTo>
    <relationshipName>Holiday_Calenders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Office_Location__c/Office_Location__c.object-meta.xml
<CustomObject>
    <label>Office Location</label>
    <nameField>
        <label>Office Locations Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Office Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/holidayTitleController.cls
public without sharing class holidayTitleController {
    
  @AuraEnabled(cacheable=true)
    public static returnedDate getMyUpcomingHoliday(){
        List<datawrapper> dataList = new List<datawrapper>();
         List<String> locaList = new List<String>(); 
        Map<String,String> locationWithId = new Map<String,String>();
        User uREc = [SELECT Id,contactId,contact.Work_Location__c,contact.Work_Location__r.Name FROM User WHERE Id=:Userinfo.getUserId()];
        List<EMS_TM_Calendar__c> holidayCalender = new List<EMS_TM_Calendar__c>();
        String resourceLocation = uREc.contact.Work_Location__c;
        Date dt = system.today();
        holidayCalender = [SELECT Id,EMS_TM_Calendar_Date__c,Office_Location__c,Name,Office_Location__r.Name,EMS_TM_Type_Of_Holiday__c 
                           FROM EMS_TM_Calendar__c 
                           WHERE EMS_TM_Calendar_Date__c=THIS_YEAR 
                           AND EMS_TM_Calendar_Date__c >:dt  
                           ];
        
        for(EMS_TM_Calendar__c holi : holidayCalender){
            system.debug('====holi.Office_Location__c=='+holi.Office_Location__c);
             system.debug('==== uREc.contact.Work_Location__c=='+ uREc.contact.Work_Location__c);
            if(holi.Office_Location__c == uREc.contact.Work_Location__c){
                System.debug('=Inside====');
                DateTime dt2 = DateTime.newInstance(holi.EMS_TM_Calendar_Date__c, Time.newInstance(0,0,0,0));
            datawrapper dtwrap = new datawrapper();
            dtwrap.holidayDate = holi.EMS_TM_Calendar_Date__c;
            dtwrap.status = dt2.format('EEEE');
            dtwrap.holidayType =  holi.Name;
            dataList.add(dtwrap);
            }
            
            locationWithId.put(holi.Office_Location__r.Name,holi.Office_Location__c);
        }
        
      locaList.addAll(locationWithId.keySet());
         dataList.sort();
        returnedDate rdData = new returnedDate();
        rdData.datalist = dataList;
        rdData.locList = locaList;
        rdData.locationList = locationWithId;
        rdData.resourceLocation = resourceLocation;
       
        return rdData;
    }
    
    @AuraEnabled(cacheable=true)
    public static List<datawrapper> getSelectLocList(Id locationId){
         List<datawrapper> dataList = new List<datawrapper>();
         Date dt = system.today();
         for(EMS_TM_Calendar__c holi : [SELECT Id,EMS_TM_Calendar_Date__c,Office_Location__c,Name,Office_Location__r.Name,EMS_TM_Type_Of_Holiday__c 
                           FROM EMS_TM_Calendar__c 
                           WHERE EMS_TM_Calendar_Date__c=THIS_YEAR 
                           AND EMS_TM_Calendar_Date__c >:dt  
                           AND Office_Location__c=:locationId ]){
            DateTime dt2 = DateTime.newInstance(holi.EMS_TM_Calendar_Date__c, Time.newInstance(0,0,0,0));
            datawrapper dtwrap = new datawrapper();
            dtwrap.holidayDate = holi.EMS_TM_Calendar_Date__c;
            dtwrap.status = dt2.format('EEEE');
            dtwrap.holidayType =  holi.Name;
            dataList.add(dtwrap);
        }
        return dataList;
    }
    
    
    
    public class returnedDate {
        @AuraEnabled 
        public List<datawrapper> datalist;
        @AuraEnabled
        public Map<String,String> locationList;
        @AuraEnabled
        public List<String> locList;
        @AuraEnabled
        public string resourceLocation;
    }
    
    public class datawrapper implements Comparable {
        @AuraEnabled
        public Date holidayDate;
        @AuraEnabled 
        public string duration;
        @AuraEnabled
        public string status;
        @AuraEnabled
        public string holidayType;
        
        public Integer compareTo(Object objToCompare) {
        datawrapper that = (datawrapper)objToCompare;
        if (this.holidayDate > that.holidayDate) return 1;
        if (this.holidayDate < that.holidayDate) return -1;
        return 0;
        }
    }

}