force-app/main/default/objects/Goal__c/Goal__c.object-meta.xml
<CustomObject>
    <label>Goal</label>
    <nameField>
        <displayFormat>GOAL{000000}</displayFormat>
        <label>Goal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Goals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Goal__c/fields/is_Navigation_Required__c.field-meta.xml
<CustomField>
    <fullName>is_Navigation_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>is Navigation Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Goal__c/fields/Navigation_address__c.field-meta.xml
<CustomField>
    <fullName>Navigation_address__c</fullName>
    <label>Navigation address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Goal__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Goals</relationshipLabel>
    <relationshipName>Goals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Goal__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Missed</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>KRA Inreview</fullName>
            </value>
            <value>
                <fullName>KRA Completed</fullName>
            </value>
            <value>
                <fullName>Pulse Submitted</fullName>
            </value>
            <value>
                <fullName>Pulse Requested</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>HR KRA Completed</fullName>
            </value>
            <value>
                <fullName>Completed - OnTime</fullName>
                <isActive>false</isActive>
                <label>Completed - OnTime</label>
            </value>
            <value>
                <fullName>Completed - PostTime</fullName>
                <isActive>false</isActive>
                <label>Completed - PostTime</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Goal__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Survey</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>KRA</fullName>
            </value>
            <value>
                <fullName>Org Level Goal</fullName>
            </value>
            <value>
                <fullName>Resource Role Level Goal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Goal__c/recordTypes/Goal.recordType-meta.xml
<RecordType>
    <fullName>Goal</fullName>
    <active>true</active>
    <label>Goal</label>
</RecordType>

force-app/main/default/classes/onboardingTileControllerTest.cls
@isTest
public class onboardingTileControllerTest {
    public static final Id Goal_Recordtype_Id = Schema.SObjectType.Goal__c.getRecordTypeInfosByDeveloperName().get('Goal').getRecordTypeId();
    public testmethod static void onboardingTileControllerMethod(){
        Task newTask = new Task(
            Status = 'Completed',
            Onboarding_UniqueKey__c = 'POS003',
            Subject = 'Testing',
            OwnerId = Userinfo.getUserId(),
            ActivityDate = system.today().addDays(2),
            Requires_Navigation__c = True
        );
        insert newTask;
        
        Task newTask1 = new Task(
            Status = 'Completed',
            Offboarding_UniqueKey__c = 'OFF00001',
            Subject = 'Testing',
            OwnerId = Userinfo.getUserId(),
            ActivityDate = system.today().addDays(2),
            Requires_Navigation__c = True
        );
        insert newTask1;
        
        user urec = [SELECT Id,ContactId FROM User WHERE Id=:Userinfo.getUserId()];
        
        Goal__c goalRec = new Goal__c();
        goalRec.Status__c = 'Active';
        goalRec.Resource__c = urec.ContactId;
        goalRec.RecordTypeId = Goal_Recordtype_Id;
        goalRec.Description__c = 'Test Description';
        goalRec.End_Date__c = System.today().addDays(10);
        goalRec.is_Navigation_Required__c = True;
        goalRec.Navigation_address__c = 'Test';
        goalRec.Type__c = 'Org Level Goal';
        insert goalRec;
        
        Goal__c goalRec1 = new Goal__c();
        goalRec1.Status__c = 'Completed';
        goalRec1.Resource__c = urec.ContactId;
        goalRec1.RecordTypeId = Goal_Recordtype_Id;
        goalRec1.Description__c = 'Test Description1';
        goalRec1.End_Date__c = System.today().addDays(10);
        goalRec1.is_Navigation_Required__c = True;
        goalRec1.Navigation_address__c = 'Test1';
        insert goalRec1;
        
        Test.startTest();
        onboardingTileController.getMyOnboardingTasks();
        onboardingTileController.getoffboardingTasks();
        onboardingTileController.updateTheTaskasComplete(newTask1.id);
        onboardingTileController.getMyActiveGoals();
        onboardingTileController.updateTheGoal(goalRec1.Id);
        onboardingTileController.getTheCurrentGoals();
        Test.stopTest();
    }
    
}