force-app/main/default/objects/Goal__c/Goal__c.object-meta.xml
<CustomObject>
    <label>Goal</label>
    <nameField>
        <displayFormat>GOAL{000000}</displayFormat>
        <label>Goal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Goals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Goal__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Missed</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>KRA Inreview</fullName>
            </value>
            <value>
                <fullName>KRA Completed</fullName>
            </value>
            <value>
                <fullName>Pulse Submitted</fullName>
            </value>
            <value>
                <fullName>Pulse Requested</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>HR KRA Completed</fullName>
            </value>
            <value>
                <fullName>Completed - OnTime</fullName>
                <isActive>false</isActive>
                <label>Completed - OnTime</label>
            </value>
            <value>
                <fullName>Completed - PostTime</fullName>
                <isActive>false</isActive>
                <label>Completed - PostTime</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Goal__c/recordTypes/Goal.recordType-meta.xml
<RecordType>
    <fullName>Goal</fullName>
    <active>true</active>
    <label>Goal</label>
</RecordType>

force-app/main/default/objects/Goal__c/recordTypes/KRA.recordType-meta.xml
<RecordType>
    <fullName>KRA</fullName>
    <active>true</active>
    <label>KRA</label>
</RecordType>

force-app/main/default/objects/PM_Configure__c/PM_Configure__c.object-meta.xml
<CustomObject>
    <label>PM Configure</label>
    <nameField>
        <displayFormat>PM - {000000}</displayFormat>
        <label>PM Configure Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PM Configure</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PM_Configure__c/fields/KRA__c.field-meta.xml
<CustomField>
    <fullName>KRA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>KRA</label>
    <referenceTo>Goal__c</referenceTo>
    <relationshipLabel>PM Configure</relationshipLabel>
    <relationshipName>PM_Answer_Configure</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PM_Configure__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Awaiting Response</fullName>
            </value>
            <value>
                <fullName>Response Recorded</fullName>
            </value>
            <value>
                <fullName>Saved</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PM_Configure__c/recordTypes/Answer.recordType-meta.xml
<RecordType>
    <fullName>Answer</fullName>
    <active>true</active>
    <label>Answer</label>
</RecordType>

force-app/main/default/classes/UpdatetheKRAStatus.cls
public class UpdatetheKRAStatus implements TriggerAction.AfterUpdate {
    
    public void afterUpdate(List<PM_Configure__c> newList, List<PM_Configure__c> oldList) {      
        System.debug(LoggingLevel.DEBUG, 'updateKraStatus.afterUpdate() : BEGIN');
        UpdatetheGoalKraStatus(newList,new Map<Id,PM_Configure__c>(oldList));
        System.debug(LoggingLevel.DEBUG, 'updateKraStatus.afterUpdate() : END');       
    }
    
    public void UpdatetheGoalKraStatus(List<PM_Configure__c> newlist,Map<Id,PM_Configure__c> oldMap) {
        
        
        Set<Id> kraIdSet = new set<Id>();
        List<Goal__c> updatedGoalList = new List<Goal__c>();
        Id AnswerRecordTypeId = Schema.SObjectType.PM_Configure__c.getRecordTypeInfosByName().get('Answer').getRecordTypeId();
        Id kraRecordTypeId = Schema.SObjectType.Goal__c.getRecordTypeInfosByName().get('KRA').getRecordTypeId();

        for(PM_Configure__c pmConfig: newlist){
            if(pmConfig.RecordTypeID == AnswerRecordTypeId && pmConfig.Status__c != oldMap.get(pmConfig.Id).Status__c && pmConfig.Status__c =='Submitted'){
                system.debug('Entered Kra Goal-----'+pmConfig);
                kraIdSet.add(pmConfig.KRA__c);
            }
        }
        Map<Id,Integer> duplicatepmConfigMap = new Map<Id,Integer>();
        Map<Id,Integer> duplicatepmConfigMap2 = new Map<Id,Integer>();
        
        if(!kraIdSet.isEmpty()){  
            for(Goal__c goalRec : [SELECT Id,
                                   Name,
                                   RecordType.Name,
                                   (SELECT Id,
                                    Name
                                    from PM_Answer_Configure__r ) from Goal__C
                                   where  Id=:kraIdSet  and recordtypeId =: kraRecordTypeId])
            {      
                duplicatepmConfigMap.Put(goalRec.Id,goalRec.PM_Answer_Configure__r.size()); 
                system.debug('duplicatepmConfigMap---'+duplicatepmConfigMap);           
            }  
        }
        
        for(Goal__c goalrecord : [SELECT Id,
                                  name,
                                  RecordType.name,
                                  (SELECT Id,
                                   name,
                                   KRA__c,
                                   Status__c
                                   from PM_Answer_Configure__r where Status__c ='Submitted' ) from Goal__C
                                  where  Id=:kraIdSet  and recordtypeId =: kraRecordTypeId ]){
                                      duplicatepmConfigMap2.Put(goalrecord.Id,goalrecord.PM_Answer_Configure__r.Size());
                                      system.debug('duplicatepmConfigMap2---'+duplicatepmConfigMap2);    
                                  }
        
        if (!duplicatepmConfigMap.isEmpty() && !duplicatepmConfigMap2.isEmpty()) {           
            for (Goal__c goalrecordId : [SELECT Id,
                                         Name,
                                         Status__c
                                         FROM Goal__c
                                         WHERE Id IN: kraIdSet ]) 
            {
                if (!duplicatepmConfigMap.isEmpty() && !duplicatepmConfigMap2.isEmpty()) {
                    
                    System.debug('### duplicatepmConfigMap------' + duplicatepmConfigMap.get(goalrecordId.Id));
                    System.debug('### duplicatepmConfigMap2-----' + duplicatepmConfigMap2.get(goalrecordId.Id));
                    if (duplicatepmConfigMap.get(goalrecordId.Id) == duplicatepmConfigMap2.get(goalrecordId.Id)) {
                        goalrecordId.Status__c ='KRA Inreview';
                        updatedGoalList.add(goalrecordId);
                    }
                }
            }
        }
        
        if(!updatedGoalList.isEmpty()){
            try{
                system.debug('updatedGoalList-----'+updatedGoalList);
                update updatedGoalList;
            }
            catch(Exception e){
                system.debug('Error----'+e.getmessage());
            }
        }
        
    }
    
}