force-app/main/default/objects/Goal__c/Goal__c.object-meta.xml
<CustomObject>
    <label>Goal</label>
    <nameField>
        <displayFormat>GOAL{000000}</displayFormat>
        <label>Goal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Goals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Goal__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Goals</relationshipLabel>
    <relationshipName>Goals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Goal__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Missed</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>KRA Inreview</fullName>
            </value>
            <value>
                <fullName>KRA Completed</fullName>
            </value>
            <value>
                <fullName>Pulse Submitted</fullName>
            </value>
            <value>
                <fullName>Pulse Requested</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>HR KRA Completed</fullName>
            </value>
            <value>
                <fullName>Completed - OnTime</fullName>
                <isActive>false</isActive>
                <label>Completed - OnTime</label>
            </value>
            <value>
                <fullName>Completed - PostTime</fullName>
                <isActive>false</isActive>
                <label>Completed - PostTime</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Goal__c/recordTypes/KRA.recordType-meta.xml
<RecordType>
    <fullName>KRA</fullName>
    <active>true</active>
    <label>KRA</label>
</RecordType>

force-app/main/default/objects/PM_Configure__c/PM_Configure__c.object-meta.xml
<CustomObject>
    <label>PM Configure</label>
    <nameField>
        <displayFormat>PM - {000000}</displayFormat>
        <label>PM Configure Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PM Configure</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PM_Configure__c/fields/KRA__c.field-meta.xml
<CustomField>
    <fullName>KRA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>KRA</label>
    <referenceTo>Goal__c</referenceTo>
    <relationshipLabel>PM Configure</relationshipLabel>
    <relationshipName>PM_Answer_Configure</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PM_Configure__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Awaiting Response</fullName>
            </value>
            <value>
                <fullName>Response Recorded</fullName>
            </value>
            <value>
                <fullName>Saved</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Resource_Resource_Relationship__c/Resource_Resource_Relationship__c.object-meta.xml
<CustomObject>
    <label>Resource Relationship</label>
    <nameField>
        <displayFormat>RRR-{000000}</displayFormat>
        <label>Resource Resource Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource_Resource_Relationship__c/fields/Relationship_Type__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Type__c</fullName>
    <label>Relationship Type</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mentor</fullName>
            </value>
            <value>
                <fullName>Leave Approver</fullName>
            </value>
            <value>
                <fullName>Resource Manager</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Resource_Resource_Relationship__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <label>Resource</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Resource Relationships (Reports To)</relationshipLabel>
    <relationshipName>Resource_Resource_Relationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Resource_Resource_Relationship__c/fields/Resource_Reports_To__c.field-meta.xml
<CustomField>
    <fullName>Resource_Reports_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Reports To</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Relationships_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/sendEmailToMentor.cls
/**
* @author Ravitheja
* @date 15/07/2024
* @description Send the email to mentor if the KRA has been rejected by Project Manager
*
* CHANGE HISTORY
* ====================================================================================================
* DATE          NAME                    DESCRIPTION
* N/A           N/A                     N/A
* ====================================================================================================
**/

public class sendEmailToMentor implements TriggerAction.AfterUpdate {
    
    public void afterUpdate(List<PM_Configure__c> newList, List<PM_Configure__c> oldList) {  
        
        System.debug(LoggingLevel.DEBUG, 'updateKraStatus.afterUpdate() : BEGIN');
        sendRejectionEmailToMentor(newList,new Map<Id,PM_Configure__c>(oldList));
        System.debug(LoggingLevel.DEBUG, 'updateKraStatus.afterUpdate() : END');       
    }
    
    public static void sendRejectionEmailToMentor(List<PM_Configure__c> newlist, Map<Id, PM_Configure__c> oldMap) {
        
        Set<Id> resourceId = new Set<Id>();
        Set<Id> reporteeId = new Set<Id>();
        List<PM_Configure__c> rejectedVsSubmittedPMConfigs = new List<PM_Configure__c>();
        Map<Id, PM_Configure__c> kraToPmConfigMap = new Map<Id, PM_Configure__c>();
        
        for (PM_Configure__c pmConfig : newlist) {
            
            if ((pmConfig.Status__c == 'Rejected' || pmConfig.Status__c == 'Submitted') 
                && pmConfig.Status__c != oldMap.get(pmConfig.Id).Status__c 
                && pmConfig.KRA__c != null) {
                    
                if (!kraToPmConfigMap.containsKey(pmConfig.KRA__c)) {
                     kraToPmConfigMap.put(pmConfig.KRA__c, pmConfig);
                     rejectedVsSubmittedPMConfigs.add(pmConfig);
                }
            }
        }
        
        for (Goal__c gl : [SELECT Id, Name, Resource__c FROM Goal__c WHERE Id IN :kraToPmConfigMap.keySet() AND Resource__c != NULL LIMIT 1]) {
            
            resourceId.add(gl.Resource__c);
        }
        
        for (Resource_Resource_Relationship__c rrr : [SELECT Id, Resource__c, Resource_Reports_To__c 
                                                      FROM Resource_Resource_Relationship__c 
                                                      WHERE Resource__c IN :resourceId 
                                                      AND Resource__c != NULL
                                                      AND Relationship_Type__c = 'Mentor'
                                                      AND Resource_Reports_To__c != NULL]){    
                                                          
                                                          reporteeId.add(rrr.Resource_Reports_To__c);
                                                      }
        
        List<Contact> conList = [SELECT Id, Name, Email FROM Contact WHERE Id IN :reporteeId LIMIT 1];
        
        sendEmail(conList, rejectedVsSubmittedPMConfigs);
    }
    
    
    public static void sendEmail(List<Contact> conList, List<PM_Configure__c> pmConfigList){
        
        OrgWideEmailAddress[] owea = [SELECT Id FROM OrgWideEmailAddress WHERE Address = 'no-reply.grid@cloudperitus.com'];
        Id templateIdOfReject = [SELECT Id FROM EmailTemplate WHERE DeveloperName ='Notifying_Mentor_On_Project_Manager_Declining_The_Feedback_Request'].Id;
        Id templateIdOfSubmit = [SELECT Id FROM EmailTemplate WHERE DeveloperName ='Notifying_Mentor_On_Feedback_Submission'].Id;
        
        for (Contact con : conList){
            
            for (PM_Configure__c pmConfig : pmConfigList) {
                
                Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
                message.setToAddresses(new String[] { con.Email });
                message.setOrgWideEmailAddressId(owea[0].Id);
                
                if(pmConfig.Status__c == 'Rejected'){
                    message.setTemplateId(templateIdofReject);
                }else{
                    message.setTemplateId(templateIdOfSubmit);
                }
                
                message.setTargetObjectId(con.Id); 
                message.setWhatId(pmConfig.Id); 
                message.setSaveAsActivity(true);
                
                Messaging.SendEmailResult[] results = Messaging.sendEmail(new Messaging.SingleEmailMessage[] { message });
                
                for (Messaging.SendEmailResult result : results) {
                    
                    if (result.isSuccess()) {
                        System.debug('Email sent successfully to: ' + con.Email);
                    } else {
                        System.debug('Failed to send email to: ' + con.Email + '. Error: ' + result.getErrors()[0].getMessage());
                    }
                }
            }
        }
    }
}