force-app/main/default/objects/Goal__c/Goal__c.object-meta.xml
<CustomObject>
    <label>Goal</label>
    <nameField>
        <displayFormat>GOAL{000000}</displayFormat>
        <label>Goal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Goals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Goal__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Goals</relationshipLabel>
    <relationshipName>Goals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Goal__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Missed</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>KRA Inreview</fullName>
            </value>
            <value>
                <fullName>KRA Completed</fullName>
            </value>
            <value>
                <fullName>Pulse Submitted</fullName>
            </value>
            <value>
                <fullName>Pulse Requested</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>HR KRA Completed</fullName>
            </value>
            <value>
                <fullName>Completed - OnTime</fullName>
                <isActive>false</isActive>
                <label>Completed - OnTime</label>
            </value>
            <value>
                <fullName>Completed - PostTime</fullName>
                <isActive>false</isActive>
                <label>Completed - PostTime</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Goal__c/recordTypes/pulse.recordType-meta.xml
<RecordType>
    <fullName>pulse</fullName>
    <active>true</active>
    <label>pulse</label>
</RecordType>

force-app/main/default/classes/pulseKraRecordFromController.cls
/**
 * Description: This Apex class represents a controller for Fetching/Updating Goal__c objects of PULSE record type.
 * Author: Shubham Maske
 * Created Date: November 6, 2023
 * Version: 1.0
 * 
 * Change Log:
 * - Version 1.0 (November 6, 2023): Initial implementation.
 */

public without sharing class pulseKraRecordFromController {
    public pulseKraRecordFromController() {

    }

    /**
     * Description: Fetch a Goal__c record by its ID.
     * 
     * @param recordId The ID of the Goal__c record to retrieve.
     * @return A Goal__c record matching the provided ID, or null if not found.
     * 
     * @throws AuraHandledException if an error occurs during the query execution.
     */

    @AuraEnabled(cacheable=true)
    public static Goal__c fetchPulseRecord(Id recordId){
        Goal__c pulseRecord = new Goal__c();
        try {
            if(recordId != null){
                pulseRecord = [Select Id,Name,Status__c,Resource__r.Name from Goal__c WHERE Id =: recordId]; 
            }else {
                return null;
            }
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
        return pulseRecord;
    }

    /**
     * Description: Update a Goal__c record.
     * 
     * @param pulseRecord The Goal__c record to be updated.
     * @return The updated Goal__c record.
     * 
     * @throws AuraHandledException if an error occurs during the update operation.
     */
    @AuraEnabled
    public static Goal__c updatePulseRecord(Goal__c pulseRecord){
        try {
            Update pulseRecord;
            return pulseRecord;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}