force-app/main/default/objects/CampaignMember/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <label>Notes</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CP_Sales_lead__c/CP_Sales_lead__c.object-meta.xml
<CustomObject>
    <label>Lead</label>
    <nameField>
        <label>Lead Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CP_Sales_lead__c/fields/Annual_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Annual_Revenue__c</fullName>
    <label>AnnualRevenue</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CP_Sales_lead__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CP_Sales_lead__c/fields/Do_Not_Call__c.field-meta.xml
<CustomField>
    <fullName>Do_Not_Call__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Do Not Call</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CP_Sales_lead__c/fields/Fax__c.field-meta.xml
<CustomField>
    <fullName>Fax__c</fullName>
    <label>Fax</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CP_Sales_lead__c/fields/HasOptedOutOfEmail__c.field-meta.xml
<CustomField>
    <fullName>HasOptedOutOfEmail__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Email Opt Out</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CP_Sales_lead__c/fields/HasOptedOutOfFax__c.field-meta.xml
<CustomField>
    <fullName>HasOptedOutOfFax__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Fax Opt Out</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CP_Sales_lead__c/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <label>Industry</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agriculture</fullName>
            </value>
            <value>
                <fullName>Apparel</fullName>
            </value>
            <value>
                <fullName>Banking</fullName>
            </value>
            <value>
                <fullName>Biotechnology</fullName>
            </value>
            <value>
                <fullName>Chemicals</fullName>
            </value>
            <value>
                <fullName>Communications</fullName>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
            <value>
                <fullName>Consulting</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Electronics</fullName>
            </value>
            <value>
                <fullName>Energy</fullName>
            </value>
            <value>
                <fullName>Engineering</fullName>
            </value>
            <value>
                <fullName>Entertainment</fullName>
            </value>
            <value>
                <fullName>Environmental</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>Food &amp; Beverage</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
            <value>
                <fullName>Hospitality</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>Machinery</fullName>
            </value>
            <value>
                <fullName>Manufacturing</fullName>
            </value>
            <value>
                <fullName>Media</fullName>
            </value>
            <value>
                <fullName>Not For Profit</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Recreation</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Shipping</fullName>
            </value>
            <value>
                <fullName>Technology</fullName>
            </value>
            <value>
                <fullName>Telecommunications</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CP_Sales_lead__c/fields/LastTransferDate__c.field-meta.xml
<CustomField>
    <fullName>LastTransferDate__c</fullName>
    <label>Last Transfer Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CP_Sales_lead__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipName>CP_Sales_leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CP_Sales_lead__c/fields/Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source__c</fullName>
    <label>Lead Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>5 Rings</fullName>
            </value>
            <value>
                <fullName>CP Sales</fullName>
            </value>
            <value>
                <fullName>Advertisement</fullName>
            </value>
            <value>
                <fullName>Customer Event</fullName>
            </value>
            <value>
                <fullName>Employee Referral</fullName>
            </value>
            <value>
                <fullName>External Referral</fullName>
            </value>
            <value>
                <fullName>Google AdWords</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Purchased List</fullName>
            </value>
            <value>
                <fullName>Trade Show</fullName>
            </value>
            <value>
                <fullName>Webinar</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CP_Sales_lead__c/fields/Lead_Status__c.field-meta.xml
<CustomField>
    <fullName>Lead_Status__c</fullName>
    <label>Lead Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unqualified</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Working</fullName>
            </value>
            <value>
                <fullName>Nurturing</fullName>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CP_Sales_lead__c/fields/MobilePhone__c.field-meta.xml
<CustomField>
    <fullName>MobilePhone__c</fullName>
    <label>Mobile</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/CP_Sales_lead__c/fields/NumberOfEmployees__c.field-meta.xml
<CustomField>
    <fullName>NumberOfEmployees__c</fullName>
    <label>No. of Employees</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CP_Sales_lead__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <label>Rating</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hot</fullName>
            </value>
            <value>
                <fullName>Warm</fullName>
            </value>
            <value>
                <fullName>Cold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CP_Sales_lead__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Notes_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Notes_Campaign__c</fullName>
    <label>Notes_Campaign</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Sales_Lead__c.field-meta.xml
<CustomField>
    <fullName>Sales_Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales _Lead</label>
    <referenceTo>CP_Sales_lead__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CustomLeadUpdateHandler.cls
public class CustomLeadUpdateHandler {
    public static boolean isLeadTriggerExecuted = false;
    public static void updateCustomLead(List<Lead> leadlist){
        Set<Id> leadIdSet=new Set<Id>();
        For(Lead l:leadlist)
        {
            leadIdSet.add(l.id);
        }
        
        List<CP_Sales_lead__c> leadlist1=new List<CP_Sales_lead__c>();
        //List<CampaignMember> campaignMemberList = [Select Id,Name,CampaignId,LeadId,Campaign.Name from CampaignMember where Campaign.Name='CP 5Rings Campaign'];
        List<Lead> scope=[Select Id,Sales_Lead__c, Address,AnnualRevenue,Company,CreatedById,Jigsaw,Description,
                        DoNotCall,Email,HasOptedOutOfEmail,Fax,HasOptedOutOfFax,Industry,LastTransferDate,OwnerId,
                        LeadSource,Status,MobilePhone,Name,NumberOfEmployees,Notes__c,Phone,Rating,Title,
                        Website from Lead Where Id=:leadIdSet];
        
        for(Lead s : scope)
        {
            
                CP_Sales_lead__c le = new CP_Sales_lead__c();
                
            if(s.Sales_Lead__c <> null)   {
                 // le=new CP_Sales_lead__c();
                 le.id = s.Sales_Lead__c;
                 //le.Lead__c=s.Id;
                 le.Name=s.Name;
                 le.Annual_Revenue__c=s.AnnualRevenue; 
                 le.Annual_Revenue__c=s.AnnualRevenue;
                 le.Company__c=s.Company;
                 le.Description__c=s.Description;
                 le.Do_Not_Call__c=s.DoNotCall;
                 le.Email__c=s.Email;
                 le.HasOptedOutOfEmail__c=s.HasOptedOutOfEmail;
                 le.Fax__c=s.Fax;
                 le.HasOptedOutOfFax__c=s.HasOptedOutOfFax;
                 le.Industry__c=s.Industry;
                 le.LastTransferDate__c=s.LastTransferDate;
                 le.OwnerId=s.OwnerId;
                 le.Lead_Source__c=s.LeadSource;
                 le.Lead_Status__c=s.Status;
                 le.MobilePhone__c=s.MobilePhone;
                 le.NumberOfEmployees__c=s.NumberOfEmployees;
                 le.Notes__c=s.Notes__c;
                 //le.Notes_Campaign__c=s.Notes_Campaign__c;
                 le.Phone__c=s.Phone;
                 le.Rating__c=s.Rating;
                 le.Title__c=s.Title;
                 le.Website__c=s.Website;
                 leadlist1.add(le); 
                 }                
        }
                
        
        If(leadlist1.size()>0)
        {
            isLeadTriggerExecuted = true;
            Database.update(leadlist1,true);
            
        }
    }
}