force-app/main/default/objects/EMS_LM_Leave_History__c/EMS_LM_Leave_History__c.object-meta.xml
<CustomObject>
    <description>It will show the employee Leave and WFH Requests.</description>
    <label>Leave Request</label>
    <nameField>
        <displayFormat>LH-{00000}</displayFormat>
        <label>Leave History Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leaves Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_LM_Leave_History__c/fields/EMS_LM_Approved_On__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Approved_On__c</fullName>
    <label>Approved On</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_History__c/fields/EMS_LM_Approver__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Leaves_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_History__c/fields/EMS_LM_Current_Approver__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Current_Approver__c</fullName>
    <description>This field is used to populate current approver details and rejected approver details.</description>
    <label>Current Approver</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_History__c/fields/EMS_LM_Remarks__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Remarks__c</fullName>
    <label>Remarks</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_History__c/fields/EMS_LM_Status__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Approver 2 Pending</fullName>
            </value>
            <value>
                <fullName>Approver 1 Pending</fullName>
            </value>
            <value>
                <fullName>Auto Approved</fullName>
            </value>
            <value>
                <fullName>Waiting For Approver 3</fullName>
                <isActive>false</isActive>
                <label>Waiting For Approver 3</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Hr_Access__c.field-meta.xml
<CustomField>
    <fullName>Hr_Access__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Hr Access</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/LeaveRequestHRRejectHandler.cls
/**
* @author Pavan
* @date 11/01/2023
* @description  To update the leave request status to Rejected for admim view tab.
*            
*
*               Test code coverage provided by the following test class:
*               -LeaveRequestHRRejectHandlerTest
*
* CHANGE HISTORY
* ====================================================================================================
* DATE          NAME                    DESCRIPTION
* N/A           N/A                     N/A
* ====================================================================================================
**/
public without sharing class LeaveRequestHRRejectHandler {
                /**
*   {Purpose} - Method used to update leave request status to Rejected.
*
*   CHANGE HISTORY
*   ====================================================================================================
*   Date        Name                    Description
*   N/A         N/A                     N/A
*   ====================================================================================================
**/
    @AuraEnabled
    public static void updateRejectStatus(String leaveRequestId , String comments){
        System.debug('### LeaveRequestId ' + leaveRequestId);
        System.debug('### Comments ' + comments);
        
        User usr = [SELECT Id, 
                           Hr_Access__c,
                           LastName,
                           FirstName
                    FROM User
                    WHERE Id =: LeaveRequestConstant.LOGGEDIN_USERID]; 
      if (usr.Hr_Access__c = true) {
        List<EMS_LM_Leave_History__c> leaveReqList = new List<EMS_LM_Leave_History__c>();
        for (EMS_LM_Leave_History__c leaveReqStatus : [SELECT Id,
                                                    		 EMS_LM_Status__c,
                                                             EMS_LM_Approver__c,
                                                       		 EMS_LM_Current_Approver__c,
                                                       		 EMS_LM_Remarks__c,
                                                             EMS_LM_Approved_On__c
                                                        FROM EMS_LM_Leave_History__c
                                                        WHERE Id =: leaveRequestId]) {
                                                                
                leaveReqStatus.EMS_LM_Status__c = LeaveRequestConstant.REJECTED;
                leaveReqStatus.EMS_LM_Current_Approver__c = usr.FirstName + ' ' + usr.LastName;
                leaveReqStatus.EMS_LM_Remarks__c = comments;
                leaveReqStatus.EMS_LM_Approved_On__c= System.today();                                       
                leaveReqList.add(leaveReqStatus); 
                                                                
           }
            System.debug('updatedLeaveReq Before Update' + leaveReqList);
        try{
           update leaveReqList;
           System.debug('updatedLeaveReq' + leaveReqList);
        }
            catch(Exception ex){
                //LogException.logHandledException(ex);
                LogException.logHandledException(ex, 'LeaveRequestHRRejectHandler', 'updateRejectStatus');
                System.debug('### Exception ' + ex.getMessage());
 
         }
      }
        
    }
    
                /**
*   {Purpose} - Method used for bulk rejection of leave request status for bulk Rejection.
*
*   CHANGE HISTORY
*   ====================================================================================================
*   Date        Name                    Description
*   N/A         N/A                     N/A
*   ====================================================================================================
**/
         @AuraEnabled
    public static void bulkLeaveReqReject(List<Id> bulkleaveReqId, String comments) {
        System.debug('### bulkleaveReqId ' + bulkleaveReqId);
        System.debug('### Comments ' + comments);
        
                User usr = [SELECT Id, 
                           Hr_Access__c,
                           LastName,
                           FirstName
                    FROM User
                    WHERE Id =: LeaveRequestConstant.LOGGEDIN_USERID]; 
        
      if (usr.Hr_Access__c = true) {
        List<EMS_LM_Leave_History__c> bulkLeaveReqList = new List<EMS_LM_Leave_History__c>();        
        for (EMS_LM_Leave_History__c bulkleaveReqReject : [SELECT Id,
                                                             EMS_LM_Status__c,
                                                             EMS_LM_Approver__c,
                                                       		 EMS_LM_Current_Approver__c, 
                                                       	     EMS_LM_Approved_On__c,
                                                      		 EMS_LM_Remarks__c
                                                       FROM EMS_LM_Leave_History__c
                                                       WHERE Id =: bulkleaveReqId]){                                              
                  bulkleaveReqReject.EMS_LM_Status__c = LeaveRequestConstant.REJECTED;
                  bulkleaveReqReject.EMS_LM_Approved_On__c	 = System.today();
                  bulkleaveReqReject.EMS_LM_Current_Approver__c = usr.FirstName + ' ' + usr.LastName;
                  bulkleaveReqReject.EMS_LM_Remarks__c = comments;
                  bulkLeaveReqList.add(bulkleaveReqReject); 
               }
        	System.debug('bulkupdatedLeaveReq Before Update' + bulkLeaveReqList);
        try{
           update bulkLeaveReqList;
           System.debug('bulkupdatedLeaveReq' + bulkLeaveReqList);
        }
            catch(Exception ex){
                //LogException.logHandledException(ex);
                LogException.logHandledException(ex, 'LeaveRequestHRRejectHandler', 'bulkLeaveReqReject');
                System.debug('### Exception ' + ex.getMessage());
        	}
    
    	}
	}
}