force-app/main/default/objects/EMS_LM_Leave_History__c/EMS_LM_Leave_History__c.object-meta.xml
<CustomObject>
    <description>It will show the employee Leave and WFH Requests.</description>
    <label>Leave Request</label>
    <nameField>
        <displayFormat>LH-{00000}</displayFormat>
        <label>Leave History Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leaves Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_LM_Leave_History__c/fields/Approver_1_Approved_Comments__c.field-meta.xml
<CustomField>
    <fullName>Approver_1_Approved_Comments__c</fullName>
    <label>Approver 1 Approved Comments</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_History__c/fields/Approver_1_Rejection_Comments__c.field-meta.xml
<CustomField>
    <fullName>Approver_1_Rejection_Comments__c</fullName>
    <label>Approver 1 Rejection Comments</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_History__c/fields/Approver_2_Approved_Comments__c.field-meta.xml
<CustomField>
    <fullName>Approver_2_Approved_Comments__c</fullName>
    <label>Approver 2 Approved Comments</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_History__c/fields/Approver_2_Rejection_Comments__c.field-meta.xml
<CustomField>
    <fullName>Approver_2_Rejection_Comments__c</fullName>
    <label>Approver 2 Rejection Comments</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_History__c/fields/Approver_3__c.field-meta.xml
<CustomField>
    <fullName>Approver_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver 3</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Leaves_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_History__c/fields/Approver_3_Approved_Comments__c.field-meta.xml
<CustomField>
    <fullName>Approver_3_Approved_Comments__c</fullName>
    <label>Approver 3 Approved Comments</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_History__c/fields/Approver_3_Rejection_Comments__c.field-meta.xml
<CustomField>
    <fullName>Approver_3_Rejection_Comments__c</fullName>
    <label>Approver 3 Rejection Comments</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_History__c/fields/EMS_LM_2nd_Approver__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_2nd_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>2nd Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Leaves_History1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_History__c/fields/EMS_LM_Approver__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Leaves_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_History__c/fields/EMS_LM_Current_Approver__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Current_Approver__c</fullName>
    <description>This field is used to populate current approver details and rejected approver details.</description>
    <label>Current Approver</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EMS_LM_Leave_History__c/fields/EMS_LM_Status__c.field-meta.xml
<CustomField>
    <fullName>EMS_LM_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Approver 2 Pending</fullName>
            </value>
            <value>
                <fullName>Approver 1 Pending</fullName>
            </value>
            <value>
                <fullName>Auto Approved</fullName>
            </value>
            <value>
                <fullName>Waiting For Approver 3</fullName>
                <isActive>false</isActive>
                <label>Waiting For Approver 3</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LeaveRequestRejectHandler.cls
/**
* @author Pavan
* @date 11/01/2023
* @description  To update the leave request status to Rejected and Rejected comments
*            
*
*               Test code coverage provided by the following test class:
*               -
*
* CHANGE HISTORY
* ====================================================================================================
* DATE          NAME                    DESCRIPTION
* N/A           N/A                     N/A
* ====================================================================================================
**/
public without sharing class LeaveRequestRejectHandler {
                /**
*   {Purpose} - Method used to update leave request status to Rejected.
*
*   CHANGE HISTORY
*   ====================================================================================================
*   Date        Name                    Description
*   N/A         N/A                     N/A
*   ====================================================================================================
**/
	@AuraEnabled
    public static void updateRejecteStatusAndComments(String leaveRequestId , String comments){
        System.debug('### leaveRequestId ' + leaveRequestId);
        System.debug('### Comments ' + comments);
        List<EMS_LM_Leave_History__c> updatedLeaveReqList = new List<EMS_LM_Leave_History__c>();
        for (EMS_LM_Leave_History__c leaveReqStatus : [SELECT Id,
                                                    		EMS_LM_Status__c,
                                                    		Approver_1_Approved_Comments__c,
                                                    		Approver_2_Approved_Comments__c,
                                                    		Approver_3_Approved_Comments__c,
                                                            EMS_LM_Approver__c,
                                                       	 	 EMS_LM_Approver__r.LastName,
                                                       	     EMS_LM_Approver__r.FirstName,
                                                             EMS_LM_2nd_Approver__c,
                                                       		 EMS_LM_2nd_Approver__r.LastName,
                                                       	     EMS_LM_2nd_Approver__r.FirstName,
                                                       		 EMS_LM_Current_Approver__c,
                                                             Approver_3__c,
                                                             Approver_3__r.LastName,
                                                             Approver_3__r.FirstName
                                                    FROM EMS_LM_Leave_History__c
                                                    WHERE Id =:leaveRequestId]) {
           if (LeaveRequestConstant.LOGGEDIN_USERID == leaveReqStatus.EMS_LM_Approver__c) {
                leaveReqStatus.EMS_LM_Status__c = LeaveRequestConstant.REJECTED;
                leaveReqStatus.Approver_1_Approved_Comments__c = comments;
                leaveReqStatus.EMS_LM_Current_Approver__c = leaveReqStatus.EMS_LM_Approver__r.LastName + ' ' + leaveReqStatus.EMS_LM_Approver__r.FirstName ;
                updatedLeaveReqList.add(leaveReqStatus); 
            }else if(LeaveRequestConstant.LOGGEDIN_USERID == leaveReqStatus.EMS_LM_2nd_Approver__c) {
                leaveReqStatus.EMS_LM_Status__c = LeaveRequestConstant.REJECTED;
                leaveReqStatus.Approver_2_Approved_Comments__c = comments;
                leaveReqStatus.EMS_LM_Current_Approver__c = leaveReqStatus.EMS_LM_2nd_Approver__r.LastName + ' ' + leaveReqStatus.EMS_LM_2nd_Approver__r.FirstName ;
                updatedLeaveReqList.add(leaveReqStatus); 
            }else if (LeaveRequestConstant.LOGGEDIN_USERID == leaveReqStatus.Approver_3__c){
                leaveReqStatus.EMS_LM_Status__c = LeaveRequestConstant.REJECTED;
                leaveReqStatus.Approver_3_Approved_Comments__c = comments;
                leaveReqStatus.EMS_LM_Current_Approver__c = leaveReqStatus.Approver_3__r.LastName + ' ' + leaveReqStatus.Approver_3__r.FirstName ;
                updatedLeaveReqList.add(leaveReqStatus); 
            }
        }
        System.debug('### updatedLeaveReq Before Update' +updatedLeaveReqList);
        try{
            update updatedLeaveReqList;
            System.debug('### updatedLeaveReq' +updatedLeaveReqList);
        }
        catch(Exception ex){
            System.debug('### Exception' + ex.getMessage());
        }
        
    }
    
                /**
*   {Purpose} - Method used for bulk rejection of leave request status to Approced.
*
*   CHANGE HISTORY
*   ====================================================================================================
*   Date        Name                    Description
*   N/A         N/A                     N/A
*   ====================================================================================================
**/
    @AuraEnabled
    public static void bulkLeaveReqReject(List<Id> bulkRejectId, String comments){
        System.debug('### bulkRejectId ' + bulkRejectId);
        System.debug('### Comments ' + comments);
        List<EMS_LM_Leave_History__c> bulkupdatedLeaveReqList = new List<EMS_LM_Leave_History__c>();
        for (EMS_LM_Leave_History__c leaveReqStatus : [SELECT Id,
                                                    		EMS_LM_Status__c,
                                                    		Approver_1_Rejection_Comments__c,
                                                    		Approver_2_Rejection_Comments__c,
                                                    		Approver_3_Rejection_Comments__c,
                                                     		EMS_LM_Approver__c,
                                                     		EMS_LM_2nd_Approver__c,
                                                            Approver_3__c
                                                    FROM EMS_LM_Leave_History__c
                                                    WHERE Id =:bulkRejectId]) {
           if (LeaveRequestConstant.LOGGEDIN_USERID == leaveReqStatus.EMS_LM_Approver__c) {
                leaveReqStatus.EMS_LM_Status__c = LeaveRequestConstant.REJECTED;
                leaveReqStatus.Approver_1_Rejection_Comments__c = comments;
                bulkupdatedLeaveReqList.add(leaveReqStatus); 
            }else if(LeaveRequestConstant.LOGGEDIN_USERID == leaveReqStatus.EMS_LM_2nd_Approver__c) {
                leaveReqStatus.EMS_LM_Status__c = LeaveRequestConstant.REJECTED;
                leaveReqStatus.Approver_2_Rejection_Comments__c = comments;
                bulkupdatedLeaveReqList.add(leaveReqStatus); 
            }else if (LeaveRequestConstant.LOGGEDIN_USERID == leaveReqStatus.Approver_3__c){
                leaveReqStatus.EMS_LM_Status__c = LeaveRequestConstant.REJECTED;
                leaveReqStatus.Approver_3_Rejection_Comments__c = comments;
                bulkupdatedLeaveReqList.add(leaveReqStatus); 
            }
        }
        System.debug('### updatedLeaveReq Before Update' +bulkupdatedLeaveReqList);
        try{
            update bulkupdatedLeaveReqList;
            System.debug('### bulkupdatedLeaveReqList' +bulkupdatedLeaveReqList);
        }
        catch(Exception ex){
            System.debug('### Exception' + ex.getMessage());
        } 
    }
}