force-app/main/default/objects/Contact/recordTypes/Resource.recordType-meta.xml
<RecordType>
    <fullName>Resource</fullName>
    <active>true</active>
    <label>Resource</label>
</RecordType>

force-app/main/default/objects/EMS_TM_Assignment__c/EMS_TM_Assignment__c.object-meta.xml
<CustomObject>
    <label>Assignment</label>
    <nameField>
        <displayFormat>A.ID-{0000}</displayFormat>
        <label>Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_TM_Assignment__c/fields/EMS_TM_EmployeeName__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_EmployeeName__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Employee Name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Resource</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Assignments</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Assignment__c/fields/EMS_TM_ProjectName_Asgn__c.field-meta.xml
<CustomField>
    <fullName>EMS_TM_ProjectName_Asgn__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Name</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>EMS_TM_Project__c.Type_Of_Project__c</field>
            <operation>notEqual</operation>
            <value>Global Projects</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>EMS_TM_Project__c</referenceTo>
    <relationshipLabel>Project Assignees</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS_TM_Assignment__c/fields/Project_Allocation__c.field-meta.xml
<CustomField>
    <fullName>Project_Allocation__c</fullName>
    <inlineHelpText>Percentage of effort allocated for this project</inlineHelpText>
    <label>Project Allocation %</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/projectAssigneeCreated2__e/fields/projectAssigneeId__c.field-meta.xml
<CustomField>
    <fullName>projectAssigneeId__c</fullName>
    <label>projectAssigneeId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/projectAssigneeCreated2__e/fields/projectAssigneeProjectName__c.field-meta.xml
<CustomField>
    <fullName>projectAssigneeProjectName__c</fullName>
    <label>projectAssigneeProjectName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/projectAssigneeCreated2__e/fields/projectAssigneeResourceName__c.field-meta.xml
<CustomField>
    <fullName>projectAssigneeResourceName__c</fullName>
    <label>projectAssigneeResourceName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/projectAssigneeCreated2__e/fields/projectAssigneeTotalProjectAllocation__c.field-meta.xml
<CustomField>
    <fullName>projectAssigneeTotalProjectAllocation__c</fullName>
    <label>projectAssigneeTotalProjectAllocation</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/showMsgBasedOnToatlProjectAllocation.cls
/**
    * @author Shubham Maske
    * @date 26/09/2023
    * 
    * @description After Insert : We are firing Platform Event for those records whose resource total project allocation is more then 100%
    * Hence Firing Platform Event and Subscribing via  LWC component.
    * 
    * @TestClass : showMsgBasedOnToatlProjectAllocationTest
    * CHANGE HISTORY
    * ====================================================================================================
    * DATE          NAME                    DESCRIPTION
    * N/A           N/A                     N/A
    * ====================================================================================================
    **/
public without sharing class showMsgBasedOnToatlProjectAllocation implements TriggerAction.AfterUpdate,TriggerAction.AfterInsert {
	

    public void afterUpdate(List<EMS_TM_Assignment__c> newList,List<EMS_TM_Assignment__c> oldList) {      
       /*System.debug(LoggingLevel.DEBUG, 'showMsgBasedOnToatlProjectAllocation.afterUpdate() : BEGIN');
        Map<id,EMS_TM_Assignment__c> assignmentOldMap = new Map<id,EMS_TM_Assignment__c>(oldList);
        showMsgOnRecordUpdate(newList,assignmentOldMap);
        System.debug(LoggingLevel.DEBUG, 'showMsgBasedOnToatlProjectAllocation.afterUpdate() : END'); */      
    }
    
   /**
 	* @author Shubham Maske
    * @date 26/09/2023
    * @description After Insert 
    *
    * CHANGE HISTORY
    * ====================================================================================================
    * DATE          NAME                    DESCRIPTION
    * N/A           N/A                     N/A
    * ====================================================================================================
    **/
    public void afterInsert(List<EMS_TM_Assignment__c> newList) {      
        System.debug(LoggingLevel.DEBUG, 'showMsgBasedOnToatlProjectAllocation.afterInsert() : BEGIN');
        showMsgOnRecordInsert(newList,Null);
        System.debug(LoggingLevel.DEBUG, 'showMsgBasedOnToatlProjectAllocation.afterInsert() : END');       
    }
    
    /*
    private void showMsgOnRecordUpdate(List<EMS_TM_Assignment__c> newAssignment,Map<Id,EMS_TM_Assignment__c> oldMap){        
    }
    */
    
    private void showMsgOnRecordInsert(List<EMS_TM_Assignment__c> newAssignment,Map<Id,EMS_TM_Assignment__c> oldMap){
		System.debug('*** INSIDE showMsgOnRecordInsert ***');
        Map<Id,EMS_TM_Assignment__c> resAssignMap = new Map<Id,EMS_TM_Assignment__c>(); 
        for(EMS_TM_Assignment__c assignRec: newAssignment){
            if((oldMap != null && (oldMap.get(assignRec.id).Project_Allocation__c != assignRec.Project_Allocation__c)) || oldmap == null ){
                resAssignMap.put(assignRec.EMS_TM_EmployeeName__c,assignRec);
            }
        }
        System.debug('*** resAssignMap ***' + resAssignMap.toString());
        
        Map<Id,String> resNameMap = new Map<Id,String>();
        for(Contact con : [Select Id,Name FROM Contact WHERE Id IN : resAssignMap.keySet() ]){
            resNameMap.put(con.Id,con.Name);
        }
        System.debug('*** resNameMap ***' + resNameMap.toString());

        Map<Decimal,EMS_TM_Assignment__c> prjAllAssignMap = new Map<Decimal,EMS_TM_Assignment__c>();
        for(Id conId : resAssignMap.keySet()){
            String conRecId = conId;
            Decimal totalProjectAllocation = ChangeProjectActionButtonController.getTotalProjectAllocationOfSingleContact(conRecId);
            if (totalProjectAllocation > 100){
                prjAllAssignMap.put(totalProjectAllocation,resAssignMap.get(conId));
            }
        }
        
        System.debug('*** prjAllAssignMap ***' + prjAllAssignMap.toString());
        
        List<projectAssigneeCreated2__e> projectAssigneeCreatedEvents = new List<projectAssigneeCreated2__e>();
        if(!prjAllAssignMap.isEmpty()){
            for(EMS_TM_Assignment__c assmntRec: prjAllAssignMap.values()){                
                projectAssigneeCreated2__e evnt  = new projectAssigneeCreated2__e();
                evnt.projectAssigneeId__c = assmntRec.Id;
                evnt.projectAssigneeProjectName__c = assmntRec.EMS_TM_ProjectName_Asgn__c;
                evnt.projectAssigneeResourceName__c = resNameMap.get(assmntRec.EMS_TM_EmployeeName__c);
                evnt.projectAssigneeTotalProjectAllocation__c = ChangeProjectActionButtonController.getTotalProjectAllocationOfSingleContact(assmntRec.EMS_TM_EmployeeName__c);
                projectAssigneeCreatedEvents.add(evnt);
            }
        }
        
        System.debug('*** projectAssigneeCreatedEvents ***' + projectAssigneeCreatedEvents );
        List<Database.SaveResult> results = new List<Database.SaveResult>();
        try {
            if(!projectAssigneeCreatedEvents.isEmpty()){
                results = EventBus.publish(projectAssigneeCreatedEvents);
            }
        } Catch(Exception excp){
            LogException.logHandledException(excp, 'showMsgBasedOnToatlProjectAllocation', 'showMsgOnRecordInsert');        
        }
    }
    
    
    
}