force-app/main/default/objects/Reward_And_Recognition__c/Reward_And_Recognition__c.object-meta.xml
<CustomObject>
    <label>Reward And Recognition</label>
    <nameField>
        <displayFormat>REC{0000000}</displayFormat>
        <label>Nominee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rewards And Recognitions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reward_And_Recognition__c/fields/Award_Type__c.field-meta.xml
<CustomField>
    <fullName>Award_Type__c</fullName>
    <label>Award Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Best Entrepreneur</fullName>
            </value>
            <value>
                <fullName>Most Professional</fullName>
            </value>
            <value>
                <fullName>Rising Star</fullName>
            </value>
            <value>
                <fullName>Rock Star</fullName>
            </value>
            <value>
                <fullName>Service Awards</fullName>
            </value>
            <value>
                <fullName>Recognize</fullName>
            </value>
            <value>
                <fullName>Shout Out</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reward_And_Recognition__c/fields/Lost_Reason__c.field-meta.xml
<CustomField>
    <fullName>Lost_Reason__c</fullName>
    <label>Lost Reason</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Reward_And_Recognition__c/fields/Primary_Nomination__c.field-meta.xml
<CustomField>
    <fullName>Primary_Nomination__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Nomination</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Reward_And_Recognition__c/fields/Reason_for_award__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_award__c</fullName>
    <label>Reason for award</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Reward_And_Recognition__c/fields/Recognization_By__c.field-meta.xml
<CustomField>
    <fullName>Recognization_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Stores the information about the user of user who created this</inlineHelpText>
    <label>Recognization By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Rewards_And_Recognitions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reward_And_Recognition__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <label>Resource</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Rewards And Recognitions</relationshipLabel>
    <relationshipName>Rewards_And_Recognitions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reward_And_Recognition__c/fields/Secondary_Nomination__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Nomination__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Secondary Nomination</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Reward_And_Recognition__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nominated</fullName>
                <default>true</default>
                <label>Nominated</label>
            </value>
            <value>
                <fullName>Review In Progress</fullName>
            </value>
            <value>
                <fullName>Not Qualified</fullName>
            </value>
            <value>
                <fullName>Winner</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reward_And_Recognition__c/fields/System_Predicted_Status__c.field-meta.xml
<CustomField>
    <fullName>System_Predicted_Status__c</fullName>
    <label>System Predicted Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Might Looser</fullName>
                <label>Most Likely Winner</label>
            </value>
            <value>
                <fullName>Might Winner</fullName>
            </value>
            <value>
                <fullName>Winner</fullName>
            </value>
            <value>
                <fullName>Looser</fullName>
                <label>Potential Winner</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reward_And_Recognition__c/recordTypes/Scoring.recordType-meta.xml
<RecordType>
    <fullName>Scoring</fullName>
    <active>true</active>
    <description>Used  for Annual Awards Scoring</description>
    <label>Scoring</label>
</RecordType>

force-app/main/default/classes/UpdateTheScoresForWinner.cls
/**
* @author Subba Kalavala
* @date 11/10/2023
* @description  UpdateTheScoresForWinner Class to update all the Scoring as Lost for other awards
*
*               Test code coverage provided by the following test class:
*               - 
*
* CHANGE HISTORY
* ====================================================================================================
* DATE          NAME                    DESCRIPTION
* N/A           N/A                     N/A
* ====================================================================================================
**/
public without sharing class UpdateTheScoresForWinner implements TriggerAction.AfterUpdate{
   /**
* @author Subba Kalavala
* @date 
* @description AfterUpdate
*
* CHANGE HISTORY
* ====================================================================================================
* DATE          NAME                    DESCRIPTION
* N/A           N/A                     N/A
* ====================================================================================================
**/
    public void afterUpdate(List<Reward_And_Recognition__c> newList, List<Reward_And_Recognition__c> oldList) {      
        System.debug(LoggingLevel.DEBUG, 'UpdateTheScoresForWinner.beforeUpdate() : BEGIN');
        updateTheScoring(newList,new Map<Id,Reward_And_Recognition__c>(oldList));
        System.debug(LoggingLevel.DEBUG, 'UpdateTheScoresForWinner.beforeUpdate() : END');       
    }

/**
*   {Purpose} - Method
*
*   CHANGE HISTORY
*   ====================================================================================================
*   Date        Name                    Description
*   N/A         N/A                     N/A
*   ====================================================================================================
**/
    public void updateTheScoring(List<Reward_And_Recognition__c> newlist, Map<Id,Reward_And_Recognition__c> oldMap) {
          Id scoringRecordTypeId = Schema.SObjectType.Reward_And_Recognition__c.getRecordTypeInfosByName().get('Scoring').getRecordTypeId();
          set<Id> resourceId = new set<Id>();
          set<String> considerAwards = new set<String>();
          set<Id> rrIds = new set<Id>();
          Map<String,Reward_And_Recognition__c> resWithRecord = new Map<String,Reward_And_Recognition__c>();
          for(Reward_And_Recognition__c newRec :  newlist){
              Reward_And_Recognition__c oldRec = oldMap.get(newRec.Id);
              if(newRec.recordTypeId == scoringRecordTypeId && newRec.Status__c == 'Winner' && (newRec.Status__c != oldRec.Status__c)){
                 String uniqueKey = newRec.Resource__c;
                 resWithRecord.put(uniqueKey,newRec);
                 rrIds.add(newRec.Id);
                 considerAwards.add(newRec.Award_Type__c);
                 resourceId.add(newRec.Resource__c);
              }
          }
         system.debug('===rrIds======'+rrIds);
         system.debug('===resourceId======'+resourceId);
            Map<id,Reward_And_Recognition__c> updateNomsDML = new Map<Id,Reward_And_Recognition__c>();
            
            if(!resourceId.isEmpty()){
                for(Reward_And_Recognition__c newRec :  [SELECT Id,Status__c,Award_Type__c,Resource__c,Primary_Nomination__c, Secondary_Nomination__c,Recognization_By__c,Recognization_By__r.Name,Reason_for_award__c 
                 FROM Reward_And_Recognition__c WHERE Status__c = 'Review In Progress' and Id NOT IN:rrIds
                 and RecordTypeId=:scoringRecordTypeId and Resource__c IN:resourceId]){
                     String uniqueKey = newRec.Resource__c; 
                     Reward_And_Recognition__c Winnerscoring = resWithRecord.get(uniqueKey);
                     system.debug('====Winnerscoring==='+Winnerscoring);
                      system.debug(newRec.Resource__c+'====Winnerscoring==='+Winnerscoring.Resource__c);
                     if(Winnerscoring.Status__c == 'Winner' && Winnerscoring.Resource__c == newRec.Resource__c){
                        newRec.Status__c = 'Lost';
                        newRec.System_Predicted_Status__c = 'Looser';
                       // newRec.Comments__c =  Winnerscoring.Comments__c; 
                        newRec.Lost_Reason__c = 'This resource already a winner for award : '+Winnerscoring.Award_Type__c;
                        updateNomsDML.put(newRec.Id,newRec);
                     }
                }
            }
        
        if(!considerAwards.isEmpty()){
             for(Reward_And_Recognition__c newRec :  [SELECT Id,Status__c,Award_Type__c,Resource__c,Primary_Nomination__c, Secondary_Nomination__c,Recognization_By__c,Recognization_By__r.Name,Reason_for_award__c 
                 FROM Reward_And_Recognition__c WHERE Status__c = 'Review In Progress' and Id NOT IN:rrIds
                  and RecordTypeId=:scoringRecordTypeId and Award_Type__c IN:considerAwards]){
                      if(updateNomsDML.containsKey(newRec.id)){
                        updateNomsDML.get(newRec.id).Status__c = 'Lost';
                        updateNomsDML.get(newRec.id).System_Predicted_Status__c = 'Looser';
                        updateNomsDML.get(newRec.id).Lost_Reason__c = 'One of the contender for this award has been marked as winner.';
                       
                      }else{
                        newRec.Status__c = 'Lost';
                        newRec.System_Predicted_Status__c = 'Looser';
                        newRec.Lost_Reason__c = 'One of the contender for this award has been marked as winner.';
                        updateNomsDML.put(newRec.Id,newRec); 
                      }
                  }
        }        
        
        
         try{
           update updateNomsDML.values(); 
        }catch(exception ex){
           LogException.logHandledException(ex, 'UpdateTheScoresForWinner', 'UpdateTheScoresForWinner');  
        }
        
        
    }
}