force-app/main/default/objects/Reward_And_Recognition__c/Reward_And_Recognition__c.object-meta.xml
<CustomObject>
    <label>Reward And Recognition</label>
    <nameField>
        <displayFormat>REC{0000000}</displayFormat>
        <label>Nominee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rewards And Recognitions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reward_And_Recognition__c/fields/Award_Type__c.field-meta.xml
<CustomField>
    <fullName>Award_Type__c</fullName>
    <label>Award Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Best Entrepreneur</fullName>
            </value>
            <value>
                <fullName>Most Professional</fullName>
            </value>
            <value>
                <fullName>Rising Star</fullName>
            </value>
            <value>
                <fullName>Rock Star</fullName>
            </value>
            <value>
                <fullName>Service Awards</fullName>
            </value>
            <value>
                <fullName>Recognize</fullName>
            </value>
            <value>
                <fullName>Shout Out</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reward_And_Recognition__c/fields/of_Primary_Nominations__c.field-meta.xml
<CustomField>
    <fullName>of_Primary_Nominations__c</fullName>
    <label># of Primary Nominations</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Reward_And_Recognition__c/fields/of_Secondary_Nominations__c.field-meta.xml
<CustomField>
    <fullName>of_Secondary_Nominations__c</fullName>
    <label># of Secondary Nominations</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Reward_And_Recognition__c/fields/Primary_Nomination__c.field-meta.xml
<CustomField>
    <fullName>Primary_Nomination__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Nomination</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Reward_And_Recognition__c/fields/Reason_for_award__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_award__c</fullName>
    <label>Reason for award</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Reward_And_Recognition__c/fields/Recognization_By__c.field-meta.xml
<CustomField>
    <fullName>Recognization_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Stores the information about the user of user who created this</inlineHelpText>
    <label>Recognization By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Rewards_And_Recognitions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reward_And_Recognition__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <label>Resource</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Rewards And Recognitions</relationshipLabel>
    <relationshipName>Rewards_And_Recognitions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reward_And_Recognition__c/fields/Secondary_Nomination__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Nomination__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Secondary Nomination</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Reward_And_Recognition__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nominated</fullName>
                <default>true</default>
                <label>Nominated</label>
            </value>
            <value>
                <fullName>Review In Progress</fullName>
            </value>
            <value>
                <fullName>Not Qualified</fullName>
            </value>
            <value>
                <fullName>Winner</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reward_And_Recognition__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ShoutOut</fullName>
            </value>
            <value>
                <fullName>Recognize</fullName>
            </value>
            <value>
                <fullName>Annual Award</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reward_And_Recognition__c/recordTypes/Nominations.recordType-meta.xml
<RecordType>
    <fullName>Nominations</fullName>
    <active>true</active>
    <label>Nominations</label>
</RecordType>

force-app/main/default/objects/Reward_And_Recognition__c/recordTypes/Scoring.recordType-meta.xml
<RecordType>
    <fullName>Scoring</fullName>
    <active>true</active>
    <description>Used  for Annual Awards Scoring</description>
    <label>Scoring</label>
</RecordType>

force-app/main/default/classes/UpdateTheNominatedCountOnNoms.cls
/**
* @author Subba Kalavala
* @date 11/10/2023
* @description  UpdateTheNominatedCountOnNoms Class to update all the Primary and Secondary Counts on Original Noms
*
*               Test code coverage provided by the following test class:
*               - 
*
* CHANGE HISTORY
* ====================================================================================================
* DATE          NAME                    DESCRIPTION
* N/A           N/A                     N/A
* ====================================================================================================
**/
public without sharing class UpdateTheNominatedCountOnNoms implements TriggerAction.AfterInsert{
   /**
* @author Subba Kalavala
* @date 
* @description AfterUpdate
*
* CHANGE HISTORY
* ====================================================================================================
* DATE          NAME                    DESCRIPTION
* N/A           N/A                     N/A
* ====================================================================================================
**/
    public void AfterInsert(List<Reward_And_Recognition__c> newList) {      
        System.debug(LoggingLevel.DEBUG, 'UpdateTheNominatedCountOnNoms.AfterInsert() : BEGIN');
        updateTheCounts(newList);
        System.debug(LoggingLevel.DEBUG, 'UpdateTheNominatedCountOnNoms.AfterInsert() : END');       
    }

/**
*   {Purpose} - Method
*
*   CHANGE HISTORY
*   ====================================================================================================
*   Date        Name                    Description
*   N/A         N/A                     N/A
*   ====================================================================================================
**/
    public void updateTheCounts(List<Reward_And_Recognition__c> newlist) {
        Map<String, Reward_And_Recognition__c>  scoringWithNomnMap = new Map<String, Reward_And_Recognition__c>();
        set<Id> resourceIds = new set<Id>();
         set<String> awardsIds = new set<String>();
        List<Reward_And_Recognition__c> updateRR = new List<Reward_And_Recognition__c>();
        Id scoringRecordTypeId = Schema.SObjectType.Reward_And_Recognition__c.getRecordTypeInfosByName().get('Scoring').getRecordTypeId();
        
         for(Reward_And_Recognition__c score : newlist ){
             if(score.Resource__c != null && score.Award_Type__c != null && score.RecordTypeId == scoringRecordTypeId && score.Status__c == 'Review In Progress'){
               String uniqueKey = score.Resource__c+';'+score.Award_Type__c;
               resourceIds.add(score.Resource__c);
                awardsIds.add(score.Award_Type__c);
               scoringWithNomnMap.put(uniqueKey,score);
             }
        }
        
        if(!scoringWithNomnMap.isEmpty()){
             Id nomRecordTypeId = Schema.SObjectType.Reward_And_Recognition__c.getRecordTypeInfosByName().get('Nominations').getRecordTypeId();
            for(Reward_And_Recognition__c rr : [SELECT Id,Status__c,Award_Type__c,Resource__c,Primary_Nomination__c,
                                          Secondary_Nomination__c,Recognization_By__c,Recognization_By__r.Name,Reason_for_award__c 
                                          FROM Reward_And_Recognition__c WHERE Status__c = 'Nominated' and Resource__c != null and Award_Type__c != null 
                                          and RecordTypeId=:nomRecordTypeId and Type__c = 'Annual Award']){             
              String uniqueKey = rr.Resource__c+';'+rr.Award_Type__c;
                if(scoringWithNomnMap.containsKey(uniqueKey)){
                      rr.of_Primary_Nominations__c = scoringWithNomnMap.get(uniqueKey).of_Primary_Nominations__c;
                      rr.of_Secondary_Nominations__c = scoringWithNomnMap.get(uniqueKey).of_Secondary_Nominations__c;
                    updateRR.add(rr);
                }
             
            }
            
        }
        try{
            update updateRR;
        }catch(exception ex){
           LogException.logHandledException(ex, 'UpdateTheNominatedCountOnNoms', 'UpdateTheNominatedCountOnNoms');  
        } 
        
        
        
        
      }
      
}