force-app/main/default/objects/Reward_And_Recognition__c/Reward_And_Recognition__c.object-meta.xml
<CustomObject>
    <label>Reward And Recognition</label>
    <nameField>
        <displayFormat>REC{0000000}</displayFormat>
        <label>Nominee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rewards And Recognitions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reward_And_Recognition__c/fields/Award_Type__c.field-meta.xml
<CustomField>
    <fullName>Award_Type__c</fullName>
    <label>Award Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Best Entrepreneur</fullName>
            </value>
            <value>
                <fullName>Most Professional</fullName>
            </value>
            <value>
                <fullName>Rising Star</fullName>
            </value>
            <value>
                <fullName>Rock Star</fullName>
            </value>
            <value>
                <fullName>Service Awards</fullName>
            </value>
            <value>
                <fullName>Recognize</fullName>
            </value>
            <value>
                <fullName>Shout Out</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reward_And_Recognition__c/fields/Lost_Reason__c.field-meta.xml
<CustomField>
    <fullName>Lost_Reason__c</fullName>
    <label>Lost Reason</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Reward_And_Recognition__c/fields/Primary_Nomination__c.field-meta.xml
<CustomField>
    <fullName>Primary_Nomination__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Nomination</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Reward_And_Recognition__c/fields/Reason_for_award__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_award__c</fullName>
    <label>Reason for award</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Reward_And_Recognition__c/fields/Recognization_By__c.field-meta.xml
<CustomField>
    <fullName>Recognization_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Stores the information about the user of user who created this</inlineHelpText>
    <label>Recognization By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Rewards_And_Recognitions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reward_And_Recognition__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <label>Resource</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Rewards And Recognitions</relationshipLabel>
    <relationshipName>Rewards_And_Recognitions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reward_And_Recognition__c/fields/Secondary_Nomination__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Nomination__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Secondary Nomination</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Reward_And_Recognition__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nominated</fullName>
                <default>true</default>
                <label>Nominated</label>
            </value>
            <value>
                <fullName>Review In Progress</fullName>
            </value>
            <value>
                <fullName>Not Qualified</fullName>
            </value>
            <value>
                <fullName>Winner</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reward_And_Recognition__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ShoutOut</fullName>
            </value>
            <value>
                <fullName>Recognize</fullName>
            </value>
            <value>
                <fullName>Annual Award</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reward_And_Recognition__c/recordTypes/Nominations.recordType-meta.xml
<RecordType>
    <fullName>Nominations</fullName>
    <active>true</active>
    <label>Nominations</label>
</RecordType>

force-app/main/default/objects/Reward_And_Recognition__c/recordTypes/Scoring.recordType-meta.xml
<RecordType>
    <fullName>Scoring</fullName>
    <active>true</active>
    <description>Used  for Annual Awards Scoring</description>
    <label>Scoring</label>
</RecordType>

force-app/main/default/classes/UpdateTheNomsBasedOnScoring.cls
/**
* @author Subba Kalavala
* @date 11/10/2023
* @description  UpdateTheNomsBasedOnScoring Class to update all the nominations based on score result
*
*               Test code coverage provided by the following test class:
*               - 
*
* CHANGE HISTORY
* ====================================================================================================
* DATE          NAME                    DESCRIPTION
* N/A           N/A                     N/A
* ====================================================================================================
**/
public without sharing class UpdateTheNomsBasedOnScoring implements TriggerAction.AfterUpdate{
   /**
* @author Subba Kalavala
* @date 
* @description AfterUpdate
*
* CHANGE HISTORY
* ====================================================================================================
* DATE          NAME                    DESCRIPTION
* N/A           N/A                     N/A
* ====================================================================================================
**/
    public void afterUpdate(List<Reward_And_Recognition__c> newList, List<Reward_And_Recognition__c> oldList) {      
        System.debug(LoggingLevel.DEBUG, 'UpdateTheNomsBasedOnScoring.beforeUpdate() : BEGIN');
        updateTheNoms(newList,new Map<Id,Reward_And_Recognition__c>(oldList));
        System.debug(LoggingLevel.DEBUG, 'UpdateTheNomsBasedOnScoring.beforeUpdate() : END');       
    }

/**
*   {Purpose} - Method
*
*   CHANGE HISTORY
*   ====================================================================================================
*   Date        Name                    Description
*   N/A         N/A                     N/A
*   ====================================================================================================
**/
    public void updateTheNoms(List<Reward_And_Recognition__c> newlist, Map<Id,Reward_And_Recognition__c> oldMap) {
          Id scoringRecordTypeId = Schema.SObjectType.Reward_And_Recognition__c.getRecordTypeInfosByName().get('Scoring').getRecordTypeId();
          Id nomRecordTypeId = Schema.SObjectType.Reward_And_Recognition__c.getRecordTypeInfosByName().get('Nominations').getRecordTypeId();
          set<Id> resourceId = new set<Id>();
          Map<String,Reward_And_Recognition__c> resWithRecord = new Map<String,Reward_And_Recognition__c>();
          for(Reward_And_Recognition__c newRec :  newlist){
              Reward_And_Recognition__c oldRec = oldMap.get(newRec.Id);
              if(newRec.recordTypeId == scoringRecordTypeId && (newRec.Status__c == 'Winner' || newRec.Status__c == 'Lost') && (newRec.Status__c != oldRec.Status__c)){
                 String uniqueKey = newRec.Resource__c+';'+newRec.Award_Type__c;
                 resWithRecord.put(uniqueKey,newRec);
                 resourceId.add(newRec.Resource__c);
              }
          }
         system.debug('====resWithRecord==='+resWithRecord);
            List<Reward_And_Recognition__c> updateNomsDML = new List<Reward_And_Recognition__c>();
            if(!resourceId.isEmpty()){
                for(Reward_And_Recognition__c newRec :  [SELECT Id,Status__c,Award_Type__c,Resource__c,Primary_Nomination__c, Secondary_Nomination__c,Recognization_By__c,Recognization_By__r.Name,Reason_for_award__c 
                 FROM Reward_And_Recognition__c WHERE Status__c = 'Nominated'
                 and RecordTypeId=:nomRecordTypeId and Type__c = 'Annual Award' and Resource__c IN:resourceId]){
                     String uniqueKey = newRec.Resource__c+';'+newRec.Award_Type__c; 
                     system.debug('====uniqueKey==='+uniqueKey);
                       system.debug('====resWithRecord.get(uniqueKey)==='+resWithRecord.containsKey(uniqueKey));
                     if(resWithRecord.containsKey(uniqueKey)){
                     Reward_And_Recognition__c scoring = resWithRecord.get(uniqueKey);
                     if(scoring.Status__c == 'Winner' && scoring.Resource__c == newRec.Resource__c && scoring.Award_Type__c == newRec.Award_Type__c){
                        newRec.Status__c = 'Winner';
                        newRec.Comments__c =  scoring.Comments__c;
                        updateNomsDML.add(newRec);
                     }else if(scoring.Status__c == 'Lost' && scoring.Resource__c == newRec.Resource__c && scoring.Award_Type__c == newRec.Award_Type__c){
                        newRec.Status__c = 'Lost';
                       // newRec.Comments__c =  scoring.Comments__c; 
                        newRec.Lost_Reason__c = scoring.Lost_Reason__c;
                         updateNomsDML.add(newRec);
                     }
                     }
                }
            }
        
         try{
           update updateNomsDML; 
        }catch(exception ex){
           LogException.logHandledException(ex, 'UpdateTheNomsBasedOnScoring', 'UpdateTheNomsBasedOnScoring');  
        }
        
    }
}