force-app/main/default/objects/EMS_EM_Onboarding_Request__c/EMS_EM_Onboarding_Request__c.object-meta.xml
<CustomObject>
    <label>Onboarding Request</label>
    <nameField>
        <displayFormat>O-{00000}</displayFormat>
        <label>Onboarding Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Onboarding Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_EM_Onboarding_Request__c/fields/EMS_EM_Name__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_Name__c</fullName>
    <displayFormat>AP.ID-{000000}</displayFormat>
    <label>Applicant Id</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/EMS_EM_Onboarding_Request__c/fields/Google_Drive_ID__c.field-meta.xml
<CustomField>
    <fullName>Google_Drive_ID__c</fullName>
    <label>Google Drive ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OnboardingRequestTriggerHandler.cls
public class OnboardingRequestTriggerHandler {
    public static void createDriveFornewRequest(list<EMS_EM_Onboarding_Request__c> newRequestList){
        List<EMS_EM_Onboarding_Request__c> RequestList = new List<EMS_EM_Onboarding_Request__c>();
        for(EMS_EM_Onboarding_Request__c request : newRequestList){
            if(request.EMS_EM_Name__c != null && request.EMS_EM_Name__c != '' && request.Google_Drive_ID__c==null){
                RequestList.add(request); 
            }
        }
        if(!RequestList.isEmpty()){
            Database.executeBatch(new CreateOnboardingDriveFolderBatch(RequestList), 1); 
        }
    }
}