force-app/main/default/objects/EMS_EM_Onboarding_Request__c/EMS_EM_Onboarding_Request__c.object-meta.xml
<CustomObject>
    <label>Onboarding Request</label>
    <nameField>
        <displayFormat>O-{00000}</displayFormat>
        <label>Onboarding Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Onboarding Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_EM_Onboarding_Request__c/fields/Address_Details_Value_Filled__c.field-meta.xml
<CustomField>
    <fullName>Address_Details_Value_Filled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Address Details Value Filled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EMS_EM_Onboarding_Request__c/fields/Education_Details_Filled__c.field-meta.xml
<CustomField>
    <fullName>Education_Details_Filled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Education Details Filled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EMS_EM_Onboarding_Request__c/fields/EMS_EM_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_Last_Name__c</fullName>
    <label>Last Name</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EMS_EM_Onboarding_Request__c/fields/Identify_Details_Value_Filled__c.field-meta.xml
<CustomField>
    <fullName>Identify_Details_Value_Filled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Identify Details Value Filled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EMS_EM_Onboarding_Request__c/fields/Other_Certifications_Value_Filled__c.field-meta.xml
<CustomField>
    <fullName>Other_Certifications_Value_Filled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Other Certifications Value Filled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EMS_EM_Onboarding_Request__c/fields/Personal_Details_Value_Filled__c.field-meta.xml
<CustomField>
    <fullName>Personal_Details_Value_Filled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Personal Details Value Filled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ProgressBarApplicantControllerTest.cls
@isTest
public class ProgressBarApplicantControllerTest {
	public testmethod static void progressBarData(){
        EMS_EM_Onboarding_Request__c onboardingRequestRec = new EMS_EM_Onboarding_Request__c();
        onboardingRequestRec.EMS_EM_Last_Name__c = 'Test';
        onboardingRequestRec.Personal_Details_Value_Filled__c = True;
        onboardingRequestRec.Identify_Details_Value_Filled__c = True;
        onboardingRequestRec.Address_Details_Value_Filled__c = True;
        onboardingRequestRec.Other_Certifications_Value_Filled__c = True;
        onboardingRequestRec.Work_Details_Filled__c = True;
        onboardingRequestRec.Education_Details_Filled__c = True;
        
        insert onboardingRequestRec;
        
        Test.startTest();
        ProgressBarApplicantController.fetchOnboardingRecords(onboardingRequestRec.Id);
        Test.stopTest();
    }
}