force-app/main/default/objects/EMS_EM_Onboarding_Request__c/EMS_EM_Onboarding_Request__c.object-meta.xml
<CustomObject>
    <label>Onboarding Request</label>
    <nameField>
        <displayFormat>O-{00000}</displayFormat>
        <label>Onboarding Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Onboarding Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_EM_Onboarding_Request__c/fields/EMS_EM_First_Name__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_First_Name__c</fullName>
    <label>First Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EMS_EM_Onboarding_Request__c/fields/EMS_EM_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_Last_Name__c</fullName>
    <label>Last Name</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EMS_EM_Onboarding_Request__c/fields/Google_Drive_ID__c.field-meta.xml
<CustomField>
    <fullName>Google_Drive_ID__c</fullName>
    <label>Google Drive ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EMS_EM_Onboarding_Request__c/fields/Is_Inegration_Needed__c.field-meta.xml
<CustomField>
    <fullName>Is_Inegration_Needed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Inegration Needed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CreateOnboardingDriveFolderBatchTest.cls
@isTest 
public class CreateOnboardingDriveFolderBatchTest {
    private class RestMock implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            String fullJson = '{"name" : "","mimeType" : "application/vnd.google-apps.folder"}';
            HTTPResponse res = new HTTPResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setBody(fullJson);
            res.setStatusCode(200);
            return res;
        }
    }   
    static testMethod void CreateOnboardingDriveFolderBatchTest(){
        Test.setMock(HttpCalloutMock.class, new RestMock());
        List<EMS_EM_Onboarding_Request__c> RequestList = new List<EMS_EM_Onboarding_Request__c>();
        EMS_EM_Onboarding_Request__c onboard =new EMS_EM_Onboarding_Request__c();
        onboard.EMS_EM_First_Name__c='test';
        onboard.EMS_EM_Last_Name__c='last';
        onboard.Is_Inegration_Needed__c=true;
        onboard.Google_Drive_ID__c = '';
        insert onboard;
        RequestList.add(onboard);
        test.startTest();
        CreateOnboardingDriveFolderBatch createOnboardingFolder = new CreateOnboardingDriveFolderBatch(RequestList);
        DataBase.executeBatch(createOnboardingFolder);
        test.stopTest();
        
    }
    
}