force-app/main/default/objects/EMS_EM_Onboarding_Request__c/EMS_EM_Onboarding_Request__c.object-meta.xml
<CustomObject>
    <label>Onboarding Request</label>
    <nameField>
        <displayFormat>O-{00000}</displayFormat>
        <label>Onboarding Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Onboarding Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_EM_Onboarding_Request__c/fields/EMS_EM_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_Last_Name__c</fullName>
    <label>Last Name</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ems_EM_AddCommentsTest.cls
@isTest
public class ems_EM_AddCommentsTest {
	public testmethod static void sendOnboardingFormReopenTest(){
        EMS_EM_Onboarding_Request__c onRec = new EMS_EM_Onboarding_Request__c();
        onRec.EMS_EM_Last_Name__c = 'Test';
        insert onRec;
        
        String commentsOnRec = 'Testing comments';
        
        Test.startTest();
        ems_EM_AddComments.sendOnboardingFormReopenEmail(onRec.Id,commentsOnRec);
        Test.stopTest();
    }       
}