force-app/main/default/objects/EMS_EM_Onboarding_Request__c/EMS_EM_Onboarding_Request__c.object-meta.xml
<CustomObject>
    <label>Onboarding Request</label>
    <nameField>
        <displayFormat>O-{00000}</displayFormat>
        <label>Onboarding Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Onboarding Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS_EM_Onboarding_Request__c/fields/EMS_EM_First_Name__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_First_Name__c</fullName>
    <label>First Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EMS_EM_Onboarding_Request__c/fields/EMS_EM_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>EMS_EM_Last_Name__c</fullName>
    <label>Last Name</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EMS_EM_Onboarding_Request__c/fields/Google_Drive_ID__c.field-meta.xml
<CustomField>
    <fullName>Google_Drive_ID__c</fullName>
    <label>Google Drive ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EMS_EM_Onboarding_Request__c/fields/Is_Inegration_Needed__c.field-meta.xml
<CustomField>
    <fullName>Is_Inegration_Needed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Inegration Needed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EMS_EM_Onboarding_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CP_ConvertButtonOnOnboardingTest.cls
/**
    * @author Mukesh Rawat
    * @date 1/02/2023
    * @description  ConvertButton to Change the Status Approved to Converted on Onboarding Records 
    *
    *               Test code coverage for CP_ConvertButtonOnOnboarding class
    *        
    *
    * CHANGE HISTORY
    * ====================================================================================================
    * DATE          NAME                    DESCRIPTION
    * N/A           N/A                     N/A
    * ====================================================================================================
    **/
@istest
public class CP_ConvertButtonOnOnboardingTest {
    
    static testmethod void approveButtonTest(){
        EMS_EM_Onboarding_Request__c onboard =new EMS_EM_Onboarding_Request__c();
        onboard.EMS_EM_First_Name__c='test';
        onboard.EMS_EM_Last_Name__c='last';
        onboard.Is_Inegration_Needed__c=true;
        onboard.Google_Drive_ID__c = '';
        onboard.Status__c = 'Approved';
        insert onboard;
        onboard.Status__c = 'Converted';
        update onboard;
        test.startTest();
        CP_ConvertButtonOnOnboarding.ConvertButton(onboard.Id);
        test.stopTest();
    }

}